### ISSUE TITLE
flush() not exported in 0.6.2

### ISSUE THREAD

**Issue by ZempTime** [open-wc/open-wc#100]
Using:
```
"@open-wc/testing-helpers@^0.6.2":
  version "0.6.2"
  integrity sha1-sjLqpu6CXLUmB+bMxgaPe3GoyJc=
```

Pulling in flush as specified here: https://open-wc.org/recommendations/testing-helpers.html#timings
```
import { litFixture, flush } from "@open-wc/testing-helpers";
```
Getting red squigglies in vscode, as well as errors indicating flush isn't there. When I click through to source, I see inside `index.d.ts`:

```
export { html, unsafeStatic } from './lit-html';
export {
  aTimeout,
  defineCE,
  isIE,
  nextFrame,
  oneEvent,
  triggerBlurFor,
  triggerFocusFor,
} from './helpers';
export { litFixture, litFixtureSync } from './litFixture';
export { fixture, fixtureSync } from './fixture';
```

**Comment by thepassle** [comment]
iirc `flush` was deprecated, and you should use `nextFrame` instead, as mentioned here: https://github.com/open-wc/open-wc/issues/32

But maybe @daKmoR can correct me if i'm wrong. I do see it in the code still: https://github.com/open-wc/open-wc/blob/43acfad699ab20d898fb305e8b49d5c73b07b5b2/packages/testing-helpers/helpers.js
So maybe we should just remove it completely?

**Comment by ZempTime** [comment]
I think the issue is instead, let's remove flush usage from the main documentation!

**Comment by ZempTime** [comment]
Yep, discussed here. https://github.com/open-wc/open-wc/issues/32#issuecomment-445529997

this issue feels like a duplicate, so I'm gonna close it.
