### ISSUE TITLE
Component Libraries page is hard to find.

### ISSUE THREAD

**Issue by Westbrook** [open-wc/open-wc#1002]
https://open-wc.org/faq/component-libraries.html is hidden in the FAQ section and is difficult to find without a manual share action. Its content is relatively as important as https://open-wc.org/developing/routing.html to a similar part of a project workflow. We should promote the Libraries page to the `Developing` section as a sibling page or similar.

**Comment by Westbrook** [comment]
Related to #947

**Comment by thepassle** [comment]
fixed in https://github.com/open-wc/open-wc/pull/1078
