### ISSUE TITLE
[testing] flaky test

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1005]
The dynamic import test is flaky, it sometimes fails in the CI because the dynamic import takes longer than the configured timeout. Probably because 6 browsers are running tests concurrently. We could either increase the timeout, but we already set it to 20sec. 

Alternatively we can change the test, we don't really need to test if the dynamic import resolves but just that it didn't throw a syntax error. We could check if it returns a promise, and leave it at that.

**Comment by LarsDenBakker** [comment]
This is the problematic test https://github.com/open-wc/open-wc/blob/master/packages/testing/test/module-features.test.js#L10

**Comment by daKmoR** [comment]
yeah we really should fix it... just had it 2 times that it was green in the PR but then on master it failed... so way tooo flaky 😭

**Comment by daKmoR** [comment]
fixed it for now like this
https://github.com/open-wc/open-wc/pull/1007

if you wanna revisit please reopen 🤗 

maybe we wanna reduce the timeout again?

**Comment by daKmoR** [comment]
apparently even testing for a promise is flaky 😭

**Comment by LarsDenBakker** [comment]
The element snapshot test is also flaky on IE11 :(

They work fine locally on IE11, and when I run only IE11 in browserstack. It's really a problem of concurrency. Perhaps it's even a bug in es-dev-server with concurrent requests?

**Comment by LarsDenBakker** [comment]
This was fixed
