### ISSUE TITLE
[demoing-storybook] Storybook fails on Windows

### ISSUE THREAD

**Issue by amielucha** [open-wc/open-wc#1009]
Environment:

- Windows 10
- NPM v6.13.0
- Node v10.16.3

I have encountered two issues with the Storybook script.

After generating a project scaffolding using `npm init @open-wc`, running `npm run storybook` fails with the following errors:

```
We could not find any stories for the provided pattern "C:\dev\test-project/'components/*/stories/*.stories.{js,mdx}'".
```
I submitted a PR for that: #1008 but there's still a remaining issue. The Storybook starts without loading any components and with the following error in the console:

```
TypeError: Failed to fetch dynamically imported module: http://localhost:8001/c:/dev/test-project/components/my-component/stories/my-component.stories.js
```

It looks like the URL is not being constructed correctly in `demoing-storybook/src/shared/getAssets.js:55`.

**Comment by LarsDenBakker** [comment]
Thanks for your PR. I think https://github.com/open-wc/open-wc/pull/1017 should address the other issue.

**Comment by LarsDenBakker** [comment]
Please reopen if the fix doesn't work for you.
