### ISSUE TITLE
[testing] karma sometimes stops running tests in watch mode

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1022]
When running karma in watch mode, after multiple reloads it can randomly stop running the actual test. We need to investigate this, whether it's an actual issue we're creating in `karma-esm` or if it's just a general karma bug.

The tests run fine when opened in the browser, so it could also be something to do with chrome headless.

**Comment by manolakis** [comment]
It happens sometimes with Firefox too, but less frequently than with Chrome. With Chrome, In my case, happens constantly, and not only with chrome headless.

**Comment by daKmoR** [comment]
we recommend `@web/test-runner` as a replacement for karma. If the issue persists there feel free to open an issue at https://github.com/modernweb-dev/web
