### ISSUE TITLE
Add recommendation for event usage and firing

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#1037]
For usage of events have a TLDR.
- wire-up to local DOM via @some-event in template (let Lit do the actual wire-up)
- wire-up events to this in constructor (no need to clean up - as it will be garbage collected on destroying)
- wire-up to elements outside of scope (ex. window) using connectedCallback , and remove them in disconnectedCallback. 

For firing events have a TLDR.
- prefer "just" events without `bubble` or `composed` e.g. `new Event('something-happened')`
- when needing data consider extending `Event` or using `CustomEvent`
- use `bubble: true` if a node up the tree needs the event
- retrain from using `composed: true` as it leads to event pollution 
- use composed only if absolutely needed

Add a link for details too https://dev.to/open-wc/composed-true-considered-harmful-5g59

**Comment by LarsDenBakker** [comment]
Great overview

**Comment by thepassle** [comment]
related/the same: https://github.com/open-wc/open-wc/issues/895#issuecomment-554067855

**Comment by daKmoR** [comment]
@Westbrook can I request that you pick this up soonish? 🙏 

I wanted to reference something like this now more then 2 times 🙈  so it would help me a lot if it would be there 🤗 

if you don't have time soonish I will just copy it as-is and we can improve it later 🤗

**Comment by Westbrook** [comment]
Wow, the holidays really just went...

We're good placing this in the `FAQ` section? I could also see it going in the `Guides & Docs` section.

I'll start fleshing out this overview today.

**Comment by thepassle** [comment]
Maybe even a codelab?
