### ISSUE TITLE
npm run lint:types  too many error 

### ISSUE THREAD

**Issue by hikaruna** [open-wc/open-wc#1043]
## version
see my yarn.lock file

[yarn.lock](https://github.com/open-wc/open-wc/files/3884105/yarn.lock.txt)

## step
1. do https://open-wc.org/linting/linting-types.html#manual
    - tsconfig https://github.com/open-wc/open-wc/commit/0f1d30d7a401be298d11c9e239e4af6231d49182
2. npm run lint:types

## expect
no error

## actual
long time wait...
output many error( An amount that the console cannot display )

error from
  - dist folder
  - node_modules/@open-wc folter

[error.log](https://github.com/open-wc/open-wc/files/3884100/error.log)

---

Sorry my bad english.
and
Thank you for the wonderful framework

**Comment by LarsDenBakker** [comment]
Sorry for the late response on this issue. You will need to instruct your typescript config to not do any checking of dependencies in your node modules for this.
