### ISSUE TITLE
[building] potential browserslist conflict

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1044]
Because we are calling browserslist ourselves here: https://github.com/open-wc/open-wc/blob/master/packages/building-utils/find-supported-browsers.js it's possible to end up with a different version than the one used by `@babel/preset-env` in one of the build configs. 

This creates situations where one version of `browserslist` passes versions to another version, creating errors as it doesn't know about certain new browsers.

**Comment by petrubocsanean** [comment]
I had this issue when updating an existing project.

**Comment by LarsDenBakker** [comment]
@petrubocsanean if you regenerate your lockfile, does the error go away?

**Comment by petrubocsanean** [comment]
Yes, removing the lockfile and a clean install solves the error.

**Comment by LarsDenBakker** [comment]
This was solved in v1 of building-rollup.
