### ISSUE TITLE
[create] update snapshots doesnt scaffold test files

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc#1047]
The update snapshots command in `create` doesn't seem to scaffold test files for `page-one` and `page-main`:

<img width="271" alt="Screenshot 2019-11-25 at 21 09 31" src="https://user-images.githubusercontent.com/17054057/69575081-ddaa7380-0fc9-11ea-93d5-c5bed49997f6.png">

Running the actual generator itself with either `npm init @open-wc` or `npm run start` (inside the project) does scaffold these files:

<img width="260" alt="Screenshot 2019-11-25 at 21 10 59" src="https://user-images.githubusercontent.com/17054057/69575139-f61a8e00-0fc9-11ea-95b3-4bf7942c3e38.png">

EDIT:
seems to be a problem with the `scaffoldFilesFor` flag when running the generator itself, see:

```bash
npm run build && node ./dist/create.js \
  --destinationPath . \
  --type scaffold \
  --scaffoldType app \
  --features linting testing demoing building \
  --buildingType rollup \
  --scaffoldFilesFor testing demoing building \
  --tagName scaffold-app \
  --writeToDisk true \
  --installDependencies false
```

**Comment by bennypowers** [comment]
see also #1040 which is tangentially related

**Comment by bennypowers** [comment]
Also see #966

**Comment by LarsDenBakker** [comment]
Was this fixed with https://github.com/open-wc/open-wc/pull/966?
