### ISSUE TITLE
 Build tools can be over eager with their whitespace management.

### ISSUE THREAD

**Issue by Westbrook** [open-wc/open-wc#1049]
# Expected:
The following code:
```
<p>
    Spectrum Web Components are implemented using the <sp-link
        class="spectrum-Link"
        href="https://lit-element.polymer-project.org/"
    >LitElement</sp-link> base class.
</p>
```
should be bundled to something similar to:
```
<p>Spectrum Web Components are implemented using the <sp-link href="https://lit-element.polymer-project.org/">LitElement</sp-link> base class.</p>
```
So as to maintain the structure of the sentence.

# Actual
The following code:
```
<p>
    Spectrum Web Components are implemented using the <sp-link
        class="spectrum-Link"
        href="https://lit-element.polymer-project.org/"
    >LitElement</sp-link> base class.
</p>
```
is bundled to:
```
<p>Spectrum Web Components are implemented using the<sp-link href="https://lit-element.polymer-project.org/">LitElement</sp-link>base class.</p>
```
Which collapses the following: `the<sp-link href="https://lit-element.polymer-project.org/">LitElement</sp-link>base`.

# How it happens:
Currently, the build tools use:
```
htmlMinifier: {
    collapseWhitespace: true,
    removeComments: true,
    caseSensitive: true,
    minifyCSS: customMinifyCSS,
},
```
This means that tags not included in [this list](https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L67): 
```
var inlineTags = createMapFromString('a,abbr,acronym,b,bdi,bdo,big,button,cite,code,del,dfn,em,font,i,ins,kbd,label,mark,math,nobr,object,q,rp,rt,rtc,ruby,s,samp,select,small,span,strike,strong,sub,sup,svg,textarea,time,tt,u,var');
```
will have the white space before and after them removed.

# Alternative
I suggest we move to:
```
htmlMinifier: {
    collapseWhitespace: true,
    conservativeCollapse: true,
    removeComments: true,
    caseSensitive: true,
    minifyCSS: customMinifyCSS,
},
```
So that `conservativeCollapse` ensures that while we collapse whitespace in the whitespace is never removed entirely so as to maintain users' intended content structures.

**Comment by Westbrook** [comment]
Happy to put together the PR when this approach is agreed on. Would this count as a `fix: ...` or a `feat: ...`?

**Comment by daKmoR** [comment]
I would count it as a fix 👍 

@LarsDenBakker added the htmlMinifier so maybe he knows more?

**Comment by LarsDenBakker** [comment]
Yep sounds like the right approach
