### ISSUE TITLE
[demoing-storybook] could not build 

### ISSUE THREAD

**Issue by petrubocsanean** [open-wc/open-wc#1054]
### Expected Behavior
Running `storybook:build` should build the Storybook successfully.

### Current Behavior
Running `storybook:build`  gives the following error: 

> We could not find any stories for the provided pattern. 

After setting the pattern for stories and running `storybook:build`  gives the following error: 

`ode_modules@open-wcstorybook-prebuiltdistpreview.js'], function (exports) {
  3 |     'use strict';
  4 |     var _classCallCheck, _createClass, _toConsumableArray, _typeof, _inherits, _possibleConstructorReturn, _getPrototypeOf, _get, _wrapNativeSuper, _taggedTemplateLiteral, _objectSpread2, _objectWithoutProperties, previewCjs_31, previewCjs_10, previewCjs_23, previewCjs_29, previewCjs_28, previewCjs_27, previewCjs_30, mdx, DocsContainer;`

### Steps to Reproduce

1. Generate a web component with `npm init@open-wc`
2. Add Linting, Testing, Demoing
3. Scaffold Testing, Demoing
4. Install dependencies using npm 
5. Run `storybook:build`

**Comment by petrubocsanean** [comment]
To be more precise, the error was ` Unterminated string constant`.  
This seems occur only if there are `.mdx` stories. With `.js` I was able to build it successfully.

**Comment by LarsDenBakker** [comment]
We're missing a default value of the `stories` pattern, that's a good catch. Fixing that in https://github.com/open-wc/open-wc/pull/1143

I'm not able to reproduce the other issue, are you still seeing this with the latest versions?

**Comment by petrubocsanean** [comment]
On a Windows machine i'm still getting the error. I've tried on a mac and didn't had any issue.

**Comment by LarsDenBakker** [comment]
I've verified with the latest version it's working on windows.
