### ISSUE TITLE
[demoing-storybook] broken encoding

### ISSUE THREAD

**Issue by kuka-radovan** [open-wc/open-wc#1055]
There is a broken encoding in storybooks menu. This is related only with `storybook-start`. Everything looks fine when building own static version.

![Screenshot 2019-11-27 at 11 30 17](https://user-images.githubusercontent.com/5869729/69735437-f6816900-1130-11ea-8823-2637b826336e.png)

**Comment by LarsDenBakker** [comment]
Fixed by https://github.com/open-wc/open-wc/pull/1136
