### ISSUE TITLE
[doc] generator with linting types does not work

### ISSUE THREAD

**Issue by kuka-radovan** [open-wc/open-wc#1056]
Accoding to [documentation](https://open-wc.org/linting/linting-types.html#linting-types), there is an option to add `linting-types-js` for enabling types linting. It's not working and I suppose it's unupdated documentation about that. What is a correct option for generator to enable that? If it still supposed to work of course.

**Comment by LarsDenBakker** [comment]
I think this was removed from the generator to keep the number of options to a minimum, so we just have the docs for now since it's not really web component related.

**Comment by LarsDenBakker** [comment]
We need to remove this mention of the generator in the docs.
