### ISSUE TITLE
[es-dev-serve] a way to ignore a script in compatibility mode

### ISSUE THREAD

**Issue by jarrodek** [open-wc/open-wc#1061]
Hi,

I would like to ignore a script in my demo page by the transformers when requesting a resource.

I have a package already compiled and ready in my demo directory. I am using it in the `head` as 

```html
<head>
  ...
  <script src="vendor.js"></script>
</head>
```

I am running the server with compatibility mode set to auto. The problem is that it transforms my script to use `System` which at the moment of including the script is unavailable and does not work.  As a result the whole application cannot run because of a missing dependency.
So far I have build a middleware that looks for this specific file and serve its content but this is not scalable solution. Is there a way to ignore this file?

**Comment by LarsDenBakker** [comment]
Indeed, we will work on a better solution for this

**Comment by jarrodek** [comment]
Maybe I can help? I am using your modules extensively for work, and I can afford to spend some time developing it as well. Just let me know if and how to start.

**Comment by LarsDenBakker** [comment]
That's much appreciated, but @tmsns is already working on a fix for this :)

**Comment by LarsDenBakker** [comment]
The fix for this was merged, we not use a systemjs hook to only transform files that were actually imported. This way we don't need to exclude scripts manually, which is great.
