### ISSUE TITLE
[es-dev-server]: Add `context` property that behaves like rollup's context option. 

### ISSUE THREAD

**Issue by jarrodek** [open-wc/open-wc#1062]
I am receiving an error in compatibility mode under IE11 (unfortunately I am being forced to add support for this):

```
TypeError: Cannot create property for a non-extensible object
```

I have traced this problem to the Marked library. This library is defined as follows:

```javascript
(function (root) {
  var marked = ...

  if (typeof module !== 'undefined' && (typeof exports === "undefined" ? "undefined" : _typeof(exports)) === 'object') {
     module.exports = marked;
  } else if (typeof define === 'function' && define.amd) {
     define(function () {
       return marked;
     });
  } else {
     root.marked = marked;
  }
})(this || (typeof window !== 'undefined' ? window : global));
```

It looks like `this` is actually defined to an empty object when this code is executed but it never gets to be added to the DOM.

In my component that uses this library I am importing marked as:

```
import * as marked from 'marked/lib/marked.js';
if (!window.marked) {
  window.marked = marked;
}
```

It works for normal mode in a normal browser. When I am building the application I am using `context` property of rollup. It makes it work. However when I run the demo p[age in the compatibility mode and I open the demo page in IE11 nothing gets rendered.

![image](https://user-images.githubusercontent.com/3320020/69829053-5597ba00-11d3-11ea-8cb3-e930ff7f537e.png)

So I am looking for an option similar to rollup's `context` that I can set to `window` and be happy again.

**Comment by LarsDenBakker** [comment]
This is an issue with the babel systemjs transform, I've filed an issue upstream: https://github.com/babel/babel/issues/10775

You could monkey patch this with a `responseTransformer` in the meantime, let me know if you need any help with that.

**Comment by jarrodek** [comment]
I guess I will have to wait since I have about a 100 components that have this problem :)

**Comment by LarsDenBakker** [comment]
This will land in babel 7.8 https://github.com/babel/babel/pull/10780
