### ISSUE TITLE
Inline whitespace in text removed around a custom element (in build only)

### ISSUE THREAD

**Issue by tomherni** [open-wc/open-wc#1063]
I have a web component that outputs text only (a formatted logo that does some stuff that would justify making it a component). Because it is text-based, it is often used inline with other text. But, when I make a build using `$ npm run build` it minifies and removes the whitespace before and after the component. During development (using the es-dev-server), whitespace is maintained just fine.

The main issue for me is that a built version of my application now looks differently than the development version. I can work around this by replacing the whitespace with `nbsp;`, but obviously not preferred.

This issue can be reproduced with the bare code samples below.

```js
class MyElement extends LitElement {
  render() {
    // expect: lorem logo ipsum
    // actual: loremlogoipsum
    return html`lorem <my-logo></my-logo> ipsum`;
  }
}
```

```js
export class MyLogo extends LitElement {
  render() {
    return html`logo`;
  }
}
```

This might be a build issue with custom elements only. Because `lorem <strong></strong> ipsum` builds just fine. See images below.

**Whitespace gone:**

<img width="184" alt="whitepace-gone" src="https://user-images.githubusercontent.com/3840632/69829058-c87a5280-121e-11ea-8822-016c3f4bf158.png">

**Whitespace maintained:**

<img width="180" alt="whitespace-maintained" src="https://user-images.githubusercontent.com/3840632/69829059-c87a5280-121e-11ea-84ee-2a67bef0f509.png">

**Comment by LarsDenBakker** [comment]
Can you try with the latest version of `building-rollup`? I think this is fixed by https://github.com/open-wc/open-wc/pull/1050

**Comment by tomherni** [comment]
You are right, that fixed it and it's working fine now. Thanks!
