### ISSUE TITLE
[building]: question about how styles are processed

### ISSUE THREAD

**Issue by jarrodek** [open-wc/open-wc#1066]
I promise it's the last issue reported today :)
I have quite specific use case. but I hope you guys will be able to help me somehow.

I have an application build on top of tens of web components. Most of them are build with lit-element/html. The application itself is a web component as well (shell app, Polymer style).
The final application supposed to work in various environments. It's an open source tool for web APIs documentation. We use this application on our platform and recently we have added this application to the Salesforce cloud. As it turns out Salesforce platform don't like constructable styles (at least I think that's the reason). So after bundling the application and embedding it in the platform the styles didn't work. Al least with static `styles` property. However when we applied styles directly to the shadow DOM and removing static `styles` it worked perfectly.

Finally we moved all the components to use styles in the shadow DOM directly to eventually learn that this doesn't work well in IE11. Styles are not rendered at all. Because of the other two issues I reported today it is very hard to debug the problem on an individual component level so I am only trying to debug generated bundle. My best guess at the moment is that I am not initializing `ShadyCSS `properly (via `styleElement` function). So the question is, when the legacy bundle is generated, is the support for the ShadyCSS is somehow added for me automatically? Or do I need to add run `ShadyCSS.styleElement(this)` in each `connectedCallback()` method?

**Comment by LarsDenBakker** [comment]
The build does nothing specific with styles other than minification. If you're using `LitElement` this takes care of all the styling for you, both a static getter and a style element should work fine assuming you're rendering to shadow dom. 

I don't really know anything about salesforce and if they're somehow modifying the environment to make this not work.

**Comment by jarrodek** [comment]
It's not about salesforce cloud. We actually have fixed the issue for Salesforce by moving styles to the shadow DOM instead of static `styles` getter. But then I have an issue with IE11 as it won't style the components. So the question is more about how the styles are processed in legacy mode when components are loaded with the polyfills.

**Comment by LarsDenBakker** [comment]
Also in legacy build we dont do anything other than minification. Do the styles work with es dev server and IE11?

**Comment by jarrodek** [comment]
I forgot about this issue. 
It turned out to be an issue with styles. There was an error in syntax in one of our shared styles. Small thing. The second argument for CSS `var()` function, which is a default value,  was a list of fonts. However, the value was not quoted and the polyfill couldn't parse the css as it was expecting something else (I guess...). Because it was in a shared style that was included in multiple components it looked like the application wasn't styled in general. After fixing the issue with syntax it started working.
This did not happen with other browsers as, apparently, browsers' CSS parser is more forgivable for syntax mistakes.
I am closing this ticket as WAI.
