### ISSUE TITLE
[building] Recommendation to add inline scripts in the index.html

### ISSUE THREAD

**Issue by abdonrd** [open-wc/open-wc#1068]
My use case is add the Google Analytics script.

It's something like:

```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXX');
</script>
```

I think the best idea could be have some option to add this script to the `index.html` in the build step. Because we don't needed during the development process, just in production/staging.

**Comment by LarsDenBakker** [comment]
I agree that we need to do something here, I've had some different ideas but I haven't had time to work it out yet.

**Comment by LarsDenBakker** [comment]
Not stale, working on this.

**Comment by abdonrd** [comment]
Any news here? Thanks!

**Comment by LarsDenBakker** [comment]
I have almost finished a refactor of the html plugin, this allow you more customizations like this.

**Comment by abdonrd** [comment]
Great, thanks Lars! 👏

**Comment by abdonrd** [comment]
@LarsDenBakker this is fixed with the last version?

**Comment by LarsDenBakker** [comment]
Yes you can add it in the html plugin

**Comment by abdonrd** [comment]
Thanks!

Reference to docs: https://github.com/open-wc/open-wc/tree/master/packages/rollup-plugin-html#transform-output-html
