### ISSUE TITLE
Rendertron doesn't work with open-wc application

### ISSUE THREAD

**Issue by abdonrd** [open-wc/open-wc#1070]
[Rendertron](https://github.com/GoogleChrome/rendertron) doesn't work with `open-wc` application.

You can see how the app works:
https://open-wc-starter-app.netlify.com

But Rendertron show a white screen:
https://render-tron.appspot.com/render/https://open-wc-starter-app.netlify.com

Same white screen with the `?wc-inject-shadydom=true`:
https://render-tron.appspot.com/render/https://open-wc-starter-app.netlify.com?wc-inject-shadydom=true

Any idea why it doesn't work?

**Comment by abdonrd** [comment]
I also had tried with the PWA Starter Kit.

You can see how the app works:
https://pwa-starter-kit.appspot.com

It just works:
https://render-tron.appspot.com/render/https://pwa-starter-kit.appspot.com

Also works with the `?wc-inject-shadydom=true`:
https://render-tron.appspot.com/render/https://pwa-starter-kit.appspot.com?wc-inject-shadydom=true

**Comment by jimmy-collazos** [comment]
check the [documentation](https://github.com/GoogleChrome/rendertron#web-components). The demo page don't load `webcomponents-lite.js` or `webcomponents-loader.js` for activate the shadydom

**Comment by abdonrd** [comment]
Fixed by #1071.

**Comment by abdonrd** [comment]
It happens again with the new `@open-wc/building-rollup@^1.0.0`.

**Comment by abdonrd** [comment]
I also had tried with my Freestyle Stats project (using `@open-wc/building-rollup@^1.0.0`).

You can see how the app works:
https://freestylestats.com

It just works:
https://render-tron.appspot.com/render/https://freestylestats.com

Also works with the `?wc-inject-shadydom=true`:
https://render-tron.appspot.com/render/https://freestylestats.com?wc-inject-shadydom=true

**Comment by abdonrd** [comment]
@AVGP any idea about how could I debug this? Thanks in advance!
