### ISSUE TITLE
[es-dev-server] Chrome 41 Transpilation Errors

### ISSUE THREAD

**Issue by e111077** [open-wc/open-wc#1074]
Heyo, I'm running `@open-wc/karma-esm` and have compatibility as `auto`, when running a script with block-scoped declarations (let, const, etc), the file is not compiled on certain browsers such as `chrome 41` and `safari 9`.

Chrome 41 and Safari 9 both support block-scoped variables, but they are only allowed in strict mode which causes some files written after this restriction went away to fail.

**Comment by LarsDenBakker** [comment]
I think we're running into https://github.com/systemjs/systemjs/issues/2071#issuecomment-555355259 here, I wasnt sure if anyone still needs to test Chrome 41 so I didnt pursue further. 

So we should cook up a PR to systemjs for this.

**Comment by e111077** [comment]
That's 100% the issue I was running into. There is less rush as the MWC team has decided that dev speed + IE support >> testing chrome 41 and safari 9 especially since googlebot is now evergreen and apple has a tight grip over safari updates.

Though it is a would-be-nice feature as caniuse has them at about 2% usage which is IE11-level (though perhaps a different market)

**Comment by LarsDenBakker** [comment]
Going to close the issue here, this needs to be fixed on the SystemJS side.
