### ISSUE TITLE
chai-dom not registered in custom karma webpack setup

### ISSUE THREAD

**Issue by bschlenk** [open-wc/open-wc#1091]
I'm trying migrate some of my existing tests over to the `@open-wc/testing` library, mainly to use the snapshots and chai-dom.

My setup uses webpack with karma to run the tests. This seems to cause chai-dom to not be registered. It looks like [register-chai-plugins.js](https://github.com/open-wc/open-wc/blob/master/packages/testing/register-chai-plugins.js#L2) imports `chai-dom` and does nothing with it. [Chai dom is a UMD](https://github.com/nathanboktae/chai-dom/blob/master/chai-dom.js#L1-L10), so when run this way it exports `ChaiDom` instead of implicitly calling `chai.use` with it.

Is there a way to force chai-dom to be registered in this case?

**Comment by LarsDenBakker** [comment]
I *think* we can make it work for both webpack and browser es modules by doing this instead:

```
// non es module plugins
import 'chai-dom';
import 'sinon-chai';

// es module plugins
import { chaiDomDiff } from '@open-wc/semantic-dom-diff';
import { chaiA11yAxe } from 'chai-a11y-axe';

let chai = window.chai;
if (!chai && require) {
  chai = require('chai');
}

// @ts-ignore
chai.use(chaiDomDiff);
// @ts-ignore
chai.use(chaiA11yAxe);
```

Could you test if this works on your setup? I don't have a webpack karma setup to test this out.

**Comment by bschlenk** [comment]
That didn't work for me, but this does work:

```js
// non es module plugins
import chaiDom from 'chai-dom';
import 'sinon-chai';

// es module plugins
import { chaiDomDiff } from '@open-wc/semantic-dom-diff';
import { chaiA11yAxe } from 'chai-a11y-axe';

// @ts-ignore
chai.use(chaiDomDiff);
// @ts-ignore
chai.use(chaiA11yAxe);

chai.use(chaiDom);
```

What happens if you run `import chaiDom from 'chai-dom';` with your setup? If that returns null or an empty object, then you should be able to check that and only call `chai.use(chaiDom)` if it is an actual chai plugin.

sinon-chai would have the same problem, since it is a UMD as well.

**Comment by LarsDenBakker** [comment]
Unfortunately the browser complains that there is no export from that modules, so we can't do that.

**Comment by bschlenk** [comment]
It looks like the author of chai-dom is considering moving towards an es module approach: https://github.com/nathanboktae/chai-dom/issues/38#issuecomment-549221553

**Comment by daKmoR** [comment]
as long as chai itself is not an es module it's probably tough 🙈

**Comment by LarsDenBakker** [comment]
I was able to find a solution for this in https://github.com/open-wc/open-wc/pull/1142
