### ISSUE TITLE
Implement Prettier via ESLint

### ISSUE THREAD

**Issue by paales** [open-wc/open-wc#1096]
The idea is that, less separate processes to run, the faster the tooling can be. Also it makes it easier to set everything up.

Practical upside: By running eslint and prettier in vscode for example can cause race conditions where you'd need to save a file twice for everything to be fixed. ESLint is later than prettier and has changed something that needs to be reformatted. By integrating prettier in eslint we won't hit that problem.

Integrating prettier in eslint should be fairly easy to do: https://prettier.io/docs/en/integrating-with-linters.html#eslint

**Comment by LarsDenBakker** [comment]
This looks really good, I think we should investigate and see if it works the same way.

**Comment by blikblum** [comment]
When i used prettier/eslint integration on vscode prettier plugin, performance got worse.

In large files vscode would not format on save because format time hit 750ms limit.

But AFAIR it was using https://github.com/prettier/prettier-eslint. Not sure how running prettier as a eslint plugin would work

**Comment by paales** [comment]
A use case against this: eslint, lints js/ts files, prettier does way more..

**Comment by blikblum** [comment]
Seems this already done: https://open-wc.org/linting/linting-eslint.html#running-with-prettier

**Comment by daKmoR** [comment]
indeed thx 🤗

**Comment by blikblum** [comment]
Sorry for the confusion, but the OP meant to use eslint-plugin-prettier which is not the case for open-wc

**Comment by paales** [comment]
I think it isn't relevant for me anymore. Since prettier does format other file formats besides js/ts files.
