### ISSUE TITLE
[demoing-storybook] .storybook/es-dev-server.config.js is not picked up

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#1102]
even if such a file is available it's not taken into account when configuring storybook

current workaround is
```
-c path/to/es-dev-server.config.js
```

full-example
```
"storybook": "start-storybook -p 9001 --stories \"packages/calendar/stories/*.stories.{js,mdx}\" -c demo/.storybook/es-dev-server.config.js --config-dir packages/replace-lion-features/demo/.storybook --root-dir ../../ --node-resolve --watch --open",
```

imho defining the `--config-dir` should be enough and a different config for es-dev-server should be applied :+1:

**Comment by LarsDenBakker** [comment]
es-dev-server looks for a config in the current working directory, so this is expected behavior.

Looking in the storybook directory makes sense in most cases, but sharing the same config between storybook and regular es-dev-server is nice too.
