### ISSUE TITLE
[demoing-storybook] Storybook fails on Windows

### ISSUE THREAD

**Issue by AERK-work-account** [open-wc/open-wc#1103]
See #1009 

Issue is not yet resolved. Please re-open. I've verified that all fixes from #1017 are in place, but issue persists for me.

**Comment by LarsDenBakker** [comment]
I just tried it on a clean `npm init @open-wc` and it works for me on windows. What errors are you running into?

**Comment by Cuttsy27** [comment]
I tried running Storybook on a clean `npm init @open-wc` also and got the following: 
```We could not find any stories for the provided pattern "C:\open-wc\open-wc-test/'components/*/stories/*.stories.{js,mdx}'".```

**Comment by DanielTurner** [comment]
@Cuttsy27 can you confirm what version(s) you have installed and are running, just in case your npm fetched a cache copy.

**Comment by Cuttsy27** [comment]
These are the devDependencies in my package.json ```"devDependencies": {
    "eslint": "^6.1.0",
    "@open-wc/eslint-config": "^2.0.0",
    "@open-wc/prettier-config": "^0.1.10",
    "husky": "^1.0.0",
    "lint-staged": "^8.0.0",
    "@open-wc/testing-karma": "^3.0.0",
    "webpack-merge": "^4.1.5",
    "@open-wc/testing-karma-bs": "^1.0.0",
    "@open-wc/testing": "^2.0.0",
    "@open-wc/demoing-storybook": "^1.0.1",
    "@open-wc/building-rollup": "^0.15.1",
    "rimraf": "^2.6.3",
    "rollup": "^1.15.4",
    "es-dev-server": "^1.5.0"
  },```
I deleted package-lock.json and node_modules and did a fresh install.

**Comment by Cuttsy27** [comment]
Removing the single quotes around `'components/*/stories/*.stories.{js,mdx}'` fixes the problem on Windows.

**Comment by LarsDenBakker** [comment]
Good to know! Now to check where it comes from...

**Comment by AERK-work-account** [comment]
@LarsDenBakker The issue brought by @Cuttsy27 above is the same as my issue. Thank you

**Comment by daKmoR** [comment]
so just to verify the only change that is need is to modify the script in package.json to not use single quotes...

then it works fine on Windows?

e.g. we only need to adjust the generator and potentially update the Readme

**Comment by AERK-work-account** [comment]
Yes, removing the single quotes fixed the issue for me. Thank you
