### ISSUE TITLE
[doc] Sample Code incorrect in module 7 and 8 of codelabs intermediate

### ISSUE THREAD

**Issue by jdeekonda** [open-wc/open-wc#1109]
In Codelabs " lit-html & lit-element: intermediate", Chapter 7 and 8 mentions incorrect code in "View final result" section due to which sample code do not work as expected.
We need to introduce following line of code in <news-article> tag in render function of NewsApp class-
          **.read=${article.read}**

Please note that this mistake is not present in chapter 9 and there on.
Final code looks like -

            <h1>News App</h1>

            <h2>Articles</h2>
            <p>( ${totalRead} read and ${totalUnread} unread) </p>
            <ul>
              ${this.articles.map(
                article => html`
                  <li>
                    <news-article
                      .title=${article.title}
                      .description=${article.description}
                      **.read=${article.read}**
                      @toggle-read-status=${() => this._toggleReadStatus(article)}
                    ></news-article>
                  </li>
                `,
              )}
            </ul>

**Comment by daKmoR** [comment]
thx for reporting this 🤗 

care to create a MR?
the code is here
https://github.com/open-wc/open-wc/blob/master/packages/codelabs/src/intermediate/lit-html.md
