### ISSUE TITLE
[es-dev-server] not serving images

### ISSUE THREAD

**Issue by jdevega** [open-wc/open-wc#1114]
Hi, I'm trying to load static images, but the server is not sending them. I enabled debug mode and this is the error shown :

```bash
[es-dev-server]:  Receiving request: /static/images/building.jpg
[es-dev-server]:  Serving request: /static/images/building.jpg with status: 200

  Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
```

Am I missing any configuration option?

**Comment by LarsDenBakker** [comment]
I actually had a similar issue when response transformers are set up as well, can you check with the latest `es-dev-server`?

**Comment by jdevega** [comment]
With latest es-dev-server version is working again!
I checked your fix and make sense 
https://github.com/open-wc/open-wc/commit/a13811a7e51f7d2feba6c55e7571ac1ae10b5dd2

Thanks, great job !
