### ISSUE TITLE
[es-dev-server] package.json "browser" field is ignored

### ISSUE THREAD

**Issue by blikblum** [open-wc/open-wc#1121]
The package.json "browser" field is not respected when resolving packages.

See https://github.com/open-wc/open-wc/blob/8c9eb6edab078c495d2a8a5a2388dd44d5590c2c/packages/es-dev-server/src/utils/resolve-module-imports.js#L83

Example:

when importing [superagent](https://github.com/visionmedia/superagent/blob/master/package.json#L6) its loading ./src/node/index.js instead of ./src/client.js. 

The basic resolution does not require much work but the advanced (like in superagent) is not so simple. See: https://github.com/defunctzombie/package-browser-field-spec

**Comment by LarsDenBakker** [comment]
I'd like to align with the behavior of `@rollup/plugin-node-resolve` here. It looks like they handle the `browser` field, so we should too. (https://github.com/rollup/plugins/blob/master/packages/node-resolve/src/index.js)

It looks like the `browser`field needs quite some more complex handling, open for PRs one this one.
