### ISSUE TITLE
[testing-helpers] Allow to inject wrapper element in fixture

### ISSUE THREAD

**Issue by blikblum** [open-wc/open-wc#1125]
Currently there's no way to customize the creation of wrapper element used as parent to the template.

A use case is testing an element that uses the dependency injection technique described by Polymer dev [here](https://www.youtube.com/watch?v=6o5zaKHedTE) and [here](https://youtu.be/x9YDQUJx2uw?t=2444). It relies on a parent element that listen to an event dispatched in the connectedCallback

An actual example of testing is [here](https://github.com/blikblum/lit-element-mobx-realworld-example-app/blob/master/test/app-header.js#L23). `app-header` element depends on a context provided by a parent element. Currently there's no way to properly test it.

This is something i can work if approved

**Comment by daKmoR** [comment]
a context would need to be put onto a dom element right?

so how about something like this?

```js
const wrapper = await fixture(html`
  <my-context .data=${...}>
    <div>
       <my-el></my-el>
    </div>
  </my-context>
`;

const el = wrapper.querySelector('my-el');
```

as far as I can see such a context system should not require a special way of testing? do you have some more context what would not work that way?)

also as far as I know such a system based on events will not work on IE11 😭

**Comment by blikblum** [comment]
my-el would be empty ( not rendered ) because fixture waits only for top level elements AFAIK

**Comment by LarsDenBakker** [comment]
I think the fixture should await all the elements in the fixture, that would make it more flexible. We could even (optionally) do andeep await of all children including in shadow dom

**Comment by blikblum** [comment]
I think It should be optional both because performance and because many times you dont want the content of inner components (kind of implementation detail)

**Comment by daKmoR** [comment]
As a user you create the fixture and therefore you should also know if the element needs some more time then the default... 

this could mean to await a next frame or a timeout or adding an extra fooComplete (which could be a promiseall of all child's updateComplete)

or by making the updateComplete of you class to include all it's children (lit element has some docs on how to adjust your updateComplete) this would mean the fixture would await it automatically (but might not be doable or practical)

imho doing any of the above sounds like a better solution then to add an extra sync wrapper around

**Comment by blikblum** [comment]
> by making the updateComplete of you class to include all it's children

1) Changing the implementation of the component (with complexity increase and performance penalty) just to allow testing does not sound good

2) Even considering the above, context provider elements does not deals with children rendering at all

> As a user you create the fixture and therefore you should also know if the element needs some more time then the default...

Yes, the solution is to await the rendering for the child element like below:

```js
const wrapper = await fixture(html`
  <my-context .data=${...}>
       <my-el></my-el>
  </my-context>
`;

const el = wrapper.querySelector('my-el');
await el.updateComplete
```
With the following caveats

- adds yet more boilerplate and the whole reason of testing-helpers is to avoid them
- it makes harder to visualize what component you are testing. Compare with the below:

```js
const el = await fixture(html`<my-el></my-el>`, { parent: contextEl });
```

Finally, the code required to implement the ability to define the the wrapper/parent is moving one line in [one place](https://github.com/open-wc/open-wc/pull/1131/files#diff-dd3a4dc814a056cdc5e1fa886ac0e6d3R10) (the remaining code just pass options argument down the call stack).

Its less than the required code to implement one test case with the proposed solution

**Comment by LarsDenBakker** [comment]
Yeah I dont think changing production code is the right solution, but I really feel that the wrapper should be an implementation detail of the test fixture.

I think the test fixture should await updateComplete (and equivalents of other libs) of all light dom elements, that will fix your situation. 

The options object could accept a selector to select the element to return.

**Comment by blikblum** [comment]
> I think the test fixture should await updateComplete (and equivalents of other libs) of all light dom elements, that will fix your situation.

I think this should be opt-in because: 1) will break existing tests 2) can slowdown the tests potentially

Regarding the original issue, i'd be using my version for now. 

Anyway thanks for all work.

**Comment by LarsDenBakker** [comment]
We would just be querying the light dom elements, not the shadow dom elements. So there are no implementation details that we are accessing here.

**Comment by blikblum** [comment]
> So there are no implementation details that we are accessing here.

By implementation detail i mean the rendered html tree from the child element.

Say i have an element 'my-form' which renders to DOM (no shadow DOM) ten inputs and i'm testing 'my-el' that have one 'my-form`' element:

```js
const el = await fixture(html`<my-el></my-el>`);
expect(el).to.match.snapshot()
```

I would expect the following snapshot output (as is today):
```html
<my-el><my-form></my-form></my-el>
``` 

If is enabled by default, the output would be

```html
<my-el><my-form><input/><input/><input/><input/><input/><input/>...</my-form></my-el>
``` 

So basically, i'm saying i dont care what 'my-form' is rendering i just want to know that i'm rendering an 'my-form' element

**Comment by LarsDenBakker** [comment]
If you're not using shadow dom you are leaking implementation details by design, but you're right this does create a change in behavior assuming that both `my-el` and `my-form` render async and their timing is consistent.

We may be able to render to a template or document fragment first and check which elements were actually in the fixture, but it gets pretty messy.

Another approach could be to allow setting specific data attributes on elements which need to be awaited.

**Comment by LarsDenBakker** [comment]
Allowing setting the wrapper element does seem like a simple solution as well given the complexities. @daKmoR what do you think?
