### ISSUE TITLE
[lit-helpers] ref directive

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#1126]
when all you have is a template and not a full web component it can become a hassle if you need to reference one node to another

Example:
```js
return html`
  <my-dialog>some content</my-dialog>
  <button @click=${() => dialog???.open()}>open dialog</button>
`;
```

a ref directive could allow getting a reference to the node
```js
import { setRef, getRef } from '@open-wc/lit-helpers';

return html`
  <my-dialog ~=${setRef('dialog')}>some content</my-dialog>
  <button @click=${() => getRef('dialog').open()}>open dialog</button>
`;
```

PS: `setRef` would be a directive whereas `getRef` is just a plain function

#### Why `~=`?
A directive needs a hook on an attribute or property in order to work. It could be anything... as a best practice proposal it could be `~=`... feel free to propose alternatives

#### Why `setRef` and not `setReference`
Good question - both are fine... one is short the other is more explicit.
Let us know what you would prefer.

**Comment by LarsDenBakker** [comment]
Great idea! I think a directive for getting a reference to an element would be good, but I think a global registry is problematic and I think unneeded. 

With just getRef you can do this:

```js
function myStory() {
  let dialogRef;
  return html`
    <my-dialog ~=${getRef(ref => dialogRef = ref)}>some content</my-dialog>
  <button @click=${() => dialogRef.open()}>open dialog</button>

`;
}
```

**Comment by daKmoR** [comment]
uh that looks even nicer 💪 
less magic ✨ is always good 👍

**Comment by georges-gomes** [comment]
function myStory() {
  return html`
    <my-dialog id="mydialog">some content</my-dialog>
  <button @click=${() => getRef("mydialog").open()}>open dialog</button>
  `;
}

**Comment by LarsDenBakker** [comment]
```
function myStory() {
  return html`
    <my-dialog id="mydialog">some content</my-dialog>
  <button @click=${e => e.target.getRootNode().getElementById("mydialog").open()}>open dialog</button>
  `;
}
```

**Comment by georges-gomes** [comment]
getRef() is simple :)

**Comment by paales** [comment]
```typescript
import { html } from 'lit-html'
import { LitElement, customElement } from 'lit-element'

@customElement('my-dialog')
class MyDialog extends LitElement {
  open = () => {}
}

const refs = {}
function getRef<T = HTMLElement>(key: string): [(element: T) => void, () => T] {
  return [
    (element: T) => {
      refs[key] = element
    },
    () => refs[key],
  ]
}

function myStory() {
  const [assign, ref] = getRef<MyDialog>('dialogref')
  return html`
    <my-dialog connectedCallback()=${assign}>some content</my-dialog>
    <button @click=${() => ref().open()}>open dialog</button>
  `
}
```

Would require lit-element to expose it's lifecycle callbacks, not sure if it's possible to do the `connectedCallback()` syntax.

**Comment by Cuttsy27** [comment]
We can also just create a function to return querySelector to provided string as ID easily enough without adding something like setRef and getRef to Lit?

**Comment by paales** [comment]
Fair point, I think i'd prefer this (less magic, less code):
```typescript
    <my-dialog id="mydialog">some content</my-dialog>
    <button @click=${() => this.querySelector('#mydialog').open()}>open dialog</button>
```

**Comment by daKmoR** [comment]
if all you have is a function then ids or query function might be dangerous... as you can't assume that there will be only one story in your current dom...  
```js
// story1.js
function myStory() {
  return html`
    <my-dialog id="mydialog">some content</my-dialog>
    <button @click=${() => getRef("mydialog").open()}>open dialog</button>
  `;
}

// story2.js
function myStory2() {
  return html`
    <my-dialog id="mydialog">some other content</my-dialog>
    <button @click=${() => getRef("mydialog").open()}>open other dialog</button>
  `;
}
```

if you render them both on the same page it would result in 
```html
    <my-dialog id="mydialog">some content</my-dialog>
    <button @click=${() => getRef("mydialog").open()}>open dialog</button>
    <my-dialog id="mydialog">some other content</my-dialog>
    <button @click=${() => getRef("mydialog").open()}>open other dialog</button>
```

which will fail for the same ID 🙈 also a querySelector to my-dialog would fail...

I think inside of those functions the only reliable way that works all the time is by using using a direct reference to the node...

**Comment by LarsDenBakker** [comment]
You could do things with `e.currentTarget.closest(...)` but a ref directive can be useful in other contexts. We will need to be careful with performance impact and creating memory leaks though.

**Comment by paales** [comment]
What is the reason you can't have a unique ID for each element? Create a factory method that passes you the index as an argument and create an ID for that purpose. Or do something like `Math.random` to randomly generate an ID.

The whole `ref` system is to go from Virtual DOM to real DOM of course :)

**Comment by LarsDenBakker** [comment]
lit-html templates are not the same as live DOM nodes either, so you still need something to map between templates and DOM nodes. Not so different from going from vritual DOM to real DOM.

I've played around with my proposed solution, but the challenge is that the template function is called for each re-render so we need something to store the state (dom reference) of the function for each rendered instance, and teach developers the right mental model. It's basically creating a hooks system.

I don't think a global reference registry is a good idea either, maybe we can do something where it's scoped to a particular template instance but that seems like a lot of work for something where the only known use case is a demos and tests.

@georges-gomes I'm not sure how your suggestion for `getRef("mydialog").open()` would work. Would that select from the document? Then it wouldn't for when rendered inside of a shadow root.

@paales your proposal suffers from the same drawbacks like mine, where we need to create a concept of maintaining state between function calls. What do you mean with `<my-dialog connectedCallback()=${assign}>some content</my-dialog>`? It's not valid syntax I think...

For the use case in the original issue post, I think this is actually pretty concise and reliable:
```js
html`
  <my-dialog ~=${setRef('dialog')}>some content</my-dialog>
  <button @click=${e => e.target.closest('my-dialog').open()}>open dialog</button>
  <!-- or -->
  <button @click=${e => e.target.previousElementSibling.open()}>open dialog</button>
`;
```

If you're able to guarantee unique ids, you can use `e.target.getRootNode().getElementById()` or `e.target.getRootNode().querySelector()`. We could perhaps create a helper to make that more concise?

Any thoughts on this?

**Comment by georges-gomes** [comment]
My proposal was more pseudo-code.
But a short helper for `e.target.getRootNode().getElementById()` sounds good to me 👍

**Comment by thepassle** [comment]
This comment may be a bit premature, but im not really sure how I feel about the `~` prefix, for a few reasons: We're gonna run out of weird symbols to use at some point, and 2: it gives me flashbacks to angularjs where nothing makes sense

![image](https://user-images.githubusercontent.com/17054057/71078574-f271c580-2189-11ea-9088-3ff269b44f36.png)

I think the prefixes lit-html uses make a lot of sense, `@` for events reads as '_at_ event', `.` for properties refers to setting props in js, etc. But `~` in relation to `ref` just doesn't mean anything to me, and I really dont look forward to having my templates filled with a bunch of symbols `~%*&` in the future 🙈

**Comment by jorenbroekema** [comment]
> I don't think a global reference registry is a good idea either, maybe we can do something where it's scoped to a particular template instance but that seems like a lot of work for something where the only known use case is a demos and tests.

I was also thinking of scoping it to a particular template instance, but technically I don't know how this is possible. How do you scope something to a lit html template instance?

For me the most important thing here is to be able to:
- refer from one part of your template, to another part in the same template
- without having to set up ID + querySelector, or needing to do some JavaScript stuff next to the template like offline rendering your reference as a node so you can refer to it in your template. 

A simple use case that goes beyond tests or demos is:
```html
<my-dialog>
  <button @click=${() => close the dialog}></button>
</my-dialog>
```
Right now that scenario can only be solved by either having the node reference somehow to the my-dialog or by bubbling an event to it, both non-ideal.

For me, the perfect API would be:
```html
<my-dialog ${setRef('dialog')}>Some content</my-dialog>
<button @click=${()=> getRef('dialog').open}>open dialog</button>
```
Where 'dialog' is a scoped reference on that lit-html template instance (avoiding conflicts that way).

How we can technically do this, I'm not sure :|
- How to setRef in the TemplateResult to refer to a node that doesn't exist yet.
- How to getRef in the TemplateResult to refer to a node that doesn't exist yet.

I lack knowledge on lit-html + directives to be able to reason about those challenges, but I am posting mostly to stress that for me a simple helper for `e.target.getRootNode().getElementById()` has very little to no value. I would never use it, I would just use the native JS one-liner 100% of the time.... because it's kinda straightforward. And it still has the downside that the user is responsible for ensuring a unique ID. With the ideal setRef/getRef you only need to ensure uniqueness in the scope of the directive of that specific template which is much less error prone, and it makes the template code very readable to me.

**Comment by daKmoR** [comment]
It seems we have 2 serious contenders

## 1. 
```js
function myStory() {
  let dialogRef;
  return html`
    <my-dialog ~=${getRef(ref => dialogRef = ref)}>some content</my-dialog>
    <button @click=${() => dialogRef.open()}>open dialog</button>
  `;
}
```
- scoped via javascript 👍 
- no internal data structure (e.g. no issues with garbage collection) 👍 
- needs "external" variable 👎 

## 2.
```js
function myStory() {
  let dialogRef;
  return html`
    <my-dialog ${setRef('dialog')}>Some content</my-dialog>
    <button @click=${()=> getRef('dialog').open}>open dialog</button>
  `;
}
```
- very intuitive (feels like an id) 👍 
- needs to be a unique name 👎 
- needs internal data structure (howto make sure it can be garbage collected?) 👎 


I would personally vote for 1 🤗 What do you guys think?

**Comment by jorenbroekema** [comment]
I think you forgot to delete `let dialogRef;` in the second option, which is actually why it's so good in my opinion, because you only have a template and **nothing else**
```js
function myStory() {
  return html`
    <my-dialog ${setRef('dialog')}>Some content</my-dialog>
    <button @click=${()=> getRef('dialog').open}>open dialog</button>
  `;
}
```

Number two definitely has my vote, because it supports my use case for not needing external javascript (template-only)

**Comment by LarsDenBakker** [comment]
I think that for your use case this is sufficient, and there is no need to make a reference registry:

```js
html`
  <my-dialog>some content</my-dialog>
  <button @click=${e => e.target.closest('my-dialog').open()}>open dialog</button>
  <!-- or -->
  <button @click=${e => e.target.previousElementSibling.open()}>open dialog</button>
`;
```

Also in the case of a demo system (like storybook) there should be a hook for getting a reference to the rendered element:

```js
export const myStory = {
  render: () => html`...my story...`,
  afterRender(element) {
    // imperative code after rendering
  } 
}  
```

I have a prototype for this for a storybook addon.

**Comment by daKmoR** [comment]
for the stories we write having a query selector is quite inconvenient as we have nodes that get moved to the body (for a11y reasons) so the button and the element you want to access may be in fastly different parts of the dom... same implications to an afterRender... it does not help us in this situation...

so a ref is basically the only thing that works always without needing unique generated IDs or so...

**Comment by jorenbroekema** [comment]
Yes, not just the stories but our dialogs in general, where the content node is moved outside of the scope of the <my-dialog> element, so the "relative" query selectors will not work like that.

**Comment by daKmoR** [comment]
how about adding 2 helpers

one for simple usecases (probably > 80% of cases)
```js
function myStory() {
  let dialogRef;
  return html`
    <my-dialog ref=${setRefAs(dialogRef)}>Some content</my-dialog>
    <button @click=${()=> dialogRef.open()}>open dialog</button>
  `;
}
// the ref in "ref=${}" is completely irrelevant you can call it foo=, bar=, ...
```

one where you want/need more control (e.g. if you wanna story it somewhere on an object)

```js
function myStory() {
  let dialogRef;
  const demoElements = {};
  return html`
    <my-dialog ${getRef(ref => demoElements.dialog2 = ref)}>Some content2</my-dialog>
    <button @click=${()=> demoElements.dialog2.open()}>open dialog2</button>
  `;
}
```

**Comment by LarsDenBakker** [comment]
@daKmoR that first example won't work, you can't reassign a variable in that way.

The relative query works fine in your use case even if you move the content to the DOM, the dialog element isn't moved. The dialog element should provide the necessary APIs to find the moved elements.

**Comment by bennypowers** [comment]
@daKmoR in your example above, would it be cool if the `ref` attr actually left behind a unique id string that maps to the js var, then referencing that ref would use a some `getRef` directive that used `getRootNode().querySelector(`[ref=${theRefId}]`)` under the hood?

**Comment by daKmoR** [comment]
There is now an official `ref` directive with the latest version of lit.

https://lit.dev/docs/api/directives/#ref
