### ISSUE TITLE
[karma-esm] implement importMap support

### ISSUE THREAD

**Issue by blikblum** [open-wc/open-wc#1127]
I tried to pass importMap option to karma-esm as pointed in docs but seems that this feature is not implemented at all.

I looked in the code and only place that deals with import maps are  in https://github.com/open-wc/open-wc/blob/8633499fa17987a57d6c25b63dc554e693cdacd8/packages/es-dev-server/src/utils/import-maps.js#L9 which uses importMaps extracted from an index html content. So it seems that importMap option is ignored at all.

This is something i can take a look but would like some guidance at what place this code handling should go.

At first look the importMap path content should be read somewhere in karma-esm, passed as option to dev-server and injected in es-dev-server `getTransformedIndexHTML`

**Comment by blikblum** [comment]
I looked at the code and the correct place to handle this is in karma-esm leaving es-dev-server untouched

**Comment by LarsDenBakker** [comment]
This should be added in a responseTransformer in karma-esm, to inject into debug.html an context.html

**Comment by blikblum** [comment]
Done
