### ISSUE TITLE
[Demoing Storybook] code sample unavailable

### ISSUE THREAD

**Issue by beth-panx** [open-wc/open-wc#1129]
![Screen Shot 2019-12-13 at 2 17 41 PM](https://user-images.githubusercontent.com/7429891/70835943-80793500-1db3-11ea-900c-600b10191255.png)

System: MacOS
Version: @open-wc/demoing-storybook": "^1.3.5
Browser: Chrome

repro: followed migration guide to update from 0.4.0 to 1.0.0

**Comment by LarsDenBakker** [comment]
This looks like it has been fixed in the meantime, sorry we didn't report back here.
