### ISSUE TITLE
[karma-esm] Could not resolve module imports in '.mjs' file

### ISSUE THREAD

**Issue by guillemcordoba** [open-wc/open-wc#1139]
I'm trying to use `karma-esm` to test my [libraries monorepo](https://github.com/uprtcl/js-uprtcl), writing typescript tests. 

A simple test that does not import anything else than the testing works fine, but a second test that imports `ApolloClient` fails with: 

```
Could not resolve module imports in /packages/lenses/node_modules/graphql/type/definition.mjs?08bad0e2a63e9ae2b6a670f55d590ce1a753555f: Unable to parse the module, this can be due to experimental syntax or a bug in the parser.
Error: Parse error at 24322.
    at parse (/home/guillem/projects/uprtcl/js-uprtcl/packages/common/node_modules/es-module-lexer/dist/lexer.cjs:1:401)
    at resolveModuleImports (/home/guillem/projects/uprtcl/js-uprtcl/packages/common/node_modules/es-dev-server/dist/utils/resolve-module-imports.js:203:48)
    at compileMiddleware (/home/guillem/projects/uprtcl/js-uprtcl/packages/common/node_modules/es-dev-server/dist/middleware/compile-middleware.js:137:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at watchServedFilesMiddleware (/home/guillem/projects/uprtcl/js-uprtcl/packages/common/node_modules/es-dev-server/dist/middleware/watch-served-files.js:40:5)
    at messageChannelMiddleware (/home/guillem/projects/uprtcl/js-uprtcl/packages/common/node_modules/es-dev-server/dist/middleware/message-channel.js:51:5)
    at responseCacheMiddleware (/home/guillem/projects/uprtcl/js-uprtcl/packages/common/node_modules/es-dev-server/dist/middleware/response-cache-middleware.js:107:5)
    at etagCacheMiddleware (/home/guillem/projects/uprtcl/js-uprtcl/packages/common/node_modules/es-dev-server/dist/middleware/etag-cache-middleware.js:14:5)
    at log404 (/home/guillem/projects/uprtcl/js-uprtcl/packages/common/node_modules/@open-wc/karma-esm/src/esm-config.js:62:7)
    at /home/guillem/projects/uprtcl/js-uprtcl/packages/common/node_modules/koa-compress/index.js:38:5 {
  idx: 24322
}

Could not resolve module imports in /packages/common/node_modules/graphql/type/definition.mjs: Unable to parse the module, this can be due to experimental syntax or a bug in the parser.
HeadlessChrome 79.0.3945 (Linux 0.0.0) ERROR
```

Here is the first test (passing):
```ts
import { html, fixture, expect } from '@open-wc/testing';

describe('<uprtcl-common>', () => {
  it('has a default property title', async () => {
    expect(true).to.equal(true);
  });
});
```

Here is the second test (failing): 
```ts
import { ApolloClient, InMemoryCache } from 'apollo-boost';

describe('basic GraphQl getEntity', () => {
  beforeEach(async () => {
    // Fails directly in this line
    const client  = new ApolloClient({
      cache: new InMemoryCache()
    });
  });
```

Here is my `karma.conf.js`: 

```js
/* eslint-disable import/no-extraneous-dependencies */
const cjsTransformer = require('es-dev-commonjs-transformer');
const { createDefaultConfig } = require('@open-wc/testing-karma');
const deepmerge = require('deepmerge');

module.exports = config => {
  const defaultConfig = createDefaultConfig(config);
  config.set(
    deepmerge(defaultConfig, {
      // see the karma-esm docs for all options
      esm: {
        babel: true,
        nodeResolve: true,
        fileExtensions: ['.ts', '.mjs'],
        responseTransformers: [
          cjsTransformer(
            ...defaultConfig.esm.babelModernExclude,
            '**/node_modules/@open-wc/**/*',
            '**/node_modules/chai-dom/**/*',
            '**/node_modules/sinon-chai/**/*'
          )
        ]
      },

      basePath: '../../',

      files: [
        { pattern: './tools/global-test-variables.js', type: 'module' },
        { pattern: 'packages/*/node_modules/graphql/**/*.mjs', type: 'module' },
        {
          pattern: config.grep ? config.grep : './packages/common/test/**/*.test.ts',
          type: 'module'
        }
      ]
    })
  );

  return config;
};
```

I need `es-dev-commonjs-transformer` to deal with commonjs dependencies.

And here is my `.babelrc`: 

```json
{
  "presets": ["@babel/preset-typescript"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "decoratorsBeforeExport": true }],
    "@babel/plugin-proposal-class-properties"
  ]
}
```

PD: Sorry I was typing the title of the issue and hit create before filling the description :)

**Comment by LarsDenBakker** [comment]
Do you have some more information?

**Comment by LarsDenBakker** [comment]
I spent some time investigating, but there is quite a lot to unpack here. Since you're using typescript, commonjs and `.mjs` files it's pretty easy for something to get lost in the shuffle somewhere. We do actually have tests for `.mjs` files which are passing.

I did find one issue with karma-esm not including used-defined response transformers https://github.com/open-wc/open-wc/pull/1140

Also, I saw that `es-dev-commonjs-transformer` has a hardcoded check where it returns for non `.js` files, that would need to be modified to support this use case.

**Comment by guillemcordoba** [comment]
Wow, really appreciate the quick response!

I updated to the new release, and now I get two more errors:

```
  TypeError: excludePaths.some is not a function
      at /home/guillem/projects/uprtcl/js-uprtcl/packages/common/node_modules/es-dev-commonjs-transformer/index.js:30:25
```

(I guess this one has to do with `es-dev-commonjs-transformer`.

And this one:

```
HeadlessChrome 79.0.3945 (Linux 0.0.0) LOG: 'Error loading test file: /packages/common/node_modules/graphql/type/definition.mjs'
HeadlessChrome 79.0.3945 (Linux 0.0.0) LOG: 'Error loading test file: /packages/common/node_modules/graphql/type/definition.mjs'
HeadlessChrome 79.0.3945 (Linux 0.0.0) LOG: 'Error loading test file: /packages/lenses/node_modules/graphql/type/definition.mjs'
HeadlessChrome 79.0.3945 (Linux 0.0.0) LOG: 'Error loading test file: /packages/lenses/node_modules/graphql/type/definition.mjs'
HeadlessChrome 79.0.3945 (Linux 0.0.0) LOG: 'Error loading test file: /packages/common/test/graphql/get-entity.test.ts'
HeadlessChrome 79.0.3945 (Linux 0.0.0) LOG: 'Error loading test file: /packages/common/test/graphql/get-entity.test.ts'
HeadlessChrome 79.0.3945 (Linux 0.0.0) LOG: 'Error loading test file: /packages/common/test/uprtcl-common.test.ts'

(And this gets repeated for a lot of files)
```

What should I do/expect? I already spent quite some time trying to get the tests to work, should I look into switching to something like `karma-webpack`?

**Comment by LarsDenBakker** [comment]
In theory it should be possible to make it work, mostly the commonjs transform is what makes it complicated because there are so many assumptions in existing codebases that can't always map properly. 

My suggestion is to try and create the most minimal reproduction and observe what's served in the browser. If you can push the setup somewhere, I can take a look.

**Comment by guillemcordoba** [comment]
I could reproduce the issue here: https://github.com/guillemcordoba/karma-esm-reproduction

I also found a minor issue in `es-dev-commonjs-transformer`: https://github.com/ashubham/es-dev-commonjs-transformer/issues/1, does not seem to affect the code from yesterday.

**Comment by LarsDenBakker** [comment]
I found the issue with `es-module-lexer`, I've reported it: https://github.com/guybedford/es-module-lexer/issues/39 he's usually quit fast with fixing them.

One thing I noticed is that you're loading all graphql files in your karma config, this shouldn't normally be needed since you're already importing it from the test files? When I remove it from the karma config, it doesnt load the problematic file. However it looks like some modules aren't transformed from commonjs to es module correctly, that's something to check with the transform plugin.

**Comment by guillemcordoba** [comment]
Great, thanks for all the support!

Yeah I thought so as well, I tried with that import in and out and it was giving issues, I was trying to tell `karma-esm` to interpret '.mjs' files as modules, but I guess that gets figured out automatically.

About the commonjs files, there isn't a better way to do it than that plugin right? My libraries depend to some degree on lodash, and that gets loaded as commonjs. I could use lodash-es, but it's not the recommended approach when your source code is in typescript.

**Comment by LarsDenBakker** [comment]
I think that plugin is the best way for it right now, es-dev-server and karma-esm are really intended for working with es modules. I'd definitely go for lodash-es, why would that be any different with typescript?

**Comment by blikblum** [comment]
@guillemcordoba 

You can try [this tip](https://github.com/open-wc/open-wc/issues/843#issuecomment-566295786)

**Comment by guillemcordoba** [comment]
Good! Updating the version of the lexer package did the trick. I'm facing now a new issue, I'll show it here but feel free to tell me I should open another one.

I have a dependency to feross's [buffer](https://github.com/feross/buffer), and running the tests throws this error:

```
Error compiling: Import "buffer" resolved to the file "buffer" which is outside the root directory. Install the module locally in the current project, or expand the root directory. If this is a symlink or if you used npm link,  you can run es-dev-server with the --preserve-symlinks option.
```

I've tried to install 'buffer' in the package where I'm running the tests, with no luck. Any directions/comments?

**Comment by LarsDenBakker** [comment]
That's interesting... I think it's resolving to the built-in node `buffer` library instead of the user provided one. That's definitely a bug, could you open an issue for this?

As a workaround, you could perhaps try importing the file directly `./node_modules/buffer/index.js` (not sure about the exact path) but I'll get this one fixed ASAP.

**Comment by guillemcordoba** [comment]
Created https://github.com/open-wc/open-wc/issues/1156, closing this one.
