### ISSUE TITLE
[testing-karma] Add option to disable loading snapshot plugins

### ISSUE THREAD

**Issue by blikblum** [open-wc/open-wc#1145]
I replaced a custom karma + rollup setup by testing-karma in one (non web component) library and is a great improvement.

Since i did not need snapshot support, i manually disabled snapshot plugins and startup time improved.

While is possible to manually disable, it is cumbersome and error prone. See the commit: https://github.com/blikblum/slick-router/commit/da71776d8aaea1f36fe8a97c2934293fb0e0a68d

So, any chance to have an option in `createDefaultConfig` to opt-out snapshot support?

**Comment by LarsDenBakker** [comment]
I want to try to avoid create configs to create configs, I'd rather create separate exports from the package for different use cases. How much extra startup time does it add?

**Comment by blikblum** [comment]
I need to profile. Do you have any idea how to profile?
