### ISSUE TITLE
Clarify use of await before fixture helper

### ISSUE THREAD

**Issue by blikblum** [open-wc/open-wc#115]
The docs are not consistent about usage of await before fixture helper:

In test custom element [example](https://open-wc.org/recommendations/testing-helpers.html#test-a-custom-element) await is used.
Just below, in test custom class [example](https://open-wc.org/recommendations/testing-helpers.html#test-a-custom-class) it does not use await.

This confused me: is necessary or not use await?

After looking into the source i found that fixture is a wrapper around fixtureSync followed to a nextFrame call.

It would be good to newcomers to clarify when await is needed before a fixture call and when not.

As i can see when using a string or a lit-html tagged template as fixture is not needed, but when using a lit-element await is necessary.

**Comment by daKmoR** [comment]
Hey,

thx for reporting this :)

fixture returns a promise so await is always recommended.

the examples for custom classes should be updated :)

care to create a Pull Request?

**Comment by blikblum** [comment]
> fixture returns a promise so await is always recommended.

I figured that. I ended using fixtureSync since somehow await is not working in my setup

> care to create a Pull Request?

Yes

**Comment by daKmoR** [comment]
> Yes

thx :)

fyi: depending on which custom element you are testing it may be that the custom element itself is async (e.g., for example, all lit-element extending elements are async) in that case you will need to check if you can make await work as otherwise, these elements will not be testable right after the fixture

**Comment by daKmoR** [comment]
you change is already visible at https://www.npmjs.com/package/@open-wc/testing-helpers :tada:

**Comment by blikblum** [comment]
> 
> 
> > Yes
> 
> thx :)
> 
> fyi: depending on which custom element you are testing it may be that the custom element itself is async (e.g., for example, all lit-element extending elements are async) in that case you will need to check if you can make await work as otherwise, these elements will not be testable right after the fixture

I'm aware of that. I understand that fixtureSync is for advanced use, those that know this caveats so is really better to promote usage of fixture
