### ISSUE TITLE
`storiesPattern` doesn't need be prefixed by `rootDir`

### ISSUE THREAD

**Issue by jorgecasar** [open-wc/open-wc#1151]
I notice that `storyUrls` are listed using the glob `storiesPattern` using `rootDir` as current working directory, then it's unnecessary prefixing it.

Without prefixing `rootDir` we have more flexibility with `stories` config flag (very useful in monorepos)

https://github.com/open-wc/open-wc/blob/bb3875dd7e356a2ca6b723d89b71d78ed3827ce7/packages/demoing-storybook/src/start/cli.js#L23-L24

**Comment by LarsDenBakker** [comment]
I merged https://github.com/open-wc/open-wc/pull/1152 but I'm not sure if it fixes your issue. A user would expect that the stories pattern resolves relative to your current working directory, not the root dir. Especially in monorepositories. With this change, you'd still be resolving from the root dir I think.

@daKmoR should we change this to resolve relative to the working directory?

**Comment by jorgecasar** [comment]
Yes, I tested locally and works in rootDir and monorepository. But It could be great if someone else can test it.

Thanks!

**Comment by LarsDenBakker** [comment]
Closing this as we settled on a solution in https://github.com/open-wc/open-wc/pull/1160
