### ISSUE TITLE
[building-rollup] breaking changes (v1)

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1153]
We are preparing a breaking change for `building-rollup`. The changes will improve the dev experience using the config generator, and implement more output optimizations.

This is the list of things we are planning, if you have anything you'd like to see let us know.

- [x] Rename current config to SPA config, to prepare for other types of configs in the future.
- [x] Use the new rollup multi output option
- [x] Use the new rollup plugin babel v5, which can run babel on a chunk instead of per file
- [x] Use babel runtime helpers, instead of duplicating them in each chunk.
- [x] Use babel preset modules.
- [x] Split rollup index html plugin into separate plugins with a single job, making it much easier for people to compose and tweak the settings.
- [x] Use the new rollup asset API for outputting assets, also making it easier for people to control their output index html
- [x] Add docs explaining the necessary steps to create your own rollup config for web components and/or lit html.
- [x] Remove all options from the config creator, use standard rollup input option for input and document filtering/modifying plugins using a simple array filter or map.
- [x] Encourage forking the rollup config, or extending only the base config, for experienced users.

**Comment by LarsDenBakker** [comment]
We released a beta version of https://github.com/open-wc/open-wc/tree/master/packages/rollup-plugin-html which takes us part of the way. @thepassle and I are working on an update of the rollup config.

**Comment by abdonrd** [comment]
We can add update to Rollup v2 here, right?

**Comment by LarsDenBakker** [comment]
Yes indeed. We're almost done, prepared in this repository: https://github.com/open-wc/building-rollup-changes

Sorry this took quite a long time to set up :)

**Comment by abdonrd** [comment]
@LarsDenBakker awesome! There are any ETA?

**Comment by LarsDenBakker** [comment]
I'm trying to push it out as soon as possible :) My aim is this weekend or next.

**Comment by LarsDenBakker** [comment]
This was implemented in v1 of building-rollup.
