### ISSUE TITLE
[demoing-storybook] question - import global css 

### ISSUE THREAD

**Issue by atla5** [open-wc/open-wc#1154]
_NOTE: this is low priority and almost certainly not a bug, but a misunderstanding/lack of clarity on my part._

### Quick Overview

What is the **standard/best way to import global CSS** into your main `index.(html, js?)` such that you don't need to have multiple imports for each environment?

I've **got an effective workaround**  that I'm not too concerned about (so no rush), but Ideally I'd like to have the path automatically adjusted in the process of `build_storybook`.

### Background

I’m trying to centralize the inclusion of a number of css files into **global css** affecting my entire component library. 

I'd like to use the same method of inclusion for all environments (local, built, and deployed), but currently am having to concatenate them all and copy them over manually in rudimentary script.

```css
/* assets/css/shared.css */
@import url("./common.css");
@import url("./variables.css");
@import url("./layouts.css");
@import url("./benton-font.css");
@import url("./material-icons.css");
@import url("./card.css");
@import url("./cta.css");
@import url("./tabs.css");
@import url("../../src/header/header.css");
```

### Context

In a [previous version](https://github.com/bulib/bulib-wc/blob/master/docs/index.stories.js#L11)
   of storybook and open-wc, i was able to import my `shared.css` file like so:

```javascript
/* docs/index.stories.js */
import { storiesOf } from '@open-wc/demoing-storybook';
import '../src/index.js';
import '../assets/css/shared.css';
```

After switching to storybook 5.2 (and upgrading `open-wc`), the css import broke, and I’ve had to use the `.storybook/preview-head.html` method, which is working locally, but breaks when it’s deployed (since the path changes).

```html
<link rel="stylesheet" href="../assets/css/shared.css">
```

#### versions/pre-reqs

I'm using the following scripts and dependencies in my **`package.json`** and working from the `npm init @open-wc` boilerplate/docs:

```json
"scripts": {
  "storybook:build": "build-storybook --stories 'src/*/*.stories.mdx'",
  "deploy:storybook": "npm run storybook:build && storybook-to-ghpages"
}
...
"devDependencies": {  
  ...
  "@open-wc/demoing-storybook": "^1.0.1",
  "@storybook/cli": "^5.2.3",
  "@storybook/storybook-deployer": "^2.8.1",
  ...
}
```

#### locally
running it locally (via `start-storybook `) with the relative path syntax in the `.storybook/preview_head.html` (as above) works just fine:

```bash
$ git clone https://github.com/atla5/wc-setup.git
$ npm i
$ npm run storybook
``` 

see that the color shows up (you can see #CC0000 under the ‘--color-accent-background’ ):
![color showing up because relative works on local just fine](https://user-images.githubusercontent.com/5565284/71205738-0f34f880-2271-11ea-8ed0-c09ee8deb83f.png)

#### built version 

building it and running it from the built directory (via `build-storybook`), however, and the css isn’t working out because the path changes:

```bash
$ npm run start:build
```

![color doesn't show up because of broken path](https://user-images.githubusercontent.com/5565284/71205958-7f437e80-2271-11ea-8fc3-d2451a7d9b27.png)

**Comment by LarsDenBakker** [comment]
These imports used to work because storybook uses webpack, and allows importing CSS. Now we're using `es-dev-server` which uses just the browser's own capabilities. CSS modules aren't supported (yet).

Using `preview-head.html` should be the right solution here for global CSS. Which paths are changing/which files aren't being loaded properly?

**Comment by atla5** [comment]
Thank you for the explanation, that makes sense to me. No further action is needed, then. 

I'm happy to see the move away from `webpack` and build systems, and will continue using `preview-head.html` with both local and deployed paths.
