### ISSUE TITLE
[testing-karma] Error when using snapshots

### ISSUE THREAD

**Issue by blikblum** [open-wc/open-wc#1166]
After i upgrade @open-wc/testing-karma from 3.2.17 to 3.2.21 i get the following error:

```
  Uncaught SyntaxError: Invalid or unexpected token
  at __snapshots__/Tags.md:1:1
  SyntaxError: Invalid or unexpected token
Chrome 79.0.3945 (Windows 10.0.0) ERROR
  Uncaught SyntaxError: Invalid or unexpected token
  at __snapshots__/app-header.md:1:1
```

Downgrading it, the error does not occurs.

See https://github.com/blikblum/lit-element-mobx-realworld-example-app yarn and yarn test to trigger the error

**Comment by LarsDenBakker** [comment]
Did you also update `karma-esm` as it requires a change from that as well.

**Comment by blikblum** [comment]
I just added [@open-wc/testing-karma](https://github.com/blikblum/lit-element-mobx-realworld-example-app/blob/master/package.json#L13) as [the instructions](https://open-wc.org/testing/testing-karma.html#setup) 
karma-esm is a dependency of it

**Comment by blikblum** [comment]
By updating @open-wc/testing-karma it also updated [karma-esm](https://github.com/blikblum/lit-element-mobx-realworld-example-app/commit/d3e40c5d7c324281e96c2db2bf6e838b04899820#diff-8ee2343978836a779dc9f8d6b794c3b2R978) from 2.11.10 to 2.11.14

**Comment by LarsDenBakker** [comment]
I checked this a couple of times, but I couldn't reproduce it. Turns out it was a windows specific issue. Fixed by https://github.com/open-wc/open-wc/pull/1200

**Comment by blikblum** [comment]
Uograded to     "@open-wc/testing": "^2.4.3",    "@open-wc/testing-karma": "3.2.27",

Now i get HeadlessChrome 79.0.3945 (Windows 10.0.0) LOG: 'Error loading test file: /test/app-header.test.js'

**Comment by LarsDenBakker** [comment]
Unfortunately we had another issue as well 👀can you try with 2.5.0 of testing?

**Comment by blikblum** [comment]
Works now. Many thanks
