### ISSUE TITLE
[testing-karma] Unhelpful error when using invalid grep

### ISSUE THREAD

**Issue by blikblum** [open-wc/open-wc#1167]
If i try to use --grep option with an invalid value i get the following error:

```
  TypeError: Cannot read property 'map' of null
      at fetchKarmaHTML (D:\repositories\react-mobx-realworld-example-app\node_modules\@open-wc\karma-esm\src\setup-es-dev-server.js:62:6)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

A more helpful message would good

For https://github.com/blikblum/lit-element-mobx-realworld-example-app
This does not work
```
npm run test -- --grep tags
```

This works
```
npm run test -- --grep test/tags*
```

**Comment by LarsDenBakker** [comment]
@bennypowers reported this as well, it's tackled by https://github.com/open-wc/open-wc/pull/1138

**Comment by LarsDenBakker** [comment]
https://github.com/open-wc/open-wc/pull/1138 was merged
