### ISSUE TITLE
Recommend webpack-babel-multi-target-plugin for modern build

### ISSUE THREAD

**Issue by web-padawan** [open-wc/open-wc#118]
See implementation in web-padawan/polymer3-webpack-starter@fb82b28a0ae697cdfed3a34e88bd81aa40f059ba

The results of the config for the starter app (first page load in Chrome 71):

## Before (ES5)

Load: 2.00 s (9 requests)

<img width="581" alt="screen shot 2019-01-07 at 8 16 12" src="https://user-images.githubusercontent.com/10589913/50751974-cbf69b00-1254-11e9-9ab8-3f0e2452a08d.png">

## After (ES6)

Load: 1.35 s (7 requests)

<img width="579" alt="screen shot 2019-01-07 at 8 17 00" src="https://user-images.githubusercontent.com/10589913/50752019-f3e5fe80-1254-11e9-9fc8-d592b13637f3.png">

**Comment by LarsDenBakker** [comment]
That's a great plugin, thanks for sharing!

**Comment by LarsDenBakker** [comment]
I'm seeing some caveats around code splitting. Have you had any experience with this yet?

**Comment by web-padawan** [comment]
What kind of caveats have you encountered so far? We are also interested, especially the team currently working on [base-starter-connect](https://github.com/vaadin/base-starter-connect) project who actually decided to try this plugin for modern build.

**Comment by LarsDenBakker** [comment]
In the documentation there are a few mentions of dynamic loading / code splitting and some caveats. I'm haven't used the plugin yet, so I was wondering if you ran into anything with it yet.

**Comment by daKmoR** [comment]
thx for bringing this our attention - this is now part of our recommended webpack build: https://www.npmjs.com/package/@open-wc/building-webpack

More details: https://open-wc.org/building/
