### ISSUE TITLE
404 on https://open-wc.org/faq/component-libraries.html

### ISSUE THREAD

**Issue by softdays** [open-wc/open-wc#1184]
At the moment we got a HTTP 404 on https://open-wc.org/faq/component-libraries.html

**Comment by thepassle** [comment]
This page moved to https://open-wc.org/guide/component-libraries.html

**Comment by softdays** [comment]
Thanks you very much!

**Comment by softdays** [comment]
So the FAQ page link to the `component-libraries.html` should be updated accordingly.

**Comment by thepassle** [comment]
fixed here https://github.com/open-wc/open-wc/pull/1188
