### ISSUE TITLE
[demoing-storybook] allow extending rollup config

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1206]
The `@open-wc/demoing-storybook` build command should allow extending the rollup config, probably it can be a factory function in the `build-storybook.config.js` file:

```js
module.exports = {
  rollupConfig = baseConfig = ({
    // config additions
  }),
}
```

Open for PRs if anyone needs this

**Comment by Alucard17** [comment]
Hi @LarsDenBakker  I would like to work on this, can you guide me what i have to do

**Comment by LarsDenBakker** [comment]
@Alucard17 Sorry, I missed your reply here. We implemented it at https://github.com/open-wc/open-wc/pull/1232 because we actually need it for another project. Really sorry about that!
