### ISSUE TITLE
[testing-karma] Cannot execute a single test when running `test:watch`

### ISSUE THREAD

**Issue by goremikin** [open-wc/open-wc#1208]
In demo sample when running `test:watch` in DEBUG mode, I cannot execute a single test (a small right handed arrow next to each test). For instance: `http://localhost:9876/debug.html?grep=OpenWc has a default title "Hey there" and counter 5`.

The problem is with `inline-module` that incorrectly interprets `grep` argument.

**Comment by goremikin** [comment]
This is still an issue

**Comment by daKmoR** [comment]
we recommend `@web/test-runner`. If the issue persists there feel free to open an issue at https://github.com/modernweb-dev/web
