### ISSUE TITLE
[es-dev-server] CustomStyleInterface polyfill is missing

### ISSUE THREAD

**Issue by TremayneChrist** [open-wc/open-wc#1209]
When serving to legacy browsers, the ShadyCSS.CustomStyleInterface polyfill is not loaded. This means external CSS Variables cannot be used to style elements.

```html
<style>
  my-custom-element {
    --my-prop: red;
  }
</style>

<my-custom-element>
  <!-->begin: shadow<-->
  <style>
    :host {
      color: var(--my-prop, blue);
    }
  </style>
  <slot></slot>
  <!-->end: shadow<-->
  Colour should be red.
</my-custom-element>

<script>
  ShadyCSS.CustomStyleInterface.addCustomStyle(document.querySelector('style'));
</script>
```

**Comment by daKmoR** [comment]
do yeah mean something like this?
https://github.com/open-wc/open-wc/pull/809

**Comment by TremayneChrist** [comment]
Something like that, yeah. Mainly [this](https://github.com/open-wc/open-wc/pull/809/files#diff-0a09ec55ca2108cb9656fd314415a8e8R181).

**Comment by LarsDenBakker** [comment]
Which package is this actually a part of? Why isn't it loaded with the regular web component polyfills?

**Comment by TremayneChrist** [comment]
It looks like it's only loading the core parts of shady css and doesn't include the `CustomStyleInterface`.

https://github.com/webcomponents/polyfills/tree/master/packages/shadycss#about-customstyleinterface

**Comment by TremayneChrist** [comment]
Any plans on adding this in?

**Comment by gregorymachon** [comment]
+1

**Comment by LarsDenBakker** [comment]
With https://github.com/open-wc/open-wc/pull/1292 there is an option to configure to load this

**Comment by daKmoR** [comment]
and it's released 🎉
