### ISSUE TITLE
[testing-karma] Disconnected, because no message in 10000 ms.

### ISSUE THREAD

**Issue by Westbrook** [open-wc/open-wc#1211]
I get this issue pretty regularly (maybe 40% of the time) when running my tests in CI, though almost never when running locally 😓 However, it seems there is a path forward: https://github.com/jasmine/jasmine/issues/1327#issuecomment-524281104

I added `karma-chrome-launcher@^3.1.0` to my local project and manually removed `karma-chrome-launcher@^2.0.0` from my `node_modules` as a rough test of this, and my tests ran fine on local. So, hopefully, there's no reason to worry about this change, generally. Whether it actually solves my CI issue or not 🤞 

I'll make a PR for the update of `karma-chrome-launcher@^2.0.0` -> `karma-chrome-launcher@^3.1.0`, but please respond here with any issues you think that might bring to light.

**Comment by Westbrook** [comment]
@daKmoR is it possible to release `beta` or `canary` versions to NPM so I can test this on my project first?

**Comment by daKmoR** [comment]
@Westbrook 

```
Successfully published:
 - @open-wc/testing-karma-bs@1.3.29-alpha.0
 - @open-wc/testing-karma@3.2.29-alpha.0
```

**Comment by LarsDenBakker** [comment]
@daKmoR could you describe how to do it? Maybe in contributing.md? :)

**Comment by Westbrook** [comment]
Thanks @daKmoR! I’ll be testing these updates tomorrow night. 🤞🏼

**Comment by Westbrook** [comment]
The changes upstream did not end up being what _mitigated_ this issue for me. After a pretty exhaustive review I found that for years people have just been adding something like:
```
            browserDisconnectTolerance: 2,
            browserNoActivityTimeout: 60000,
```
To their `karma.config.js`. I'm not sure if that's something that we should look at adding by default. I guess if no one else runs into this issue on CI, then no...though that means there's something that's just me going on, which is 😞
