### ISSUE TITLE
[lit-helpers]: converter factories

### ISSUE THREAD

**Issue by bennypowers** [open-wc/open-wc#1216]
This issue is a **feature request**/RFC on an idea that came to me today.

There are times when an observed property/attribute pair needs more nuance to it than the built-in constructors. 

An example of this is enumerated attributes:

```js
/** @type {'this'|'that'|'the-other'} */
@property({ type: String }) thing = 'this';
```

The built in String constructor will not suffice here, as it would accept any string, e.g. `<x-e thing="nothing"></x-e>`

So we'd need to implement a [`converter`](https://lit-element.polymer-project.org/guide/properties#conversion-converter):

```js
/** @type {'this'|'that'|'the-other'} */
@property({
  converter(value) {
    const ALLOWED = ['this', 'the-other', 'that']
    return ALLOWED.includes(value) ? value : undefined;
  }
})
thing = 'this';
```

I think this is a common enough need (enumerated attributes are common in html) that some helpers merit publishing:

```js
import { enumerated } from '@open-wc/lit-helpers/attributes';

const thingConverter = enumerated(['this', 'that', 'the-other']);

class XE extends LitElement {
  @property({ converter: thingConverter }) thing = 'this';
}
```

Another interesting case could be reference by id within the local root:

```js
import { idRef } from '@open-wc/lit-helpers/attributes';

@customElement('form-analytics')
class FormAnalytics extends LitElement {
  @property({ converter: idRef }) for;
}
```

```html
<form id="purchase">
  <!-- ... -->
</form>
<form-analytics for="purchase"></form-analytics>
```

**Comment by kuka-radovan** [comment]
I have done my enumeration feature exactly the same way... it is really useful feature

**Comment by hsablonniere** [comment]
Would you log an error or something on top of not allowing the bad value?

**Comment by daKmoR** [comment]
but it's not about conversion right?
even if you do not reflect to attribute or you do not have an Attribute at all it should only accept the coded values right?

depending on your use case I would throw an error in order to make sure developers don't use wrong values (if it can depend on user input then it's a different story) but for developers imho you should throw

**Comment by bennypowers** [comment]
HTML elements generally don't throw errors (or log to the console) when you set their attributes, though.

**Comment by frank-dspeed** [comment]
i would throw errors and all my elements do so else they would not be test able ........
