### ISSUE TITLE
Support web_modules

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1219]
web_modules is the folder name used by pika, I think it would be useful if we resolve imports from this folder directly. this will require changes to building rollup, webpack and es-dev-server.

web_modules is also generic enough that it might be used by other tools as well, I think I've seen it around before somewhere.

CC @thepassle @FredKSchott

**Comment by thepassle** [comment]
@LarsDenBakker Can you give me some pointers how to start on this? Would like to take a stab at it

**Comment by LarsDenBakker** [comment]
I think making https://github.com/open-wc/open-wc/blob/master/packages/es-dev-server/src/config.js#L138 default to node_modules and web_modules should be enough.

**Comment by LarsDenBakker** [comment]
@thepassle are you still looking to pick this up?

**Comment by thepassle** [comment]
Yes definitely, I missed your last comment
