### ISSUE TITLE
[semantic-dom-diff] TypeScript typings aren't available

### ISSUE THREAD

**Issue by justinfagnani** [open-wc/open-wc#1228]
When I import `@open-wc/semantic-dom-diff`, TypeScript complains that it can't find the module. The .d.ts file is installed with the package, though I don't see a `"typings"` entry in package.json.

**Comment by LarsDenBakker** [comment]
@bennypowers I think you fixed this one?

**Comment by bennypowers** [comment]
in c8a3b18936de43cba0227c146e77b60a04327e41
