### ISSUE TITLE
[docs] links to storybook dont work

### ISSUE THREAD

**Issue by drBenway** [open-wc/open-wc#1231]
Page: https://open-wc.org/demoing/#demo

The 2 links  in the demo box give console errors:
- https://open-wc.org/demoing-storybook/?path=/docs/demo-card-docs--simple
and 
https://open-wc.org/demoing-storybook/?path=/docs/decorators-withwebcomponentknobs--example-output

Tested in recent Chrome and latest Firefox

**Comment by AERK-work-account** [comment]
Links work; this seems to be a storybook build issue related to other storybook build issues.

**Comment by LarsDenBakker** [comment]
Thanks for reporting this guys, we had an issue with our deployment script. We fixed it now!
