### ISSUE TITLE
Replace live directive

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1245]
The live directive is being implemented in `lit-html` main library: https://github.com/Polymer/lit-html/pull/1057

We should recommend using that one instead. I think it's functionally equivalent, with some more error handling, so we should be able to just reexport from `lit-html` to avoid breaking changes.

**Comment by daKmoR** [comment]
As we update to the latest Lit release all directives need a breaking change - we will remove `live` with this change

to be released soonish
