### ISSUE TITLE
rollup-plugin-index-html handle imports. as input

### ISSUE THREAD

**Issue by frank-dspeed** [open-wc/open-wc#1247]
I am often doing single file components where i inline everything into the html even <script type="module">import myStruff</script>

and also cjs <script>import()</script>

i would love to see this case handled with index-html 

**importent is ***
cjs needs to stay cjs and esm needs to stay esm they have diffrent loading algos that trigger in diffrent dom state.

it should only inline or build the import from statements from esm and the dynamic imports from cjs
it should in general sanitize any urls referencing js

rollup has now also support for data urls that should also get used here.

i created a little https://github.com/direktspeed/esm-loader that allows isomorphic loading via data url feature 

here is the rollup support for it https://github.com/rollup/plugins/pull/150

**Comment by LarsDenBakker** [comment]
I dont quite understand what you mean exactly. I dont think we should treat scripts as modules.

**Comment by frank-dspeed** [comment]
sure we should we should see index HTML as entry point that loads scripts and also it self contains scripts of 2 types 

index.html => index.js, index.mjs => dependencys of both files.

```html
<!-- Will end up in index.mjs as every other module it makes no trouble as modules are self encapsulated at all --> 
<script type="module">
import toplevel from "top-level"
// some more code that does
import().then()
// To make it a evil horror we will simply add some extra assets
import("data:base64")

</script>

<!-- Some thing for index.js -->
<script>
// Some magic let it change title 
window.title = "Hello"
</script>

<script>
// Some magic that gets landed directly into the index.js not with a extra module identifyer as JS has no module system.

</script>
```

**Comment by frank-dspeed** [comment]
@LarsDenBakker ok i agree we should not handle the scripts and modules them self we should handle the imports they are doing so static and dynamic import
