### ISSUE TITLE
[es-dev-server] polyfills are not always being loaded

### ISSUE THREAD

**Issue by tmsns** [open-wc/open-wc#1248]
When es-dev-server is adding its polyfills (eg. for IE) the script urls for the polyfills are not always resolving. This is happening when following two conditions match:

- when no `<base />` tag to the root of the project is used in the appIndex
- when a page in a sub path is accessed (ie. http://localhost:8000/sub/sub)

I'll see if I can make a PR for this. 😃

**Comment by tmsns** [comment]
I see two solutions here:
- make sure es-dev-server can resolve polyfills request in sub paths by changing [transform-index-html.js#L47](https://github.com/open-wc/open-wc/blob/master/packages/es-dev-server/src/middleware/transform-index-html.js#L47)
- change the references for the script tags [create-index-html.js#L127](https://github.com/open-wc/open-wc/blob/master/packages/building-utils/index-html/create-index-html.js#L127) and the loader script [loader-script.js#L125](https://github.com/open-wc/open-wc/blob/master/packages/building-utils/index-html/loader-script.js#L125). But as this is `building-utils`, it also affects the build version. And over there, it sometimes needs to be relative to the base path. So, we could pass the root path for the polyfills from dev server to build-utils, but that seems overkill.

What do you think @LarsDenBakker?

PS: while looking through the code I notice that by default we add polyfills for fetch and webcomponents by default. As es-dev-server is, afaik, more targeted for using regular (hence the name), shouldn't those polyfills be optional? Or maybe having a system to hook in other polyfills as well?

**Comment by LarsDenBakker** [comment]
I think for es-dev-server we will need to use absolute paths to make this work. I have a bit refactor of the way we generate polyfills for the index.html on a branch, probably that's the best place to implement it.

**Comment by tmsns** [comment]
> I think for es-dev-server we will need to use absolute paths to make this work. I have a bit refactor of the way we generate polyfills for the index.html on a branch, probably that's the best place to implement it.

I guess you mean server-relative paths instead of pure relative paths? This will have the same effect as absolute paths, but without the host. And I don't think you specifically need the host, right?

So based on your response, I think you want the something like the second solution, changing the reference (and probably passing a root to build-utils, if build-utils is still involved in the generation of polyfills in the new branch)

**Comment by LarsDenBakker** [comment]
Yes that's the one. Started last year, been working on it on and off.

I created a separate package for the whole polyfills loading logic: https://github.com/open-wc/open-wc/tree/feat/polyfills-loader/packages/polyfills-loader, extracting it from building utils. The idea is to make it clearer what it does, and easier to customize.

There is already something in there for specifying the polyfills directory, it might need to be tweaked to make it work. 

I started working on integrating it with es-dev-server, I don't remember how far I got. The polyfills loader package is stable now.

**Comment by LarsDenBakker** [comment]
I just pushed the latest code which I had locally. There is a readme, but it's not up to date with the config structure. Best to look at the typescript types + tests.

**Comment by LarsDenBakker** [comment]
I have a PR up for this now https://github.com/open-wc/open-wc/pull/1261, are you still interested in picking this up?

**Comment by tmsns** [comment]
Saw the PR. But wasn’t able yet to go through all the code: some busy week(s).
Always interested to help out. I might be able to already take a look tomorrow or Friday. But if you already have something extra ready: go for it!

**Comment by tmsns** [comment]
The problem might be fixed in the MR. 😃 
There is a new config parameter `cfg.polyfillsDir` which let you specify the dir to use. I expect that when I use a server relative dir in the configuration `polyfillsDir: '/polyfills'` that it will work and that the es-dev-server will resolve them from this new directory.

**Comment by LarsDenBakker** [comment]
I merged https://github.com/open-wc/open-wc/pull/1261 now

I added multi-page demos and integration tests, and they're all passing for me on mac and windows. The polyfills loader tests all pass on windows too, but es-dev-server has other failing tests on windows. Some are due to whitespace differences, but as you mentioned there is an issue with symlinks. But that's already there on master too.

I didn't need to customize the polyfills dir, can you check if it works for you too?

**Comment by LarsDenBakker** [comment]
Closing this one since the issue was fixed.
