### ISSUE TITLE
Dev server

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#125]
We should create a recommendation what to use as a dev server during development.

I think it's really useful to have a dev server similar to `polyserve` but with the ability to just read the project's .babelrc.

At the same time if we're using webpack to bundle our app, it becomes really easy to just use the webpack dev server as well. It's mostly just plug and play.

**Comment by daKmoR** [comment]
we now have very simple dev server: https://www.npmjs.com/package/owc-dev-server
