### ISSUE TITLE
Rollup config does not pick up changes to index.html in watch mode

### ISSUE THREAD

**Issue by maxwell8888** [open-wc/open-wc#1256]
I am using the rollup config `createDefaultConfig` from `@open-wc/building-rollup` as supplied by `npm init @open-wc`. I am not using esdevserver during development as suggested, instead I need to use my own server, so I run `rollup -c -w` during development and my dev server serves the build that is generated. Rollup successfully picks up changes to js and rebuilds, but does not pick up on changes to `index.html`, so I have to restart `rollup -c -w`. It would be great if the rollup config could be updated to handle this.

**Comment by LarsDenBakker** [comment]
Rollup now has a asset api which we can use for this, that didnt exist before.

**Comment by bennypowers** [comment]
For reference to whomsoever wants to tackle the PR, I whipped up this little ad-hoc plugin in a project earlier today.

```js
{
  name: 'watch-assets',
  load() {
    this.addWatchFile(require('path').resolve('./index.html'));
    this.addWatchFile(require('path').resolve('./styles/style.css'));
    this.addWatchFile(require('path').resolve('./styles/print.css'));
  },
}
```

**Comment by LarsDenBakker** [comment]
We should add this to `@open-wc/rollup-plugin-html`

**Comment by bennypowers** [comment]
so I ended up publishing that ad-hoc plugin [here](https://http://npm.im/rollup-plugin-watch-assets)

not saying it's a good plugin, just saying it's a plugin :D
