### ISSUE TITLE
Evaluate showroom for automated tests / DDD env

### ISSUE THREAD

**Issue by eavichay** [open-wc/open-wc#126]
https://www.npmjs.com/package/showroom

Showroom is an alternative to storybook focusing web-components and supporting the FULL API (i.e. attributes, properties, events, innerHTML and outerHTML) - features that cannot be found on storybook without cumbersome work.

Showroom also supports puppeteer API for automated tests and can be integrated with non-puppeteer test runners.

**Comment by daKmoR** [comment]
thx for reaching out to us :)

We will check it out - however, it will probably take some time 🙈 
We are still quite busy with all the basics...

**Comment by eavichay** [comment]
@daKmoR Ping?

**Comment by daKmoR** [comment]
wow time flies by 🙈  I'm so sorry didn't had the chance yet... it's still on my todo 🙈

**Comment by eavichay** [comment]
@daKmoR ping?

**Comment by daKmoR** [comment]
@eavichay so I finally had a close look at showroom... however I'm a little confused - it seems more an alternative to Storybook? so my question would be what's different to storybook then? (storybook uses js but the upcoming docs mode will also support mdx... showroom seems to use a custom data set with md inside? just my assumption from seeing this https://github.com/eavichay/showroom/blob/master/example/.showroom/showroom.demo-component-avengers.js

For testing it seems to be sort of "just a server"... e.g. you use puppeteer to do the work of doing the actual e2e tests... so I assume this is not "competing" with karma... as it's not multi browser and does not support running via browser services like browserstack/sourcelabe right?
So my question would be "what are the benefits of using it over native puppeteer or cypress.io?"

**Comment by eavichay** [comment]
The pros vs storybook: Easy setup, Full puppeteer integration.
It supports attributes, properties, inner and outerHTML (that affects how the component behaves).
We are using this tool (production product) as we need to support all kinds of custom elements (from multiple libraries) that behaves in different host-contexts, different attributes and executing functions that alters their inner state.

After attempts to use storybook we found that we require too much boilerplate for full coverage of unit-tests for our components.

Replacing innerHTML/outerHTML requires storybook to create multiple stories for components and we cannot share styles using isolated IFRAMES.

Storybook is mostly for DDD and cataloging the components, as showroom provides easier integration with unit tests.

Running unit tests via browserstack seems a bit overhead as E2E tests are covering more behavior and running unit-tests is expensive on browserstack, but this is a feature to be supported.
