### ISSUE TITLE
rename scoped elements to uniqeElementTag

### ISSUE THREAD

**Issue by frank-dspeed** [open-wc/open-wc#1260]
It has nothing to do with scope we should rename it uniqeTag as that is what it does it returns a uniqeTagname if needed for a Element and registers it under that uniqe tag.

**Comment by thepassle** [comment]
From what I can see in the PR, and as I understand it the elements actually _are_ scoped by the 'origin' element where `createScopedHtml` is used.

I also think it's quite nice to have some parity with the [scoped custom elements registry proposal](https://github.com/w3c/webcomponents/issues/716).

If we _do_ decide to change the name, it should be `uniqueElementTag`. 'Uniq' is not an english word.

**Comment by frank-dspeed** [comment]
@thepassle your not correct its not really scoped to that it uses a map at present it depends on the bundler what happens :) the map is maybe shared over all instances.

but thats not the point i see there no real scope as this is backed by the custom element registry on window and then also all elements will render with the right name anywhere on page that leads to even more funny effects :) 

the name algo used at present is incementing the provided basename so imagin a component called my-element-v1 could get registered under my-element-v2 and my-element-v2 can get my-element-v3 and that for the whole page

while scoped element registry is a real isolated way of doing that with a mutation observer and assigned definitions

**Comment by daKmoR** [comment]
We choose this name as from a users point of few it allows them to "scope" the elements they are using... e.g. allow to use the specific version they depend on... without running into registration errors

indeed technically it is not a fully correct term but let's call it artistic freedom... also it is probably easier to "market" (and such a feature will only succeed if the community can get behind it... especially as it requires a shift towards not self-register components)

once a bigger set of users has tried out and evaluated it - we can reevaluate the name.

For now, I am going to close this as we are not going to take action on it
