### ISSUE TITLE
Scoped Elements Discussion 

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#1262]
This is a general issue regarding our new experimental feature [scoped-elements](https://open-wc.org/scoped-elements/). Please use this thread for any feedback, criticism, concerns, or questions you may have regarding this library.

Related Issues:
- [[scoped-elements] demos/docs code does not support extending elements](https://github.com/open-wc/open-wc/issues/1272)
- [[scoped-elements] add option to retrieve the tags used in WC definition](https://github.com/open-wc/open-wc/issues/1270)

**Comment by mzeiher** [comment]
Hi, I really like the solution and looking forward for a stable release, this solves some issues we had in our projects. The current utilities are quite static, we use a lot of dynamic imports for code splitting I just prototyped a mixin which would work nice with your implementation
https://github.com/mzeiher/lit-html-scoped-registry-helper/blob/with-dependencies-mixin/src/lib/with-dependencies.ts
```
class MyElement extends WithDependency({'info-element': async () => (await import('./infoelement.js)).InfoElement }, LitElement) {

  renderFallback() {
    return html`Loading...`
  }

  renderContent() {
    return this.scopedHtml`<info-element></info-element>`;
  }
}
```
when one of the MyElement custom elements render for the first time, the mixin will pull all dynamic imports from the scoped registry, execute them and display a fallback until all dependend imports are resolved. I'd love to switch to your implementation when it's stable!

Are there also plans to provide some helper utilities for other frameworks (if possible) for working with scoped registries?

**Comment by daKmoR** [comment]
interesting idea 🤗 

it seems this is still quite a low level "api"... for usage in elements maybe a mixin makes more sense...?

funny enough testing this with extending components highlights another issue https://github.com/open-wc/open-wc/issues/1272

for these cases probably a mixin would be more appropriated (but not sure if this mixin should be within open-wc or more within elements/libraries implementing it)

**Comment by mzeiher** [comment]
sorry for the late response, a place for small little helper mixins (justin's pending state protocol mixin would also fit) would be nice. Did you test with ES5 down compilation? The mixin I posted only works with es6 at the moment because it relies on inheritance of static properties (defined at the constructor) these only work nice in a native es6 environment. I really like where this repository is going with all the tooling/helpers.
