### ISSUE TITLE
Grammar typo on codelabs step 6.

### ISSUE THREAD

**Issue by davidmaxwaterman** [open-wc/open-wc#1266]
Grammar typo on codelabs step 6.

https://open-wc.org/codelabs/basics/web-components.html?index=/codelabs/#5

```
To test the encapsulation of to our component
```

**Comment by daKmoR** [comment]
would love a pull request 🤗 

code is here
https://github.com/open-wc/open-wc/tree/master/packages/codelabs/src/basics

**Comment by gpista** [comment]
This has been fixed with #1503. Could you please close this issue? Thanks!
