### ISSUE TITLE
Multi page application

### ISSUE THREAD

**Issue by devalexqt** [open-wc/open-wc#1267]
How to configure project for multi page application?

**Comment by LarsDenBakker** [comment]
That really depends on your requirements.

**Comment by devalexqt** [comment]
I have 20 different html pages, and want bundle for every page

**Comment by daKmoR** [comment]
this should be possible with https://www.npmjs.com/package/@open-wc/rollup-plugin-html

and we will also integrate it into `@open-wc/building-rollup` 👍
