### ISSUE TITLE
import-meta-url-loader.js assumes this.rootContext contains node_modules

### ISSUE THREAD

**Issue by Artur-** [open-wc/open-wc#127]
If you configure webpack to use another folder as the `context` folder, e.g.
```
module.exports = {
  context: path.resolve(__dirname, 'src'),
```
then `import-meta-url-loader.js` won't work as it assumes `this.context` contains `this.rootContext`: `this.context.indexOf(this.rootContext)`, which will return -1 in this case, e.g.
```
context: /path/to/my-project/node_modules/@fooloomanzoo/input-picker-pattern
rootContext: /path/to/my-project/src
```

**Comment by daKmoR** [comment]
@Artur- any idea what would need to change to make it also work with a different configured context?
