### ISSUE TITLE
[rollup-plugin-index-html] Files emitted using Rollup emitChunk are incorrectly imported inside html.

### ISSUE THREAD

**Issue by minht11** [open-wc/open-wc#1271]
JavaScript files emitted from plugins using Rollup emitChunk are incorrectly imported inside outputted html file. One example is https://github.com/surma/rollup-plugin-off-main-thread which outputs worker file to be later imported by worker itself. rollup-plugin-index-html creates script tag for it inside html file even though it shouldn't.

Probably related to https://github.com/open-wc/open-wc/issues/1153 using new assets api.

**Comment by LarsDenBakker** [comment]
This is something we need to tackle in the new version of the plugin.

**Comment by LarsDenBakker** [comment]
We've released `@open-wc/rollup-plugin-html` which addresses this.
