### ISSUE TITLE
Update Workbox to v5.0.0

### ISSUE THREAD

**Issue by abdonrd** [open-wc/open-wc#1281]
https://github.com/GoogleChrome/workbox/releases/tag/v5.0.0

Migrate from Workbox v4 to v5:
https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v4

**Comment by LarsDenBakker** [comment]
Thanks for letting us know. @thepassle @bennypowers are on it.

**Comment by abdonrd** [comment]
Maybe we can use something like this rollup plugin by @thepassle?
To avoid register the SW in the `index.html`.

https://twitter.com/passle_/status/1243845136188084225

**Comment by thepassle** [comment]
We are working on that yes 🙂

**Comment by abdonrd** [comment]
I think this is fixed with the last version, right?

**Comment by LarsDenBakker** [comment]
Yep! Thx.
