### ISSUE TITLE
Rollup non index.html entrypoint conflicting documentation

### ISSUE THREAD

**Issue by abraham** [open-wc/open-wc#1282]
I'm trying to use a non index.html entrypoint and there is conflicting documentation and each initially don't seem to work. Neither example has worked for me so far.

- https://open-wc.org/building/building-rollup.html#non-index-html-entrypoint
- https://open-wc.org/building/rollup-plugin-index-html.html#non-index-html-entrypoints

**Comment by daKmoR** [comment]
hey there 🤗 

what do you mean by a `non index.html entrypoint`?
e.g. use a `my-app.js`? then you will still need to define the "default html around" somewhere

this could be an example 🤗 

```js
import { createDefaultConfig } from '@open-wc/building-rollup';
import { indexHTMLPlugin } from 'rollup-plugin-index-html';
import deepmerge from 'deepmerge';

// use js as entry point => disable default indexHTML 
// (which only supports a index.html file entry point)
const basicConfig = createDefaultConfig({
  input: './my-app.js',
  plugins: {
    indexHTML: false,
  },
});

// add the html plugin yourself with some hardcoded html
export default merge(basicConfig, {
  plugins: [
    indexHTMLPlugin({
      indexHTML: `
        <html>
          <head></head>
          <body></body>
        </html>
      `,
    }),
  ],
});
```

if that does not work - can you post your errors?

**Comment by abraham** [comment]
Yes, using HTML that's in a string and not using an index.html file.

Using the sample code you included and that is in my first link (and fixing the `deepmerge` vs `merge` bug) on a brand new scaffolded app. The error is "rollupPluginIndexHtml.indexHTMLPlugin is not a function"

> [!] TypeError: rollupPluginIndexHtml.indexHTMLPlugin is not a function
> TypeError: rollupPluginIndexHtml.indexHTMLPlugin is not a function
>     at Object.<anonymous> (/Users/abraham/Sandbox/rollup-html-test/app-demo/rollup.config.js:25:27)
>     at Module._compile (internal/modules/cjs/loader.js:959:30)
>     at Object.require.extensions.<computed> [as .js] (/Users/abraham/Sandbox/rollup-html-test/app-demo/node_modules/rollup/dist/bin/rollup:830:24)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
>     at Module.require (internal/modules/cjs/loader.js:852:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at /Users/abraham/Sandbox/rollup-html-test/app-demo/node_modules/rollup/dist/bin/rollup:837:32

If I modify the import:

    import indexHTMLPlugin from 'rollup-plugin-index-html';

I get this error:

> [!] (plugin index-html) Error: config.indexHTML must be a html file
> Error: config.indexHTML must be a html file
>     at getOutputIndexHTML (/Users/abraham/Sandbox/rollup-html-test/app-demo/node_modules/rollup-plugin-index-html/src/create-output.js:53:13)
>     at createOutput (/Users/abraham/Sandbox/rollup-html-test/app-demo/node_modules/rollup-plugin-index-html/src/create-output.js:114:21)
>     at Object.generateBundle (/Users/abraham/Sandbox/rollup-html-test/app-demo/node_modules/rollup-plugin-index-html/rollup-plugin-index-html.js:166:21)
>     at /Users/abraham/Sandbox/rollup-html-test/app-demo/node_modules/rollup/dist/shared/node-entry.js:13096:25
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)

If I try the example from my second link using 

    entry: './path/to/file.js',

instead of 

    input: './path/to/file.js',

and instead of `indexHtml` using

```
indexHTML({
      template: () => `
        <html>
          <head></head>
          <body></body>
        </html>
      `,
    }),
```

I get the following error:

> [!] TypeError: Cannot read property 'endsWith' of undefined
> TypeError: Cannot read property 'endsWith' of undefined
>     at Object.createBasicConfig [as createDefaultConfig] (/Users/abraham/Sandbox/rollup-html-test/app-demo/node_modules/@open-wc/building-rollup/modern-config.js:28:33)
>     at Object.<anonymous> (/Users/abraham/Sandbox/rollup-html-test/app-demo/rollup.config.js:13:36)
>     at Module._compile (internal/modules/cjs/loader.js:959:30)
>     at Object.require.extensions.<computed> [as .js] (/Users/abraham/Sandbox/rollup-html-test/app-demo/node_modules/rollup/dist/bin/rollup:830:24)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
>     at Module.require (internal/modules/cjs/loader.js:852:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at /Users/abraham/Sandbox/rollup-html-test/app-demo/node_modules/rollup/dist/bin/rollup:837:32

**Comment by abraham** [comment]
This configuration seems to work but it's pretty different from the documented version and the `fake string` isn't ideal.

```
import { createDefaultConfig } from '@open-wc/building-rollup';
import indexHTMLPlugin from 'rollup-plugin-index-html';
import deepmerge from 'deepmerge';

const basicConfig = createDefaultConfig({
  input: './components/app-demo/app-demo.js',
});

export default deepmerge(basicConfig, {
  plugins: [
    indexHTMLPlugin({
      template: () => `
        <html>
          <head>two</head>
          <body></body>
        </html>
      `,
      indexHTML: 'fake string',
    }),
  ],
});
```

**Comment by LarsDenBakker** [comment]
That doesn't look right indeed, something we need to fix. We also plan to split up the index html plugin into separate parts, so it's easier to assemble and customize based on requirements. Right now it's pretty single use case oriented.

**Comment by frank-dspeed** [comment]
why do you generate that html via a plugin? why is that not a html file in your dist folder or some where else?

**Comment by dlockhart** [comment]
@abraham #1446 should have fixed the `TypeError: Cannot read property 'endsWith' of undefined` error you were seeing.

**Comment by LarsDenBakker** [comment]
@abraham We just released a new version of the rollup config, along with our new HTML plugin. Would you be willing to take another look and see if it's better documented and easier to use?

See https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/README.md and https://github.com/open-wc/open-wc/tree/master/packages/rollup-plugin-html
