### ISSUE TITLE
Bundling Complex Siglepage SPA in 2020

### ISSUE THREAD

**Issue by jogibear9988** [open-wc/open-wc#1283]
Hello,

we have a Big SPA wich uses some old ES5 Libs like 'JQuery', 'Sha256',... but also many ES6 Lib's.
The ES5 Libs are included in the index.html via <scrpt src tags.
We do all ES6 imports in or APP Relatively, so the complete App works without Bundling.

We also have a bundling Process via PolymerCLI but this takes over 40 Minutes. (But it works)

We'd like to switch to Rollup (or webpack or parcel), but we did not find a solution wich works with ES6 Modules and also classic "<script src" includes.

Or Requests are:
-  The "script src" includes should also be bundeled and minimized
- The Polyfills we need are already included in the index.html via "scrpit src"
- The ES6 Modules should be included and minized.
- It Should be possible to "Minimize and Bundle" Customer Modules. Means we have some Modules wich are only loaded when included via a json config. It should be possible that they are modified so they could also loaded in a minized main page (so this means some of their includes may be included in the main page, some may not)  
- The Page needs also to work without bundling, cause we sometimes need to change something at the customers side, where we have not setup the bundling infrastructure

**Comment by daKmoR** [comment]
hey there 🤗 

did you check https://open-wc.org/building/building-rollup.html? 
it should cover most (maybe even all your need)?

if there is something specific missing - feel free to open an issue - also open for contributions 🤗

**Comment by jogibear9988** [comment]
Yes I read this.

I did not find any suggestions about global Javascript Librarys, how they could be inlined (the ones loaded via "script src" in the index.html.
And I did not find a Solution to the "Customer Modules" problem.
And how can I disable all polyfills, cause we have them already in index.html included

**Comment by jogibear9988** [comment]
I got it now workin using webpack.
problem with rollup is we have circular references.
