### ISSUE TITLE
Removin hash from [polyfill].hash.js inside polyfills generated from rollup

### ISSUE THREAD

**Issue by lakshay35** [open-wc/open-wc#1284]
Hello,

I am trying to find a way to remove the hash from the polyfill files that are generated using open-wc's rollup configuration

**Comment by LarsDenBakker** [comment]
This is not currently possible to do, we will add support for this in a new version.

**Comment by LarsDenBakker** [comment]
With the new rollup config you can configure hashing behavior:

```js
import merge from 'deepmerge';
import { createSpaConfig } from '@open-wc/building-rollup';

const baseConfig = createSpaConfig({
  polyfillsLoader: {
    polyfills: {
      hash: false
    }
  }
});

export default merge(baseConfig, {
  input: './index.html',
});
```

See https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/README.md and https://github.com/open-wc/open-wc/tree/master/packages/rollup-plugin-polyfills-loader

I'm closing this issue, let me know if you have any further questions.
