### ISSUE TITLE
[es-dev-server] ES6 code is not transformed to ES5 in html <script> tags

### ISSUE THREAD

**Issue by goremikin** [open-wc/open-wc#1285]
In IE11 ES6 code is not transformed into ES5 when used inside `index.html` file and `<script>` tags. For instance, try to add the following to `demo/index.html`

```
<script>
  const myFn = v => {
    const str = `test ${v}`;
    console.log(str);
  }
 myFn('Hello');
</script>
```

open the demo page in IE11 and Syntax error is thrown

**Comment by LarsDenBakker** [comment]
The dev server only handles module scripts right now. https://github.com/open-wc/open-wc/pull/1261 will handle regular scripts too.

**Comment by LarsDenBakker** [comment]
It's merged now, please try with the latest es-dev-server
