### ISSUE TITLE
[scoped-elements] mangling elements class names makes dom tags unrecognizable

### ISSUE THREAD

**Issue by manolakis** [open-wc/open-wc#1293]
Often, class names are mangled in the bundling process. That makes the tags used when defining an item as `MyButton`, instead of having a meaningful name like` my-button`, to get a meaningless name like `c-a`,` c-b`, `c-c`, etc., which makes it very difficult to identify which element is used in the DOM.

**Comment by LarsDenBakker** [comment]
We could use the keys for setting the name instead of the class.

**Comment by manolakis** [comment]
Agree. I have a PR almost ready

**Comment by manolakis** [comment]
Fixed by https://github.com/open-wc/open-wc/commit/b6667ef88c79e6440d5804874fbf641452f1a63e

Closing
