### ISSUE TITLE
[es-dev-server] Default babel configuration breaks custom one

### ISSUE THREAD

**Issue by Lodin** [open-wc/open-wc#1295]
I'm using `es-dev-server` through the `karma-esm`, `lerna`, and united custom `karma` configuration for each package of multirepository. To start karma in a separate package, I need to import `babel.config.json` in the karma configuration file and load it through the `babelConfig` of `karma-esm`. 

However, when I do it, karma fails with the following error:
```
Error compiling: Duplicate plugin/preset detected.
```
My `babel.config.json` file is the following:
```json
{
  "comments": false,
  "presets": ["@babel/preset-typescript"],
  "plugins": [
    [
      "@babel/plugin-proposal-nullish-coalescing-operator",
      {
        "loose": true
      }
    ],
    ["@babel/plugin-proposal-optional-chaining", {"loose": true}]
  ]
}
```
I just require it as a JSON file and push it to `babelConfig` option.

After some research, I found that `es-dev-server` loads some default configuration that includes `@babel/plugin-proposal-nullish-coalescing-operator`, `@babel/plugin-proposal-optional-chaining`, etc. That configuration merges with my configuration and due to name differences has the duplicates inside. It happens [here](https://github.com/open-wc/open-wc/blob/f260638843d24b084c81774c901199a5c2d0d410/packages/es-dev-server/src/utils/babel-transform.js#L48).

I think there should be some checks that disables default configuration if the user configuration is used or a some kind of option to disable default configuration.

**Comment by Lodin** [comment]
UPDATE: Issue happens only with `@babel/plugin-proposal-nullish-coalescing-operator`, `@babel/plugin-proposal-optional-chaining` on board. There is a remark that these plugins could be removed when babel/babel#10811 is merged. It is merged 21 days ago, the latest babel release was [7.8.5](https://github.com/babel/babel/releases/tag/v7.8.5), so I think it can be removed now. I can create a PR for it if you don't mind.

However, still something should be done for deduping plugins or at least the list of used plugins should be mentioned in the documentation somewhere.

**Comment by LarsDenBakker** [comment]
There is a PR for removing those plugins https://github.com/open-wc/open-wc/pull/1242

I'm surprised this causes babel conflicts, I wasn't aware of that. That makes it pretty hard to compose plugins. Will look into it

**Comment by Lodin** [comment]
BTW, the workaround for this issue is quite simple. You just need to make sure your plugins that conflict with the default ones are moved to a separate environment and not affect the `test` one.
