### ISSUE TITLE
[Friendly Suggestion]  Autogenerate react wrapper element

### ISSUE THREAD

**Issue by bahrus** [open-wc/open-wc#1296]
I think it would be wonderful if open-wc provided a utility to take as an input the custom-elements.json definition file, and autogenerate React (<17) wrapper components for each component, that can proxy or autoforward property settings, and add additional properties to turn a custom event into a call back function / property of the React component.

Does anyone see any "gotcha's" I'm missing in why this wouldn't work?

Or has it been done?

**Comment by daKmoR** [comment]
hey, there 👋 

that could theoretically work 👍 
`custom-elements.json` is not that stable but if you would like to work on something like that it would be awesome 💪

**Comment by frank-dspeed** [comment]
https://github.com/webcomponents/custom-elements-json/issues/14
