### ISSUE TITLE
Express server: Serving index.html

### ISSUE THREAD

**Issue by mercmobily** [open-wc/open-wc#1299]
Forgetting completely about #1298, and resigning to the idea that it's not gonna happen...
I have a rather complex Express application, and want to migrate the whole thing to open-wc (since the original PWA is in maintenance mode, and a lot of the tools like polimer-cli will be a thing of the past soon enough).

Till now, I used the prpl-server which worked really well for me. I would:

* Set all routes of my Express application

* Add the prpl server as a middleware:

    const prplHandler = prpl.makeHandler('build', polyConfigFile)
    app.get('/*', (req, res, next) => {
      prplHandler(req, res, next)
    })

From what I can see, open-wc doesn't yet deal with differential serving. So, again assuming that either PRPL is not a thing anymore, or that it's months/years away, how would you serve an app? 
Should I just serve `index.html` like this, as the last route?

    app.get('/*', function(req, res){
        res.sendfile('index.html');
    });

I am asking here because I have a _lot_ to learn in terms of open-ws, and don't want to bang my head against a wall more than strictly necessary.

Is this already documented? Are there any gotchas I should be careful about? What about paths etc.? Is the "base" thing no longer happening?

Sorry for the basic questions. I am looking at the open-ws mountain from the bottom right now...

**Comment by LarsDenBakker** [comment]
In es-dev-server you can add custom middleware:
https://open-wc.org/developing/es-dev-server.html#custom-middlewares-proxy

You can also boot up the server programatically:
https://open-wc.org/developing/es-dev-server.html#using-es-dev-server-programmatically

es-dev-server is based on koa, made by the same team as express. The API is similar, but a lot simpler. You can use https://www.npmjs.com/package/express-to-koa to convert express middleware to koa.

**Comment by LarsDenBakker** [comment]
Note that es-dev-server is a development server, and not optimized for use in production.

**Comment by mercmobily** [comment]
Yep. My question was uniquely about production -- not development. Sorry for not being clear.

**Comment by LarsDenBakker** [comment]
We don't plan on providing any production server from open-wc. There are many great options out there, which are composable too :)

Closing this, let mek now if you have any other questions.

**Comment by mercmobily** [comment]
Sorry, my question obviously wasn't clear enough..
In the context of a SPA, where the file "index.html" is served by default.
I saw this section: https://open-wc.org/building/#using-index-html-as-an-entry-point

However... how does that work? Surely, serving "index.html" as the entry point regardless of where you point the browser requires *some* server-side trickery?

**Comment by LarsDenBakker** [comment]
Ah, now I get it :) 

The "index.html as entrypoint" part in the building docs refer to the fact that you can give an index.html to your build config which will figure out which modules you are using and generate a bundle for you. 

For serving in production we haven't documented anything, because it's not really unique to web components. You just need a static file server like nginx, apache or something in node. For SPA routing, you need to set up "history API fallback" or "SPA routing. I don't know any specific projects to recommend, but for express there is for example https://www.npmjs.com/package/express-history-api-fallback.

**Comment by mercmobily** [comment]
I am feeling more and more stupid.
You do realise that the code of that "module" really, really tiny and just slightly more generic than what I had added already:

````
app.use((req, res, next) => {
  if ((req.method === 'GET' || req.method === 'HEAD') && req.accepts('html')) {
    res.sendFile('index.html', { root: `${__dirname}/public` }, err => err && next())
  } else next()
})
````
So... that's it? I mean, without the whole PRPL stuff, this is so simple that it's a non-problem.

I think this should be documented, so that people like me, with their heads tuned into the old stuff, realise that things were actually just horribly over-complicated...

**Comment by LarsDenBakker** [comment]
Yes it's as simple as that, this is the implementation of es-dev-server: https://github.com/open-wc/open-wc/blob/master/packages/es-dev-server/src/middleware/history-api-fallback.js we make sure it's not a file request.

This isn't web component specific, so we haven't documented that. But it could be something to add somewhere.

**Comment by mercmobily** [comment]
I don't think the world will ever thank you enough for this... THANK YOU!
