### ISSUE TITLE
[Codelabs intermediate] Google news API alternative

### ISSUE THREAD

**Issue by tkgroot** [open-wc/open-wc#1303]
Is there a reasonable reason why the codelabs is using the Google news API? 
Wouldnt it be better to use open resources instead? The Hackernews API is publically available, hence no registration step required. It reduces complexity (yet another registration form with captcha), completely omits the construction of the url with the API key and doesnt interrupt the flow of the codelabs.

I did implement the codelabs with the Hackernews API instead. With some minor modifications (see code below), it has the same outcome, no real value though (just a bunch of comments to an "unknown" topic).

```javascript
async fetchArticles() {
          this.loading = true
          let idx = 0
          const array = []
          const path = "https://hacker-news.firebaseio.com/v0/item"
          const maxItem = 22115410

          while (idx < 5) {
            await fetch(`${path}/${maxItem - idx}.json`)
            .then(res => res.json())
            .then(data => array.push(data))  
            
            idx++
          } 
          
          this.articles = array
          this.loading = false
        }
```

**Comment by LarsDenBakker** [comment]
The registration for the google news API is a bit annoying indeed. I think the hackernews API is a good alternative, I don't mind switching over to that. Open for PRs :)

**Comment by LarsDenBakker** [comment]
This was implemented.
