### ISSUE TITLE
No JavaScript from generated from `npm init`

### ISSUE THREAD

**Issue by jsilvermist** [open-wc/open-wc#1304]
When I'm trying to use `npm init @open-wc` for the first time to start a new Application, there are no `.js` files being generated. (See screenshot below)

Am I missing something really obvious, or is this just not working as intended?

![image](https://user-images.githubusercontent.com/10246291/73617076-0b72f080-45e9-11ea-9a72-d467113c489c.png)

Node Version: v12.14.1
NPM Version: v6.13.4

**Comment by LarsDenBakker** [comment]
This is not correct, thanks for reporting it
