### ISSUE TITLE
Help migrate build from polymer-cli to open-wc

### ISSUE THREAD

**Issue by mercmobily** [open-wc/open-wc#1308]
I am a new convert. First of all, thank you for your terrific work here.
I am trying to build my project with the default Rollup configuration, but I am hitting some problems.
For what it's worth, I volunteer myself to writing a guide for sobs like me who exit the Polymer/PWA world and enter the real Javascript tooling world!

* In rollup.config.js we have:

````
import { createDefaultConfig } from '@open-wc/building-rollup';
export default createDefaultConfig({ input: './index.html' });
````
I looked at the source code of `modern-config.js` and it's totally clear to me what the options can be. Do you have this already documented? Or, would you like me to write an explanation?

* In my `index.html` I have the following:

````
    <!-- JS libraries -->
    <script src="node_modules/moment/min/moment-with-locales.min.js"></script>
    <script src="node_modules/moment-timezone/builds/moment-timezone-with-data.js"></script>
    <script src="node_modules/moment-precise-range-plugin/moment-precise-range.js"></script>
    <script src="node_modules/sortablejs/Sortable.min.js"></script>
    <script src="node_modules/ejs/ejs.min.js"></script>
    <script src="node_modules/datalist-polyfill/datalist-polyfill.min.js"></script>
````

I added these as "extraDependencies" in the good ol `polymer.json` file. What's the equivalent here? How do you get rollup to include those in the build?

* In `polymer.json` there is the concept of 'entry point' (index.html, normally) and "shell". With Rollup,  all you give it is the entry point. What's the consequence of this in practical terms? Am I right when I say that Rollup effectively works out the shell on its own?

Thanks for your help!

**Comment by mercmobily** [comment]
(I wonder if I should just copy those files over)

**Comment by mercmobily** [comment]
Alright, the offer to write documentation stands.
For the second point, the answer is that yes, I do need to copy over those files:

````
import { createDefaultConfig } from '@open-wc/building-rollup'
import copy from 'rollup-plugin-copy'

// if you need to support IE11 use "modern-and-legacy-config" instead.
// import { createCompatibilityConfig } from '@open-wc/building-rollup';
// export default createCompatibilityConfig({ input: './index.html' });

const copyConfig = {
  targets: [
    { src: 'node_modules/moment/min/moment-with-locales.min.js', dest: 'dist/node_modules/moment/min/' },
    { src: 'node_modules/moment-timezone/builds/moment-timezone-with-data.js', dest: 'dist/node_modules/moment-timezone/builds/' },
    { src: 'node_modules/moment-precise-range-plugin/moment-precise-range.js', dest: 'dist/node_modules/moment-precise-range-plugin/' },
    { src: 'node_modules/sortablejs/Sortable.min.js', dest: 'dist/node_modules/sortablejs/' },
    { src: 'node_modules/ejs/ejs.min.js', dest: 'dist/node_modules/ejs/' },
    { src: 'node_modules/datalist-polyfill/datalist-polyfill.min.js', dest: 'dist/node_modules/datalist-polyfill/' },
  ]
}

const config = createDefaultConfig({ input: './index.html' })
export default { ...config, plugins: [...config.plugins, copy(copyConfig)] }
````

My third question stands :D

**Comment by LarsDenBakker** [comment]
With es modules and dynamic imports, manually defining a shell is no longer needed. You can declare this in your own code by using dynamic imports to defer loading non critical parts of your application.

You could write a dev.to blog post perhaps to document the migration?

**Comment by mercmobily** [comment]
OK for the blog post! And thank you so much for the hard work.
