### ISSUE TITLE
[webpack-import-meta-loader] Not working in web worker

### ISSUE THREAD

**Issue by theochampion** [open-wc/open-wc#1314]
Hi there,

I'm trying to use this loader for code that uses `import.meta.url` and will eventually run in a web worker.
Thing is, the import statement gets replaced with:
```javascript
({ url: `${window.location.protocol}//${window.location.host}/relative/path/to/file.js` }).url
```
thus using the `window` object that is not accessible in the context of a web worker.
 
Is there any workaround to make this work ? Happy to help if needed 😃 

Cheers!

**Comment by LarsDenBakker** [comment]
The current solution is mostly a workaround, because of lack of support in webpack. Since web workers support es modules, we recommend using rollup. For everything else we recommend rollup too ;)

**Comment by LarsDenBakker** [comment]
Closing this one, since we cannot change this until webpack supports `import.meta.url`
