### ISSUE TITLE
es-dev-server: watcher's "add" method always called even when no watcher is there

### ISSUE THREAD

**Issue by mercmobily** [open-wc/open-wc#1315]
When using es-dev-server programmatically as middleware, it will add the watched middleware even when there is no watcher set.
I am not submitting a PR because I am very confused by the idea of "watch" in the code -- sometimes it seems to refer to messages being forwarded to the browser, whereas other times it's about watching files change.

Anyhow, using it like this in an Express app:

````
  const Koa = require('koa')
    const config = esDevServer.createConfig({
      nodeResolve: true,
      appIndex: 'index.html',
      moduleDirs: ['node_modules'],
      watch: false
    })
    const middlewares = esDevServer.createMiddlewares(config)
    const koaApp = new Koa()
    middlewares.forEach(middleware => {
      koaApp.use(middleware)
    })

    const root = `${__dirname}`
    app.use(express.static(root))
    app.use(koaApp.callback())
````

This piece of code is always invoked:

````
  middlewares.push((0, _watchServedFiles.createWatchServedFilesMiddleware)({
    rootDir,
    fileWatcher
  })); // compile code using babel and/or resolve module imports
````

Which causes:

````
UNHANDLED REJECTION! TypeError: Cannot read property 'add' of undefined
    at watchServedFile (/disk/home/merc/Development/node/compAs/node_modules/es-dev-server/dist/middleware/watch-served-files.js:28:19)
    at watchServedFilesMiddleware (/disk/home/merc/Development/node/compAs/node_modules/es-dev-server/dist/middleware/watch-served-files.js:42:5)
    at process._tickCallback (internal/process/next_tick.js:68:7) PROMISE: Promise {
  <rejected> TypeError: Cannot read property 'add' of undefined
      at watchServedFile (/disk/home/merc/Development/node/compAs/node_modules/es-dev-server/dist/middleware/watch-served-files.js:28:19)
      at watchServedFilesMiddleware (/disk/home/merc/Development/node/compAs/node_modules/es-dev-server/dist/middleware/watch-served-files.js:42:5)
      at process._tickCallback (internal/process/next_tick.js:68:7) }
````

Commenting that code out "solves" the problem (although I suspect it cripples normal command line uses of it).

**Comment by mercmobily** [comment]
Do you want me to dive into the code and try to fix it? Any hints?

**Comment by LarsDenBakker** [comment]
Sorry for the late response. We use the file watcher for the response cache to invalidate the cache on changes. We should change it to create a file watcher when one isn't given though. If you want to pick this up you can have a look at the `createServer` and `startServer` functions.

**Comment by mercmobily** [comment]
This fix is as simple as adding `fileWatcher =  chokidar.watch([])` to create-middleware.js:

````
export function createMiddlewares(config, fileWatcher =  chokidar.watch([])) {
````

As well as import an extra middleware in the same file:

````
import chokidar from 'chokidar';
````

This will make sure that createMiddlewares has a watcher even if one wasn't psassed.

I don't think I am missing anything.
I think it would be a little difficult to add tests for this.

**Comment by LarsDenBakker** [comment]
Indeed. We can do without a test for this one.

**Comment by mercmobily** [comment]
Question...  I must be missing something. How do you run it without building it?
