### ISSUE TITLE
[testing] watch command doesn't work

### ISSUE THREAD

**Issue by jarrodek** [open-wc/open-wc#1334]
I've updated dependencies in one of my projects to the following:
- @open-wc/testing: 2.5.4
- @open-wc/testing-karma: 3.2.42

When I run `npm run test:watch` command then it does the first run but then after I save changes it only says `START:` and that's it. Nothing else happens. Each time I save a file it just adds another "START" line.

![image](https://user-images.githubusercontent.com/3320020/74298129-b5473100-4cfd-11ea-9534-2c6fb1afd052.png)

**Comment by LarsDenBakker** [comment]
I just tried this with a clean `npm init @open-wc` and it's working fine for me. I get this issue too sometimes, I think it's something in karma. But a restart usually fixes this for me. Can you try a clean project?

**Comment by jarrodek** [comment]
I afraid it is not what is happening. I have 2 setups in front of me and in both it is happening the same.
I have Ubuntu 19.10 and MacOS 10.15.3. I've restarted both devices and have the same symptoms.

Would it be possible for you to test it against this repo? https://github.com/advanced-rest-client/authorization-method
