### ISSUE TITLE
webpack, outputpath could not be adjusted.

### ISSUE THREAD

**Issue by jogibear9988** [open-wc/open-wc#1338]
I have a webpack config like this:

    const path = require('path');
    const { createDefaultConfig } = require('@open-wc/building-webpack');

    module.exports = createDefaultConfig({
        input: path.resolve(__dirname, './index.html'),
        webpackIndexHTMLPlugin: {
            polyfills: {
                fetch: false,
                intersectionObserver: false,
                polyfillsHash: false,
                coreJs: false,
                regeneratorRuntime: false,
                webcomponents: false,
            },
        },
        plugins : {
            workbox: false
        },
        output: {
            filename: '[name].bundle.js',
            path: path.resolve(__dirname, 'webpack-dist'),
        },
    });

but the path und er output will not be used, cause in here:

https://github.com/open-wc/open-wc/blob/1dcbe3c35906a75ff92eafa9777da9813fa223c0/packages/building-webpack/modern-config.js#L49

the option from outside is not used!

**Comment by LarsDenBakker** [comment]
You can override any options by using `deepmerge`:

```js
const path = require('path');
const merge = require('deepmerge');
const { createDefaultConfig } = require('@open-wc/building-webpack');

const config = createDefaultConfig({ .. options .. });

module.exports = merge(config, {
  .. custom webpack options ...
});
```

I prefer this over creating extra options in the webpack config creator.

**Comment by jogibear9988** [comment]
@LarsDenBakker 

If I do this:

    const config = createDefaultConfig({
        input: path.resolve(__dirname, './index.html'),
        webpackIndexHTMLPlugin: {
            polyfills: {
                fetch: false,
                intersectionObserver: false,
                polyfillsHash: false,
                coreJs: false,
                regeneratorRuntime: false,
                webcomponents: false,
            },
        },
        plugins : {
            workbox: false
        },
        output: {
            filename: '[name].bundle.js',
            path: path.resolve(__dirname, 'webpack-dist'),
        } 
    });

    module.exports = merge(config, {
        output: {
            filename: '[name].bundle.js',
            path: path.resolve(__dirname, 'webpack-dist'),
        }
    });

I get the following error:

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.optimization.minimizer[0] misses the property 'apply'.
   function
   -> The run point of the plugin, required method.
 - configuration.plugins[1] misses the property 'apply'.
   function
   -> The run point of the plugin, required method.

**Comment by thepassle** [comment]
Not sure why deepmerge is making it throw that webpack error, but this works:

```js
const path = require('path');
const { createDefaultConfig } = require('@open-wc/building-webpack');

const config = createDefaultConfig({
  input: path.resolve(__dirname, './index.html'),
  webpackIndexHTMLPlugin: {
      polyfills: {
          fetch: false,
          intersectionObserver: false,
          polyfillsHash: false,
          coreJs: false,
          regeneratorRuntime: false,
          webcomponents: false,
      },
  },
  plugins : {
      workbox: false
  }
});

const conf = {
  ...config,
  output: {
    filename: 'foo-[name].bundle.js',
    path: path.resolve(__dirname, 'webpack-dist'),
  },
};

module.exports = conf;
```

```
Hash: 1ddc99b2abdc01f3a962
Version: webpack 4.41.6
Time: 991ms
Built at: 02/22/2020 3:39:25 PM
                            Asset       Size  Chunks                   Chunk Names
            foo-asd-asd.bundle.js   25.1 KiB       0  [emitted]        asd-asd
foo-asd-asd.bundle.js.LICENSE.txt   1.07 KiB          [emitted]        
        foo-asd-asd.bundle.js.map  126 bytes       0  [emitted] [dev]  asd-asd
                       index.html  454 bytes          [emitted]        
Entrypoint asd-asd = foo-asd-asd.bundle.js foo-asd-asd.bundle.js.map
[0] ./components/asd-asd/asd-asd.js + 25 modules 111 KiB {0} [built]
    |    26 modules
```

**Comment by jogibear9988** [comment]
thanks... now it works.
