### ISSUE TITLE
withWebComponentsKnobs > Addons not displaying

### ISSUE THREAD

**Issue by konradgorski** [open-wc/open-wc#1346]
It looks like the knobs are not displayed while the canvas is open when using the withWebComponentsKnobs from @open-wc/demoing-storybook.

I'm using the mdx format and custom-elements.json to organize my stories and properties. Below is an example meta for one of the story files.

`import { Story, Preview, Meta, Props, html, withKnobs, withWebComponentsKnobs } from '@open-wc/demoing-storybook';

import '../some-file.js';

<Meta 
  title="Some title
  decorators={[withKnobs, withWebComponentsKnobs]}
  parameters={{
    component: "some-component",
    options: { selectedPanel: "storybookjs/knobs/panel" }
  }}
/>`

Oddly enough, the knobs **ARE** accessible if the viewport width is less than 600px but anything greater than that I cannot use them. I'be attached some screenshots for additional context.

**Missing addons panel**
When viewing the canvas you'll notice the missing addons panel.
![open-wc-knob-1](https://user-images.githubusercontent.com/4640511/74611348-f4dc9700-50c8-11ea-898c-a29a382b554c.png)

**Viewed with a smaller viewport ( vp < 600)**
If you make the browser window/viewport smaller than 600px the addons are accessible. Those tabs should display regardless of the browser width.
![open-wc-knob-2](https://user-images.githubusercontent.com/4640511/74611370-33725180-50c9-11ea-8738-4016e88fa5bb.png)

**Access the knobs (or any other addon)**
![open-wc-knob-3](https://user-images.githubusercontent.com/4640511/74611427-bd221f00-50c9-11ea-8e49-d957a0317cd8.png)

**Comment by konradgorski** [comment]
Well... https://github.com/open-wc/open-wc/issues/1048 this workaround resolves the immediate issue but it's odd that it happens in the first place.

**Comment by LarsDenBakker** [comment]
storybook puts some things in local storage, can you try clearing and it and seeing if you still have this issue?
