### ISSUE TITLE
[scoped-elements] how to handle unscoped elements

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1352]
When using scoped-elements, a web component could write templates with custom elements that are not declared in the scoped elements field:

```js
class MyElement extends ScopedElementsMixin(LitElement) {
  static scopedElements = {
    'my-button': MyButton
  };

  render() {
    return html`
      <my-button></my-button>
      <my-link></my-link>
    `;
  }
}
```

If the developer's intention is to use a global definition of `my-link`, this would be OK. However I don't think this is a common use case, it is far more common to want to scope all elements inside your web component. 

One of the things I don't like about self defining components is that it's easy to forget an import, and the mistake is hidden because the component may already be defined globally. When using scoped elements, this mistake is far worse. 

I think we can help the developer here by throwing when using an element that isn't declared. This could be a default option enabled for all elements, to disable scoping for a particular element this could be declared explicitly:

```js
class MyElement extends ScopedElementsMixin(LitElement) {
  static scopedElements = {
    'my-button': MyButton,
    'my-link': false
  };
}
```

Since this is not a very common use case, we could also support the partial scoping with a separate mixin:

```js
class MyElement extends PartialScopedElementsMixin(LitElement) {
  static scopedElements = {
    'my-button': MyButton,
  };
}
```

Looking for opinions on this one.

**Comment by LarsDenBakker** [comment]
@manolakis while this is a nice idea, it clashes with the plans for lazy loaded elements. Also the final standard would also not include this, so I think we should let this one go for now.

**Comment by daKmoR** [comment]
this is intended behavior... every scoped shadow dom is "new" there is no inheritance of parent or global customElement registries.

If you need it you can bring the global element into the scoped registry you can do it like so

```js
class MyElement extends ScopedElementsMixin(LitElement) {
  static scopedElements = {
    'my-button': MyButton,
    'my-link': customElements.get('my-link')
  };

  render() {
    return html`
      <my-button></my-button>
      <my-link></my-link>
    `;
  }
}
```
