### ISSUE TITLE
starter app features missing?

### ISSUE THREAD

**Issue by RERepos** [open-wc/open-wc#1353]
Greetings,

I ran the `npm init @open-wc` to create a starter app/project, hoping to learn about your suggested build process and configuration.  The readme indicates that `build` will output the results into a `dist` folder.  But, the command doesn't seem to do anything.  I checked out the package.json, and the only script defined is `start` for opening es-dev-server.

Am I missing something, or is the `npm init` not where I would learn about your suggested build process and configuration?

Thanks for your help!

Best regards,
Robert

**Comment by thepassle** [comment]
Hi Robert, did you make sure to select the ‘build’ option with space in the cli menu?

**Comment by RERepos** [comment]
I got faked out by the ubuntu ui.  I did not have the 'build' option selected.  I re-installed with all the options selected now, and it's all there ...

Thank you for your help!
