### ISSUE TITLE
[scoped-elements] how to handle lazy loaded elements

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1354]
A component might lazy load some component definitions. We will need to think about how we want to tackle this. The difficulty is that for any given class, it would be nice to always have the same tagname.

**Comment by daKmoR** [comment]
So you have a template and render some "undefined" custom elements

maybe something like this?
```js
static get scopedElements() {
  return {
    'load-me-later': HTMLElement
  }
}

render() {
  setTimeout(() => {
    import('../LoadMeLater.js').then(module => {
      this.constructor.scopedElements['load-me-later'] = module.LoadMeLater;
      // do we need to clear some cache here?
    });
  }, 1000); // load 1s later
  return html`
     <h1>Load next later</h1>
     <load-me-later></load-me-later>
  `;
}
```
if yes we should add a test for it

**Comment by LarsDenBakker** [comment]
yes that's correct

**Comment by manolakis** [comment]
Probably we are going to need something like
```js
static get scopedElements() {
  return {
    'load-me-later': 'lazy'
  }
}
```

in order to scope the tag and the we could use some function like `scopeLazyComponent('load-me-later', LoadMeLater)` in order to define the component with the scoped tag.

**Comment by jorenbroekema** [comment]
What about

```js
static get scopedElements() {
  return {
    'load-me-later': import('../LoadMeLater.js');
  }
}
```

Easiest API for the user, and the scopedElements will have to deal with Promises where if the value of the key is of type promise, you await it and only do the scoping stuff after it's resolved.

**Comment by thepassle** [comment]
@jorenbroekema I like that API, but how would be decided _when_ to lazy load the component though?

**Comment by daKmoR** [comment]
```js
'load-me-later': import('../LoadMeLater.js');
```
this will always be executed even if you override it later

so if we want something like that it needs to become a function
```js
'load-me-later': () => import('../LoadMeLater.js');
```

however, then it becomes tough to distinguish? 
```
class Foo {}
function bar() {}
console.log(typeof Foo); // function
console.log(typeof bar); // function
```

hmm you could probably do 
```js
if (klass.prototype instanceof HTMLElement)
```
to check between actual classes and dynamic loading functions


```js
static get scopedElements() {
  return {
    'foo-bar', FooBar,
    'load-me-later': () => import('../LoadMeLater.js');
  }
}
```

when the first render or access to that object appears we can trigger the import

**Comment by LarsDenBakker** [comment]
Loading the import when the tag is rendered basically makes it work like https://github.com/w3c/webcomponents/issues/782, which is interesting but a different use case. The use case here is that the user decides when to load it.

**Comment by manolakis** [comment]
What about something like this?

```js
static get scopedElements() {
  return {
    'load-me-later': () =>  import('../LoadMeLater.js'),
  }
}

render() {
  setTimeout(() => loadScopedElement('load-me-later'), 1000); // load 1s later

  return html`
     <h1>Load next later</h1>
     <load-me-later></load-me-later>
  `;
}
```

**Comment by jorenbroekema** [comment]
Hmm I was actually aware that the script would always be ran, that was the point. 
```js
static get scopedElements() {
  return {
    'load-me-later': new Promise(resolve => {
      setTimeout(() => { 
        import('../LoadMeLater.js').then(module => {
          resolve(module.LoadMeLater);
        };
      }, 1000));
    }
  }
}
```

The only thing the mixin does is check if it is a promise, and start scoping only when the promise resolves. You as a user need to ensure that the resolve returns the class. Then you are fully in control of doing stuff like dynamically importing, delaying the start of the import by 1000 ms, etc.

Or am I doing totally crazy impossible JS things here?

**Comment by bennypowers** [comment]
a function that loads the component (presumably through import) is the simplest and most portable.

**Comment by daKmoR** [comment]
that is actually pretty nice... as you can combine custom "loading" and just an import (as it is a promise)

```js
static get scopedElements() {
  return {
    'load-me-on-element-loading': import('../LoadMeOnElementLoading'),
    'load-me-later': new Promise(resolve => {
      setTimeout(async () => { 
        const { LoadMeLater } = await import('../LoadMeLater.js');
        resolve(LoadMeLater);
      }, 1000));
    }
  }
}
```

**Comment by btopro** [comment]
throwing in the context of dynamic loading based on visibility. Could also do a variation of this that the element on visibility queries itself using the `*:not(:defined)` and then sets flags on the children so that they'll dynamically import their definitions once they are visible by the browser.

We do something like this combined w/ MutationObservers to see children in slots and then import definitions on the fly which also seem like they could be simple methodology abstractions to give us things like the threads referenced as spec work discussions.

```js
// implementation
class WhatEver extends IntersectionObserverMixin(LitElement) {

  static get scopedElements() {
    return {
      'load-me-later': '../LoadMeLater.js',
      'load-something-later': '../LoadSomethingLater.js',
    }
  }

  updated(changedProperties) {
    changedProperties.forEach((oldValue, propName) => {
      if (propName === "elementVisible" && this[propName]) {
        if (this.intersectionObserver) {
          // remove the IO, we're visible
          this.intersectionObserver.disconnect();
          // load a specific one as per past examples or....
          loadScopedElement('load-me-later');
          // or querying to wake up the tags currently not defined
          this.shadowDom.querySelectorAll("*:not(:defined)").forEach((el) => {
            loadScopedElement(el.tagName.toLowerCase());
            // OR, you could apply an IntersectionObserver
            // to everything undefined and then when they become visible
            // load the definition at that point
          }
        }
      }
    });
  }

  render() {
    return html`
      <h1>Load next later</h1>
      <load-me-later></load-me-later>
      <load-something-later></load-something-later>
    `;
  }
}

// mixIn in question
const IntersectionObserverMixin = function(SuperClass) {
  // SuperClass so we can write any web component library / base class
  return class extends SuperClass {
    /**
     * Constructor
     */
    constructor() {
      super();
      // listen for this to be true in your element
      this.elementVisible = false;
      // threasholds to check for, every 25%
      this.IOThresholds = [0.0, 0.25, 0.5, 0.75, 1.0];
      // margin from root element
      this.IORootMargin = "0px";
      // wait till at least 50% of the item is visible to claim visible
      this.IOVisibleLimit = 0.5;
      // drop the observer once we are visible
      this.IORemoveOnVisible = true;
      // delay in observing, performance reasons for minimum at 100
      this.IODelay = 100;
    }
    static get properties() {
      return {
        elementVisible: { type Boolean; }
      };
    }
    /**
     * HTMLElement specification
     */
    connectedCallback() {
      if (super.connectedCallback) {
        super.connectedCallback();
      }
      // setup the intersection observer, only if we are not visible
      if (!this.elementVisible) {
        this.intersectionObserver = new IntersectionObserver(
          this.handleIntersectionCallback.bind(this),
          {
            root: document.rootElement,
            rootMargin: this.IORootMargin,
            threshold: this.IOThresholds,
            delay: this.IODelay
          }
        );
        this.intersectionObserver.observe(this);
      }
    }
    /**
     * HTMLElement specification
     */
    disconnectedCallback() {
      // if we have an intersection observer, disconnect it
      if (this.intersectionObserver) {
        this.intersectionObserver.disconnect();
      }
      if (super.disconnectedCallback) {
        super.disconnectedCallback();
      }
    }
    /**
     * Very basic IntersectionObserver callback which will set elementVisible to true
     */
    handleIntersectionCallback(entries) {
      for (let entry of entries) {
        let ratio = Number(entry.intersectionRatio).toFixed(2);
        // ensure ratio is higher than our limit before trigger visibility
        if (ratio >= this.IOVisibleLimit) {
          this.elementVisible = true;
          // remove the observer if we've reached our target of being visible
          if (this.IORemoveOnVisible) {
            this.intersectionObserver.disconnect();
          }
        }
      }
    }
  };
};
```

We leverage dynamic imports to improve TTFP by breaking up the execution chain but this would go to another level by breaking import execution up into user based activation. This is a major advantage Stencil has over LitElement currently is that it's compiler provides something like this built into their base element definition.

**Comment by LarsDenBakker** [comment]
I think this is definitely a very interesting use case, but not something for the scoped-elements projects. With this project we try to implement the minimal code required to solve a specific problem and to keep the path open for migration to an official standard version of scoped custom elements. 

Lazy loading on intersection could actually be implemented today as a lit directive, would be really interesting to look into.

**Comment by LarsDenBakker** [comment]
This was implemented.
