### ISSUE TITLE
Routing solution for open-wc

### ISSUE THREAD

**Issue by mercmobily** [open-wc/open-wc#1357]
I love open-wc. I cannot express how grateful I am for your great work.
When I first saw it, one thing that pushed me away was the lack of a good routing solution. There are some options in your page, but none of them worked.
In the end, I implemented routing in my app directly. However, I felt I had to give something back to the community.

So... I made this:

https://mobily-enterprises.github.io/routify/

I basically made it for open-wc. I humbly offer this for you to review, tell me what you think, and decide what to do.

My dream is to see this as an available option to the default open-wc install. But, maybe I think too highly of myself and my code. Please have a look. And please keep in mind that I have just finished typing it... I still haven't documented the API and haven't yet provided a straight HTML example (it doesn't need lit-html at all).

Thank you for your efforts.

**Comment by bennypowers** [comment]
You're welcome to issue a PR to our routing page. There are a few examples here in the repo you can use as templates

**Comment by mercmobily** [comment]
It's not mature enough to be added yet. I am adding the ability to have
different routing groups too.

I am adding this to a huge complex project and will see if it actually
works in a complex real world example

This issue is to see if, once it's fully tested,  you would be willing to
add it as an option to `npm init @open-wc` .

Only a humble offer and proposal.

Merc.

**Comment by mercmobily** [comment]
Quick follow up: I am pushing full routing documentation and added the ability to have multiple routing groups so that you can have sub-sub pages.

I am aiming at adding this to the big application this week. At that point I will know if every actually works, or if there are hidden little bugs.

I would love feedback, ideas, and anything that would make the code better.

**Comment by mercmobily** [comment]
I am working on integrating routify in the big application. It's looking good.
I realise that open-wc focuses on web components. However, I really think that the example application should at least have working routing. But, I might be wrong.

What are my chances of adding an option to `npm init @open-wc` so that it asks users if they want to enable routing with routify?

**Comment by thepassle** [comment]
We've been getting a lot of contributions related to routing, to the point where we're trying to actually slim down on our routing recommendations and add some extra criteria like npm download stats before adding new routers. See more [here](https://open-wc.org/developing/routing.html).

Routing seems to be a very hot topic, with some more opinionated solutions than others, which is exactly the reason that `npm init @open-wc` _doesn't_ come with a routing solution out of the box, much like it doesn't come with a state management solution out of the box. We like our tools to be very extendable and configurable.

I really do appreciate the work you're doing, but I think at this moment in time the chances of adding a router to `npm init @open-wc` are very small. We could potentially add your router to the recommendations in the future once the project has matured, and has gained more traction/usage.

**Comment by mercmobily** [comment]
I totally understand that you want to leave routing out of the equation. No worries at all.
I will make a PR once we use routify in our huge production project.

At that point I will make the PR. Please note that it's important that people know about it so that it *can* get traction. When I make the PR, I will ask you guys to actually look at the code, documentation and API, rather than raw download stats, before deciding whether it's a valuable addition.
