### ISSUE TITLE
workbox precaching legacy and polyfill files by default

### ISSUE THREAD

**Issue by vikerman** [open-wc/open-wc#1360]
The default workbox config glob seems to be '**/*.{html,js,css}' which is precaching all JS including the polyfill and legacy JS. For the starter app with legacy config it comes to 368KB over 10 URLs which seems pretty big.

Is this behavior intentional? I would think just precaching the modern ES modules JS without the polyfills would be better since the chances of service worker being present in older browser(IE11 and friends) is anyway lower.

**Comment by LarsDenBakker** [comment]
You are right, the legacy files should not be cached.

**Comment by thepassle** [comment]
I think I know why this is happening, workbox should not run when [`legacy` is set to false](https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/modern-and-legacy-config.js#L126), but the legacy config is ran first, and _then_ the modern config runs, which also runs workbox, meaning that the legacy files also get precached.

I think this can be fixed by switching:

```js
return [createConfig(options, true), createConfig(options, false)];
```

to 

```js
return [createConfig(options, false), createConfig(options, true)];
```
I'll investigate further tomorrow, but would also be happy to look at a MR 😊

**Comment by vikerman** [comment]
The above fix could potentially break people extending the legacy config to add plugins based on index(config[0], config[1] etc.).

For now I have created a local workbox config of just *.{html|css|js} which could also work since the legacy and polyfills JS go into subdirectories. Let me know how you would want to fix and I can try to create a PR.

**Comment by LarsDenBakker** [comment]
If we cant find a nom breaking fix, we have a breaking change upcoming for the rollup configs, we can take along this change then.

**Comment by vikerman** [comment]
This would handle only the legacy files and not the polyfills?

**Comment by LarsDenBakker** [comment]
Correct, our polyfill setup doesnt only handle features for really old browser but also modern features for browsers which do support service workers. For example intersection observer, resize observer, dynamic imports. There will also be new web component apis that will need polyfills in the future.

**Comment by thepassle** [comment]
We could probably improve on that and add runtime caching for the polyfills now that I think of it actually. It doesnt make sense to aggressively precache _all_ polyfills, when maybe not all of them will be used, but when they get used, they'll still get cached.

I think we may be able to do this as a non breaking change, too.

**Comment by LarsDenBakker** [comment]
Ah yes, interesting. Should we open a separate issue for that?
