### ISSUE TITLE
History management solution for open-wc

### ISSUE THREAD

**Issue by mercmobily** [open-wc/open-wc#1364]
This is another piece of software I just spent _hours_ rewriting and publishing.

https://mobily-enterprises.github.io/historify

It basically provides the ability to have a "back" button in your application (using the function `back()`), which will play nicely with the browsers'. It also provides `teleport()`, `go()` and allows you to add code to ensure login redirects for non-logged in users and so on.

You interested?

It's not quite mature yet, but it will be soon (as soon as I port the current big application so that it uses it). I think it's great, especially since so many sites need to work on mobile and users are really used to their "back" buttons in the app...

**Comment by LarsDenBakker** [comment]
Thanks for the suggestion! It's definitely an interesting project. For open-wc, we mainly focus on tools and configurations or web component specific helper libraries. We don't really do anything with general runtime libraries right now, other than the suggestions we have listed.

**Comment by mercmobily** [comment]
Ah, I see. No worries at all, feel free to close this. I think you are right, in that you need to  keep the scope of your project tight, or scope creep will drive you insane!

**Comment by LarsDenBakker** [comment]
Will close this one :)
