### ISSUE TITLE
IE 11 fails on invalid syntax error from the rollup output

### ISSUE THREAD

**Issue by lakshay35** [open-wc/open-wc#1370]
I am using the latest version of the rollup build configuration and using that inside IE 11. I am getting an 'invalid character' and I believe it is due to the string template backtick (  `  ) that is included in the build files. I am not sure why its being added because it seems that babel is being used to compile down the code to es5 syntax. Could someone take a look please and help me out?

**Comment by LarsDenBakker** [comment]
Do you have a reproduction?

**Comment by LarsDenBakker** [comment]
I just tried a clean `npm init @open-wc`, it's working fine there.
