### ISSUE TITLE
[building-rollup] workbox add runtime caching for polyfills

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc#1371]
as discussed: https://github.com/open-wc/open-wc/issues/1360

We should probably add runtime caching for anything in `polyfills/`, because it doesnt make sense to aggressively precache them when they may not all be used. Using runtime caching, we can cache them on demand.

Investigate if we can make this a non-breaking change, if not, it should go with https://github.com/open-wc/open-wc/issues/1153

**Comment by LarsDenBakker** [comment]
@thepassle Was this implemented?
