### ISSUE TITLE
[scoped-elements] align API more with CustomElementsRegistry proposal

### ISSUE THREAD

**Issue by tmsns** [open-wc/open-wc#1373]
As the use of the scoped-elements experiment is in full force in Lion (https://github.com/ing-bank/lion/pull/599), we see some developer questions/discussions about the use of classnames instead of tagnames. We also see that the CustomElementsRegistry proposal is getting an official explainer by Justin. (https://github.com/w3c/webcomponents/pull/865)

Here, I'd like to propose some changes to scoped-elements in order to align more to the "current" target.
- only allow scoped elements within shadow roots
- abstract away the use of the versioned tagnames by:
  - polyfilling the most used API's: `shadowRoot.querySelector`, `shadowRoot.querySelectorAll`, `styles` (this could use the same algorithm as the template transformation)
  - adding support for the proposed `shadowRoot.createElement()`, `shadowRoot.createElementNS()`, `shadowRoot.importNode()`

The benefits I see from this:
- the use of tag name within code would be still allowed (no big refactors for users)
- migration to the new CustomElementsRegistry will be possible by only updating `ScopedElementsMixin` (when creating the shadowRoot, you'll be able to pass the a CustomElementsRegistry object with the element's `scopedElements` `)
- there might be some possibility to hide the usage of the `ScopedElementsMixin` in a build step (by analyzing the imports and rewriting them and creating a `scopedElements` property) Gut feeling says it might be error prone, though.

Let me know what you think: @manolakis, @LarsDenBakker, @daKmoR , @jorenbroekema

**Comment by tmsns** [comment]
In the end, one could see this as polyfilling the complete proposal, while the scoped-elements project is the use of the polyfill in `LitElement`.

**Comment by jorenbroekema** [comment]
Templates are scoped to the CE they are rendered inside of, so.. practically speaking, aren't scoped elements already scoped within shadow roots just because of the fact that usually you'll apply the mixin on elements that have a shadow root? Or would you really go as far as to only rewrite templates if their target is inside the component's shadow root? Because I'm assuming if you set createRenderRoot to `this` and render everything to light-dom, it would currently work right?

I like the idea of minimizing the migration work by the time the proposal hits the browser and we can rid ourselves of the technical debt this package gives us, but I'm personally not sure how much work it would be to polyfill the entire spec vs how much value it provides in terms of minimizing the work of "yet another migration" to solve the same problem.

**Comment by LarsDenBakker** [comment]
Until scoped custom element registry becomes a web standard, I don't think we should be going anywhere near anything resembling a polyfill. We've had too many bad experiences with that in the web component ecosystem. So overwriting built-in functions is definitely something I think we shouldn't do.

The goal for scoped elements is to solve only the problem of multiple definitions, in the lightest way possible with the most minimal impact on DX and performance. (it's quite a DX improvement actually in my opinion).

Of course if we can align as much as possible to how it might eventually look like, that would be ideal. That way the transition will be easier. It's also important that whatever we do, multiple implementations can coexist on the page. This way a migration away from scoped element doesn't need to be a big bang.

Finally I think we should be clear in our documentation that the scoped elements project is not suitable for every kind of application, it should only be used when using multiple versions is a dealbreak for your project.

**Comment by tmsns** [comment]
> Templates are scoped to the CE they are rendered inside of, so.. practically speaking, aren't scoped elements already scoped within shadow roots just because of the fact that usually you'll apply the mixin on elements that have a shadow root? Or would you really go as far as to only rewrite templates if their target is inside the component's shadow root? Because I'm assuming if you set createRenderRoot to `this` and render everything to light-dom, it would currently work right?

Yup, indeed.  
Currently, scoped elements can be rendered using `createRenderRoot` in the light dom. Lars was mentioning the hope to be able to switch to custom element registry under the hood. (it's actually also the second benefit I was mentioningt) If developers actually start using these scoped elements outside the shadow root, it will be more difficult to switch the internals (or you should support both implementations internally, depending on the usage)  
"Blocking it", I think, would indeed mean to not rewrite templates when used outside.


> I like the idea of minimizing the migration work by the time the proposal hits the browser and we can rid ourselves of the technical debt this package gives us, but I'm personally not sure how much work it would be to polyfill the entire spec vs how much value it provides in terms of minimizing the work of "yet another migration" to solve the same problem.

> Until scoped custom element registry becomes a web standard, I don't think we should be going anywhere near anything resembling a polyfill. We've had too many bad experiences with that in the web component ecosystem. So overwriting built-in functions is definitely something I think we shouldn't do.

Duly noted. 😃
And you certainly have a point about its potential about breaking the web component ecosystem. When drafting it up, I was not really thinking of patching *all* `querySelector`s (ie. `Element.querySelector), but rather patching only those within the element using scoped elements. Then again, is there a difference? 🙈  As it might break the ecosystem anyway?

Would ponyfills be acceptable?
eg.
```javascript
import {querySelector, ScopedElementsMixin} from 'scoped-elements'

class MyElement extends ScopedElementsMixin {
  updated() {
    const el = querySelector(this.shadowRoot, 'my-element');
  }
  render() {
    return html´<my-element></my-element>´;
  }
}
````

> The goal for scoped elements is to solve only the problem of using multiple versions of a web component on a page, in the lightest way possible with the most minimal impact on DX and performance. (it's quite a DX improvement actually in my opinion).

I guess you mean here "as opposed to maintaing the new custom tag yourselve", right? 😃 

> Of course if we can align as much as possible to how it might eventually look like, that would be ideal. That way the transition will be easier. It's also important that whatever we do, multiple implementations can coexist on the page. This way a migration away from scoped element doesn't need to be a big bang.
> 
> I'm also hoping that if we get native support for scoped custom element registries, we would be able to use this under the hood in the scoped elements library. By keeping the library simple and focused, this should be possible.

Do you think extending the library with support of rewriting the `CSSResult` of `static getStyles()` (next to the current rewrite of the (`TemplateResult`) return `render()` and the ponyfills (5 functions) would still be focused enough? 😃 

> Finally I think we should be clear in our documentation that the scoped elements project is not suitable for every kind of application, it should only be used when using multiple versions is a dealbreak for your project.

I totally agree.  
However, as a sidenote, I see it often that developers, even when warned, still misuse technology. In a lot of big environments, once something is delivered with such misusage, it is rarely fixed correctly. In the end, in order to advance, this results in having to maintain multiple versions of that legacy/technology, which, ironically, is what this library is trying to do in the first place. 🙈

**Comment by LarsDenBakker** [comment]
> Yup, indeed.
Currently, scoped elements can be rendered using createRenderRoot in the light dom. Lars was mentioning the hope to be able to switch to custom element registry under the hood. (it's actually also the second benefit I was mentioningt) If developers actually start using these scoped elements outside the shadow root, it will be more difficult to switch the internals (or you should support both implementations internally, depending on the usage)
"Blocking it", I think, would indeed mean to not rewrite templates when used outside.

Good point, we should restrict it to shadow dom only.

> I guess you mean here "as opposed to maintaing the new custom tag yourselve", right? 😃

I think the dev experience of importing classes is better than importing modules with side effects.

> Would ponyfills be acceptable?

> Do you think extending the library with support of rewriting the CSSResult of static getStyles() (next to the current rewrite of the (TemplateResult) return render() and the ponyfills (5 functions) would still be focused enough?

We could do that, but I'm not sure if that's worth it. If we just export a function to get the scoped tag name, you can use it in all the other APIs. I think that keeps it simple, but if there is a high demand we can do it.

**Comment by tmsns** [comment]
> We could do that, but I'm not sure if that's worth it. We will need to add scoped versions of a lot of APIs. If we just export a function to get the scoped tag name, you can use it in all the other APIs. I think that keeps it simple, but if there is a high demand we can do it.

Next to adding support for `LitElement.styles()`, I expect ponyfills for  `querySelector`, `querySelectorAll`, `createElement`, `createElementNS` and `importNode` (where `createElement`  should be avoided when using `LitElement` and the last two are quite exotic) Do you expect any more API's to be covered? Would be great to know, as they might impact the proposal of Justin as well. 😃 

Some API's that I didn't cover here are retrieval properties (ie. `.innerHTML` and `.nodeName`).
