### ISSUE TITLE
[demoing:storybook, storybook:build] Add static folder(s) when running build-storybook

### ISSUE THREAD

**Issue by jdvivar** [open-wc/open-wc#1374]
Hi

I started a project from scratch just to show what the bug is about:
https://github.com/jdvivar/demo-static-files-bug

## Bug reproduction

1. Create web component scaffolding with demoing
    ```sh
    $ npm init @open-wc
    # web component scaffolding > demoing
    ```
2. Add a public statics assets folder and use it in a story
    ```sh
    $ mkdir public
    # I coppied kitten.jpg in public/kitten.jpg
    ```

    On `index.stories.mdx` I added:
    ```md
    ## Kitten image
    <img src="public/kitten.jpg"/>
    ```
3. Start storybook
    ```sh
    $ npm run storybook
    > start-storybook --node-resolve --watch --open
    ```
    It works!  🎉

4. Build storybook
    ```sh
    $ npm run storybook:build
    > build-storybook -s public
    ```
    It doesn't work  `/public` folder is not copied. The `-s` flag shouldn't even be needed because `/public` is the default static folder. The kitten image throws a 404 error when serving `/storybook-static`

5. Not elegant solution for now
    In `pakage.json`
    ```json
    "poststorybook:build": "cp -R public storybook-static/public"
    ```
    I'm sure something similar can be done ad-hoc for rollup config too. However this shouldn't be needed.

## Notes
Note I'm not asking to support the static flag as in https://github.com/open-wc/open-wc/issues/1220, although that would be nice too. I'm asking that `start-storybook` and `build-storybook` **work in the same way**. If the default static folder `/public` is served correctly when doing `start-storybook` the same should go for `build-storybook`.

**Comment by LarsDenBakker** [comment]
Although we try to keep things in sync with regular storybook, there is a stylistic difference between the `start-storybook` of open-wc and the `start-storybook` of storybook itself. 

In regular storybook it always runs webpack, and serves static resources *only* from a `public` folder. Our storybook runs a regular web server, and serves all files regularly.

**Comment by jdvivar** [comment]
Hi @LarsDenBakker, thanks for answering! Please note I'm comparing how `start-storybook` works against `build-storybook`, both for the same `demoing-storybook` package. Maybe I should have omitted the `s` flag, as `public` is the default static folder anyway, am I right?

**Comment by LarsDenBakker** [comment]
`public` isn't the default static folder in `start-storybook`. Because `start-storybook` uses `es-dev-server` any file is available for serving. I understand that can be confusing when running a build, I'm not sure what the best way is to handle this other than document how to copy assets.

**Comment by jdvivar** [comment]
I see! Thank you so much for the clarification!
