### ISSUE TITLE
[polyfills-loader] shadyCssCustomStyle doesn't work

### ISSUE THREAD

**Issue by mosmaall** [open-wc/open-wc#1377]
**Bug reproduction**

- Create simple project that served by es-dev-server.
- Add `webcomponents` and `shadyCssCustomStyle` to polyfillsLoader configs.

![configs](https://user-images.githubusercontent.com/18676651/75431431-6f39d080-597f-11ea-89bb-a3e48a8374b2.png)

- use some CSS variable in `index.html` with `shady-css-scoped` tag.

![index_html](https://user-images.githubusercontent.com/18676651/75431574-9b555180-597f-11ea-9af1-3a3acfeddaac.png)

**Expected Results**
CSS variable should work on all browser.

**Actual Results**
CSS variable not work on IE and got error like this.
![errors](https://user-images.githubusercontent.com/18676651/75431710-d8b9df00-597f-11ea-91ff-ac1e71a26324.png)

**Comment by LarsDenBakker** [comment]
It looks like this polyfill is not shipped as es5. @jrobinson01 is it possible to create an es5 distribution of the polyfill? Of course we generally recommend people to ship modern code, but for polyfills I think it's still a good convention to stick to es5 since they're not part of an app bundle.

**Comment by jrobinson01** [comment]
v0.0.2 published to npm. Thanks @phetw!

**Comment by LarsDenBakker** [comment]
Closing this since the issue was fixed.
