### ISSUE TITLE
Our slogan

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#139]
We print out slogan and badges in pretty much every markdown file:

Open Web Components provides a set of defaults, recommendations and tools to help facilitate your Web Component. Our recommendations include: developing, linting, testing, tooling, demoing, publishing and automating.

(+ badges)

I see them getting out of sync a few times, and it adds quite a bit of repetition in every file. You need to scroll down to see the actual content, which is a problem on mobile phones.

I'd like to suggest only keeping the `Part of Open Web Component Recommendation open-wc` part

**Comment by daKmoR** [comment]
this header is only needed for packages which are individually available as their info will be displayed on npmjs.com.
I agree the header should be shorter and aligned.
@thepassle what is your take on this?

PS: in some distant future we could have plug-in for vuepress or a build step to remove them when displayed in open-wc so then they would only be visible on npmjs.org

**Comment by LarsDenBakker** [comment]
Right, I understand the use case for having them in the regular readmes. A vuepress plugin which removes the header would be cool though!

**Comment by thepassle** [comment]
In the docs site I think we don't need them, yeah. But we do need them for npm packages, do we still want them shorter there? If so, I'd say its okay to cut it down to one sentence: "Open Web Components provides a set of defaults, recommendations and tools to help facilitate your Web Component."

**Comment by daKmoR** [comment]
our slogan can now be managed from a central place and is only visible on npmjs (where it makes sense).
If it should still become shorter or different pls just reopen.
