### ISSUE TITLE
RFC: Reduced support for webpack

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1390]
When we started with open-wc, using rollup for web apps was still pretty new. We started out with configs and recommendations for both webpack and rollup, and were mostly neutral in our recommendations between the two. 

Over time the story for using rollup for web apps improved a lot and we starting leaning more and more towards Rollup. We now generally recommending it for all use cases. 

As a project open-wc has grown a lot, we picked up a lot of tools, guides and configurations over time. All these things cost time to maintain. We have to be careful we don't grow too big, and sometimes let go of things that no longer fit with the goal of open-wc or things that didn't work out so well.

Whenever we add new things for rollup, our current policy is to also add an equivalent for webpack. I'd like to change that strategy, going more all-in on rollup and reducing the level of support we have for webpack. 

I don't want to forget about webpack users, a lot of people don't have the freedom to choose their tools and we still should provide guidance and building web components for them. But these same people likely cannot use our plugins or configs, but need to integrate in an existing build setup. Our documentation and recommendations should focus on that, and it's actually an area we are lacking in already.

In practice, I'm proposing the following changes:
- Deprecate `webpack-index-html-plugin`
- Remove the multi-build option from `building-webpack` (which was always a hack anyway)
- Use `webpack-plugin-html` in `building-webpack` (losing the ability to use HTML as input)
- Add docs on web component specific requirements when integrating with an existing webpack config
- Remove webpack option from generator
- Make rollup more prominent in our docs

This is not something we will do overnight, I'd like to gather feedback (from other maintainers & the community) on this approach first.

**Comment by tmsns** [comment]
I, for one, am always a big proponent of deprecating and removing unused/old options as soon as possible. Therefor, I also agree with most of the proposals. There is only one I am not sure of: the removal of the multi-build.  
What do you mean this?
- having only one exported config? (modern or modern-and-legacy config)
- removing support for IE11 (and thus only having modern config?)

If it's the latter, I think that change might have a deep impact on some users. As you mention, some users don't have the freedom to choose their tools, but they often don't have the choice to choose the browsers they need to support.  
It might be that you mean to have only one config, and having legacy support as an option within the config? That would actually also remove the multi-build aspect.

**Comment by LarsDenBakker** [comment]
@tmsns I mean a single config, where you choose the list of supported browsers yourself. So people who need to support IE11 it will be an es5 build for all browsers. For people who don't need to support IE11, it can be es2015, es2016, es2017 etc.

**Comment by tmsns** [comment]
Great, love it. ❤️ 
Any chance that would come to the `building-rollup` package as well?
And I guess you will (still) use the `browserslist` package for that list of supported browsers?

**Comment by LarsDenBakker** [comment]
the `createDefaultConfig` for both webpack and rollup already work this way, based on `browserslist`.

**Comment by tmsns** [comment]
My bad... for some reason, I expected only `createCompatibilityConfig` to use it. 🙈

**Comment by bennypowers** [comment]
While I agree with the principles offered here, this change has the potential to create a lot of churn for users. I recommend a gradual deprecation with a clear schedule posted ahead of time, maybe with some `postInstall` console logs.

**Comment by LarsDenBakker** [comment]
You're definitely right about churn. My main concern is our documentation, recommendations and further developments. For example I don't want to maintain a webpack version of our new rollup HTML plugin. I actually don't mind maintaining the status quo to avoid breaking existing setups.

**Comment by frank-dspeed** [comment]
i suggest to stay with webpack as rollup needs to much user knowledge every day new typescript users ask how to use rollup and they want to produce none ECMAScript builds rollup is only a ECMAScript module ast builder and writer it is not designed to bundle web components with pollyfills and such stuff.

**Comment by LarsDenBakker** [comment]
I dont agree, I have used both extensively and I find rollup a lot simpler to understand and use.

We recommend building web components with es modules, and to load polyfills as scripts.

**Comment by frank-dspeed** [comment]
Sure rollup is better if you understand as you pointed out but your project does nothing to help your people understand rollup or does it?

**Comment by thepassle** [comment]
Im with lars on this, as a user I find rollup much easier to configure, use, and even write plugibs for. We have extensive documentation on our website on how to set up rollup (and webpack) for your project.

**Comment by emilio-martinez** [comment]
I kind of tend to agree with a full webpack config may not be worth the maintenance. To be honest, it's great from a "getting started" point of view, but depending on the requirements of various projects, I've ended up just using it as reference due to the need to heavily customize the webpack config anyway, or having to integrate it into an existing webpack pipeline.

Would it make sense to just convert the package into a set of utilities/plugins for people to piece together their own config? For example, the particulars of the babel config would become a babel preset? After all, some parts are already their own open-wc packages now.

**Comment by frank-dspeed** [comment]
@emilio-martinez I think you recognized something that I also did. You can not create a generic general purpose config. People need to understand Packaging and Coding, at last, there is no real way around it without offering a full Guided IDE.

**Comment by frank-dspeed** [comment]
but maybe this should look into parcel as alternate the zero config bundlerhttps://parceljs.org/getting_started.html

**Comment by LarsDenBakker** [comment]
Not stale

**Comment by daKmoR** [comment]
Rollup is the recommend setup now
