### ISSUE TITLE
[doc] wrong polyfillsHash option in the documentation

### ISSUE THREAD

**Issue by korial29** [open-wc/open-wc#1397]
Hi,
In the WebpackIndexHTMLPlugin documentation : 
The "polyfillsHash" option should be replaced by "hashPolyfills".

See it in : building-utils/create-index-html line 78.

**Comment by teamgroove** [comment]
@korial29 Thank you for your time creating the issue in the first place. Someone stole some time and corrected the docs and created a PR. Please come back, if you see any issues that need to be corrected. It might take some time, and get prioritized, but you are heard, of course. It's been done. Thank you! https://github.com/open-wc/open-wc/pull/1815#event-3672150732
