### ISSUE TITLE
[es-dev-server]: expose chokidar options

### ISSUE THREAD

**Issue by bennypowers** [open-wc/open-wc#1398]
https://polymer.slack.com/archives/CE6D9DN05/p1583315939403900

I propose changing the type of the `watch` option from `boolean` to `boolean|WatchOptions`

https://github.com/paulmillr/chokidar/blob/6217706d11cac734c437fa4757e4b002a1d90b43/types/index.d.ts#L67-L167

**Comment by danielvanmil** [comment]
this could also solve/workaround #1322
