### ISSUE TITLE
[building-webpack] Consider removing async function transformation

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#140]
In our webpack setup we use the `fast-async` plugin to compile async functions. However that makes it always kick in. Based on: https://caniuse.com/#search=async%20function any browser which supports `type="module"` supports async functions. 

Probably we can remove this transform, but we should properly test this.

**Comment by thepassle** [comment]
I tested this by removing:
`@open-wc/building-webpack/default-config.js:131`
```
'module:fast-async',
```

and adding:
```
async asyncFunction() {
  await new Promise(resolve => setTimeout(resolve, 500));
}
asyncFunction();
```

to my demo app.

I tested on the following browsers (on browserstack):
- firefox 62 and up
- chrome 69 and up
- opera 55 and up
- edge 15 and up
- safari 10.1

where everything works.

Bundlesize savings:

with fast-async
`27.9 kb`

without fast-async
`27.4 kb`

**Comment by LarsDenBakker** [comment]
Thats great, thanks for testing! Performance is probably better too.

**Comment by thepassle** [comment]
Very slightly, yeah
