### ISSUE TITLE
[es-dev-server] 1.44.0 - Resolved to invalid user agent: {"family":"Chrome","version":"80.0.3987"}.

### ISSUE THREAD

**Issue by wsloth** [open-wc/open-wc#1419]
We have es-dev-server set up with babel transpilation enabled.

Both `es-dev-server --babel true --watch` and `es-dev-server --babel true --watch --compatibility auto` result in  the following stack trace:
```
es-dev-server started on http://localhost:8000
  Serving files from ...
  Opening browser on ...
  Using history API fallback, redirecting route requests to '/index.html'
  Using a custom babel configuration.
  
es-dev-server is configured to always compile code. For the fastest dev experience, use compatibility auto without any custom babel configuration.
Resolved to invalid user agent: {"family":"Chrome","version":"80.0.3987"}.
```

In my frontend I get the following stacktrace:
```
updating-element.ts:207 Uncaught (in promise) ReferenceError: regeneratorRuntime is not defined
    at updating-element.ts:207
    at updating-element.ts:207
    ...
```

Our dependencies are up-to-date and we are running the latest es-dev-server version. It seems the breaking change was introduced today. Could this be because we have our own babel setup and the es-dev-server also has one?

Running `es-dev-server --babel true --watch --compatibility none` seems to work fine for the time being on Chrome at least, but that's not a great fix.

**Comment by LarsDenBakker** [comment]
Was this error not there with 1.43.x?

**Comment by wsloth** [comment]
That's correct, I just hardcoded the version to `1.43.0` and it worked as expected

**Comment by LarsDenBakker** [comment]
I'm not able to reproduce this :(

I created a clean project with `npm init @open-wc` and used `npm start`.

I also tried adding the `--babel` flag and a `.babelrc`:

```
{
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-private-methods"
  ]
}
```

The main problem though is the `Resolved to invalid user agent: {"family":"Chrome","version":"80.0.3987"}.`, I don't think the babel flag is related. 

Can you try `npm init @open-wc` to scaffold an app (no other options selected) and see if you still get the error? 

Also, can you try `npm list browserslist browserslist-useragent caniuse-lite`? I suspect some dependencies may have conflicting versions, and are installed with duplicates. Clearing your lockfile could help there.

For this scenario we do have a fallback, where it compiles all to es5 so that at least things still work. But it seems that that's not working correctly, so that's something I'm going to look into.

**Comment by wsloth** [comment]
Sorry, I was quite busy but I managed to try it out. Initializing a new project with the CLI works perfectly, and like you demonstrated, I added babel transpilation too and verified it all working well. The installed version of es-dev-server was 1.44.0. When I run the `npm list browserslist browserslist-useragent caniuse-lite` command in this generated application, I get quite around six results.

However, when I run this in my own application...
```
$ npm list browserslist browserslist-useragent caniuse-lite
<my-project>@<version> /Users/<username>/Developer/<my-project>
├─┬ @babel/preset-env@7.8.7
│ ├─┬ @babel/compat-data@7.8.6
│ │ └─┬ browserslist@4.9.1 
│ │   └── caniuse-lite@1.0.30001033 
│ ├─┬ @babel/helper-compilation-targets@7.8.7
│ │ └─┬ browserslist@4.9.1 
│ │   └── caniuse-lite@1.0.30001033 
│ ├─┬ browserslist@4.9.1 
│ │ └── caniuse-lite@1.0.30001033 
│ └─┬ core-js-compat@3.6.4
│   └─┬ browserslist@4.9.1 
│     └── caniuse-lite@1.0.30001033 
├─┬ @open-wc/webpack-index-html-plugin@1.7.3
│ └─┬ @open-wc/building-utils@2.16.0
│   └─┬ browserslist@4.9.1 
│     └── caniuse-lite@1.0.30001033 
├─┬ es-dev-server@1.43.0
│ ├─┬ @open-wc/building-utils@2.16.0
│ │ └─┬ browserslist@4.9.1 
│ │   └── caniuse-lite@1.0.30001033 
│ ├─┬ browserslist@4.7.3 
│ │ └── caniuse-lite@1.0.30001012  deduped
│ ├─┬ browserslist-useragent@3.0.2 
│ │ └── browserslist@4.7.3  deduped
│ ├─┬ caniuse-api@3.0.0
│ │ ├── browserslist@4.7.3  deduped
│ │ └── caniuse-lite@1.0.30001012  deduped
│ ├── caniuse-lite@1.0.30001012 
│ └─┬ polyfills-loader@1.4.2
│   └─┬ @open-wc/building-utils@2.16.0
│     └─┬ browserslist@4.9.1 
│       └── caniuse-lite@1.0.30001033 
├─┬ <ing specific karma config>@1.2.1
│ └─┬ @open-wc/testing-karma@3.3.1
│   └─┬ @open-wc/karma-esm@2.13.12
│     └─┬ es-dev-server@1.42.0
│       ├─┬ @babel/preset-env@7.8.6
│       │ ├─┬ @babel/compat-data@7.8.6
│       │ │ └─┬ browserslist@4.9.1 
│       │ │   └── caniuse-lite@1.0.30001031 
│       │ ├─┬ @babel/helper-compilation-targets@7.8.6
│       │ │ └─┬ browserslist@4.9.1 
│       │ │   └── caniuse-lite@1.0.30001031 
│       │ ├─┬ browserslist@4.9.1 
│       │ │ └── caniuse-lite@1.0.30001031 
│       │ └─┬ core-js-compat@3.6.4
│       │   └─┬ browserslist@4.9.1 
│       │     └── caniuse-lite@1.0.30001031 
│       ├── browserslist@4.7.3  deduped
│       ├── browserslist-useragent@3.0.2  deduped
│       └── caniuse-lite@1.0.30001012  deduped
└─┬ <ing specific webpack config>@1.3.5
  └─┬ @open-wc/building-webpack@2.13.1
    ├─┬ @babel/preset-env@7.8.6
    │ ├─┬ @babel/compat-data@7.8.6
    │ │ └── browserslist@4.9.1  deduped
    │ ├─┬ @babel/helper-compilation-targets@7.8.6
    │ │ └── browserslist@4.9.1  deduped
    │ ├─┬ browserslist@4.9.1 
    │ │ └── caniuse-lite@1.0.30001031  deduped
    │ └─┬ core-js-compat@3.6.4
    │   └── browserslist@4.9.1  deduped
    ├─┬ @open-wc/building-utils@2.15.0
    │ └── browserslist@4.7.3  deduped
    └─┬ es-dev-server@1.42.0
      ├── browserslist@4.9.1  deduped
      ├── browserslist-useragent@3.0.2  deduped
      └── caniuse-lite@1.0.30001031 
```

**Comment by LarsDenBakker** [comment]
Can you try installing without node_modules and package lock? Also make sure you're on the latest of the different open-wc packages.

It's really annoying, but with npm we have very little control over this :(

**Comment by wsloth** [comment]
For some reason that worked! Completely removing package-lock and installing everything again.

Thank you for helping 😄
