### ISSUE TITLE
[open discussion] Our philosophy

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc#142]
So in regard to the earlier discussion with @petecarapetyan on slack, I think we have some things that require some more explanation/argumentation. I think it would be good to have an 'Our philosophy' page. I made a little draft of what could be on that page, with a couple of points that are good to cover, PR here: https://github.com/open-wc/open-wc/pull/141 (very much a draft to iterate on, phrasing/wording is not perfect etc)

Furthermore, per category, I think it's good to write some clarification/argumentation on why we made some of the choices that we did:

```
Developing:
	- Why lit-html/lit-element over Hybrids, Gluon, Skate, Svelte, etc etc etc?
		-> developed/maintained by Google

Testing:
	- Why karma over WCT
		-> State some of the WCT painpoints

Demoing:
	- Why Storybook

Publishing:
	- Why Netlify over heroku, firebase, etc

Automating:
	- Why circleci

How did we come to these conclusions, what did we try
Do we have blogs/links to back up our choices?
```

Would love to get some input from anyone.

Edit: Some of the documentation in the webpack branch lars is really good. Im not saying every section has to be as elaborate, but it really gives me some trust-like feeling, as opposed to simply saying "Here is the tool. Use this.".

**Comment by daKmoR** [comment]
Our rational for what we recommend e.g. that it needs to be available in at least on stable browser release - 
I think that should be one of our core philosophys... e.g we recommend webpack but we don't say go full out webpack (and use loaders for importing css or decorators and stuff)

**Comment by bennypowers** [comment]
As discussed in Slack, I think it would be nice if this page was a fully-explained repository for rationales. That way we wouldn't have to explain every recommendation each time, but just link back to the philosophical approach.

**Comment by thepassle** [comment]
Closed by https://github.com/open-wc/open-wc/pull/141
