### ISSUE TITLE
Exchange VuePress for a static site generator and web components ⁉️

### ISSUE THREAD

**Issue by Westbrook** [open-wc/open-wc#1421]
I see you're using VuePress to ship your documentation site... 😏 What a strange decision for a set of recommendations around web components. You should probably change that!

What if you used a static site generator (I [hear](https://github.com/Polymer/lit-html/pull/1076) [11ty](https://11ty.dev) is cool), and then leverage actual web components to deliver your content? 🤔 

Let's chat about it here to make plans. I know that people would be interested in taking part in the process...as well as seeing the success in this area. 🎉

**Comment by LarsDenBakker** [comment]
Excellent suggestion

**Comment by Westbrook** [comment]
I'm approaching what it would like like to build this site in this way with the documentation site at https://github.com/adobe/spectrum-web-components and have started to make some good headway. Luckily, the open-wc set up is a little simpler, no TS, but I'm still parsing some of the Vue work that we had been building on top of previously.  One larger file structure change I'd like to make is moving the docs (and all associated dependencies/scripts) into a package that is private. Does anyone have anything against that package being in `/packages`? It's easy to add other workspaces to yarn/lerna, but I'm not sure it's worth doing for a single package. Where ever the package ended up, we could list it as private so it didn't get published to NPM and via the `yarn site:build` and `yarn site:start` commands we could access that package from the root making it easier to alter/replace if needed in the future.

Thoughts?

**Comment by Westbrook** [comment]
So this happened in #1594, yay!
