### ISSUE TITLE
How do I use existing bootstrap like packages ?

### ISSUE THREAD

**Issue by mritunjaymusale** [open-wc/open-wc#1427]
How do I go on about using materialize-css or bootstrap in open-wc?
I did the regular install with npm then how do I import the css files like the way create-react-app does?
I tried the global `<link>` tag approach while doing
`createRenderRoot() {
  return this;
}`
 it manages to load the css but it fails to load the js for some reason.

**Comment by LarsDenBakker** [comment]
This sounds like a lit-element question rather than an open-wc question. In general we don't recommending doing things that you can't do in the browser (yet), such as importing CSS files, and we recommend using shadow DOM.

I'l leave this open if anyone wants to respond with a good answer, but I also recommend checking with lit-element and joining the slack to ask for support.

**Comment by daKmoR** [comment]
indeed global style libraries like bootstrap are fundamentally in conflict how web components with shadow dom work...

hence we do not advice to combine it...

you will need to get the relevant parts in each shadow dom yourself until bootstrap support improved

closing this as it's no something we will work on... 😅 sorry

**Comment by bennypowers** [comment]
I haven't vetted this package, so this isn't an "official open-wc recommendation", but you might want to look into this helper

https://www.npmjs.com/package/lit-css-global-scope

**Comment by daKmoR** [comment]
this basically moves ALL global CSS into the web component... 

https://github.com/ianes1978/lit-css-global-scope/blob/master/src/style.loader.js

```js
import { css } from 'lit-element';

const styleRules = Object.values(document.styleSheets).reduce((obj, styleSheet) => {
   return obj = [...obj, ...Object.values(styleSheet.cssRules)]
}, [])

let externalStyles = styleRules.map(rule => rule.cssText).join('\n');
externalStyles = externalStyles.replace(/html {/g, ":host {");
externalStyles = externalStyles.replace(/@import/g, "/@import");
const globalStyle = css([externalStyles]);

export { globalStyle };
```

not sure if that is what you really want... I personally would avoid it but for a throw it all together usecase it might be okisch...

**Comment by LarsDenBakker** [comment]
I wonder if this is a problem with constuctable stylesheets?

**Comment by bennypowers** [comment]
In principle, this is not all that different than `static get style() { return [shared, css`/* ... */` ]; }`, really
