### ISSUE TITLE
ETA for import maps with NPM (not Yarn)?

### ISSUE THREAD

**Issue by trusktr** [open-wc/open-wc#1429]
I don't use Yarn. Any plan to support imports maps with NPM/package.json/package-lock.json?

**Comment by LarsDenBakker** [comment]
We don't have any plans right now to do further development on our import maps packages. We are waiting for browser implementors to show more interest so that we can recommend people to use it.

**Comment by daKmoR** [comment]
the import maps spec changes significantly so we will need to update existing features and only then will we consider adding more enhancements 😅

closing this for now as it's not an actionable item as we need to wait for an "intend to implement" in a browser
