### ISSUE TITLE
[demoing-storybook] sw generation fails when workbox-config.js exists

### ISSUE THREAD

**Issue by mbeneyto** [open-wc/open-wc#1432]
Having a `workbox-config.js` file at root for app workbox configuration, breaks the Storybook ServiceWorker generation.

Steps to reproduce:
```
npm init @open-wc 
   --destinationPath /demoing-sw 
   --type scaffold 
   --scaffoldType app
   --features demoing building 
   --buildingType rollup 
   --scaffoldFilesFor demoing building 
   --tagName demoing-sw 
   --writeToDisk true 
   --installDependencies npm
```

Create a workbox-config.js file:
```
module.exports = {
  globDirectory: "dist/",
  globPatterns: ["*"],
  swDest: "dist/sw.js",
  swSrc: "sw.js"
};
```

And run `npm run storybook:build`
![image](https://user-images.githubusercontent.com/12471097/76757540-0aa4b100-6788-11ea-8862-ea2bbbc9f43a.png)

The only solution I've found is to delete this file and use [rollup-plugin-workbox](https://www.npmjs.com/package/rollup-plugin-workbox) to configure workbox directly from rollup.config.js:
```
injectManifest({
          globDirectory: 'dist/',
          globPatterns: ['**/*.{html,js,json,ico}'],
          swDest: 'dist/sw.js',
          swSrc: './sw.js',
})
```
Maybe there is a way to deactivate or configure Storybook Service Worker from `main.js` **rollup** option, but I just don't see it 😅

**Comment by LarsDenBakker** [comment]
This is indeed a problem, we should not include the workbox plugin when building storybook.

**Comment by LarsDenBakker** [comment]
This was implemented in the latest version of `@open-wc/demoing-storybook`
