### ISSUE TITLE
Tests don't run when i imports css on lit-element

### ISSUE THREAD

**Issue by boguz** [open-wc/open-wc#1437]
### Problem
I have created a project with the `npm init @open-wc` command, as seen [here](https://open-wc.org/testing/).
I am creating lit-elements and using karma (as configured in the wizard) to test them.
I have written a simple test, which works fine when i run `karma start --coverage`.

The problem is as soon as i import a css file at the top of my webcomponent the tests don't run anymore and i get the following errors:
```
HeadlessChrome 80.0.3987 (Mac OS X 10.13.6) LOG: 'Error loading test file: /test/shadow-dom.test.js'
18 03 2020 16:22:36.894:WARN [HeadlessChrome 80.0.3987 (Mac OS X 10.13.6)]: Disconnected (0 times), because no message in 30000 ms.
```
If i comment out the import, or remove it, then the tests run.

### Environment Details
- Using: `"@open-wc/testing-karma": "^3.0.0"`
- My karma.config.js:
```javascript
const { createDefaultConfig } = require('@open-wc/testing-karma');
const merge = require('deepmerge');

module.exports = config => {
  config.set(
    merge(createDefaultConfig(config), {
      files: [
        // runs all files ending with .test in the test folder,
        // can be overwritten by passing a --grep flag. examples:
        //
        // npm run test -- --grep test/foo/bar.test.js
        // npm run test -- --grep test/bar/*
        { pattern: config.grep ? config.grep : 'test/**/*.test.js', type: 'module' },
      ],

      esm: {
        nodeResolve: true,
      },
      // you can overwrite/extend the config further
    }),
  );
  return config;
};
```

- My dependencies that might be related to this:
```
    "@open-wc/testing": "^2.0.0",
    "@open-wc/testing-karma": "^3.0.0",
    "karma-chai": "^0.1.0",
    "sinon": "^9.0.1"
```

- My lit-element:
```javascript
import { LitElement, html } from 'lit-element';
import styles from './my-element.css';

export class MyElement extends LitElement {
  render() {
    return html`
    <style>${styles}</style>
    <span>Test</span>
  `;
  }

  static get properties() {
    return {
      type: { type: String },
    };
  }

  constructor() {
    super();
    this.type = 'default';
  }
}

customElements.define('my-element', MyElement);
```

- I am using Rollup, but as i import the original webcomponent js file on my tests, i don't think that is of importance now.

- i have seen [this issue](https://github.com/open-wc/open-wc/issues/701), not sure if related...
- i also found an [question on stackoverflow](https://stackoverflow.com/questions/58592923/karma-testing-and-headlesschrome-fail-when-i-try-to-test-webcomponents-that-impo) with a very similar question, but without answers...

This is my first time trying to write tests, and i don't understand what the problem is.
Maybe the problem is that i am importing css (which works fine if i am not testing)?
Any suggestions would be much appreciated.
Please let me know if there is any other information you need...
Thank you

**Comment by LarsDenBakker** [comment]
The problem is that you're importing a CSS file as if it's a module. This doesn't work in the browser. You're probably using a build during development to make it work, you will need to run the same build for testing.

Because we don't recommend writing code that requires a custom build setup we don't have this included in our build setup.

**Comment by boguz** [comment]
Yes, i am using rollup to build everything.
So, other than test using with the build files, the solution would be to have the css in the component itself, something like:
```javascript
static get styles() {
  return css`
    p {
      font-family: Roboto;
    }
  `;
}
```

I have tried it and it works ok, but if the element has a lot of styles it's not nice.   :(

**Comment by LarsDenBakker** [comment]
The stylesheet is just a variable, so you could export it from a JS file:
```
export const myStyles = css`
    p {
      font-family: Roboto;
    }
`;
```

With a code highlighter like `lit-plugin` for VSCode the developer experience is not much different from using `.css` file and you don't get all the build complexities :)

Being able to import CSS modules is a standard that's in the works, when it becomes a standard then we will be able to do something to use it on browsers that don't support them yet.

**Comment by boguz** [comment]
ok, thank you. i will try that!
