### ISSUE TITLE
[testing-helpers] No typings starting from v1.5.3

### ISSUE THREAD

**Issue by floridoo** [open-wc/open-wc#1438]
The package `@open-wc/testing-helpers` is missing the typings. It was fine in v1.5.2.

**Comment by floridoo** [comment]
That was fast, thanks a lot!

**Comment by floridoo** [comment]
Seems like this is not fully resolved yet. There are `*.d.ts` files for the root of the package now, but still not for the files in `src`.

**Comment by Westbrook** [comment]
Just caught that too, testing an extended fix... reopening!

**Comment by floridoo** [comment]
Working perfectly now, thank you!
