### ISSUE TITLE
Prose Style Guide

### ISSUE THREAD

**Issue by bennypowers** [open-wc/open-wc#144]
I'd like to start work on a style guide to help inform contributions.

A few potential examples of the kinds of guidelines that it should contain:

> Use the phrase "Open Web Components" (title case) or "`open-wc`" (lowercase, in backticks) to refer to the project

> Prefer simple English, so that the documentation is as accessible as possible.

> All headings should be Title Case e.g. `Our Philosophy`, not `Our philosophy`

> If list items contain more than two sentences, prefer to use headings.

Thoughts?

**Comment by thepassle** [comment]
+1

Should this be added to `CONTRIBUTING.md`?
