### ISSUE TITLE
[testing-karma] Recent release doesn't understand my browser versions...

### ISSUE THREAD

**Issue by Westbrook** [open-wc/open-wc#1442]
Somewhere between version 3.2.43 and 3.3.8 the tests started to not understand my browsers' user agents:

```
Resolved to invalid user agent: {"family":"Chrome","version":"80.0.3987"}. Using max compatibility mode. Try updating your dependencies, or file an issue with a reproduction.
```

```
Resolved to invalid user agent: {"family":"Firefox","version":"74.0.0"}. Using max compatibility mode. Try updating your dependencies, or file an issue with a reproduction.
```

It's unclear whether this is directly related, but when doing so the test subsequently timeout without running in both browsers...

```
Disconnected (0 times), because no message in 30000 ms.
Firefox 74.0.0 (Mac OS X 10.14.0) ERROR
  Disconnected, because no message in 30000 ms.
Firefox 74.0.0 (Mac OS X 10.14.0) ERROR
  Disconnected, because no message in 30000 ms.
```

I plan to investigate further soon but wanted to get this into the world in case anyone else knows something I don't. You can recreate this by cloning a copy of https://github.com/adobe/spectrum-web-components, bumping `"@open-wc/testing-karma"` in the package JSON and running `yarn && yarn test`.

**Comment by LarsDenBakker** [comment]
This can happen when the browserslist and caniuse-lite dependencies get out of sync with NPM. I don't fully understand the logic, because we list it in our dependencies.... can you try a reinstall without a yarn.lock file?

**Comment by LarsDenBakker** [comment]
Closing, the issue was with nested node modules.
