### ISSUE TITLE
[testing-helpers] change default timeout to 1000ms

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1460]
In `@open-wc/testing-helpers` the `waitUntil` helper gas a default timeout of 2000ms. This is also the default karma timeout. This means that error messages configured aren't actually shown, because karma times out before `waitUntil` does.

We should change this to something else, probably 1000ms.

**Comment by Tomastomaslol** [comment]
Hi @LarsDenBakker It looks like the previous attempt to solve this was closed due to inactivity. Are you happy with me trying to get a fix merged for this issue?

**Comment by LarsDenBakker** [comment]
Yep!
