### ISSUE TITLE
[scoped-elements] Doesn't register the element when using lit-html "until" directive. 

### ISSUE THREAD

**Issue by carloviviano** [open-wc/open-wc#1462]

**Comment by LarsDenBakker** [comment]
Do you have some more information? Can you create a reproduction with  https://webcomponents.dev/create/issue?

**Comment by manolakis** [comment]
I'm trying to reproduce it in webcomponents. Seems a problem with promises.

**Comment by manolakis** [comment]
Reproduction https://webcomponents.dev/edit/yWaR2kJsf06QNnw6nUBv

It's not scoping the element when the promise is resolved
