### ISSUE TITLE
Exclude some module in es-dev-server.config.js

### ISSUE THREAD

**Issue by BenoitClaveau** [open-wc/open-wc#1463]
I failed to exclude mode module from moduleDirs.
ex: moduleDirs: ["node_modules", "!"node_modules/pdf.js-parser/dist/pdf.js"],

**Comment by LarsDenBakker** [comment]
This is not how this option works, the option is to specify module directories. 

We use https://github.com/rollup/plugins/tree/master/packages/node-resolve so it's best to check with the documentation there to see what options are available.

**Comment by BenoitClaveau** [comment]
thx
