### ISSUE TITLE
[polyfills-loader] <template> content is undefined in IE11

### ISSUE THREAD

**Issue by dlockhart** [open-wc/open-wc#1478]
This is a weird one. I'm using a standard setup via `createCompatibilityConfig()`. In IE11, if I try to grab a `<template>` element's [`content` property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTemplateElement/content), it's `undefined` -- as if the web component polyfill isn't fully polyfilling. I'm aware that I can't do anything with templates until after `DOMContentLaoded` -- that's not the issue.

The problem appears to be related to how `webcomponents-bundle.js` is getting included, which is done by creating a script element in JS and appending it to the `<head>`. If instead I include it using a `<script>` element right in the markup, all is fine -- as long as I include it _after_ `core-js`. If I include it before `core-js`, "Out of stack space" errors occur.

Obviously I don't actually want to do this, since then I can't use the nice open-wc feature detection code to exclude the bundle on modern browsers.

My page has something like this in it:

```html
<template>Oh hello</template>
<script>
window.addEventListener('DOMContentLoaded', function() {
    // just be extra super sure that all the polyfills have loaded
    setTimeout(function() {
        var node = document.querySelector('template');
        console.log(node.content); // -> undefined
    }, 5000);
});
</script>
```

Any thoughts/ideas?

**Comment by justinfagnani** [comment]
> The problem appears to be related to how webcomponents-bundle.js is getting included, which is done by creating a script element in JS and appending it to the <head>

If this is true, this is a bug. `webcomponents-bundle.js` bundle is a block script and needs to be in a script tag in the source to function correctly.

**Comment by dlockhart** [comment]
Using the test app, here's essentially what gets produced (sorry it minifies things):

```
<script>
        window.importShim = t =>
            import (t.startsWith(".") ? new URL(t, document.baseURI) : t);
    </script>
    <script src="polyfills/core-js.577a5602a7262d6256830802d4aaab43.js" nomodule=""></script>
    <script src="polyfills/systemjs.6dfbfd8f2c3e558918ed74d133a6757a.js" nomodule=""></script>
    <script src="polyfills/regenerator-runtime.92d44da139046113cb3739b173605787.js" nomodule=""></script>
    <script>
        ! function() {
            function e(e, o) {
                return new Promise((function(t, n) {
                    document.head.appendChild(Object.assign(document.createElement("script"), {
                        src: e,
                        onload: t,
                        onerror: n
                    }, o ? {
                        type: "module"
                    } : void 0))
                }))
            }
            var o = [];

            function t() {
                "noModule" in HTMLScriptElement.prototype ? window.importShim("./d2l-test-app-2283c0e2.js") : System.import("./legacy/d2l-test-app-0c265be5.js")
            }
            "fetch" in window || o.push(e("polyfills/fetch.191258a74d74243758f52065f3d0962a.js", !1)), "noModule" in HTMLScriptElement.prototype && !("importShim" in window) && o.push(e("polyfills/dynamic-import.b745cfc9384367cc18b42bbef2bbdcd9.js", !1)), "attachShadow" in Element.prototype && "getRootNode" in Element.prototype && (!window.ShadyDOM || !window.ShadyDOM.force) || o.push(e("polyfills/webcomponents.d406f4685fdfb412c61f23b3ae18f2dc.js", !1)), !("noModule" in HTMLScriptElement.prototype) && "getRootNode" in Element.prototype && o.push(e("polyfills/custom-elements-es5-adapter.84b300ee818dce8b351c7cc7c100bcf7.js", !1)), o.length ? Promise.all(o).then(t) : t()
        }();
    </script>
```

Note how the webcomponent bundle is included with all the rest of the polyfills and loaded async.

**Comment by LarsDenBakker** [comment]
Both our webpack and rollup configs support only modules. Inline module scripts are delayed until after polyfills are loaded.

We could look into supporting inline scripts, but it can get pretty complicated.

**Comment by tmsns** [comment]
Try putting the `async` property of the script element to `false` before appending it. The scripts should now be run on time (and thus before `DOMContentLoaded`)

**Comment by dlockhart** [comment]
@LarsDenBakker switching my inline script to a module (in my `index.html`) still doesn't work. And I would have expected the 5 second timeout before execution would ensure all the polyfills are loaded anyway. If I run the same script inside a LitElement, it does weirdly have access to the `content` property. So I don't _think_ it's a polyfill timing issue, but maybe a scoping (root document vs. in a component) issue? Like somehow templates are polyfilled correctly inside LitElement but not in the root document.

@justinfagnani is right though that the polyfill docs only seem to mention using the bundle with a `<script>` element. The loader on the other hand can be used asynchronously, so I might play around with using it and the `defer` attribute and then loading the rest of the polyfills and the app.

@tmsns I don't think there's any way to load a script synchronously without using a `<script>` element or doing something hacky like using a synchronous XHR.

**Comment by LarsDenBakker** [comment]
Ah, now I understand the problem. You have a template element in the index.html directly, and when the template polyfill is loaded is crawls the DOM and upgrades the elements. This doesn't work with the polyfills loader, it loads polyfills before running your application. 

The only way to handle your use case is indeed to not load the web components polyfills with the polyfills loader, and include the webcomponents-loader.js in your page directly. The web component polyfills include their own polyfills for promise and symbol, which clash with the core-js polyfills like you experiences. So you will also need to load core-js polyfills yourself.

**Comment by dlockhart** [comment]
Yeah that's kind-of it. I think it's that the template polyfill only [runs on the main document](https://github.com/webcomponents/polyfills/blob/master/packages/template/template.js#L340) when the `DOMContentLoaded` event fires. But by loading the polyfill asynchronously, `DOMContentLoaded` has already fired by the time it loads.

I've confirmed this with some `console.log`s in the polyfill's event handler -- it's adding the listener after `DOMContentLoaded` has already fired. Potentially it could be fixed to check for this case and execute right away in this scenario.

Regardless, now that I see what's going on, this seems more like I have a strange edge case (templates in the main document) and I can work around it in a few different ways.

Thanks for the help all!

**Comment by dlockhart** [comment]
FYI I ended up [raising a defect](https://github.com/webcomponents/polyfills/issues/291) in the Template polyfill in case they want to handle the polyfill being loaded after `DOMContentLoaded`.
