### ISSUE TITLE
[karma-esm] allow nodeResolve to be an object

### ISSUE THREAD

**Issue by chuckhousley** [open-wc/open-wc#1486]
The [karma-esm docs](https://open-wc.org/testing/karma-esm.html#configuration) have the nodeResolve type listed as a boolean, but the [es-dev-server docs](https://open-wc.org/developing/es-dev-server.html#node-resolve) allow for the nodeResolve option to be an object with extra settings that get passed to the rollup plugin.  Is it possible to allow that object to be set in the karma-esm config?

**Comment by ryuhhnn** [comment]
I took a look at this, and it seems like although that type is listed as a boolean, it _is_ indeed accepting an object that's getting passed through to the node-resolve plugin. This might not be an actual bug, but more a documentation error.

**Comment by LarsDenBakker** [comment]
Indeed the docs should be updated.

**Comment by daKmoR** [comment]
we recommend `@web/test-runner`. If the issue persists there feel free to open an issue at https://github.com/modernweb-dev/web
