### ISSUE TITLE
[building-rollup] Missing dedupeModules option

### ISSUE THREAD

**Issue by vikerman** [open-wc/open-wc#1488]
The commit https://github.com/open-wc/open-wc/commit/7320c4643b780e75f8a66091aaa2e9a6a118ea29 never seems to have made it to master or a release.

**Comment by vikerman** [comment]
I am using this with preact and with es-dev-server things work ok with --dedupe option (Fails without that option due to two copies of preact)

However when I built the production build there are two copies of preact getting bundled causing an error in runtime.

I'm guessing this is a problem in other projects too where things like lit-element is potentially getting included multiple times in the final bundle.

**Comment by LarsDenBakker** [comment]
Dedupe is an option of the node resolve plugin: https://github.com/rollup/plugins/tree/master/packages/node-resolve#dedupe

You would need to remove the variant of the config, and add your own variant of node resolve. In an upcoming release we're making it so that you can add provide configuration for node resolve.

**Comment by vikerman** [comment]
Thanks. That worked. 

Sorry for the dumb question - What's the right way to override the `resolve` plugin? I'm just replacing the plugin at position 2. Is there a better way?

And which release should I look out for the `dedupeModules` feature?

**Comment by LarsDenBakker** [comment]
You could use an array filter and filter out plugins with the name `node-resolve`. It's not ideal either unfortunately.

Right now we're on 0.x, 1.x will bring this along with rollup v2 and various other improvements. We've prepared the changes here: https://github.com/open-wc/building-rollup-changes

**Comment by LarsDenBakker** [comment]
We just released v1 where it's easier to adjust. See https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/README.md and https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/MIGRATION.md.

Closing this issue, let me know if something isn't working for you!
