### ISSUE TITLE
Migrate from polymer-cli

### ISSUE THREAD

**Issue by RoXuS** [open-wc/open-wc#1495]
hey everybody,

Someone have migrate from polymer-cli (with prpl-server) to open-wc rollup build?

I do that and all is ok (without issue).

But our clients are on older service-worker url (example `hostname/esm-bundled/service-worker.js`) but my "new service worker" are in `hostname/sw.js`.

I haven't any idea how to refresh all service worker to the new.

**Comment by thepassle** [comment]
this was discussed and solved on slack https://polymer.slack.com/archives/CE6D9DN05/p1586276276188200

**Comment by RoXuS** [comment]
yeah thx !
