### ISSUE TITLE
[mdjs] Single `story` keyword and multiple renderers of stories

### ISSUE THREAD

**Issue by georges-gomes** [open-wc/open-wc#1498]
Hi

I feel like the use of `story` and `story-preview` as 2 keywords is limiting.
Both are stories just not rendered the same way.
what if we want to open up to multiple renderers with support for other rendering engines like React, Vue and other more exotic. I feel like mdjs should support all.

I initially thought that

```
'''js story <my-render>
export const s1 = ...
'''
```

Would be a good way.

1) You have a single keyword for stories (js story)
2) you can use any render of the story

This would render as `<my-render story="name">`

You can import `my-render` via a `js script` in the document or have it loaded my the mdjs host automatically depending on the situation.

```
'''js story
export const s1 = ....
'''
```

Without render should show just the code block?

I look forward to discuss further.

**Comment by georges-gomes** [comment]
Thanks staly 😄

**Comment by LarsDenBakker** [comment]
@daKmoR what's the status on this?

**Comment by daKmoR** [comment]
moving the discussion to https://github.com/modernweb-dev/rocket/issues/315
