### ISSUE TITLE
Legacy build not working with new build setup

### ISSUE THREAD

**Issue by peschee** [open-wc/open-wc#1512]
I just tried the new `open-wc` build setup and notices that the legacy build is broken in IE 11. Here's an example repository https://github.com/peschee/open-wc-legacy-build-test to reproduce the problem.

Steps to reproduce:

- `$ npm init @open-wc` (select "Application" and add "Building")
- Set `legacyBuild: true` in `rollup.config.js`
- Run `npm run start:build` and open in IE 11

The application does not work, the following error is shown in the browser console:

```
Unhandled promise rejection ReferenceError: '_arrayLikeToArray' is undefined
```

**Comment by LarsDenBakker** [comment]
That's odd, I don't see this in our demo app but I do see it in the app scaffolded by `npm init`. Looks like not all the babel helpers are added correctly, will look into it!

**Comment by LarsDenBakker** [comment]
I found the issue, the babel helpers function didn't work the way I expected. It doesn't add dependencies of dependencies automatically. Can you try building-rollup v1.1.1 when it's released? The build is running now.

Sorry about this, and thanks a lot for reporting!

**Comment by qpitlove** [comment]
Good works~
