### ISSUE TITLE
build-storybook/storybook-static build version missing docs and addons.

### ISSUE THREAD

**Issue by konradgorski** [open-wc/open-wc#1516]
start-storybook works great after updating @open-wc/demoing-storybook v1.0.1 to v1.15.2. But I'm seeing that the addons panel, toolbar tools, and docs are missing from the static build.

Below are screenshots.

`start-storybook`
![start-sb](https://user-images.githubusercontent.com/4640511/79379652-35bc2500-7f2d-11ea-8c89-98d35eb15558.png)

`build-storybook`
![build-sb](https://user-images.githubusercontent.com/4640511/79379748-5f754c00-7f2d-11ea-91f0-fa574d6049fb.png)

**Comment by LarsDenBakker** [comment]
Can you try this with the latest demoing-storybook (v2) ?
