### ISSUE TITLE
es-dev-server docs can confuse a reader

### ISSUE THREAD

**Issue by Westbrook** [open-wc/open-wc#1519]
A number of places in the documentation for `es-dev-server` the following code is present:
```
const { app, server } = createServer(config);
```
or 
```
const { app, server } = startServer(config, fileWatcher);
```
Which can confuse because it looks like these methods can't assign values without `await`.

Am I understanding the API for this feature correctly? If this is correct, I'll prepare a PR.

**Comment by LarsDenBakker** [comment]
`createServer` is sync, but `startServer` is async so we need to add an await there indeed.
