### ISSUE TITLE
[building] custom browserslist configuration (including legacy browsers) not allowed, even for valid use cases

### ISSUE THREAD

**Issue by wsloth** [open-wc/open-wc#1522]
Loosely related to: https://github.com/open-wc/open-wc/issues/767

I understand why the browserslist IE11 check exists in https://github.com/open-wc/open-wc/blob/master/packages/building-utils/find-supported-browsers.js , but I do have a valid use case for wanting a "complete" browserslist in my project.

I want to configure https://github.com/amilajack/eslint-plugin-compat which can be very helpful to spot places where developers are writing code which is not necessarily Polyfilled. However, this plugin relies on a complete browserslist configuration to function.

This conflicts a bit with the `open-wc` build tooling, where you can override the existing configuration, but the legacy build is separated and you're not allowed to combine them into one browserslist where `ie 11` is included.

Now, there are a few steps I could take:
- Create a PR for `eslint-plugin-compat` and ask them to allow have a custom browserslist just for that plugin
    - Not preferred, as there are likely other plugins using browserslist too. Additionally, it feels wrong making a change to the eslint plugin just to support OWC build tooling.
- Create a PR for `building-utils/find-supported-browsers.js` to allow the user to configure a flag to ignore their own custom browserslist configuration
    - Example: use `process.argv.includes('--ignore-custom-browserslist')` and ignore any user-defined browserslist configurations if that flag is passed
        - Better solutions would be nicer like just a boolean in a build configuration file
    - A bit hacky and not transparent behavior. At the same time it's also abstracting away the browserslist configuration from the project, which is also not transparent behavior.

I'm not sure which direction to take. I know for sure we want to have this linting plugin to spot polyfill issues, as we've already ran into situations where obscure methods were called (`String.prototype.normalize`) which are not included in polyfill bundles like `core-js-bundle`.

What do you think?

**Comment by LarsDenBakker** [comment]
This is a tough problem indeed. I guess it can be a setting on the config creator, though we generally try to avoid this. Another solution is to skip reading the user's browserslist in general, there are quite a lot of assumptions in our code already about which browsers you're going to build for. If people want to customize the browserslist, they probably should make their own config.

**Comment by wsloth** [comment]
I think if the aim is to have a low-config build this makes sense, however I can imagine people find it useful to have a custom configuration for their specific use-case.

Perhaps it's an idea to ignore legacy browsers in the user-defined browserslist, and only look at those when running the legacy build?

**Comment by LarsDenBakker** [comment]
I started fixing this in https://github.com/open-wc/open-wc/pull/1555 then I realized this is about the webpack config :)

Will need to address that separately...

**Comment by wsloth** [comment]
Issue not resolved, but switched over to rollup as well and will drop this as it's a very low-prio nice to have.
