### ISSUE TITLE
using third party components.

### ISSUE THREAD

**Issue by Dixit199213bafna** [open-wc/open-wc#1526]
I am using the third party component vaadin-grid in my application. But it does not get rendered as in element name few extra numbers are appended i believe that is due to scopedElements. Now when debugged i see vaadin-grid has few functions that use the tagname for some functionality but it is not able to find due to few extra numbers added to tag name. But this issue will have if we use any third party component in our application.

I got the work around is to wrap the vaadin-grid in a custom element and then use that custom element in my app. But with this i have an issue as i have more than 20 grid in my app in few rows i need to display the data in different manner like a link or button etc.

**Comment by LarsDenBakker** [comment]
This issue was addressed and documented in the latest version of scoped-elements.
