### ISSUE TITLE
[storybook-addon-markdown-docs] not ignoring user babel config

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1527]
When compiling jsx to js, we should ignore the user's babelrc and babel config. The user can use babel to modify es-dev-server's response, but this particular compilation is internal to the addon and should not be altered.

The config is here: https://github.com/open-wc/open-wc/blob/master/packages/storybook-addon-markdown-docs/src/jsxToJs.js

**Comment by daKmoR** [comment]
closed via https://github.com/open-wc/open-wc/pull/1542
