### ISSUE TITLE
Shadow Dom not rendering in karma test when using inheritence from another lerna package

### ISSUE THREAD

**Issue by apennamen** [open-wc/open-wc#1530]
Hello,

## Context
I'm using Lerna to manage 2 packages. One package is the "base" package, it contains a class that inherits LitElement (this is my webcomponent base):
```javascript
import { html, LitElement } from 'lit-element';

export class LitKarmaBase extends LitElement {
	render() {
    return html`
      <div>dummy</div>
    `;
  }
}
```

The other packages depends on this first one (symlink on Windows 10). I have another webcomponent that inherits the one in the base package:
```javascript
import { html } from 'lit-element';
import { LitKarmaBase } from 'lit-karma-base';

export class LitKarmaSon extends LitKarmaBase {
	render() {
    return html`
      <div>dummy</div>
    `;
  }
}

window.customElements.define('lit-karma-son', LitKarmaSon);
```

To be able to compare and showcase the issue, I made another LitKarmaSon component, but this time that inherit a LOCAL LitKarmaBase:
```javascript
import { html } from 'lit-element';
import { LitKarmaBase } from './lit-karma-base';

export class LitKarmaSon2 extends LitKarmaBase {
	render() {
    return html`
      <div>dummy</div>
    `;
  }
}

window.customElements.define('lit-karma-son2', LitKarmaSon2);
```

Here is the test that I want to run on the shadow dom for both of the Son components:
```javascript
import { html, fixture, expect } from '@open-wc/testing';
import '../lib/lit-karma-son';


describe('Karma Son', () => {
    it('should be dummy', async () => {
        const el = await fixture(html`<lit-karma-son></lit-karma-son>`);
        expect(el).shadowDom.to.equal(`<div>dummy</div>`)
    })
});

```

## Issue
The test fails for the first Son component (the one who inherits from the LitKarmaBase in the lit-karma-based package), and succeed for the second (the one who inherits from the locally imported LitKarmaBase):
```
START:
  Karma Son
    × should be dummy
  Karma Son2
    √ should be dummy

Finished in 0.259 secs / 0.08 secs @ 12:06:47 GMT+0200 (GMT+02:00)

SUMMARY:
√ 1 test completed
× 1 test failed

FAILED TESTS:
  Karma Son
    × should be dummy
      HeadlessChrome 81.0.4044 (Windows 10.0.0)
    AssertionError: expected '[object Object]\n' to equal '<div>\n  dummy\n</div>\n'

      + expected - actual

      -[object Object]
      +<div>
      +  dummy
      +</div>

    at assertHtmlEquals (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:49:17)
    at Proxy.handleDom (node_modules/@open-wc/semantic-dom-diff/chai-dom-diff.js:70:9)
    at Proxy.overwritingMethodWrapper (node_modules/chai/chai.js:9039:33)
    at Context.<anonymous> (__tests__/lit-karma-son.test.js:8:33)
```
![image](https://user-images.githubusercontent.com/7101875/79634858-6f7b6e80-816d-11ea-9706-12656166b7c6.png)

## Expected Behaviour
It should be at least consistent (either both fail, or both succeed).
I have absolutely no idea why when using the 'distant' base class, the shadow dom can't be rendered. When looking in Chrome with Karma debug mode, the shadow Dom of the first Son is indeed:
```
<!---->
"[object Object]"
<!---->
```
![image](https://user-images.githubusercontent.com/7101875/79634993-5f17c380-816e-11ea-91f4-2eb3b0e85654.png)

## Steps to reproduce
I put everything here to reproduce the issue: https://github.com/apennamen/lit-karma-issue
First run `lerna bootstrap` then run `yarn run test:watch` in the lit-karma-son folder.
I had to activate symlinks on the es-dev-server in the karma config

Thanks a lot for your help I'm stuck with this issue and I don't know  exactly where it comes from...

**Comment by daKmoR** [comment]
hey, this usually happens if there are 2 separate lit-html versions running at the same time. Nested installations are a common cause of this.

You can check with
```
yarn list lit-html
```

there should only be 1 result...

If you have more then 1 then you need to make sure your whole repo uses a compatible lit-html version ranges so it can resolve to one version. If you have - remove your yarn.lock and do run yarn again. (you can also try removing the node_modules folder but that should not be necessary)

**Comment by apennamen** [comment]
Thanks for this quick answer.

I tried the following:
```
lerna clean
lerna bootstrap
cd packages\lit-karma-son
npm list lit-html -dev true
| -- lit-html@1.2.1
npm list lit-html
+-- lit-element@2.3.1
| -- lit-html@1.2.1  deduped
| -- lit-html@1.2.1
```

Same results in the lit-karma-base.
And the issue still exists,

**Comment by daKmoR** [comment]
this will result in a file structure like this
```
.
├── lit-karma-base
│   ├── node_modules
│   │   ├── lit-element
│   │   ├── lit-html
│   ├── karma.conf.js
│   ├── package-lock.json
│   └── package.json
└── lit-karma-son
    ├── node_modules
    │   ├── lit-element
    │   ├── lit-html
    ├── karma.conf.js
    ├── package-lock.json
    └── package.json
```

e.g. there are 2 lit-html in there

you will need to either use lerna with "--hoist" to move all shared dependencies to the root or better yet use yarn workspaces

**Comment by apennamen** [comment]
I made it work in this simple example, thanks for your time!
![image](https://user-images.githubusercontent.com/7101875/79642608-e41ad100-819e-11ea-9ade-e62e133ad5ed.png)

So I had to run karma from the top directory, with karma.conf.js at the to level but I guess I can make it work in a more complex lerna repo with some npm scripts magic.

Just out of curiosity, do you have any idea why using different lit-html libraries, even with the same version, should lead to this?
I've dug a little bit inside lit-html and my wild guess is because the render function is stateful, with "parts" here being a weakmap:
```javascript
export const render = (result, container, options) => {
    let part = parts.get(container);
    if (part === undefined) {
        removeNodes(container, container.firstChild);
        parts.set(container, part = new NodePart(Object.assign({ templateFactory }, options)));
        part.appendInto(container);
    }
    part.setValue(result);
    part.commit();
};
```
But if you have a more comprehensive answer I'd like to read it!

**Comment by LarsDenBakker** [comment]
lit-html uses an instanceOf check to know whether something is a template. because of this, templates from two different instances of lit-html cannot be shared because it doesn't recognise the template.

**Comment by apennamen** [comment]
Thank you both for your answers, open-wc is such a great project !
I'm really enthusiast 🤟
