### ISSUE TITLE
[scoped-elements] Wrongfully replaces non-scoped tags

### ISSUE THREAD

**Issue by lazka** [open-wc/open-wc#1541]
Using @open-wc/scoped-elements@1.0.8

Example:

```js
import {html, LitElement} from 'lit-element';
import { ScopedElementsMixin } from '@open-wc/scoped-elements';

class Button extends LitElement {
    render() {
        return html`button`;
    }
}

class OtherThing extends LitElement {
    render() {
        return html`other thing`;
    }
}

customElements.define('my-other-thing', OtherThing);

class Container extends ScopedElementsMixin(LitElement) {

    constructor() {
        super();
    }

    static get scopedElements() {
        return {
          'my-button': Button,
        };
      }

    render() {
        return html`
            Button: <my-button></my-button>
            OtherThing: <my-other-thing></my-other-thing>
        `;
    }
}
```

This results in

```html
Button: <my-button-55790></my-button-55790>
OtherThing: <my-other-thing-55789></my-other-thing-55789>
```

I would have expected instead

```html
Button: <my-button-55790></my-button-55790>
OtherThing: <my-other-thing></my-other-thing>
```

because I've never set `my-other-thing` as a scoped element and it's defined somewhere else.

I've worked around this for now by doing

```js
static get scopedElements() {
    return {
        'my-button': Button,
        'my-other-thing': customElements.get('my-other-thing'),
        'my-other-thing2': customElements.get('my-other-thing2'),
        'my-other-thing3': customElements.get('my-other-thing3'),
        'my-other-thing4': customElements.get('my-other-thing4'),
    };
}
```

but that's ugly and error prone..

**Comment by lazka** [comment]
In case this is in purpose, my use case is that I'm porting things one by one to scoped elements, and having this all or nothing makes things complicated.

**Comment by daKmoR** [comment]
hey @lazka 👋

this is indeed on purpose. The currently proposed spec says every scoped registry is "new". There is no inheritance from the parent or global registry.

Hence all components you want to use in your scoped registry need to be registered.

We definitely should make this more clear in the docs 😅

@manolakis can you make sure that we have a "warning/info" in the docs about it... and that 
```
'my-other-thing': customElements.get('my-other-thing'),
```
is the recommended way to "reregister" from the global registry if needed.

**Comment by lazka** [comment]
Thanks, having this in the docs like you described would have helped me.
