### ISSUE TITLE
How to avoid unnecessary entry in rollup-plugin-index-html

### ISSUE THREAD

**Issue by kevincox** [open-wc/open-wc#1570]
I have just started using the rollup-plugin-index-html plugin but would like to avoid generating an "entry" file for performance. Right now it generates something like this:

```html
<!-- index.html -->
<script src=bundle.js></script>
```

```js
// bundle.js
export{a as default}from"./bundle-7072fcb1.js";
```

Then the app code is in the second file. I have improved this slightly by setting `entryFileNames: "[name]-[hash].js"` which allows me to set aggressive cache headers but that still has an unnecessary request of first load. It would be nice if the emitted HTML could directly include the second URL without a layer of indirection.

Simplified rollup config below, [full rollup config here](https://gitlab.com/kevincox/recipes/-/blob/0a3c3a06064df4a3ce39835867f8f0dd8664948d/rollup.config.js), [live result](https://5ea623a11eb20b0006d1a4d4--recipes-kevincox.netlify.app/).

```js
// rollup.config.js
import html from "@open-wc/rollup-plugin-html";

export default {
	output: [{
		name: "app",
		format: "esm",
		dir: "dist/",
		entryFileNames: "a/[name]-[hash].js",
	}],
	plugins: [
		html({
			inputPath: "src/index.html",
			publicPath: "/",
		}),
	],
}
```

**Comment by LarsDenBakker** [comment]
Did you try using rollup without the HTML plugin? You will see the same behavior.

It's done by rollup in order to not pollute the export signature of your main export. See: https://github.com/rollup/rollup/issues/3358

You can configure this behavior in the latest version of rollup, I recommend setting `preserveEntrySignatures` to false.

**Comment by bennypowers** [comment]
@LarsDenBakker considering OP's performance concerns, should we make that our Official Recommendation and add it to the [config defaults](https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/src/createSpaConfig.js#L30-L34)?

**Comment by LarsDenBakker** [comment]
Its in our default config, but it has nothing to do with the html plugin :)

**Comment by bennypowers** [comment]
🤦

**Comment by kevincox** [comment]
Thanks, I actually tried this option but was using a too old version of rollup.

However I wonder if there was a way to do this automatically when using this plugin? When generating a JS file it makes sense to have this "facade" to preserve the signature. However when importing into an HTML file there is no need because we can know that the import isn't actually importing anything (just loading the file).

Maybe it requires too much poking into rollup internals but on the surface it makes sense to handle this automatically.

**Comment by LarsDenBakker** [comment]
That's a good point, but since rollup already throws a warning when you don't configure this option yourself I rather not stomp over the user's options.
