### ISSUE TITLE
[npm init @open-wc]: Add choice to create a typescript project

### ISSUE THREAD

**Issue by Matsuuu** [open-wc/open-wc#1571]
As we have resources on how to use es-dev-server with typescript and documentation on using typescript with lit-element, we should be able to have a premade config for typescript also included in the `npm init @open-wc` command.

**Comment by jhoneybee** [comment]
Great advice, I need it very much .  ~~ >_< ~~

**Comment by LarsDenBakker** [comment]
@thepassle is working on this

**Comment by Matsuuu** [comment]
Pretty sure this is resolved, so it can be closed :)
