### ISSUE TITLE
Understanding the "process is not defined" error

### ISSUE THREAD

**Issue by NeilujD** [open-wc/open-wc#1572]
As I bumped a few times in this issue and did not find out a solution could you explain me how should I fix this.

## Context

I am coding a LitElement based web application using `es-dev-server` to serve my app during development phase.

Here is my `es-dev-server.config.js` : 
```js
const proxy = require('koa-proxies')

module.exports = {
  port: 3000,
  hostname: "0.0.0.0",
  watch: true,
  nodeResolve: true,
  appIndex: './index.html',
  middlewares: [
    proxy('/api', {
      target: 'http://server:8000',
    })
  ],
  debug: true
}
```

I want to use (for example) the [`history` package](https://github.com/ReactTraining/history) : 
```js
...
import { createBrowserHistory } from 'history'
...
```

## What is happening

```js
tiny-warning.esm.js:1 Uncaught (in promise) ReferenceError: process is not defined
    at tiny-warning.esm.js:1
```

## What is expected

The `history` package is imported without issues and I can use it.

## Also

I tried to import the `history/esm/history.js` file as the workaround is proposed in the [open-wc website FAQ](https://open-wc.org/faq/#redux-process-is-not-defined) to fix `redux` import but I get the same error.

What do I miss ? Should I build my code before serving it ? Should I use `babel` to compile my code and if so what settings should I use ?

**Comment by LarsDenBakker** [comment]
It's likely one of your dependencies is using `process.environment`, which doesn't exist in the browser. 

I'd file an issue on the project, since they're publishing code that doesn't work. 

You can probably hack it in your project by setting window.process = {} before you load your application. Other option is to use a responseTransformer and rewrite this piece of code in that project, that is essentially what build tools like webpack do.

**Comment by NeilujD** [comment]
@LarsDenBakker Thx !

I thought of that but wasn't sure as `history` is itself a dependency of `redux-first-router` which is recommended in [open-wc website](https://open-wc.org/developing/routing.html) among other routers.

**Comment by LarsDenBakker** [comment]
Fair point, we may not have checked if all the routers listed there work correctly with es-dev-server...

**Comment by NeilujD** [comment]
That's alright !
Still open-wc is very helpfull and you've done great work !

By the way `history` is not the only package that is not supported by es-dev-server :
`query-string` is using `CommonJS` syntax and does not provide `es6` build

**Comment by LarsDenBakker** [comment]
Es dev server just supports what the browser supports :)

**Comment by LarsDenBakker** [comment]
Closing this, as there is no actionable item for us.
