### ISSUE TITLE
[demoing-storybook] webpackFinal is not working

### ISSUE THREAD

**Issue by EragonJ** [open-wc/open-wc#1575]
Hi team, I just tested the latest demoing-storybook and it seems that `webpackFinal` option from [storybook's official documentation ](https://storybook.js.org/docs/configurations/custom-webpack-config/#webpack-customisation-modes/) is not working at all.

I have checked the discussion threads and noticed that the `storybook` here is like a **mixed** version with original storybook and es-dev-server, so I am not sure whether it's related or not. Any information is helpful here, thanks. 

```javascript
// .storybook/main.js
console.log('you can get log here')

module.exports = {
  stories: ['../stories/*.stories.{js,mdx}'],

  // Addons to be loaded, note that you need to import
  // them from storybook-prebuilt
  addons: [
    'storybook-prebuilt/addon-actions/register.js',
    'storybook-prebuilt/addon-knobs/register.js',
    'storybook-prebuilt/addon-a11y/register.js',
    'storybook-prebuilt/addon-docs/register.js',
    'storybook-prebuilt/addon-viewport/register.js',
  ],

  webpackFinal: (config) => {
    console.log('this function wont be executed, so no log here');
    return config;
  },

  // Configuration for es-dev-server (start-storybook only)
  esDevServer: {
    nodeResolve: true,
    open: true,
  },
};

```

ref: https://github.com/open-wc/open-wc/issues/1374

**Comment by daKmoR** [comment]
yes indeed the `@open-wc/storybook` version uses `storybook-prebuilt` and there is actually no webpack involved at all anymore 😬
therefore any webpack specific options are not going to work 😅

**Comment by EragonJ** [comment]
oh i see ... so thanks for the info @daKmoR . If I really wanna do so, it means that maybe I need to fork it and use the storybook (not the prebuilt one) by myself, right. Any hint is appreciated 🙇

**Comment by daKmoR** [comment]
if you wanna use webpack I would go directly with `@storybook/web-components`

**Comment by EragonJ** [comment]
ok i see, thanks for the information :) Feel free to close this thread if you want :)

**Comment by daKmoR** [comment]
thx 🤗
