### ISSUE TITLE
Was the @open-wc/testing 3.0 package unpublished?

### ISSUE THREAD

**Issue by mkay581** [open-wc/open-wc#1576]
I just got a notification from my auto-upgrade tool Dependabot which has upgraded `@open-wc/testing` package from 2.5.11 to 3.0.0 version a few days ago. After the upgrade, attempting to install the same version gives an error and npm registry says that this 3.0.0 version no longer exists. 

`'@open-wc/testing@3.0.0' is not in the npm registry.`

 It was available at some point. So what's going on with that?

**Comment by thepassle** [comment]
We had an unexpected release because of a merge that I messed up 🙁 Some packages got a major release where we didnt want them to, so some stuff had to get reverted/unpublished

**Comment by mkay581** [comment]
Oh okay. So we'll just downgrade back to 2.5 then. Thanks for clarifying. Hopefully in the future these will be a _very_ rare exceptional cases? 😉

**Comment by thepassle** [comment]
Yes, this should be very rare indeed. It was my mistake, I'm sorry for that.

**Comment by mkay581** [comment]
No worries. Thanks for the prompt response. I thought I was going crazy haha
