### ISSUE TITLE
[building-rollup] update to @rollup/plugin-babel

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1583]
The rollup babel plugin migrated to the rollup plugins monorepo. We should use the new variant.

It renames the `babel.genereated` option to `getBabelOutputPlugin`. We should rename our code (babel configs etc.) to reference `output` rather than `generated` too.

**Comment by softdays** [comment]
Also it could be help to not only handle `.babelrc` config file but also `babel.config.json`, `babel.config.js`, etc.

**Comment by LarsDenBakker** [comment]
This is something left up to the babel plugin, we don't read the config ourselves.

**Comment by softdays** [comment]
Ok.. strange... if I move my .`babelrc` to `babel.config.json` I get the following error in the browser:
```
ReferenceError: regeneratorRuntime is not defined
```

Here is my start script :
```bash
"start": "es-dev-server --file-extensions .ts --app-index demo/index.html --port 8000 --node-resolve --preserve-symlinks --babel --open --watch"
```

and my babel config:
```json
{
  "presets": ["@babel/preset-env", "@babel/preset-typescript"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "decoratorsBeforeExport": true }],
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```
I certainly miss something...

**Comment by LarsDenBakker** [comment]
This issue is about the rollup configuration, not es-dev-server.

I think when you use preset-env you need to include some polyfills yourself. It's best to check the babel docs on how that works.

**Comment by softdays** [comment]
You're right my concern is about es-dev-server. Sorry for the inconvenience.
