### ISSUE TITLE
[create] CLI scaffolding step

### ISSUE THREAD

**Issue by Tansito** [open-wc/open-wc#1585]
In the open-wc-cli when you want to create a new application with rollup there is an additional step that ask you for scaffolding files:

<img width="447" alt="Screen Shot 2020-04-30 at 2 10 16 PM" src="https://user-images.githubusercontent.com/9059044/80709087-0391f200-8aed-11ea-9bba-d6ff6e06c9a5.png">

If I remembered correctly this had some sense because you could select between rollup or webpack but now maybe can be deleted directly cause we only have the rollup option.

**Comment by LarsDenBakker** [comment]
For storybook and testing they make sense because they add example tests and stories. I'm not sure what this does for building.

We used to generate a lot more files in the init, but now it's pretty minimal. Maybe we can skip this now? And if you're upgrading a project, we just don't generate example files?

**Comment by Westbrook** [comment]
This looks like it would scaffold the Rollup config: https://github.com/open-wc/open-wc/blob/master/packages/create/src/generators/building-rollup/templates/static/rollup.config.js which I think is a requirement to actually build with Rollup. It seems like we could force the creation of this file, but beyond that, I'm not sure how we'd be able to remove this step in the CLI. Thoughts?

**Comment by Tansito** [comment]
From what I could check there is no difference between selecting or not that option:

![Screen Shot 2020-05-25 at 10 00 38 AM](https://user-images.githubusercontent.com/9059044/82791758-9749aa80-9e6e-11ea-8f91-48b8cd0b3142.png)

This is the output that I got not selecting and selecting the option **Building (rollup)** in that step respectively and it's the same. Furthermore the `rollup.config.js` is always generated too maybe because is being added in previous steps like?:

<img width="431" alt="Screen Shot 2020-05-25 at 10 03 45 AM" src="https://user-images.githubusercontent.com/9059044/82792230-5c944200-9e6f-11ea-9608-fe685da47ff1.png">
