### ISSUE TITLE
[es-dev-server] message channel not injected when body is missing

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1613]
Strictly speaking a body tag in HTML is optional. When it's not there, we don't inject the message channel script. We should look into how we can support HTML pages without a body.

**Comment by daKmoR** [comment]
or throw an error if you try to watch and have no body?

**Comment by daKmoR** [comment]
we recommend `@web/dev-server`. If the issue persists there feel free to open an issue at https://github.com/modernweb-dev/web
