### ISSUE TITLE
where is "Web components: basics" source code?

### ISSUE THREAD

**Issue by anlexN** [open-wc/open-wc#1620]
i need to review [Web components: basics](https://open-wc.org/codelabs/basics/web-components.html?index=/codelabs/#0) website source code.

**Comment by LarsDenBakker** [comment]
It's here https://github.com/open-wc/open-wc/tree/master/packages/codelabs/src/basics.

**Comment by anlexN** [comment]
@LarsDenBakker , your link just let me see some markdown file and images, but i want to know how is your site laid out, ui, router.....?
![image](https://user-images.githubusercontent.com/8686739/81628223-a2deaf80-9432-11ea-92e5-dbf408d12275.png)
