### ISSUE TITLE
[CLI] is upgrade actually supported?

### ISSUE THREAD

**Issue by lemoustachiste** [open-wc/open-wc#1621]
I was trying to upgrade my project to add testing with this tool.
However, at the end of the prompting sequence, npm install occurs (if selected) but nothing else. 
I don't get any new files and the only modified file is package-lock.

This would be the output command:
```
npm init @open-wc --destinationPath /Users/lemoustachiste/work/my-component --type upgrade --features  --typescript true --tagName my-component --writeToDisk true --installDependencies npm
```
Maybe I am mistaken, but the closest I have found to executing this is there: https://github.com/open-wc/open-wc/blob/master/packages/create/src/Generator.js#L19, and the `upgrade` option does not seem supported? https://github.com/open-wc/open-wc/blob/master/packages/create/src/Generator.js#L58

Using the `scaffold` instruction did indeed output something, so I could work with that but I just wanted to make sure this is expected behaviour? 

node -v: v11.15.0
npm -v: 6.14.4

**Comment by thepassle** [comment]
Thanks for reminding me, stale 😛 Sorry for the slow reply @lemoustachiste !

I just checked this locally — but I can't reproduce. Selecting 'upgrade' and 'testing' does indeed add a `karma.config.js` to my project. Are you sure you selected the correct option with the space bar?

```bash
⚡ npm init @open-wc
(node:9514) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
npx: installed 30 in 2.372s

        _.,,,,,,,,,._
     .d''           ``b.       Open Web Components Recommendations
   .p'      Open       `q.
 .d'    Web Components  `b.    Start or upgrade your web component project with
 .d'                     `b.   ease. All our recommendations at your fingertips.
 ::   .................   ::
 `p.                     .q'   See more details at https://open-wc.org/init/
  `p.    open-wc.org    .q'
   `b.     @openWc     .d'
     `q..            ..,'      Note: you can exit any time with Ctrl+C or Esc
        '',,,,,,,,,,''


✔ What would you like to do today? › Upgrade an existing project
✔ What would you like to add? › Testing (karma)
✔ Would you like to use typescript? › No
✔ Would you like to scaffold examples files for? › Testing (karma)
✔ What is the tag name of your application/web component? … asd-asd

./
├── karma.conf.js
└── package.json

✔ Do you want to write this file structure to disk? › Yes
✔ Do you want to overwrite /Users/au87xu/pwa-starter/package.json? › Yes for all files
Writing..... done
✔ Do you want to install dependencies? › No

If you want to rerun this exact same generator you can do so by executing:
npm init @open-wc --destinationPath /Users/au87xu/pwa-starter --type upgrade --features testing --typescript false --scaffoldFilesFor testing --tagName asd-asd --writeToDisk true --installDependencies false 
```

![image](https://user-images.githubusercontent.com/17054057/83438123-2a6f7b00-a441-11ea-994a-1774c013b63b.png)
