### ISSUE TITLE
[es-dev-server] Audit licenses by dependencies

### ISSUE THREAD

**Issue by TimvdLippe** [open-wc/open-wc#1629]
We were looking into using `es-dev-server` in DevTools. To do so, we manage our node deps and enforce that all dependencies have licenses that we are compatible with. Sadly, installing `es-dev-server` shows the following error:

```
added 896 packages in 8.991s
Package "caniuse-lite@1.0.30001055" is licensed under "CC-BY-4.0" which is not permitted by the --onlyAllow flag. Exiting.
```

The licenses we are allowed to use are listed in https://source.chromium.org/chromium/chromium/src/+/master:third_party/devtools-frontend/src/scripts/deps/manage_node_deps.py;l=22-31?originalUrl=https:%2F%2Fcs.chromium.org%2F

Would you consider dropping dependencies that do not have licenses listed in there? In this particular case, it seems like `caniuse-lite` is not actually used in the package [search link](https://github.com/open-wc/open-wc/search?q=caniuse-lite&unscoped_q=caniuse-lite)?

Let me know what your options/preferences are, thanks!

CC @jackfranklin

**Comment by web-padawan** [comment]
`caniuse-lite` is a dependency of `browserslist`: https://github.com/browserslist/browserslist

**Comment by LarsDenBakker** [comment]
We use these dependencies for the compatibility mode, to do compilation based on browser support. This is probably not necessary for chromium dev tools, so we could create a separate "core" package which doesn't include this. I also have some other ideas around this, so I'll think on it a bit and get back to you.

Is there anything wrong with the CC-BY-4.0 license? I see that CC-BY-3.0 is allowed.

**Comment by TimvdLippe** [comment]
I am not a lawyer. This is the list we were given 😢

**Comment by TimvdLippe** [comment]
We were able to resolve this issue on the DevTools side and the linked license has been approved for usage.
