### ISSUE TITLE
Remove comments in build process

### ISSUE THREAD

**Issue by anoblet** [open-wc/open-wc#163]
Assumption:
 - Removing comments will reduce load time.
 - Using 'uglifyjs-webpack-plugin' will provide a minimal impact to the build time

Self explanatory:
- Comments are helpful, if not necessary to document your code.
- They help developers, but not consumers.

In regards to removing comments in code while building a project you can use the following technique:

npm i -D uglifyjs-webpack-plugin

Add the plugin to your webpack.config.js

const UglifyJsPlugin = require("uglifyjs-webpack-plugin");

Adding it to your config:

```module.exports = {
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        uglifyOptions: {
          output: {
            comments: false
          }
        }
      })
    ],
  }`

**Comment by daKmoR** [comment]
fixed in latest release :) thx again for the contribution :)
