### ISSUE TITLE
[es-dev-server] Resolve aliases

### ISSUE THREAD

**Issue by MateWW** [open-wc/open-wc#1632]
Hello, we are trying to use `es-dev-server` to serve `demoing-storybook` in our project. 
Is it possible to configure aliases like in webpack? 
We are using webpack aliases for some locally modified dependencies.

I have tried to write simple middleware but problem is caused by node-resolve which is executed before my middleware.
I also have tested `babel-plugin-module-resolver` but it creates wrong output paths format.

Any ideas?

**Comment by LarsDenBakker** [comment]
We now have a plugin system in es-dev-server, so you could create a custom resolver if you know the full final path: https://open-wc.org/developing/es-dev-server.html#plugins

I also started an experiment that allows using rollup plugins in es-dev-server: https://github.com/LarsDenBakker/es-dev-server-rollup

You could try https://github.com/rollup/plugins/tree/master/packages/alias

**Comment by MateWW** [comment]
@LarsDenBakker Could you provide any example of `es-dev-server` plugins usage together with `demoing-storybook`?
I've tried  to use both methods but it seems to wouldn't work.
I have `es-dev-server` in version `1.50` and `demoing-storybook` in `2.2.3`.

**Comment by bennypowers** [comment]
@MateWW here's one I prepared earlier

```js
// .storybook/main.js
const proxy = require('koa-proxies');

const esmConfig = require('../es-dev-server.config');

module.exports = {
  stories: ['../src/components/**/*.stories.{js,md}'],
  outputDir: '../storybook-static',

  // Addons to be loaded, note that you need to import
  // them from storybook-prebuilt
  addons: [
    'storybook-prebuilt/addon-actions/register.js',
    'storybook-prebuilt/addon-knobs/register.js',
    'storybook-prebuilt/addon-a11y/register.js',
    'storybook-prebuilt/addon-docs/register.js',
  ],

  esDevServer: {
    open: true,
    ...esmConfig,
  },

  rollup: config => ({
    ...config
  })
};
```
```js
// es-dev-server.config.js
const dotenv = require('dotenv');
dotenv.config();

/* eslint-env node */
const { wrapRollupPlugin: wrap } = require('es-dev-server-rollup');
const rollupCommonjs = require('@rollup/plugin-commonjs');
const replace = require('@rollup/plugin-replace');
const { nodeResolve } = require('@rollup/plugin-node-resolve');

const litcss = require('es-dev-server-import-css');
const json = require('es-dev-server-import-json');
const graphql = require('es-dev-server-import-graphql');

const {
  AUTH0_DOMAIN,
  AUTH0_CLIENT_ID,
  GRAPHQL_HOST,
} = process.env;

const REPLACEMENTS = {
  AUTH0_DOMAIN,
  AUTH0_CLIENT_ID,
  GRAPHQL_HOST,
};

const cjsIncludes = [
  '**/*.cjs.js',
  '**/*.cjs',
  '**/bind-decorator/**/*',
  '**/crocks/**/*',
  '**/dedent-tag/dist/index.js',
  '**/fast-json-stable-stringify/index.js',
  '**/graphql-tag/**/*',
  '**/localforage/**/*',
  '**/zen-observable/**/*',
];

const cjsExcludes = [
  '**/mocha/*',
  '**/@open-wc/**/*',
  '**/chai/**/*',
  '**/chai-dom/**/*',
  '**/sinon-chai/**/*',
];

const browserCssGlobs = [
  '/src/styles.css',
  '/src/assets/icons/style.css',
];

module.exports = {
  appIndex: 'index.html',
  plugins: [
    wrap(nodeResolve()),
    wrap(rollupCommonjs({ include: cjsIncludes, exclude: cjsExcludes })),
    wrap(replace(REPLACEMENTS)),
    litcss({ exclude: browserCssGlobs }),
    json(),
    graphql(),
  ],
};
```

**Comment by MateWW** [comment]
@bennypowers Thanks for that advanced example. For now i need only aliases handling but i've got some problem with it.
In docs we can find near `Hook: resolveImport`:
```
es-dev-server already resolves module imports when the --node-resolve flag is turned on. You can do the resolving yourself, or overwrite it for some files.
```
So i guess i could overwrite path only for few aliases without using tons of unnecessary plugins.
When i want to add simple plugin with resolve of aliases it throws error because node-resolve cannot understand this alias.
What i've get done was copy of whole node-resolve from es-dev-server disable native node-resolve resolve aliases and finally call node-resolve with prepared paths. 
It works great now!

I want it to be supported native by node-resolve!
It seems to be oneliner change for node-resolve to add aliases
