### ISSUE TITLE
after npm init open-wc scaffold, storybook fails with 'Could not resolve import'

### ISSUE THREAD

**Issue by evaneus** [open-wc/open-wc#1634]
running `npm init open-wc` with these steps:

✔ What would you like to do today? › Scaffold a new project
✔ What would you like to scaffold? › Web Component
✔ What would you like to add? › Linting (eslint & prettier), Testing (karma), Demoing (storybook)
✔ Would you like to use typescript? › Yes
✔ Would you like to scaffold examples files for? › Testing (karma), Demoing (storybook)
✔ What is the tag name of your application/web component? … test-storybook

Then running
`npm run storybook`

Results in the following error:
```
[storybook]   Error: Could not resolve import "storybook-prebuilt/addon-knobs/register.js" in "".
[storybook]       at Object.resolveImport (/home/evaneus/devt/tmp/test-storybook/node_modules/es-dev-server/dist/plugins/nodeResolvePlugin.js:67:23)
[storybook] 

```

**Comment by LarsDenBakker** [comment]
Should work again now, sorry about that!

**Comment by LarsDenBakker** [comment]
Closing this since the issue was fixed.
