### ISSUE TITLE
[testing-helpers] "scoped-elements-test-wrapper" is already defined in monorepo

### ISSUE THREAD

**Issue by MariusVatasoiu** [open-wc/open-wc#1637]
I have a monorepo and every package uses @open-wc/testing (implicitly @open-wc/testing-helpers).

When I run karma on all packages, I get the following error:

```
HeadlessChrome 81.0.4044 (Mac OS X 10.14.6) ERROR
  Uncaught 
  at http://localhost:9876/context.html:0:0
  
  Error: Failed to execute 'define' on 'CustomElementRegistry': the name "scoped-elements-test-wrapper" has already been used with this registry
      at packages/ui/node_modules/@open-wc/testing-helpers/src/scopedElementsWrapper.js:65:18
```

The problem is that scopedElementsWrapper.js doesn't check if `scoped-elements-test-wrapper` is already defined.

**Comment by LarsDenBakker** [comment]
You are probably loading multiple instances of the testing package, this can create issues on multiple levels. I recommend looking into making sure there is only one version of the testing package installed, depending on the package manager you may need to configure the symlinks setting to ensure things are loaded just once. Otherwise you can run a separate karma instance per package.

**Comment by MariusVatasoiu** [comment]
I solved this problem by hoisting the packages.

Is there any problem if there would be a simple condition to check if that custom element is already defined?

**Comment by LarsDenBakker** [comment]
There is no way of knowing if the two instances of the library are compatible, so a simple check can create subtle bugs.

@manolakis could we auto generate the name here? or do we need to rely on a static name?

**Comment by MariusVatasoiu** [comment]
I've tested two options.
First, was to simply check is the custom element exists, but you're right, there could be different versions and that's a problem.

Second, was to register a new custom element if `scoped-elements-test-wrapper` already exists. I was checking for custom elements with an index at the end, like scoped-elements-test-wrapper-1, until I find an unregistered one.

**Comment by LarsDenBakker** [comment]
Yep that would probably work in this case

**Comment by manolakis** [comment]
Yes, I think the best option is auto-generate the name. I'm on it!

**Comment by manolakis** [comment]
Although auto-generating the name to avoid naming collision is possible, hoisting the package or using Yarn should fix the problem of many definitions, and IMHO is a better practice to have one version of testing-helpers instead of many, don't you think?

**Comment by MariusVatasoiu** [comment]
I wouldn't consider auto-generating the name as a replacement for better practices, but rather as a safe solution in case you want to do something different.

In my case I could solve this problem by hoisting the packages, but if I had some reasons to not hoist the packages (maybe some limitations), I will have this problem. In my setup, I want to be able to run karma in the root of the project through all the packages, but also independently using lerna.
