### ISSUE TITLE
Lit-html fails to render variable name for custom element

### ISSUE THREAD

**Issue by jvanderen1** [open-wc/open-wc#1655]
# Description
I am working on utility function to better grab custom elements and inject props into them for testing. However, when I interpolate a variable inside my call to `html`, my test fails.

# Reproduction
Here is my test suite conducted through `jest` called `MainApp.test.ts`:

```ts
// Imports
// -------

// Components
import '../../src/ts/MainApp';
// Utilities
import {fixture, html} from "@open-wc/testing";

// Internal
// --------

async function getComponent(customElementName: string): Promise<HTMLElement> {
  return await fixture(
      html`<${customElementName}></${customElementName}>`
  );
}

// Tests
// -----

describe('ts/index', () => {
  let component;
  let shadowRoot;

  describe('Rendering', () => {
    it('renders default correctly', async () => {
      component = await getComponent('main-app');
      shadowRoot = component.shadowRoot.innerHTML;
      expect(shadowRoot).toMatchSnapshot();
    });
  });
});
```

An error is produced when running:

```
TypeError: Cannot read property 'shadowRoot' of null
```

due to `component` being null. However, if I have the following function instead:

```ts
async function getComponent(customElementName: string): Promise<HTMLElement> {
  return await fixture(
      html`<main-app></main-app>`
  );
}
```

the tests pass.

# Specs
- `Typescript: ^3.9.2`
- `Jest: ^26.0.1`
- `Babel-jest: ^26.0.1`

**Comment by LarsDenBakker** [comment]
This is because lit-html requires HTML to be valid, because of the way it's dom updates work and because of security. You can't use variables for tagnames like this.

You could do this:

```
async function getComponent(customElementName: string): Promise<HTMLElement> {
  return await fixture(document.createElement(customElementName);
}
```

**Comment by jvanderen1** [comment]
That's interesting. I didn't know how the `html` template interpolates the string arguments, all so fascinating to me. Thanks.
