### ISSUE TITLE
[es-dev-server] Babel fails in latest version

### ISSUE THREAD

**Issue by MateWW** [open-wc/open-wc#1659]
Hi i have a problem with babel in latest version of @open-wc/demoing-storybook.

When i turned on babel transpilation i have got that error.

Error message:
```sh
Invalid mapping: {"generated":{"line":1,"column":0},"source":"","original":{"line":2,"column":0}}
```

Minimal repro repository:
[https://github.com/MateWW/es-dev-server-babel-repro](https://github.com/MateWW/es-dev-server-babel-repro)

Probably problem comes from filename provided as rootDir for babelTransform in [here](https://github.com/open-wc/open-wc/blob/9a55aa83e6b25d3b6e56403b3bbe714bcb23318e/packages/es-dev-server/src/utils/babel-transform.ts#L57)

Thanks in advance

**Comment by MateWW** [comment]
I've discovered that problem is because filename provided as rootDir for babelTransform in [here](https://github.com/open-wc/open-wc/blob/42ba4179bfac290639e1918412a09be6026385dd/packages/es-dev-server/src/utils/babel-transform.ts#L57)

**Comment by obeces** [comment]
Hi!
Try with this:

  "devDependencies": {
    "@open-wc/demoing-storybook": "^2.0.0",
    "es-dev-server": "^1.50.8"
  },

**Comment by MateWW** [comment]
Okey thanks, it works on latest version. 
It's curious how unstable is this technology. 
(there was 5 releases for 5 days)
