### ISSUE TITLE
[docs] Deployment of SPA to github pages 

### ISSUE THREAD

**Issue by diegosanchezp** [open-wc/open-wc#1662]
Hi! 

I was playing with the project generator and built a simple application then I deployed it to github pages, it was easy to do. I did the following:

1. Installed gh-pages 
`yarn add gh-pages`

2. Added a "deploy" script on `package.json`
```   
"scripts": {
  ...
  "deploy": "npm run build && gh-pages -d dist"
}
```
3. Deploy the site by running `npm run deploy`

If you are deploying to a "user or organization site" or "project site" the default config would be fine. 

You think you or I can add this information into the section of `Config & Recommendations -> deploying apps`? I'll have no problem on making a pull request.

**Comment by LarsDenBakker** [comment]
If the user navigates to `diegosanchezp.github.io/drum-machine-fcc/` shouldn't it access JS files like so: `diegosanchezp.github.io/drum-machine-fcc/foo.js` ?

**Comment by diegosanchezp** [comment]
I think i don't understand your question very well. @LarsDenBakker 

But yeah it should with that configuration. Will that lead to a problem?

Here is the working [demo](https://diegosanchezp.github.io/drum-machine-fcc/) and the  [code](https://github.com/diegosanchezp/drum-machine-fcc).

**Comment by LarsDenBakker** [comment]
I mean that without using `publicPath`, your app would be served under `/drum-machine-fcc/` so file requests relative to that (ex. `./app.js`) would point to `/drum-machine-fcc/app.js`. I don't expect you to need to make any changes for that.

**Comment by diegosanchezp** [comment]
In this case it is necessary, because if we do that the files would be served from `diegosanchezp.github.io/` e.g `diegosanchezp.github.io/app.js` and not `diegosanchezp.github.io/drum-machine-fcc/app.js` which is what we want.

I've updated the demo so you can see for yourself, now it's displaying a blank page because of the problem explained above.

**Comment by LarsDenBakker** [comment]
Ah I see, the problem is that you have a `<base href="/">` which will cause urls to be resolved relative to the `/`. Is this base element injected by github?

**Comment by diegosanchezp** [comment]
Oh yes you are right right, my apologies.

No github doesn't inject that, might be my mistake when i was editing  the `index.html`

I must did that when i was referencing an article that did that step to upload it to github, but that was with a different framework, since there it was no docs for the deployment to gh pages on the open-wc webpage, and i was not sure how to do it properly.

Thanks

**Comment by LarsDenBakker** [comment]
I do think that would be a valuable addition to the docs, we would welcome a section on github pages on https://open-wc.org/deploying/.
