### ISSUE TITLE
[building-rollup] createSpaConfig generates 2 JS files for one page

### ISSUE THREAD

**Issue by stephenwade** [open-wc/open-wc#1666]
Hi there! If I import a certain module into my SPA, rollup generates 2 JS files instead of 1. This causes an unnecessary extra request and slows down my page loading, since one critical request is chained behind another one.

I've tried to figure out why it's happening without much success. One thing I was able to figure out is that it is caused by the output plugins in the rollup config. I will include an example config that removes the output plugins and only produces one JS file.

Why is `createSpaConfig` generating 2 JS files instead of 1? This seems like a bug that I could work around by disabling the output plugins, but I'd like to understand why it's happening and see it fixed if possible.

index.html:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script type="module" src="/src/festival-app/festival-app.js"></script>
  </head>
  <body>
    <festival-app></festival-app>
  </body>
</html>
```

festival-app.js:
```js
// if I import this module, the rollup output has 2 JS files
import { AudioContext } from 'standardized-audio-context';

export class FestivalApp extends HTMLElement {
  constructor() {
    super();
    this.audioContext = new AudioContext();
  }
}

window.customElements.define('festival-app', FestivalApp);
```

rollup.config.js (2 JS files output):
```js
import merge from 'deepmerge';
import { createSpaConfig } from '@open-wc/building-rollup';

const baseConfig = createSpaConfig({
  workbox: false,
});

export default merge(baseConfig, {
  input: './index.html',
});
```

rollup.config.js (1 JS file output):
```js
import merge from 'deepmerge';
import { createSpaConfig } from '@open-wc/building-rollup';

const baseConfig = createSpaConfig({
  workbox: false,
});

const overwriteMerge = (destinationArray, sourceArray, options) => sourceArray;
export default merge(
  baseConfig,
  {
    input: './index.html',
    output: {
      plugins: [],
    },
  },
  // replace plugins array instead of merging it
  { arrayMerge: overwriteMerge }
);
```

**Comment by LarsDenBakker** [comment]
This is caused by https://github.com/open-wc/open-wc/issues/1625, we need to figure out a good solution here.

**Comment by LarsDenBakker** [comment]
Not stale

**Comment by LarsDenBakker** [comment]
Fixes by https://github.com/open-wc/open-wc/pull/1783
