### ISSUE TITLE
[es-dev-server] Feature request: HTTP range request

### ISSUE THREAD

**Issue by stephenwade** [open-wc/open-wc#1669]
I would like es-dev-server to support HTTP range requests. Without them, I can't use es-dev-server to test an app that tries to jump around in an audio file.

Sources:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Configuring_servers_for_Ogg_media#Handle_HTTP_1.1_byte_range_requests_correctly
- https://pervasivecode.blogspot.com/2012/09/currenttime-not-working-with-html5.html
- https://developpaper.com/question/html5-audio-setting-current-time-in-chrome-is-invalid/

**Comment by LarsDenBakker** [comment]
You could try adding https://github.com/koajs/koa-range in a middleware

**Comment by stephenwade** [comment]
That worked, thank you!

For anyone else running into this issue later, here's how I solved it:

1. Install `koa-range` (`npm install --save-dev koa-range`).
2. Create `es-dev-server.config.js`:

```js
var range = require('koa-range');

module.exports = {
  middlewares: [range],
};
```
