### ISSUE TITLE
[es-dev-server] In IE11 transform-systemjs throws an error on empty file

### ISSUE THREAD

**Issue by goremikin** [open-wc/open-wc#1687]
When `es-dev-server` `v1.53.0` serves an empty `*.js` file or a file with no JS code, an error is thrown.

For instance if lib/types.js contains the following content:
```
//# sourceMappingURL=types.js.map
```

the following error is thrown:

```
Unhandled promise rejection Error: Error loading http://192.168.0.25:3001/lib/types.js?transform-systemjs from http://192.168.0.25:3001/lib/coral-item.js?transform-systemjs (SystemJS Error#3 https://git.io/JvFET#3)
```

It used to be fine in `1.50.6` and prior to that.

A quick investigation shows that the output produced by running `?transform-systemjs` in `1.50.6` and `^1.53.0` is different, which may be the cause of the problem. `systemjs@6.3.2` is used in both cases.

**Comment by moodyjmz** [comment]
I have encountered this issue too.

**Comment by goremikin** [comment]
Hello, any updates on this issue, the code still failing with `v1.54.0`

**Comment by LarsDenBakker** [comment]
Sorry for the late response, will look into it
