### ISSUE TITLE
es-dev-server commonjs issue with react and prop-types

### ISSUE THREAD

**Issue by karlhepler** [open-wc/open-wc#1699]
When I run es-dev-server with react + prop-types, I get this error:

```
Uncaught SyntaxError: The requested module '../../../prop-types/index.js' does not provide an export named 'default'
```

Everything that I'm reading tells me that this rollup plugin can fix the problem: https://www.npmjs.com/package/@rollup/plugin-commonjs

Is this something that can be added to the plugin pipeline?

**Comment by bennypowers** [comment]
you've got two options that I am aware of
1. use `patch-package` to patch react
2. use rollup to transform cjs at serve-time
```js
// es-dev-server.config.js
const { wrapRollupPlugin: wrap } = require('es-dev-server-rollup');
const rollupCommonjs = require('@rollup/plugin-commonjs');
const { nodeResolve } = require('@rollup/plugin-node-resolve');

const cjsIncludes = [
  '**/*.cjs.js',
  '**/*.cjs',
  '**/prop-types/**/*',
 // etc...
];

const cjsExcludes = [
  '**/mocha/*',
  '**/@open-wc/**/*',
  '**/chai/**/*',
  '**/chai-dom/**/*',
  '**/sinon-chai/**/*',
  // season to taste...
];

module.exports = {
  appIndex: 'index.html',
  plugins: [
    wrap(nodeResolve()),
    wrap(rollupCommonjs({ include: cjsIncludes, exclude: cjsExcludes })),
  ],
};
```

**Comment by abdonrd** [comment]
@bennypowers instead of `wrap(nodeResolve()),` you can use the `es-dev-server` option `nodeResolve: true,`, right?

**Comment by bennypowers** [comment]
> @bennypowers instead of `wrap(nodeResolve()),` you can use the `es-dev-server` option `nodeResolve: true,`, right?

Absolutely. I've run into some bugs using both at the same time, so I've opted to go with a 'plugins-first' config style.

**Comment by karlhepler** [comment]
Wow! Thank you! This is great!

**Comment by bennypowers** [comment]
Glad that was helpful. I'm going to close this issue on the assumption that the above snippet solves it for you. Just reopen if you're still experiencing the same problem.
