### ISSUE TITLE
[es-dev-server] support for PNPM / rush

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1700]
After discussion with @web-padawan @benjamind we are seeing some issues with resolving modules in PNPM / Rush repositories with es-dev-server out of the box.

We should look into what we can do to improve support, or how we can document this better.

**Comment by daKmoR** [comment]
we recommend `@web/dev-server`. If the issue persists there feel free to open an issue at https://github.com/modernweb-dev/web
