### ISSUE TITLE
[es-dev-server] Rollup error on Mac

### ISSUE THREAD

**Issue by moodyjmz** [open-wc/open-wc#1701]
Mac: 10.14.16
Node: 13.6.0

Creating a new Web Component using `npm init @open-wc` and running gives errors on Mac.

### How Do We Reproduce?

`npm init @open-wc`, install and then `npm start`, on Mac.

### Expected Behavior

ES Dev Server starts and runs

### Actual Behavior

Rollup throws an error:

```bash
[es-dev-server] Error: No valid exports main found for '~/rollup-bug/node_modules/@rollup/pluginutils'
[es-dev-server]     at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
[es-dev-server]     at applyExports (internal/modules/cjs/loader.js:502:14)
[es-dev-server]     at resolveExports (internal/modules/cjs/loader.js:551:12)
[es-dev-server]     at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
[es-dev-server]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
[es-dev-server]     at Function.Module._load (internal/modules/cjs/loader.js:855:27)
[es-dev-server]     at Module.require (internal/modules/cjs/loader.js:1033:19)
[es-dev-server]     at require (internal/modules/cjs/helpers.js:72:18)
[es-dev-server]     at Object.<anonymous> (~/rollup-bug/node_modules/@rollup/plugin-node-resolve/dist/index.js:11:19)
[es-dev-server]     at Module._compile (internal/modules/cjs/loader.js:1144:30) {
[es-dev-server]   code: 'MODULE_NOT_FOUND'
```

I did do some digging and there is a change between rollup/pluginutils 3.0.10 and 3.1.0:
https://github.com/rollup/plugins/commit/c5991820e01a773ceefb6c47b5a1e312c1708892#diff-25bff1ad7bb1f51c74707c56d8efd3f0

Forcibly setting rollup/pluginutils to 3.0.10 results in no error.

**Comment by LarsDenBakker** [comment]
Thanks for filing the issue. I can't reproduce this myself, but I see that there have been a lot of changes around this are.

I updated the rollup dependencies to the latest in https://github.com/open-wc/open-wc/pull/1702, can you try again?

**Comment by LarsDenBakker** [comment]
Having some issues in the CI, looking into that.

**Comment by moodyjmz** [comment]
@LarsDenBakker pulling that PR and using the es-dev-server package runs without issue for me

**Comment by moodyjmz** [comment]
@LarsDenBakker sorry, was still pointing to my modified build using older rollup, it still fails
