### ISSUE TITLE
[es-dev-server] plugin hooks not called

### ISSUE THREAD

**Issue by ranielzed** [open-wc/open-wc#1703]
Hi, I have the following inside the config file:

```js
module.exports = {
  port: 3000,
  watch: true,
  open: true,
  plugins: [
    {
      serverStart({ app }) {
        console.log('expecting to see this on server start');
      },
    },
  ],
  nodeResolve: true,
  appIndex: 'index.html',
  moduleDirs: ['node_modules']
...
}
```

But I doesn't seem to pickup the plugins. I turned on debug, but I didn't see any plugins. Did I miss anything?

**Comment by LarsDenBakker** [comment]
Which version of es-dev-server are you using?

**Comment by ranielzed** [comment]
sorry, forgot to note that. version 1.54.1

**Comment by LarsDenBakker** [comment]
Sorry for the late response here. I just tried to reproduce this:

```
npm init @open-wc
```

Don't choose any extra options.

Added a config file `es-dev-server.config.js`:

```js
module.exports = {
  port: 3000,
  watch: true,
  open: true,
  plugins: [
    {
      serverStart({ app }) {
        console.log('expecting to see this on server start');
      },
    },
  ],
  nodeResolve: true,
  appIndex: 'index.html',
  moduleDirs: ['node_modules']
}
```

 and I'm seeing the console log from `serverStart`.

**Comment by ranielzed** [comment]
@LarsDenBakker Thank you. Seems like this is already fixed. I tried version 1.56.0 and I also saw the log.
