### ISSUE TITLE
[es-dev-server] Issue importing commonjs modules

### ISSUE THREAD

**Issue by ronnyroeller** [open-wc/open-wc#1713]
I lately encountered an issue importing a commonjs module when running the app in `es-dev-server` (it works with other bundlers like `esbuild`).

The library author (yjs) suggested to file a ticket with `es-dev-server` to see if the rollup version can be bumped (and I presume the custom transformer to bundle commonjs modules be removed): https://github.com/dmonad/lib0/issues/9#issuecomment-641507685

**Comment by LarsDenBakker** [comment]
Es dev server isnt a bundler, its a dev server that relies on using what the browsers supports and avoid complicated builds. The browser only supports standard es modules.

You could use a build tool (like esbuild) to transform this package for use in the browser.

We have a dependency on rollup, but that's only to reuse a plugin for module resolution we dont use rollup itself. The version of rollup is up to date, and rollup itself doesnt actually handle commonjs either, its supported through a separate plugin. 

So the advice is not quite accurate :)

I have been experimenting with being able to reuse rollup plugins which do single file transforms in es dev server, its experimental but you can try it: https://github.com/LarsDenBakker/es-dev-server-rollup

There are a lot of rough edges between esm and cjs, so caution is adviced :)

**Comment by bennypowers** [comment]
If your dependency is relatively simple, you might consider using `patch-package` and rewriting it as a standard module.

**Comment by nibmz7** [comment]
I wrote a simple plugin using esbuild itself for use with [web dev server](https://modern-web.dev/docs/dev-server/overview/) to be able to run React out of the box. I'm not sure if this is the right thing to do but just sharing if it helps.

Plugin - [CommonJs Transformer plugin for web dev server (formerly es-dev-server)](https://github.com/nibmz7/whatsapp-mock-ui/blob/main/scripts/esbuild_cjs_plugin.mjs).
Usage - `cjsPlugin(['react', 'react-dom'])` https://esbuild.github.io/api/#external

Before
```js
...
const React = require('react'); //external package; preserved by esbuild
const OtherDependency = __require('Y'); //generated by esbuild
...  
export default require_x();
```
After
```js
import React from 'react';  
...  
const OtherDependency = __requireY(); //generated by esbuild
...
const defaultExport = require_x();
export default defaultExport;

const namedExportY = defaultExport.Y;
export {
    namedExportY
}
```
