### ISSUE TITLE
How to build and consume scaffolded component? 

### ISSUE THREAD

**Issue by svdoever** [open-wc/open-wc#1714]
using `npm init @open-wc` I scaffolded both an application and a component. The application has the rollup configuration to produce a production build. The scaffold component only has a watch mode, no build, and no rollup configuration.

What is the best way to build a component, and to consume the component from the application?

**Comment by LarsDenBakker** [comment]
I think https://open-wc.org/publishing/ should cover what you're looking for.

**Comment by svdoever** [comment]
Yes, and I can include it in my own build tooling... but as a starter project, it is strange that there is only a development mode, and no support for adding multiple components...

**Comment by LarsDenBakker** [comment]
As the page explains, there is no build required for the component project. You can use the scaffolded project to develop your component and publish it to NPM.

The application can install this component and do the final build for production optimisations.

**Comment by svdoever** [comment]
Ah ok, sorry... understand your approach. In my case I would prefer to skip the npm publishing step and build thee collection of components into a single consumable bundle (es6 and legacy versions) because the components will be used without additional building step in a context where I can only include a bundle. I will look into another approach to accomplish this, something like the following rollup.config.js:

```javascript
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';
import { terser } from 'rollup-plugin-terser';
import filesize from 'rollup-plugin-filesize';
import typescript from '@rollup/plugin-typescript';
import sass from 'rollup-plugin-sass';

export default [
  {
    input: ['src/index.ts'],
    output: {
      file: 'build/index.js',
      format: 'esm',
      sourcemap: true
    },
    plugins: [
      sass({output:true}), 
      typescript(), 
      resolve(), 
      terser(), 
      filesize()
    ]
  },
  {
    input: ['src/index.ts'],
    output: {
      file: 'build/index.legacy.js',
      format: 'esm',
      sourcemap: true
    },
    plugins: [
      sass({output:false}),
      typescript({target: "es5"}),
      resolve(),
      commonjs({
        include: 'node_modules/**'
      }),
      babel({
        runtimeHelpers: true,
        presets: [
          [
            '@babel/preset-env',
            {
              useBuiltIns: false,
              modules: false,
              targets: {
                browsers: '> 1%, IE 11, not dead'
              }
            }
          ]
        ],
        plugins: ['@babel/plugin-transform-runtime']
      }),
      terser(),
      filesize()
    ]
  }
];
```

Where the `index.js` will include the web components for the bundle.

In that case I can consume it in my HTML like:

```html
<script src="webcomponents-loader.js"></script>
<script src='index.js' type="module"></script>
<script src='index.legacy.js' nomodule=""></script>
```

and handle both IE11 and other browsers...
