### ISSUE TITLE
[Testing] Testing Stencil Web Component

### ISSUE THREAD

**Issue by vogloblinsky** [open-wc/open-wc#172]
Hi,

I am benchmarking many solutions for testing a simple Web Component created with Stencil.

Did you already test this kind of component with open-wc ?

I have tested :
- webdriver.io : facing shadow Dom querying issues with Selenium + IE11. Seems to be a complicated way to achieve e2e testing for WC.
- Web Component tester : having difficulties with test-fixture package. Seems to not be very stable, the root README is not up to date. Also have difficulties with IE11.

Thanks

**Comment by daKmoR** [comment]
As Stencil build outputs pure native webcomponents you can definitely test these build outputs.
You will, however, need to handle the triggering of the stencil build yourself.

Stencil has a recommended way of testing if you prefer a more intergrated solution https://stenciljs.com/docs/unit-testing

**Comment by vogloblinsky** [comment]
Hi,

Ok just started with your test tooling, seems very promising :+1: 

Regards

**Comment by vogloblinsky** [comment]
First result are good, but i have an issue testing it. 

Here is my setup : 
![image](https://user-images.githubusercontent.com/2841805/52055256-2b4b8080-255f-11e9-9820-41f73e1cb78d.png)

The dist folder contains the generated Web Component with Stencil, this one : https://github.com/vogloblinsky/nutrition-web-components/tree/develop/packages/nova

Here is my test file :

```
import { expect, assert, fixture } from '@open-wc/testing';

import { nextFrame } from '@open-wc/testing-helpers';

import { defineCustomElements } from '../dist/esm/es2017/nova.define.js';
defineCustomElements(window);

describe('<nova-badge>', () => {
  it('Rendered by Stencil', async () => {
    const el = await fixture('<nova-badge></nova-badge>');
    await nextFrame();
    expect(el.getAttribute('class')).to.equal('hydrated');
    const scoreElement = el.shadowRoot.querySelector('.score');
    assert.notEqual(scoreElement.getAttribute('class').indexOf('one'), -1);
  });
  it('should have the nova badge score to 1', async () => {
    const el = await fixture('<nova-badge></nova-badge>');
    await nextFrame();
    const scoreElement = el.shadowRoot.querySelector('.score');
    assert.equal(scoreElement.textContent, "1");
  });
});
```

Each "it" works fine independently, but grouped not. I got this error, where am i wrong ?
Thanks

```
31 01 2019 13:52:19.808:INFO [karma-server]: Karma v3.1.4 server started at http://0.0.0.0:9876/
31 01 2019 13:52:19.810:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
31 01 2019 13:52:19.814:INFO [launcher]: Starting browser ChromeHeadless
31 01 2019 13:52:20.382:INFO [HeadlessChrome 72.0.3626 (Linux 0.0.0)]: Connected on socket PAvw7Cidi4R4qbL7AAAA with id 44635337
  <nova-badge>
    ✔ Rendered by Stencil
    ✖ should have the nova badge score to 1

Finished in 0.089 secs / 0.015 secs @ 13:52:20 GMT+0100 (CET)

SUMMARY:
✔ 1 test completed
✖ 1 test failed

FAILED TESTS:
  <nova-badge>
    ✖ should have the nova badge score to 1
      HeadlessChrome 72.0.3626 (Linux 0.0.0)
    TypeError: Cannot read property 'textContent' of null
        at Context.it (/tmp/_karma_webpack_/commons.js:32909:80)
```

**Comment by daKmoR** [comment]
that should definitely work 🤔 

could you provide a repo or push your changes to a branch so we could take a look?

**Comment by daKmoR** [comment]
awesome 💪  that was really helpful 👍 

I didn't know that stencil render is also pretty async and apparently may take more then 1-2 frames.

```js
const el = await fixture('<nova-badge></nova-badge>'); // has one await nextFrame();
await nextFrame(); // still not enough

// to be sure we need to await a specific stencil feedback
await el.componentOnReady();

// we can verify by using a sync render then then await - and bam that works :)
const el = await fixtureSync('<nova-badge></nova-badge>');
await el.componentOnReady();
```

I'm not super sure if that is the correct promise to await - do you know if that fits in all usecase?
if so we could bake that support into open-wc :) 

e.g. writing this is all you need and we will internally await that the stencil component is ready to be tested
```js
const el = await fixture('<nova-badge></nova-badge>');
```

**Comment by vogloblinsky** [comment]
Thanks @daKmoR 
`await el.componentOnReady();` works fine !

**Comment by daKmoR** [comment]
awesome I'm reopening this as we are going to bake this feature into the fixture itself 💪

**Comment by vogloblinsky** [comment]
Just added Browserstack test, works like a charm ! :+1: 
Just need for Stencil to add @babel/plugin-syntax-dynamic-import + reference in karma.es5.config.js

```
module.exports = config => {
  let proxyEs5Settings = es5Settings(config);
  proxyEs5Settings.webpack.module.rules[0].options['plugins'] = ["@babel/plugin-syntax-dynamic-import"];
  config.set(merge(proxyEs5Settings, karmaConf(config)));
  return config;
};
```

**Comment by vogloblinsky** [comment]
Just a remark for this page : https://open-wc.org/testing/testing-karma-bs.html#setup
It would be nice if we explain that by default, the browsers list is : 

```
browsers: [
  'bs_win10_chrome_latest',
  'bs_win10_firefox_latest',
  'bs_win10_edge_latest',
  'bs_osxmojave_safari_latest',
  'bs_win10_ie_11',
]
```

and how user can add or change this list.

You want a PR on that ?

**Comment by daKmoR** [comment]
yes plsss :)

**Comment by vogloblinsky** [comment]
Thanks guys !
