### ISSUE TITLE
[es-dev-server] Fails on message-channel with polymer 2 project

### ISSUE THREAD

**Issue by davidmaxwaterman** [open-wc/open-wc#1720]
To reproduce:

1. mkdir es-dev-server-test && cd es-dev-server-test
1. npm install -g polymer-cli
1. npm install -g es-dev-server
1. polymer init --name polymer-2-application
1. es-dev-server --debug

1. open http://localhost:8000 in chrome
1. open dev tools on network panel
1. reload the page

Expected....it all would work.

Actual...many (I count 14) requests to the following URL get stuck in 'pending', eventually timing out:

```
http://localhost:8000/__es-dev-server__/message-channel
```

NB. works fine with other servers, eg ```python -m SimpleHTTPServer 8000```

```
01:58:49 ~/es-dev-server-test$ npm list -g es-dev-server
/home/davidmaxwaterman/.nvm/versions/node/v12.14.1/lib
└── es-dev-server@1.55.0 

01:59:09 ~/es-dev-server-test$ npm list -g polymer-cli
/home/davidmaxwaterman/.nvm/versions/node/v12.14.1/lib
└── polymer-cli@1.9.11 
```

**Comment by LarsDenBakker** [comment]
There is an `--event-stream` option you can set to false to prevent injecting the message channel now: https://github.com/open-wc/open-wc/tree/master/packages/es-dev-server#code-transformation

**Comment by davidmaxwaterman** [comment]
Confirmed working. Thanks!

**Comment by davidmaxwaterman** [comment]
I find myself wondering what is causing the problem...and what the benefit is of the 'message channel' that I am missing out on when I disable it.

**Comment by LarsDenBakker** [comment]
It's used to reload the browser in watch mode, and to log syntax errors to the bowser console.

**Comment by davidmaxwaterman** [comment]
Ah, thanks for that. No great loss then, I suppose :) I never use 'watch mode' - I suppose I might have benefited from logging syntax errors to the dev console, but not realised where they had come from...

Any reason why that wouldn't work for a Polymer 2 app?

**Comment by davidmaxwaterman** [comment]
Sorry to bring this up again, but there are two problems:

1. The 'help' doesn't give as useful information as the github readme, or indeed the other options:

```
$ es-dev-server --help
es-dev-server
...
  --compatibility string            Compatibility mode for older browsers. Can be: "auto", "always", "min", "max" 
                                    or "none". Default "auto"                                                     
  --event-stream string             Whether to inject event stream script into HTML pages.                        
  --debug                           Whether to log debug messages    
...
```

It might seem trivial, but the other options don't have strings for options that are presumably boolean, so the user is left wondering what the 'string' is. The other options that require strings actually say what the options are, but this option doesn't. IMO, it should either say ```Can be: 'false' or 'true'```, or the option should be boolean like the others and it should probably be ```--no-event-stream```.

The README you linked to is much more helpful though inaccurate (should be ```Defaults to 'true'```):

```
event-stream | boolean | Whether to inject event stream script. Defaults to true.
```

2. I get a similar confusion when I attempt to add this option to es-dev-server.config.js, like below. IE, the other boolean options are not strings, and when I follow their example, it doesn't work. In fact, I only just realised that making 'false' a string is the way to get it to work.

```
$ cat es-dev-server.config.js 
module.exports = {
  port: 8000,
  watch: false,
  nodeResolve: false,
  rootDir: './',
  appIndex: 'index.html',
  eventStream: false,
};

$ es-dev-server --debug
[es-dev-server]:  "Found a default config file at ./es-dev-server.config.js"
[es-dev-server]:  "Starting server with config: " {"appIndex":"/index.html","appIndexDir":"","babelExclude":[],"babelModernExclude":[],"babelModuleExclude":[],"customBabelInclude":[],"customBabelExclude":[],"compatibilityMode":"auto","polyfillsLoader":true,"compress":true,"responseTransformers":[],"eventStream":true,"fileExtensions":[".mjs",".js",".cjs",".jsx",".ts",".tsx"],"http2":false,"plugins":[],"logStartup":true,"nodeResolve":false,"openBrowser":false,"openPath":"/","cors":false,"port":8000,"readUserBabelConfig":false,"rootDir":"./","watch":false,"logErrorsToBrowser":true,"watchDebounce":100}
es-dev-server started on http://localhost:8000
  Serving files from 'snip'.
  Using history API fallback, redirecting route requests to '/index.html'
  Using auto compatibility mode, transforming code on older browsers based on user agent.

# EDIT es-dev-server.config.js to make it a string

$ cat es-dev-server.config.js 
module.exports = {
  port: 8000,
  watch: false,
  nodeResolve: false,
  rootDir: './',
  appIndex: 'index.html',
  eventStream: 'false',
};
$ es-dev-server --debug
[es-dev-server]:  "Found a default config file at ./es-dev-server.config.js"
[es-dev-server]:  "Starting server with config: " {"appIndex":"/index.html","appIndexDir":"","babelExclude":[],"babelModernExclude":[],"babelModuleExclude":[],"customBabelInclude":[],"customBabelExclude":[],"compatibilityMode":"auto","polyfillsLoader":true,"compress":true,"responseTransformers":[],**"eventStream":false**,"fileExtensions":[".mjs",".js",".cjs",".jsx",".ts",".tsx"],"http2":false,"plugins":[],"logStartup":true,"nodeResolve":false,"openBrowser":false,"openPath":"/","cors":false,"port":8000,"readUserBabelConfig":false,"rootDir":"./","watch":false,"logErrorsToBrowser":true,"watchDebounce":100}
es-dev-server started on http://localhost:8000
  Serving files from 'snip'.
  Using history API fallback, redirecting route requests to '/index.html'
  Using auto compatibility mode, transforming code on older browsers based on user agent.
```

It strikes me that this is something I could make a PR for. Let me know if you want me to have a go, or if you want to do it yourself, since it should be easy.
