### ISSUE TITLE
Error: Uncaught TypeError: Class constructor LitElement cannot be invoked without 'new' when using karma-esm with tsc

### ISSUE THREAD

**Issue by daanbouws1** [open-wc/open-wc#1728]
Hi, I'm sorry if this is not the place for this kind of problem, but after thinking about it for a while I couldn't think of a better place where i might get an answer.

I'm working on a lit-element based project and was pointed towards testing it with your testing umbrella project open-wc/testing. I've set up a fairly basic configuration on top of the default one that you guys provide It can be seen below:
```
const { createDefaultConfig } = require('@open-wc/testing-karma');
const deepmerge = require('deepmerge');

module.exports = config => {
  config.set(
    deepmerge(createDefaultConfig(config), {
      files: [
        { pattern: config.grep ? config.grep : './ui/static/dist/**/*.spec.js', type: 'module' },
      ],
      esm: {
        nodeResolve: true,
        customBabelConfig: {
          plugins: [
              ['css-modules-transform', { extensions: ['.css', '.scss', '.less'] }],
          ],
      },
      },
    }),
  );
  return config;
};
```
Now my project is written in typescript so i used the tsc command just like you guys suggested here: [](https://open-wc.org/testing/karma-esm.html)
the exact command i typed in to test this is : 
` tsc -p ./ --outdir ui/static/dist --module ES2020 `
and my tsconfig file looks like: 
```
{
  "exclude": [
    "./node_modules/*"
  ],
  "include": [
    "./**/*.ts",
  ],
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "checkJs": false,
    "allowJs": true,
    "rootDir": "./",
    "strict": false,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "strictFunctionTypes": false,
    "strictPropertyInitialization": false,
    "noImplicitThis": false,
    "alwaysStrict": false,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": "./",
    "paths": {
      "common/*": [
          "./ui/static/ui/common/*"
      ],
      "loginui/*": [
        "./ui/static/ui/loginui/*"
      ]
    }
  }
}
```
the compiling part seems to go just fine, but as soon as i run:
`karma start --coverage`

It gives me the error described in the title (the tests do run, they just fail because of this error). I had this same problem when running the code I'm trying to test in the browser but i fixed that by telling webpack to exclude all node_modules except lit-element. From my understanding this works because the bundle will include the compiled version of lit-element, but my compiled files generated by tsc simply refer to the package as its present in my node_modules folder.

How can i fix this?

**Comment by LarsDenBakker** [comment]
Sorry for the late response here. It looks like you are compiling to es5, this requires loading the custom elements es5 adapter because of the way typescript compiles away classes. Babel does work though. 

I don't recommend running tests with es5, since that's only needed for IE11 now. Browsers support much higher versions.
