### ISSUE TITLE
[es-dev-server] Middlewares can't set the response of static files dynamically before koa-static

### ISSUE THREAD

**Issue by tmsns** [open-wc/open-wc#1730]
In some cases it's useful that a middleware sets the response to a request instead of `koa-static` and before giving it to the next middlware. `koa-static` supports this with its option `defer`: https://github.com/koajs/static#options
Normal behavior will be kept, but additionally middlewares can override  the response.

I will send in a PR with the proposal, please check if this is acceptable for you.

**Comment by LarsDenBakker** [comment]
Won't this break cases where a middleware wants to manipulate the served file, since koa static now waits on the other middlewares first?

We have the plugin serve hook for cases where you want to serve virtual files.

**Comment by tmsns** [comment]
A middleware manipulates a served file (virtual or not) after the ´wait()´ callback, (eg. the middleware that handles the transform plugins, koacompress, ..) This proposal will allow normal Koa regular koa middlewares to respond to requests, while being able to still go through the full line of middlewares. Currently, the only way a middleware has to respond is to stop the pipeline altogether (by returning without calling´next()´), an example of this is the  ´pluginServeMiddleware´ itself, you were mentioning. But, by doing so, other middlewares are not being taken and functionality might be missing (in es-dev-server case, for custom middlewares, all of these would skipped)

**Comment by tmsns** [comment]
euhm.. appearantly, I hit the shortcut to close the issue with a shortcut.. 🙈

**Comment by LarsDenBakker** [comment]
Do you have examples of when this would be useful? The static middleware is already the last in line, so which middleware would use this? And why wouldn't you use a serve plugin instead?

**Comment by tmsns** [comment]
Sure! 😊 
If a user wants to use a regular koa middleware that creates a response before `next()`, eg:
 (I checked a few of them)
- https://github.com/koajs/koa/wiki#file-serving
  - https://github.com/Secbone/koa-static2/blob/master/index.js#L28
- https://github.com/koajs/koa/wiki#templating
  - https://github.com/queckezz/koa-views/blob/master/src/index.js#L87
  - https://github.com/dominicbarnes/koa-handlebars/blob/v2/lib/renderer.js#L358
the koa-static, which is last in line, will override the response with a 404 (or a 200 if the path matches a static file by luck)

Currently, there are three ways out:
- create a wrapper with a serve plugin.  
  It's unfortunate to need to create extra code for this. Also, the serve plugin doesn't give access to `next()`. This means a plugin can not manipulate the ctx upstream, only downstream (as the serve middleware is a downstread middleware)
- do not call next() at all  
  This is unfortunate, as the user will not benefit of the other features of es-dev-server
- adapt the middleware to change the response upstream  
  This is only doable in some cases, if you don't need any of the features of es-dev-server more downstream. (and of course, koa-static will still have  run anyways, which is a shame for the resources)  
For my use case I was lucky enough to not need the extra features of es-dev-server downstream for now.

Doe this make it more clear? 🙈

**Comment by LarsDenBakker** [comment]
I will add this in the new generation of the dev server, which we will backport to es-dev-server with a breaking change soon as well. This way we don't break existing code on accident. 

https://github.com/modernweb-dev/web/pull/241
