### ISSUE TITLE
Cannot rename service worker from default and use injectServiceWorker

### ISSUE THREAD

**Issue by aarondrabeck** [open-wc/open-wc#1737]
If you choose to rename your service worker for example:

``` 
workbox: {
    swDest: './dist/service-worker.js',
  },
```

You can no longer use injectServiceWorker: true because the script it injects is hard coded (sw.js).  It would be nice to allow for configuration of the service worker path/name or be smart enough to parse it from the workbox config.

**Comment by thepassle** [comment]
Just whipped up a PR to fix this: https://github.com/open-wc/open-wc/pull/1738

This way the `injectServiceWorker` functionality will reuse the `swDest` option on the `workbox` property of the config, if available. If not, it'll default to `./sw.js`

**Comment by thepassle** [comment]
Fixed in https://github.com/open-wc/open-wc/pull/1738
