### ISSUE TITLE
feature(rollup-plugin-html): inject css assets to head of html

### ISSUE THREAD

**Issue by stanf0rd** [open-wc/open-wc#1745]
Thanks for such good plugin!

It would be great to have posibility to inject css files which were bundled by rollup.
It is usefull when css asset file names were hashed with `output.assetFileNames: [name].[hash][extname;` in rollup config.

This feature exists in [@rollup/plugin-html](https://www.npmjs.com/package/@rollup/plugin-html) or [rollup-plugin-generate-html-template](https://www.npmjs.com/package/rollup-plugin-generate-html-template).

I used html template feature of current plugin and unfortunately couldn't inject css assets.

**Comment by LarsDenBakker** [comment]
You can transform the HTML template and inject anything you want from the rollup bundle: https://open-wc.org/building/rollup-plugin-html.html#transform-output-html

For the plugin to do this automatically, which files would you expect to be injected? How would the plugin detect this?
