### ISSUE TITLE
How to consume a Typescript based WC create by the open-wc generator

### ISSUE THREAD

**Issue by Halt001** [open-wc/open-wc#1746]
I'm somewhat confused as to how a generated web component with Typescript enabled is supposed to be consumed.

I would expect it to be consumed as compiled to ECMAScript. But at the root of the project I only see a `index.ts`. This seems to be at odds with the `package.json` where main and module are pointing to a `index.js` at the root.

Should these be pointed at dist/index.js maybe?

**Comment by bennypowers** [comment]
That sounds odd indeed. Can you share the steps you used to reproduce this problem? I took a look through the generator code just now and was unable to find the mistake you described

**Comment by Halt001** [comment]
Steps are easy, just do `npm init @open-wc` in an empty folder.

Answer questions like this:
✔ What would you like to do today? › Scaffold a new project
✔ What would you like to scaffold? › Web Component
✔ What would you like to add? › Linting (eslint & prettier), Testing (karma)
✔ Would you like to use typescript? › Yes
✔ Would you like to scaffold examples files for? › Testing (karma)
✔ What is the tag name of your application/web component? … my-web-component
...
✔ Do you want to write this file structure to disk? › Yes
✔ Do you want to install dependencies? › Yes, with npm

And that's it.

**Comment by Halt001** [comment]
@bennypowers were you able to reproduce the problem?
