### ISSUE TITLE
No more createDefaultConfig?

### ISSUE THREAD

**Issue by mercmobily** [open-wc/open-wc#1747]
Help...
I did a hard package update, and am having trouble figuring this out.
My app did this:

````
import { createDefaultConfig } from '@open-wc/building-rollup'
import copy from 'rollup-plugin-copy'

// if you need to support IE11 use "modern-and-legacy-config" instead.
// import { createCompatibilityConfig } from '@open-wc/building-rollup';
// export default createCompatibilityConfig({ input: './index.html' });

const copyConfig = {
  targets: [
    { src: 'assets/*', dest: 'dist/assets' },
    ...
    { src: 'node_modules/codemirror/addon/fold/foldgutter.css', dest: 'dist/node_modules/codemirror/addon/fold/' }
  ]
}

const config = createDefaultConfig({ input: './index.html' })
export default { ...config, plugins: [...config.plugins, copy(copyConfig)] }
````

However, now I am getting:

   [!] TypeError: buildingRollup.createDefaultConfig is not a function

Has this been renamed/changed?

Merc.

**Comment by thepassle** [comment]
In the latest breaking change of `building-rollup` we renamed it to `createBasicConfig` https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/index.js#L6

**Comment by mercmobily** [comment]
There must be something else too.

````
[!] Error: You must supply options.input to rollup
Error: You must supply options.input to rollup
    at Graph.generateModuleGraph (/home/merc/Development/compAs/node_modules/rollup/dist/shared/rollup.js:18379:19)
````

But I *am* passing `input` -- but it's in the root of the config.
Has that changed too?

**Comment by thepassle** [comment]
the `createBasicConfig` is meant for js-to-js bundling, the `input` field needs to be given the rollup config, not the `createBasicConfig` function. Here's an example usage:

https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/demo/js/rollup.basic.config.js

**Comment by LarsDenBakker** [comment]
`createSpaConfig` is the equivalent of `createDefaultConfig`. I recommend just checking the updated docs: https://github.com/open-wc/open-wc/tree/master/packages/building-rollup

**Comment by mercmobily** [comment]
Wait I am confused...
I am trying to use createSpaConfig (since my app is a SPA) but I am not
very successful right now.
I am as far as:

````
import { createSpaConfig } from '@open-wc/building-rollup'
import copy from 'rollup-plugin-copy'
import merge from 'deepmerge'

// if you need to support IE11 use "modern-and-legacy-config" instead.
// import { createCompatibilityConfig } from '@open-wc/building-rollup';
// export default createCompatibilityConfig({ input: './index.html' });

const copyConfig = {
  targets: [
    { src: 'assets/*', dest: 'dist/assets' },
    { src: 'images/*', dest: 'dist/images' },
    { src: 'node_modules/moment/min/moment-with-locales.min.js', dest:
'dist/node_modules/moment/min/' },
    ....
    { src: 'node_modules/codemirror/addon/fold/foldgutter.css', dest:
'dist/node_modules/codemirror/addon/fold/' }
  ]
}

const spaConfig = createSpaConfig({})
export default merge(spaConfig, { input: './index.html' })
````
But

if I try:

````
export default merge(spaConfig, { input: './index.html', plugins:
copy(copyConfig) })
````

I get a strange:

````
./index.html → dist...
[!] Error: Unexpected token (Note that you need plugins to import files
that are not JavaScript)
index.html (1:0)
````

**Comment by thepassle** [comment]
Ah, I got mixed up, thats my bad, sorry. If you're building a SPA, go with `createSpaConfig` like lars said 🙂

**Comment by mercmobily** [comment]
Ah plugins is meant to be an array, it seems to be working now!
I love the fact that you are recommending `merge()`, I remember thinking
about suggesting it!

**Comment by mercmobily** [comment]
Thank you for your help!
