### ISSUE TITLE
Enable yarn build:watch

### ISSUE THREAD

**Issue by aress31** [open-wc/open-wc#1748]
Hi @openwc team,

Right now it is possible to do (build/bundle)-less development using the following `npm script`:
`"start": "concurrently --kill-others --names tsc,es-dev-server \"yarn tsc:watch\" \"es-dev-server --app-index index.html --node-resolve --open --watch\"",`

What I suggest is that for completeness and convenience sake adding the `bundle` alternative for the people who would require rebuilding and reloading the browser during their development process with TypeScript.

That could be something like `"start:build:watch": "foo",`.

Having this script included out of the box would help many people - me included 😅.

Kind regards,
Alex

**Comment by LarsDenBakker** [comment]
We recommend no-bundle development, this is what the project scaffolding sets up. We already have a lot of command as it is, I don't think it's a good idea to add more just to cover every possible use case.
