### ISSUE TITLE
[Testing] lit-html missing

### ISSUE THREAD

**Issue by vogloblinsky** [open-wc/open-wc#175]
Just followed this tutorial in an empty folder : https://open-wc.org/testing/

Got this error :

`
ERROR in ./node_modules/@open-wc/testing-helpers/fixture-no-side-effect.js
Module not found: Error: Can't resolve 'lit-html' in '/xxx/node_modules/@open-wc/testing-helpers'
 @ ./node_modules/@open-wc/testing-helpers/fixture-no-side-effect.js 1:0-42 16:26-40 33:26-40
 @ ./node_modules/@open-wc/testing-helpers/fixture.js
 @ ./node_modules/@open-wc/testing-helpers/index.js
 @ ./node_modules/@open-wc/testing/index.js
 @ ./test/test-open-wc-stencil.test.js
`

Run `npm i --save-dev lit-html` solve the error.

**Comment by leegee** [comment]
Once that is fixed, the dist seems to miss `../open-wc` component referenced in `test/`

**Comment by daKmoR** [comment]
yes that is true `lit-html` is a peer dependency... e.g. we assume you already have it and we don't want to force you to use a specific version as any will done.

However, I fully understand that this can be confusing... how do you think we should document this? make a note right after the install instructions?
@thepassle what's your thought on this?

**Comment by thepassle** [comment]
We could add it in the docs as a 'notification/warning' box:

<img width="757" alt="screen shot 2019-02-02 at 15 41 47" src="https://user-images.githubusercontent.com/17054057/52166140-3dfdbb00-2701-11e9-88b5-bf89100e9388.png">

```
::: warning
This is a warning
:::
```

@vogloblinsky Would you be willing to write down the steps you had to take and/or create a PR?

**Comment by vogloblinsky** [comment]
@daKmoR @thepassle i will submit a PR for that on this page https://open-wc.org/testing/testing-helpers.html, ok for that ?
