### ISSUE TITLE
[doc] typo error  in content :)

### ISSUE THREAD

**Issue by onkar75** [open-wc/open-wc#1750]
on opening the https://open-wc.org/scoped-elements/,

the page contains a WARNING block , which is having a typo.

Please find attached screenshot for the same - 

![image](https://user-images.githubusercontent.com/22467891/86639321-01f71580-bfd9-11ea-9b82-4fbb71724da1.png)

**Comment by bennypowers** [comment]
Thanks for the report @onkar75, are you interested in issuing a PR to fix it yourself?
