### ISSUE TITLE
ES-Dev-Server: File request returns 404 if requested file has no extension

### ISSUE THREAD

**Issue by bengfarrell** [open-wc/open-wc#1757]
The title is hopefully pretty self explanatory. I just got finished in an afternoon of hair pulling why some library code I had was erroring out. Turns out that their error wasn't so helpful, and a file it needed wasn't being served by es-dev-server.

My usecase was with a TensorFlow derived project called FaceAPI. Seems fairly standard that the binary model files don't have extensions. Luckily I could edit some JSON and give it a false extension and things are working now.

Even if this bug isn't fixed, I couldn't find docs that warned of this behavior, could be nice to document. But really, it would be nicer if there wasn't gotchas like this in the static file serving aspect
Thanks!

**Comment by LarsDenBakker** [comment]
I assume the file you are requesting exists on disk without file extension too? Or you expecting some file extension resolve logic?

Are you using the `--app-index` flag? In that cause that's likely the cause https://github.com/open-wc/open-wc/blob/master/packages/es-dev-server/src/middleware/history-api-fallback.ts#L17 and you're right this should be supported use case.

**Comment by bengfarrell** [comment]
I'm not familiar with the app-index flag, so I assume I'm not using it. Really, I'm just using es-dev-server for bare-module importing and static file serving. And that's to further say that the file does indeed on disk without the file extension, so def not expecting resolve logic. 

I'm starting it with:
`npx es-dev-server --watch --node-resolve --open=myurl`

And my config looks like this:
`module.exports = {
    port: 8080,
    watch: true,
    nodeResolve: true,
    appIndex: 'index.html',
    http2: true,
    moduleDirs: ['node_modules', 'custom-modules'],
};
`

**Comment by LarsDenBakker** [comment]
Yeah you're using `appIndex` from the config, this is necessary when you do front-end routing. It returns the index.html on any URL if you refresh the page. 

In order to know whether you requested a file or are doing a navigation, we check if the request has a file extension. Using files without extensions and doing front-end routing is definitely a bit of an in-between scenario.

**Comment by bengfarrell** [comment]
Gotcha, that makes sense. Looks like you're already on top of it with the open issue on dev-server-core. I probably wouldn't even have reported since I can easily workaround. Just wanted to report if it helps, cause I dig the project! Thanks, and feel free to close the issue if you're tracking elsewhere or can't/won't resolve.

**Comment by LarsDenBakker** [comment]
I'll track this in the other issue indeed. Thanks for reporting it :)
