### ISSUE TITLE
Generate scaffolding with storybook demo and typescript, no stories found by default

### ISSUE THREAD

**Issue by Holyphoenix** [open-wc/open-wc#1759]
I generated the scaffolding for a web component application, and told it to include storybook for demo purposes (including adding the default story).  I also told it to use typescript.  With these options, upon building or running storybook it does not find the default storybook.  

It works if I update main.js to look for stories in 
'../out-tsc/**/stories/*.stories.{js,md,mdx}'
instead of
'../\*\*/stories/*.stories.{js,md,mdx}'

**Comment by thepassle** [comment]
This seems to be working for me, the only thing is that you need to run `tsc` once before starting storybook. Maybe we should change the `storybook` script to `"storybook": "tsc && concurrently --kill-others --names tsc,storybook \"npm run tsc:watch\" \"start-storybook --node-resolve --watch --open\"",`

**Comment by Holyphoenix** [comment]
Oh, duh moment for me.  That does work, thanks!
