### ISSUE TITLE
Generated project scripts fail to open browsers and die

### ISSUE THREAD

**Issue by oliversalzburg** [open-wc/open-wc#1763]
I'm new to the entire WC subject and tried to use your project generator, which resulted in several issues:

1. The `npm run start` command fails, because the es-dev-server (or whatever down the line) doesn't find a browser and this situation is unhandled. Results in a broken command line and hard exit of the process.
  This can be resolved by removing `--open` from the script, but graceful handling would probably be better.
2. The storybook can't be used. The script to compile it also tries to open a browser, also fails the same way. Removing the `--open` argument has no effect here, probably not a recognized option.

**Comment by oliversalzburg** [comment]
As noted in the refrenced ticket, this is due to the fact that `cmd.exe` is not available on the `PATH`. The appending of the Windows `PATH` to the WSL `PATH` can be disabled in the WSL settings, which is what I did.

**Comment by tony** [comment]
@oliversalzburg

>  The appending of the Windows `PATH` to the WSL `PATH` can be disabled in the WSL settings, which is what I did.

Can you explain what that'd look like so we're clear what steps it'd take?

**Comment by oliversalzburg** [comment]
```
[Interop]
appendWindowsPath = false
```
In `/etc/wsl.conf`

See https://docs.microsoft.com/en-us/windows/wsl/wsl-config#interop
