### ISSUE TITLE
createServer doesn't apply all my config

### ISSUE THREAD

**Issue by aaroncadillac** [open-wc/open-wc#1768]
Starting by port, that i had to specify manualy when i call to `listen` method, other configs like `open`, `appIndex` and others doesn't apply... why?

This is my config

```js
const configServer = {
	open: true,
	appIndex: 'demo/index.html',
	watch: true,
	nodeResolve: true,
	plugins: [], //Assigned later
	fileExtensions: ['.scss', '.less', '.styl'],
	moduleDirs: ['node_modules', 'vendor'],
}
```

So when I use `createServer (config)` my server doesn't work the way I want, with `startServer` it works!

**Comment by LarsDenBakker** [comment]
What are you expecting `createServer` to do with the port? It doesn't start the server, so it can't set up a listen with the port. That's what `startServer` is for. Opening the browser is also something which just `startServer` does. If that's what you need, I recommend using that instead.

**Comment by aaroncadillac** [comment]
My opinion is: `createServer` and `startServer` should only be different because the first function only creates and configures the server and the second one also starts it, but the full configuration must be applied and the server will be ready to listen, waiting for the manual request

**Comment by LarsDenBakker** [comment]
We can't apply the port configuration if the server did not start yet, that's the point of the separate functions. We can't change how node's HTTP server works unfortunately.
