### ISSUE TITLE
`fixture` with Polymer 3?

### ISSUE THREAD

**Issue by leegee** [open-wc/open-wc#178]
I've just started with the `fixture`, and am trying with Polymer 3.0 — is that within scope of the project?

I'm seeing the fixture shadowDom as the below, missing quite a few nodes — does this mean the `dom-f`/`dom-repeat` modules are not coming into play in the test, though they are imported by the component under test, and work well in Chrome?

```
<dom-repeat as="page" style="display: none;"><template is="dom-repeat"></template></dom-repeat>```

**Comment by daKmoR** [comment]
so you maybe have a repo to reproduce this?

**Comment by LarsDenBakker** [comment]
It should work. It is possibly a timing thing, try setting a timeout to rule this out.

A reproduction would help.

**Comment by leegee** [comment]
@LarsDenBakker  — awaiting on `aTimeout` before calling `fixture` did fix it! 

I really appreciate what you folk are doing in the repo, many thanks. I'd love to see WC workflow as usable as React/Jest/Enzyme, Java/Maven/Eclipse, or even Perl!

**Comment by daKmoR** [comment]
From the top of my head, I don't really see why it should be a problem so that would need some deeper analysis.
It may be that for conditional template elements you will need to do some special thing... So if you could create a simple repository with a failing test and share it with us we could check it out.

**Comment by leegee** [comment]
After some drastic refactoring, I don't have the issue, so hoping it was just me on Friday. Thanks for your help.
