### ISSUE TITLE
Configuring workbox to exclude a path from cache

### ISSUE THREAD

**Issue by lpellegr** [open-wc/open-wc#1780]
I really love what you do with open-wc. Usually, the documentation contains all I need but Today I am fighting with Workbox.

My app is deployed on Firebase with a custom domain. A specific folder/path, let's say `data/**/*` is mapped to a serverless function. 

What I would like to achieve is to have Workbox to not cache all paths under `data`. Looking at the workbox documentation it seems the network only workbox strategy is a perfect fit:

```
import {registerRoute} from 'workbox-routing';
import {NetworkOnly} from 'workbox-strategies';

registerRoute(
  ({url}) => url.pathname.startsWith('/data/'),
  new NetworkOnly()
);
```

Unfortunately, I can't find how to extend the default service worker that is generated when using `injectServiceWorker: true` with open-wc. Is this possible? maybe there is already an option to pass glob patterns to exclude?

**Comment by thepassle** [comment]
You can override our default workbox configuration like so:

```js
const baseConfig = createSpaConfig({
  injectServiceWorker: true,
  workbox: {
     globIgnores: ['data/**.*'],
  },
});
```

Its probably a bit much to switch to `injectManifest` to achieve what you want, you should be able to just add the `data` glob to the `globIgnores` of the workbox config

You're right that it could be more clear from the docs how to extend the workbox config, ill improve that soon 🙂

**Comment by lpellegr** [comment]
Thanks a lot for your help. Unfortunately, it seems not to work.

When I open the URL:
https://my.custom.domain.com/data//MvWDKYKaLUyb5Nvsp6C9/dummy

The SPA app is loaded by default. If I do a force refresh, the page SPA is bypassed and the serverless function is invoked. However, if I close the browser and reopen the same URL the SPA loads again in first. This behavior is the same whether I applied the configuration you showed me or not.

This let me think the configuration is not taken into account. When I look at the generated files:

- workbox-HASH.js
- sw.js

none is containing a reference to `data/`.

Is `globIgnores` supposed to disable SW caching by path even for non-existing files?

**Comment by thepassle** [comment]
> none is containing a reference to data/.

I'm not expecting there to be a reference of `data/`, workbox should ignore putting anything from `data/` in your precache manifest
