### ISSUE TITLE
[es-dev-server] Partial Range Requests

### ISSUE THREAD

**Issue by bengfarrell** [open-wc/open-wc#1787]
Hi, I'm guessing that my issue is the lack of support of partial range HTTP requests, but I definitely stand to be corrected.

My use case is that I have a web component which serves as a video timeline scrubber. Setting the time on my video does not work, despite me using the proper HTML5 video API to do so. I'm using es-dev-server to serve my app during development and all assets (including the sample video) are served using it.

When I switch to a simple HTTP server provided by Node for serving the video assets only, scrubbing works just fine. So, this is why I'm assuming that partial range HTTP requests do not work, because this, in my understanding, is core to how scrubbing a media asset works.

Can this be supported through config options maybe? If not would it be easy to support with a PR? Just looking at my options. Obviously I can include dual HTTP servers in my dev pipeline, but I'd rather not

thanks!

**Comment by LarsDenBakker** [comment]
I don't have any experience working with range requests, but we should be able to support this with es-dev-server. Do you know if this works with a plain Koa server? I don't see what we could be doing that causes this to not work.

**Comment by bengfarrell** [comment]
I'm actually not familiar with Koa. So I just tried installing it for the first time and serving some static files. And no, the same use-case does not work here either.

However, I also installed the module `koa-range`, and then doing the just adding a line telling my app to "use" the import and suddenly my video was scrubbing just great.

`const Koa = require('koa');
const serve = require('koa-static');
const path = require('path');
var range = require('koa-range');

const staticDirPath = path.join(__dirname, 'public');

const server = new Koa();
server.use(range);
server.use(serve(staticDirPath));
const PORT = process.env.PORT || 3000;
server.listen(PORT, () => console.log(`Server Listening on PORT ${PORT} ..`));
`
Is this something you'd have to support directly, or is there some kind of plugin support this can be tacked on with?
thanks!

**Comment by LarsDenBakker** [comment]
Definitely, that's what the `middleware` option in the config is for. We've had other requests for this, good to know this is the solution. I will keep this issue open, maybe we'll add this middleware by default or we'll improve the docs.

**Comment by bengfarrell** [comment]
Thanks for the recommendation! I'm this can easily be done, as I was running into cross origin issues with my video if on a diff server.

I didn't feel it was crystal clear on how to use middleware, and ended up reading the source code. Likely because I wasn't familiar with Koa. I was confused on what function to pass in, and how to get a ref to the app or server variable, so I could do `app.use(range)`. I didn't realize all the middleware is "used" by default. 

Here's my config if it helps anyone with the same problem:

```
const range = require('koa-range');

module.exports = {
    port: 8080,
    watch: true,
    nodeResolve: true,
    http2: true,
    moduleDirs: ['node_modules'],
    middlewares: [ range ]
};
```

Thanks again!
