### ISSUE TITLE
npm init @open-wc not working

### ISSUE THREAD

**Issue by juliaheller** [open-wc/open-wc#1793]
Hey,
I cannot initialise open-wc. 
I get e.g. these errors:
"Install for [ '@open-wc/create@latest' ] failed with code 1"
"silly fetchPackageMetaData error for @open-wc/create@latest 404 Not Found - GET https://registry.npmjs.org/@open-wc%2fcreate - Not found"

**Comment by thepassle** [comment]
It seems like npm is having problems today, this is likely related to that

**Comment by Westbrook** [comment]
@juliaheller are you continuing to see this issue? I've checked and not run into the 404 just now, which leads me to agree with @thepassle on this. 

If you are still seeing this issue, please reach out with any other info you can share about your set up. However, closing for now.
