### ISSUE TITLE
Not properly loading es6 converted module

### ISSUE THREAD

**Issue by davidbwaters** [open-wc/open-wc#1798]
Hi.  I'm trying to use [@johh/three-effectcomposer](https://www.npmjs.com/package/@johh/three-effectcomposer) in my project which is has a module converted to an es6 module but it fails to import correctly giving the error 'does not provide an export named ..' for both named and default exports.

**Comment by LarsDenBakker** [comment]
Can you provide some more context here? What is not properly loading this module? 

Looking at the output it is a commonjs module: https://unpkg.com/browse/@johh/three-effectcomposer@0.0.7/dist/index.js so in node js you can include it using require. The browser can't load commonjs modules, so you will need to set up some tooling or ask the library author to ship web compatible code.

**Comment by davidbwaters** [comment]
Thanks for the quick reply. I was confused about what the bottom line 'esModule' means.  The description says 'three.js's r105 EffectComposer ported to ES6 for easy importing.' from https://github.com/johh/three-effectcomposer. I saw it was used here with 'import' syntax [here](https://github.com/akella/webgl-mouseover-effects/blob/master/js/scene.js) in the demo code from a Codrops article.  That demo runs in the browser.  Assuming it's compatible, what's the best way to include this with the OWC boilerplate?

**Comment by davidbwaters** [comment]
I searched and found that the code 'interop-require-default' was added by Babel so modules can be consumed as ES modules also.  I'm just not sure why it doesn't work.  https://stackoverflow.com/questions/51159447/what-is-interoprequiredefault/52008959

**Comment by LarsDenBakker** [comment]
It's ironic that the library advertises to use es6 modules, but doesn't actually ship them. The demo of that project builds and bundles the code before serving it to the browser, that's why it works. You will need to do the same unfortunately. 

Our setup is mostly based around buildless development, we have some presets for using typescript but not for converting commonjs to es modules since it's not a straightforward task. It works when bundling es modules away completely, which is what webpack, parcel or rollup can do.

**Comment by davidbwaters** [comment]
Well OK haha that's a confusing issue.  Thanks.  So I guess there's no straightforward way to add this as a Rollup step with a Babel transform, I guess?

**Comment by LarsDenBakker** [comment]
Modules are in a funky state right now, but it's getting better. 

For rollup you can use https://github.com/rollup/plugins/tree/master/packages/commonjs, but it does require running rollup during development before serving to the browser.

**Comment by davidbwaters** [comment]
Thanks.  It looks like the actual source from Github is written as an ES module, but not the NPM version, since the src folder is in .npmignore.  NPM can download the from GH, but it's unreliable.  I'll raise an issue with the maintainer and just keep the untranspiled code in a folder to import it.
