### ISSUE TITLE
usage of startsWith in transform.js for version 1.2.x

### ISSUE THREAD

**Issue by Jeevankumar555** [open-wc/open-wc#1809]
Hi, We are using this dependency in our web components in order to use the ScopedElementsMixin and observed that it has this code using **startsWith** in transform.js and our web component broke to render in IE11 due to the latest dependency (1.2.0) that pulled in the usage of this function.
Hence we fallback to 1.1.x

https://github.com/open-wc/open-wc/blob/4d8143cb62afe151e9affa209529131419a077b9/packages/scoped-elements/src/transform.js#L65.

Can this be fixed to use indexOf to support IE11 or is it the responsibility of the consumers to add any transpilation configs / polyfills ?

**Comment by manolakis** [comment]
Hello @Jeevankumar555,

It's a small change and I think it can be fixed to make it work on IE11 out of the box 🤗  

However, as you said, it's an App responsibility to load the required polyfills and transpile the code to make it work on older browsers.
