### ISSUE TITLE
[es-dev-server] crashes fatally upon missing opening `{` syntax error when using node resolve flag

### ISSUE THREAD

**Issue by jorenbroekema** [open-wc/open-wc#1811]
EDS crashes fatally on specific syntax error where you miss opening '{' bracket and have brackets later in the code. When using node-resolve flag, the server crashes on it and keeps crashing even after you've already fixed the syntax error:

```
Syntax error: Could not resolve module imports in <path>/index.js: Unable to parse the module, this can be due to experimental syntax or a bug in the parser.
```

## Reproduce

- Create index.js (loaded in index.html)
  ```js
  const foo = {};
  const bar = {};
  ```
- Run es-dev-server --node-resolve (without node resolve it works, so it's probably related in some way)
- Go to browser, all good.
- Change the code to remove the opening bracket of the FIRST const. The second const is important, you need something after that also uses brackets, in order to reproduce this.
  ```js
  const foo = };
  const bar = {};
  ```
- Fix the syntax error and refresh browser
- Syntax error: Could not resolve module imports in <path>/index.js: Unable to parse the module, this can be due to experimental syntax or a bug in the parser.

## Expected outcome

Should be able to recover from syntax error, but instead the server is entirely broken until it is restarted. This is quite bad for my use case where I give workshops on a shared EDS instance, and people make such syntax errors often.

**Comment by jorenbroekema** [comment]
Maybe this is related to cache? Do you cache import resolutions on the server? Because that could explain why it cannot recover from the error maybe 🤔

**Comment by LarsDenBakker** [comment]
Filed upstream https://github.com/guybedford/es-module-lexer/issues/52

**Comment by jorenbroekema** [comment]
Was EDS released lately with latest es-module-lexer? Otherwise I can create PR

**Comment by LarsDenBakker** [comment]
Yeah we're on the latest - and we will defer to web dev server soon :)
