### ISSUE TITLE
[es-dev-server] Event Stream related server logs while eventStream is false

### ISSUE THREAD

**Issue by jorenbroekema** [open-wc/open-wc#1812]
Somehow I'm still getting Event Stream related errors in my server logs even though I've set eventStream to false.

Could this be because the message channel is still created on the server side trying to send? I suspect eventStream false only prevents the browser script insertion, but I would actually like to squeeze more performance out of EDS by explicitly disabling event stream entirely.

**Comment by jorenbroekema** [comment]
Hmm I do believe that if `eventStream` is set to false, it should be turned off on both server side and as inserted client side script. What do you think @LarsDenBakker  ?

**Comment by LarsDenBakker** [comment]
What kind of logs are you seeing? We should tackle this in web dev server.

**Comment by jorenbroekema** [comment]
```
Error: premature close
      at onclosenexttick (/home/joren/code/starter-basic/node_modules/end-of-stream/index.js:53:86)
      at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Is one example I think?

**Comment by LarsDenBakker** [comment]
those logs are not related to the event stream

**Comment by jorenbroekema** [comment]
oh.. Do you know where else I could look in EDS for readable stream being prematurely closed? This error usually happens when you load up the browser and then close it before EDS is done serving the files to the client. Not sure to what EDS feature this is related or if it's koa related?

**Comment by LarsDenBakker** [comment]
I'm not really sure.. I've tried to debug it in the past but couldn't figure it out yet.
