### ISSUE TITLE
Errors occurring when testing a component in a mono-repo

### ISSUE THREAD

**Issue by corocoto** [open-wc/open-wc#1820]
### Description
I'm trying to run `test` script inside one of exists repos (name of the repository I'm working with is `nf-front`). 
These repos are locate inside `packages` folder. 

So when I'm trying to run `test` script, then I'm get errors like these (and the component's test execution is interrupted):

![errors](https://user-images.githubusercontent.com/37180024/91051909-6c1b5680-e629-11ea-9895-359f2cd192e4.png)

But if I'm move karma config file, test folder and scripts from `package.json` file on the top level of application, then  it'll be work fine.

### Additional
Structure of the project looks like this:

![structure of the project](https://user-images.githubusercontent.com/37180024/91052566-4f335300-e62a-11ea-8e97-1455a84c26c0.png)

#### Expected Results
Should execute tests correctly without it interrupted.

#### Actual Results
Tests execution is interrupted with errors.

**Comment by LarsDenBakker** [comment]
This is because all the files used by your tests must be within the

**Comment by corocoto** [comment]
@LarsDenBakker, thanks a lot
