### ISSUE TITLE
[karma-esm] how to use alias

### ISSUE THREAD

**Issue by quentin29200** [open-wc/open-wc#1821]
Hi, all my webcomponents use alias import such as 

`import myService from "@services/myService"`

Test failed with this message 

> Could not resolve import "@services/myService"

I tried to use this https://github.com/open-wc/open-wc/issues/1632#issuecomment-629771617 but have no effect. 

I tried to use module-solver babel plugin in babelConfig of esm (karma.conf) but have no effect too.

So I tried to set a [hook resolve import](https://open-wc.org/developing/es-dev-server.html#hook-resolveimport), I failed to make it work 

Is it possible to use alias with karma-esm ? 

Karma-esm version `2.13.28`

**Comment by LarsDenBakker** [comment]
I'm not sure what you mean by alias? An import like that should resolve to `node_modules/@services/myService`.

**Comment by quentin29200** [comment]
I defined alias in resolve of webpack,  shortcut of folder 

```
resolve: {
      extensions: ['.ts', '.js', '.json', '.scss', '.css'],
      ...
      alias: {
        '@services': path.resolve(__dirname, 'src/services'),
      },
    },
```

So I can import services : 

```
import "@services/myServiceA"
import "@services/myServiceB"
import "@services/myServiceC"
```

and webpack resolve the path. 

It's work fine for production or with storybook, but Karma do not use webpack. 
So I'm looking for a solution to run it with Karma-esm

**Comment by LarsDenBakker** [comment]
You will need to build your code with webpack if you rely on it. karma-esm is intended for testing code that doesn't need to be built, using regular es modules. You probably want to use https://www.npmjs.com/package/karma-webpack.

**Comment by quentin29200** [comment]
Ok, i'm trying this
thank's
