### ISSUE TITLE
Typo in es-dev-server docs

### ISSUE THREAD

**Issue by nicolasr75** [open-wc/open-wc#1823]
A typo in 

https://github.com/open-wc/open-wc/tree/master/packages/es-dev-server

in chapter "index.html in a folder":

"So if your app uses any node modules, they will no longer because accessible."

should probably be 

"So if your app uses any node modules, they will no longer be accessible."

**Comment by LarsDenBakker** [comment]
Thanks for reporting. We're doing a big update to the docs soon, this will be picked up in that pass.
