### ISSUE TITLE
[karma-esm] Exclude 3rd party source code from coverage

### ISSUE THREAD

**Issue by abdullahkamran** [open-wc/open-wc#1824]
## Description
I'm using a library from a 3rd party vendor in my app. I want its source code to be excluded from test coverage. The directory structure is as follows:
    
    packages 
        -> my-component
            -> vendor
                ->thirdpartylib.js
            -> src
                ->myFile.js
            -> test
                ->myFile.test.js
    karma.conf.js

In myFile.js I have imported thirdpartylib.js like this: `import '../vendor/thirdpartylib.js';` and it's showing in the test coverage. I want to exclude it.

## I have tried:

I'm running the tests using command `karma start --coverage`. Here is my karma.conf.js file:

    const { createDefaultConfig } = require('@open-wc/testing-karma');
    const merge = require('deepmerge');

    module.exports = config => {
      config.set(
        merge(createDefaultConfig(config), {
          files: [
            {
              pattern: config.grep ? config.grep : 'packages/**/*.test.js',
              type: 'module',
            },
          ],

          esm: {
            nodeResolve: true,
            coverageExclude: ['**/vendor/**'],
          },
        })
      );
      return config;
    };

Also tried with full path:

      esm: {
        nodeResolve: true,
        coverageExclude: ['packages/my-component/vendor/thirdpartylib.js'],
      },

and:

      files: [
        {
          pattern: config.grep ? config.grep : 'packages/**/*.test.js',
          type: 'module',
        },
        {
          pattern: 'packages/my-component/vendor/thirdpartylib.js',
          include: false,
        },
      ],

But these do not work.
Renaming the vendor folder to 'node_modules' excludes it from the coverage but I do not want to do that.

## Expected
Coverage should exclude the 3rd party source folder.

## Actual
Code in vendor directory is included in coverage which drops the coverage percentage.

**Comment by LarsDenBakker** [comment]
I'm not sure what to suggest here, we are using the exclude here and it's working: https://github.com/open-wc/open-wc/blob/master/karma.conf.js#L29

We pass it to `babel-plugin-istanbul` here: https://github.com/open-wc/open-wc/blob/master/packages/karma-esm/src/esm-config.js#L54

We are soon switching to our new test runner, you could look into that if Karma is giving issues. https://modern-web.dev/docs/test-runner/overview/
