### ISSUE TITLE
Unused @ts-expect-error directive in @open-wc/testing-helpers

### ISSUE THREAD

**Issue by buzzub** [open-wc/open-wc#1826]
A change introduced in @open-wc/testing-helpers 1.8.9 (https://github.com/open-wc/open-wc/commit/88ffd995efeb94d79ee686f665d18e8ca405e3bc) is causing an error when running all our tests via jest. The addition of `// @ts-expect-error` produces this error:

```
Test suite failed to run

node_modules/@open-wc/testing-helpers/src/scopedElementsWrapper.js:32:1 - error TS2578: Unused '@ts-expect-error' directive.

32 // @ts-expect-error
 ~~~~~~~~~~~~~~~~~~~
```

The only way we can get around this error is by limiting the version of @open-wc/testing-helpers to 1.8.8

What is the purpose of the @ts-expect error ? Could @ts-ignore be used here instead?

Struggling to understand how to prevent this error as there seems to be no way to bypass it

**Comment by daKmoR** [comment]
@buzzub would a `// @ts-ignore` work?

@bennypowers why did we go for expect error again? 🤔

**Comment by buzzub** [comment]
@ts-ignore would work fine. @ts-expect-error doesn’t get an error / isn’t used and that causes the problem.

**Comment by bennypowers** [comment]
`@ts-expect-error` is preferable to `@ts-ignore` in most cases, as `@ts-ignore` will simply suppress all errors, whereas `@ts-expect-error` tells the compiler that there should be an error on that line, for example, when unit testing bad input to a function that throws on bad input.

If the compiler finds a `@ts-expect-error` but _doesn't_ find an error afterwards, that itself becomes an error.

So it looks like according to @buzzub that in fact the original code now works properly. Perhaps @buzzub has some tsconfig which allows for the usage on https://github.com/open-wc/open-wc/commit/88ffd995efeb94d79ee686f665d18e8ca405e3bc or is using TS 4?

@buzzub  when you remove the `@ts-expect-error` comment altogether (and don't replace it with a `@ts-ignore`), do your tests compile?

**Comment by buzzub** [comment]
> @buzzub when you remove the @ts-expect-error comment altogether (and don't replace it with a @ts-ignore), do your tests compile?

Yes, just removed `@ts-expect-error` line and the tests run just fine. I also switched it to `@ts-ignore` and the tests still compile fine.

We are using Typescritpt 4.0.2

FYI compiler options from tsconfig below, but I can't find any relevant config that would prevent this error:
```
"compilerOptions": {
    "target": "ES2018",
    "module": "commonjs",
    "moduleResolution": "node",
    "lib": ["ES2018", "dom"],
    "strict": false,
    "experimentalDecorators": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "emitDecoratorMetadata": true,
    "noImplicitAny": false,
    "noImplicitUseStrict": false,
    "noImplicitReturns": true,
    "noEmitOnError": false,
    "noFallthroughCasesInSwitch": true,
    "suppressImplicitAnyIndexErrors": true,
    "outDir": "lib",
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "typeRoots": [
      "node_modules/@types",
      "./types.d.ts"
    ]
  }
```

**Comment by bennypowers** [comment]
without having looked deeply into it, my impression is that TypeScript 4 fixed whatever the type error was the @jorenbroekema  originally had.

@jorenbroekema  can you confirm?

@daKmoR Do we want to require ts 4 for this package?

**Comment by jorenbroekema** [comment]
Hmm that's pretty odd, I looked into https://github.com/microsoft/TypeScript/issues/40110 again and Ryan marked it as a bug and to fix for 4.1.0, and if I check the typescript playground, it seems like it's still broken vor 4.0.2.

Did we look into just upgrading all of open-wc to use TS 4 yet? If nothing breaks, I guess we could just go with it and remove the ts-expect-error, but I'm not sure how the error is gone on TS 4.0.2 when on the playground bug repro it's still there.

**Comment by bennypowers** [comment]
maybe OP is using VS Code, which bundles TS 4.1.0?

**Comment by fernandopasik** [comment]
Would it be ok if I try a PR updating to typescript 4? Still sounds from what was said that this issue would be resolved in 4.1

**Comment by jorenbroekema** [comment]
Yeah I think we would like to upgrade if possible, let's see if we can overcome the breaking changes :)

**Comment by bennypowers** [comment]
@fernandopasik  hit us up in polymer slack's #typescript channel if you need any help

**Comment by fernandopasik** [comment]
Hi! I've created a branch with the update, so far I found one type error, looks minor.

https://github.com/open-wc/open-wc/pull/1855

**Comment by fernandopasik** [comment]
The upgrade to typescript 4 was merged. Would it be possible to release @open-wc/testing-helpers?

**Comment by buzzub** [comment]
> Raised a PR to fix it, so people can at least move to latest version of testing-helpers and not be blocked by this.

This will great as we have been stuck on 1.8.8 since this issue came up.
