### ISSUE TITLE
Outdated terser does not support optional chaining

### ISSUE THREAD

**Issue by felixapitzsch** [open-wc/open-wc#1830]
open-wc uses outdated versions of `terser` and `rollup-plugin-terser` as dependencies which will break on code with optional chaining (ES2020). Please update to dependency versions using at least terser ^5.2.0 in order to allow for optional chaining code with open-wc.

**Comment by felixapitzsch** [comment]
This will also fix https://github.com/open-wc/open-wc/pull/1805#issue-467202783 .

**Comment by LarsDenBakker** [comment]
I updated the rollup plugin inhttps://github.com/open-wc/open-wc/pull/1831, updating terser itself will be done later but I think this will fix the issue for most user code.
