### ISSUE TITLE
[es-dev-server]: API fallback middleware does not handle url encoded parameters

### ISSUE THREAD

**Issue by jarrodek** [open-wc/open-wc#1835]
I have a parameter in the path part of the URL that is an URL encoded URI. The encoded value has a dot in it (in `.dom`) that is interpreted as an extension. This causes the dev server to request for the next middleware while this should be handled by the fallback API.

Example full URL:
```
http://localhost:8000/demo/project/http%3A%2F%2Fmulesoft.com%2Fmodeling%2Finstances%2Fd8ca6956-1a8d-40bc-af74-55bd4bd84f24
```

**Comment by LarsDenBakker** [comment]
I'm not sure what we can do here. The idea of history API fallback, or SPA routing, is to return the index.html file on route requests and technically speaking this is a file request. Checking for the file extension is an important part of the consistency, there aren't many other checks we can do.

**Comment by jarrodek** [comment]
I've made this configuration that helps me with that. Maybe you can use it in the dev sever:

```javascript
const fs = require('fs');
const path = require('path');

module.exports = {
  watch: true,
  nodeResolve: true,
  appIndex: 'demo/index.html',
  plugins: [],
  moduleDirs: ['node_modules'],
  middlewares: [
    function rewriteIndex(ctx, next) {
      // whether it starts with "cfg.appIndex"
      if (!ctx.url.startsWith('/demo/')) {
        return next();
      }
      // test if file exists
      const test = path.join('./', ctx.url);
      const exists = fs.existsSync(test);
      if (exists) {
        return next();
      }
      // use the fallback
      ctx.url = '/demo/index.html';
      return next();
    }
  ]
};
```

**Comment by LarsDenBakker** [comment]
This will cause HTML to be served when a file doesn't exist, hiding the actual 404.

**Comment by jarrodek** [comment]
Isn't that the goal of having fallback for the history API?

**Comment by LarsDenBakker** [comment]
I think you want this behavior for route requests like `/demo/foo` and `/demo/bar` but not for others. But maybe that's just my assumption. We could check how other tools are handling this and align the logic.

**Comment by jarrodek** [comment]
When using browser's history API (for example `window.history.pushState({}, null, '/project/something')`) the path is being rewritten (I have logic inside the app that handles the `/demo/` case). This means that any URL that is not requesting an actual file has to go to the main file for the routing to ever work. Here I don't rely on server handling 404 as I have a 404 page inside the application that is rendered when a route doesn't match. 
Take a look into [lit-element-router](https://www.npmjs.com/package/lit-element-router) module that uses a similar pattern to handle 404s on the client side.
