### ISSUE TITLE
[Testing] Sauce Labs support 

### ISSUE THREAD

**Issue by vogloblinsky** [open-wc/open-wc#184]
It it possible to add support in @open-wc/testing for saucelabs ? via https://github.com/karma-runner/karma-sauce-launcher

**Comment by daKmoR** [comment]
We would like to wherever possible only recommend one solution. That is for the time being browserstack.
We are however totally open on adding a tutorial on howto create a config that works with saucelabs. (if provided via PR)

PS: also our recommendation may adapt to whatever service provides the most "value" - if you want to start that discussion feel free to list pros/cons on browserstack vs saucelabs.
