### ISSUE TITLE
Has anyone tried to make a web-component with third party request using fetch and tried to test it ?

### ISSUE THREAD

**Issue by BnitoBzh** [open-wc/open-wc#1853]
I tried to mock fetch, but after many attempts with fetch-mock, fetch-mock-fixtures and others i am not able to do any test...
does anyone have a reliable example of how to do this?

My projet is a fresh web-component built with `npm init @open-wc`.

My use case is simple. A web component that makes an HTTP request using fetch to a specific URL with a value passed to it and shows the result.

**Comment by bennypowers** [comment]
you can stub fetch with sinon

https://gist.github.com/coder36/a5c6f37623a066e50bbe52dd258b77f0

**Comment by BnitoBzh** [comment]
Like always, i get an error ..
Here is the error with your code snippet : `The requested module '../../node_modules/sinon-stub-promise/index.js' does not provide an export named 'default'`

**Comment by bennypowers** [comment]
that gist is 4 years old. the principle is solid but the specifics are a little out of date.

you don't need sinon-stub-promise.

```js
import sinon from 'sinon';

function mockApiResponse(body = {}) {
    return new window.Response(JSON.stringify(body), {
       status: 200,
       headers: { 'Content-type': 'application/json' }
    });
}

let stubbedFetch;

beforeEach(function() {
  stubbedFetch = sinon.stub(window, 'fetch');
  stubbedFetch.returns(Promise.resolve(mockApiResponse()));
});

afterEach(function() {
  stubbedFetch.restore();
});
```
