### ISSUE TITLE
Unable to include SASS using rollup plugin

### ISSUE THREAD

**Issue by vaibhavkulkarni** [open-wc/open-wc#1854]
Hello,

I am trying to import scss file into a standard generated project. When I run `npm run start` and observe the console on the browser, I see the following error message.

> Failed to load module script: The server responded with a non-JavaScript MIME type of "text/x-scss". Strict MIME type checking is enforced for module scripts per HTML spec.

Below is my js code where I import:
`import "./test.scss";
`

Below is my rollup.config.js:
`
import merge from "deepmerge";
// use createSpaConfig for bundling a Single Page App
import { createSpaConfig } from "@open-wc/building-rollup";
import postcss from "rollup-plugin-postcss";

// use createBasicConfig to do regular JS to JS bundling
// import { createBasicConfig } from '@open-wc/building-rollup';

const baseConfig = createSpaConfig({
  // use the outputdir option to modify where files are output
  // outputDir: 'dist',

  // if you need to support older browsers, such as IE11, set the legacyBuild
  // option to generate an additional build just for this browser
  // legacyBuild: true,

  // development mode creates a non-minified build for debugging or development
  developmentMode: process.env.ROLLUP_WATCH === "true",

  // set to true to inject the service worker registration into your index.html
  injectServiceWorker: false,
});

export default merge(baseConfig, {
  // if you use createSpaConfig, you can use your index.html as entrypoint,
  // any <script type="module"> inside will be bundled by rollup
  input: "./index.html",

  // alternatively, you can use your JS as entrypoint for rollup and
  // optionally set a HTML template manually
  // input: './app.js',
  plugins: [
    postcss({
      plugins: [],
    }),
  ],
});
`
Am I doing something wrong? 

Any help would be appreciated.

Thanks,
Vaibhav

**Comment by LarsDenBakker** [comment]
If you're using the generated project, npm start doesn't run rollup. You will need to run rollup first and serve the build result.

**Comment by vaibhavkulkarni** [comment]
I agree. I asked in the slack channel and didn't close this issue. Apologies for that. 

I installed web-dev-server and the following config worked like charm:
`const postcss = require("rollup-plugin-postcss");
const rollupAdapter = require("@web/dev-server-rollup").rollupAdapter;

module.exports = {
  open: true,
  nodeResolve: true,
  watch: true,
  appIndex: "index.html",
  mimeTypes: {
    "**/*.scss": "js",
  },
  plugins: [rollupAdapter(postcss())],
};
`
