### ISSUE TITLE
Extending Event is it possible?

### ISSUE THREAD

**Issue by Christian24** [open-wc/open-wc#1870]
Hi,

I just came across this site of the docs: https://open-wc.org/faq/events.html#even-more-data

It says you can inherit from Event to create your own Event class. I tried this, I always get an error: `Constructor requires 'new' operator.`. This happens in both Safari as well as in Edge Chromium. I haven't tried in Firefox. I have not really seen this anywhere else, so my question is: Is this even possible? 

Thanks,
Christian

**Comment by daKmoR** [comment]
you mean

```
class MyEvent extends Event {}
```

does not work? 🤔 

can you maybe share a complete code snippet? 🤗

**Comment by Christian24** [comment]
Sure, I do: 
````typescript
export class MyEvent extends Event {
  public detail: string;
  constructor(detail: string, options) {
    super('MyEvent', options);
    this.detail = detail;
  }
}
````
You can also find a Stackblitz here: https://stackblitz.com/edit/extends-event?file=my-event.ts

**Comment by LarsDenBakker** [comment]
This might be due to stackblitz, they do quite a lot of building behind the scenes. This should work in the browser as is.
