### ISSUE TITLE
[eslint-plugin-lit-a11y] alt-text: allow <img role="presentation">

### ISSUE THREAD

**Issue by bennypowers** [open-wc/open-wc#1872]
The `alt-text` rule should allow images with `role="presentation"`.
The rule should also check elements with `role="img"` for alt atttibutes

> yep, would be a good addition 👍 maybe we can create a new hacktoberfest issue for it? Or we can also do it in this PR if you prefer

_Originally posted by @thepassle in https://github.com/open-wc/open-wc/pull/1871#discussion_r502952817_

**Comment by thepassle** [comment]
Guidance for any interested contributors can be found here: https://github.com/open-wc/open-wc/pull/1781

**Comment by thepassle** [comment]
fixed in #1884
