### ISSUE TITLE
Building into one single js file with createSpaConfig

### ISSUE THREAD

**Issue by mercmobily** [open-wc/open-wc#1873]
When I build my SPA, using a fairy common configuration:

    export default merge(spaConfig, { input: './index.html', plugins: [copy(copyConfig)] })

I end up with a lot of files in my output directory:

````
index.html
00811fff.js  4cddc6e4.js  76ecabd6.js  b8e3f834.js  e92ed3ad.js
0590587a.js  4e76eeea.js  77208223.js  b92d1c0e.js  eb6d8f62.js
0670e323.js  50834273.js  77d65228.js  b998b9d0.js  efb49ea4.js
0d0fc308.js  570005b0.js  79e457b8.js  bb338114.js  efe6a354.js
1374955f.js  5762d558.js  7affa294.js  bc14155c.js  f20cd71e.js
1c4c9ba8.js  58662e02.js  85801b13.js  bd27e845.js  f442b143.js
1d5bb389.js  5872e412.js  85b7b6bf.js  bd9251aa.js  f654f0ae.js
1e69db75.js  59254024.js  891405d9.js  c45b46c6.js  f7035649.js
````

Our app is used in precarious environments, where one big download tends to be more successful than several small ones.
index.html simply has one import line:

     <script type="module" src="src/my-app.js"></script>

my-app.js then has several static `import` statements:

````
import { LitElement, html, css } from 'lit-element'
import 'tpe-material/material.js'
import('./v2/co-app.js')
````

Is there any way to convince rollup to create one big fat file which includes the full javascript for the app? Or, that is what is meant to happen, and I am doing something stupid on my end?

**Comment by mercmobily** [comment]
BTW My use case is exactly the one explained in the [official documentation](https://open-wc.org/building/building-rollup.html):

**SPA Projects**
If you have a SPA (Single Page App) project you can use createSpaConfig to generate your config. This will inject the rollup output into a single index.html file, generate a service worker and load polyfills using feature detection.

**# HTML as input**
You can set an index.html file as rollup input. Any modules inside will be bundled by rollup and the final output will be injected into the final HTML file.

View example

````
import merge from 'deepmerge';
import { createBasicConfig } from '@open-wc/building-rollup';

const baseConfig = createBasicConfig();

export default merge(baseConfig, {
  input: './index.html',
});
````
Unless I am using the wrong version of Open-wc, I am not seeing this: "This will inject the rollup output into a single index.html file". But, that is exactly what I need: a single index.html file which includes _everything_.

It's very possible I am doing something very wrong -- I apologise in advance if that is the case!

**Comment by LarsDenBakker** [comment]
Bundlers do code splitting based on dynamic imports. If you use a dynamic import, the intention is to lazy load it at a later point and thus it has to become a separate file. 

You can turn off this behavior in rollup: https://rollupjs.org/guide/en/#outputinlinedynamicimports but it would be pretty bad for performance :)

**Comment by mercmobily** [comment]
Thank you for answering Lars!

Is one single dynamic import enough to trigger the behaviour?
(I didn't think I had any, but I might be wrong?)

Thank you again..

**Comment by mercmobily** [comment]
OK, it was my fault. (It tends to often be that way...). I changed the app to static imports, with the "slight" oversight of keeping the `import('...')` syntax rather than the `import '...'` syntax. Ugh. I apologise for the noise here. On a brighter note, I now totally understand why I was getting what I was getting!

My output is now:

* `index.html`
* `4e0bbf5b.js` (a big 700Kg file containing absolutely everything)
* `sw.js.map`, `sw.js.map`
* `workbox-80efdfd1.js`
* `workbox-80efdfd1.js.map`

Is there any way to get the contents of `4e0bbf5b.js` *within* `index.html`?

ALSO, is there any way to include `workbox-80efdfd1.js` in `sw.js`? (yes, I am on am mission to really minimise the number of files...)

Thank you again!

**Comment by thepassle** [comment]
Out of curiosity, why are you on a mission to minimise the number of files? As Lars mentioned, its highly likely you're hurting performance by doing this.

As for workbox, you can set `inlineWorkboxRuntime` to `true` in workbox's `generateSW` configuration

**Comment by mercmobily** [comment]
> Out of curiosity, why are you on a mission to minimise the number of files? As Lars mentioned, its highly likely you're hurting performance by doing this.

Oh this is a very sad story...
We have a SPA being served on a _very_ unreliable connection. Some files will just randomly fail to load. The connection goes up and down, within the space of 4-5 minutes.
I had a SPA with dynamic imports which only got loaded when they were actually used. But, when I noticed that sometimes those imports failed, I very meticulously wrote carefully crafted code which would attempt to preload the modules that a user would most likely need next. It was beautiful... it all sparked from here https://github.com/open-wc/open-wc/issues/1551#issuecomment-618686616 However, I noticed that once a module failed, any attempt to reload would fail. Then I stumbled upon this, and I was... speechless, let's just say: https://github.com/tc39/proposal-dynamic-import/issues/80 A module that fails once for any reason (including network failure), will fail forever. The _network_ error is basically _cached_ on most browsers!
I got fed up with trying to load things dynamically, and noticed that the connection dealt with downloading of 700Kb much, much better than downloading several small little files -- especially if the little files's download is attempted later, when the connection is having a hard time.

At this stage, until most browsers *do* support re-attempting of module loading, I think I might as well just load the whole thing in one big gulp. I guess I may be over-reacting, but... well, the retrying code I wrote is useless, and I need my users to know that _everything_ in the application will work once it's loaded. Having them to face blank pages is really less than ideal.

Right now the service worker is being created by the rollup build process... Right  now I simply have:

    ....
    const spaConfig = createSpaConfig({})
    export default merge(spaConfig, { input: './index.html', plugins: [copy(copyConfig)] })

What's the spot in the `spaConfig`'s object to set rollup's options? I tried this, but no success:

    export default merge.all([spaConfig, { input: './index.html', plugins: [copy(copyConfig)] }], { plugins: { workbox: { inlineWorkboxRuntime: true } } })

I apologise for the obvious clumsiness shown in this ticket.

**Comment by thepassle** [comment]
>  However, I noticed that once a module failed, any attempt to reload would fail. Then I stumbled upon this, and I was... speechless, let's just say: tc39/proposal-dynamic-import#80 A module that fails once for any reason (including network failure), will fail forever. The network error is basically cached on most browsers!

Yep... I've run into this myself 😓 

Maybe a potential solution could be to use this: https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars

And then in your dynamic imports do something like 
```js
import(`./my-module.js?${Date.now()}`)
```
when retrying to fetch that module?

As for inlining workbox, this should do the trick:

```js
  createSpaConfig({
    // ...
    workbox: {
      inlineWorkboxRuntime: true
    },
  })
```

**Comment by mercmobily** [comment]
First of all:

````
createSpaConfig({
    // ...
    workbox: {
      inlineWorkboxRuntime: true
    },
  })
````

Damn, of course. Damn, I see createSpaConfig's code now and think: how did I not work that out on my own? Thanks for the  solution.

You would happen to know if there is any way to have the full code inside index.html rather than in a large external file? (Sorry, just trying my luck :D )

About this one:

> Maybe a potential solution could be to use this: https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars

Oh WOW. What I had done, before ditching reliable dynamic imports into the "too hard" basket, was using a lookup function:

```
  importModuleForPath (f) {
    try {
      switch (f) {
        case 'page-login':
          return import('./co-page-login.js')
        case 'view-ais':
          return import('./co-view-ais.js')
        case 'list-invoices':
          return import('./co-list-invoices.js')

The module name is taken from the path:

    const cleanPath = path.split(/[#?/]/)[1]
    ... (a little later)...
    mod = await this.importModuleForPath(cleanPath)

But wow, dynamic-import-vars renders this round-about code useless!

About this one:

> import(`./my-module.js?${Date.now()}`)

I explored this one at the time. It actually worked (!). Then I realised that it was rendering the service worker caching useless...!
I got into the service worker's code, trying to figure out if it was actually happening or if maybe I could have lived with that, and after a while I noticed my hair graying further.

In the end, my app ended up loading 400Kb and then the rest slowly... or 700Kb and never deal with _all_ of this again. I assure you, after dealing with a flaky internet connection, modules reload, after writing a whole lot of code to run retries and discover that _network errors are cached_ with no certainty of when browsers will apply this update, I truly had enough. I personally have the feeling the platform is not yet ready for dynamic imports as long as network errors are cached.

**Comment by thepassle** [comment]
> You would happen to know if there is any way to have the full code inside index.html rather than in a large external file?

I didnt see anything in the rollup docs to do this, but a quick google led me to this plugin: https://github.com/alwaysonlinetxm/rollup-plugin-fill-html

Not sure how well that works though

**Comment by mercmobily** [comment]
Wait, is what I am after not something that is normally done, so to speak?
Do people avoid doing it?

**Comment by thepassle** [comment]
I've personally never seen anybody take this approach, no :p

**Comment by mercmobily** [comment]
If nobody does it, it must be a bad idea.
I will never, ever  thank you enough for this help.

**Comment by mercmobily** [comment]
This issue is polluting your awesome project. I am closing it now, but will update later to let you know -- if you are interested -- how I went with dynamic loading. Yes, I have re-enabled it after all... And am checking whether I can make it all work with the service worker etc.

**Comment by thepassle** [comment]
Please do keep me posted, id be very interested to hear your progress especially with the dynamic loading/service worker. I worked on something similar a while ago, but got blocked because of the modules not being able to reloaded issue. At that time, the rollup plugin didnt exist though, so I'd be very interested to revisit.

The problem I was working on was basically a PWA app shell pattern that displays an offline page when a module fails to dynamically load, in case a user is offline. But ofcourse you want to be able to show the user the page when the user regains network connection again.

**Comment by mercmobily** [comment]
@thepassle Update:

This won't work:

````
      if (!failedLoadingAttempts[cleanPath]) mod = await import(`./co-${cleanPath}.js`)
      else mod = await import(`./co-${cleanPath}.js?` + Date.now())
````
I mean it _works_ unless you build. Once you build, using the module you recommended (dynamic-import-vars -- thank you!) it actually creates two import functions: the one without Date.now() is correct (it makes up a switch/case statement etc.), whereas the other one has no options in the switch/case.

What I am doing now, is simpler: if there is a loading error, since  loading effectively cannot be retried (yet?), I simply offer the option to reload the whole app. In a few  years, this will hopefully not be necessary anymore as failed network attempts won't return the cached error object...

**Comment by fatso83** [comment]
@mercmobily Since https://github.com/whatwg/html/issues/6768 still is not closed, you might be interested in the workaround packaged as a small library: https://github.com/fatso83/retry-dynamic-import
