### ISSUE TITLE
Service worker + Server Side Rendering

### ISSUE THREAD

**Issue by dejan9393** [open-wc/open-wc#1876]
Hi, is it currently possible to set up a service worker that works with SSR?

I have an application that was built using `npm init @open-wc`. It's bundling with Rollup and internally it's using Workbox's `generateSW` method to generate a service worker.

This works very well until we put server-side rendering into the mix. Since we provide a `navigateFallback` property to the `generateSW` method, this means that our index.html file must exist in the precache. This also means that we cannot define another strategy for caching the `index.html` file.

My thinking was that I could get the `index.html` file cached with the `StaleWhileRevalidate` strategy, then any new changes from the server-side rendered index.html file will be shown to the user on next reload. I did however read on an issue in workbox that mixing precache with other strategies is not ideal (https://github.com/GoogleChrome/workbox/issues/1988#issuecomment-506467218)

Are there any ideas on how to get this implemented documented? I would love to give it a try.

**Comment by thepassle** [comment]
I have personally not implemented SSR in combination with service workers, but having said that, the `index.html` should indeed be in the precache manifest of your `sw.js` created by `generateSW`. If you'd like more fine grain control on your caching strategies, you could try to use the `injectManifest` mode.

Also, as far as I'm aware there still are some issues with server side rendering and web components that havent been entirely ironed out, did you manage to find a solution for that?

**Comment by dejan9393** [comment]
Thanks for the response

To answer your question, no. I looked into a few options with SkateJS being the most promising of the lot, but decided that it's not worth implementing full-blown SSR for WebComponents just yet. My implementation is very simple and focuses on meta tags and page title + a little additional config from a backend server that gets injected as a JSON blob into a prop on the main component (multi-tenant app with slightly differing configs/titles/descriptions depending on domain).

Having said that, if there were a change to the <title> or any meta tags, requests for the index.html file would respond with the precached index.html with the title saved on first load, which is undesirable. I'm currently experimenting with injectManifest and a combination of precache and a custom handler that implements a StaleWhileRevalidate-like functionality, but am yet to see if that does what i'd like it to do

**Comment by thepassle** [comment]
Why not just update the index html on service worker change then? Implementing a custom stale while revalidation function sounds like more trouble and effort than just precaching the index.html and updating it whenever there has been a change

**Comment by dejan9393** [comment]
I might not have explained correctly. The contents of the index.html can change without changes to the service worker.

Maybe a short example can illuminate:

* User accesses Site A
* The SSR script recognises a request for the index.html file
* The SSR script asks an API for config for Site A
* API returns title and other config values
* SSR script retrieves file contents of index.html and replaces <title> tag with new value + responds to client (we don't make physical changes to the index.html file, just alter the response sent to the client, basically just `indexHtml.replace('<title>', '<title>Some Title From Config');`)
* Client receives response and Service Worker saves the response to the browser's precache storage
* Now lets say admin changes config in API, and the title is something new
* Client accesses Site A again, but gets a cached response from the SW because the precache has stayed the same, since the index.html file on the file system did not actually change

Or perhaps I've twisted my thoughts on this, and it's a lot simpler than i'm imaging?

I finished up a simple `injectManifest` implementation that so far seems to do the trick, i'll post it here for reference:

<details><summary>injectManifest example</summary>
<p>

```javascript
import {precacheAndRoute} from "workbox-precaching";
import {clientsClaim, skipWaiting} from "workbox-core";
import {NavigationRoute, registerRoute} from "workbox-routing";
import {cacheNames} from 'workbox-core'

const manifest = self.__WB_MANIFEST;
precacheAndRoute(manifest);

skipWaiting();
clientsClaim();

self.addEventListener('install', (event) => {
    // Add index.html to cache on SW install
    const populateCache = async () => {
        const cache = await caches.open(cacheNames.runtime);

        await cache.add('/index.html');
    };

    event.waitUntil(populateCache());
});

const handlerForUrl = (url) => async () => {
    const cache = await caches.open(cacheNames.runtime);
    const request = new Request(url);

    console.log("Fetching index.html for caching...");
    const newRequest = fetch(request).then(response => {
        cache.put(request, response);

        console.log("cached result of index.html for next time");
    });

    const response = await cache.match(request);
    if (response) {
        console.log("found a match! returning cached response");
        return response;
    }

    console.log("No match found, returning the new fetch request");
    return newRequest;
}

registerRoute(new NavigationRoute(handlerForUrl('/index.html')))

```

Note: This requires you to exclude index.html from the precache
</p>
</details>
