### ISSUE TITLE
[eslint-plugin-lit-a11y] add click-events-have-key-events whitelist

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc#1878]
The following code is valid:
`<button @click=${foo}>click</button>`

But the following is not:
`<ing-button @click=${foo}>click</ing-button>`

We should add a allowList to allow button-like custom-elements via options. We can just add the check here:

https://github.com/open-wc/open-wc/blob/34ef9e392b8c3a21dc75c809d8bcdafab7aa885b/packages/eslint-plugin-lit-a11y/lib/rules/click-events-have-key-events.js#L61

Something like:

```js
allowList.includes(element.name)
```

You can find an example of how to add configurable options for a rule here:

https://github.com/open-wc/open-wc/blob/34ef9e392b8c3a21dc75c809d8bcdafab7aa885b/packages/eslint-plugin-lit-a11y/lib/rules/img-redundant-alt.js#L38

```js
schema: [
      {
        keywords: {
          type: 'array',
          items: {
            type: 'string',
          },
          uniqueItems: true,
          additionalItems: false,
        },
      },
    ],
```

**Comment by trystan2k** [comment]
Hey !

I have opened a PR that I believe solve this.
