### ISSUE TITLE
[eslint-plugin-lit-a11y] accessible-emoji is deprecated, remove it

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc#1903]
see title

also remove from the packages main README and the recommended settings in the index.js

bonus points for going through all the other rules and seeing if we added any other deprecated rules by chance

https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/accessible-emoji.md

**Comment by momosetti** [comment]
Hi @thepassle , i will go through it.

**Comment by bennypowers** [comment]
I'm already working on this in #1899

**Comment by bennypowers** [comment]
@momosetti would you consider implementing one of the missing rules instead?

**Comment by thepassle** [comment]
this was fixed, we deprecated instead of removed
