### ISSUE TITLE
[eslint-plugin-lit-a11y] detect lit-html import

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc#1904]
We should add a check to each rule to see if `html` is indeed imported from lit-html or lit-element. Different rendering libraries may use a `html` tagged template literal as well, and may have a differing syntax than lit-html, we dont want to clash with that.

We can look at `ImportDeclaration`s in the visitor (similar to how we declare the `TaggedTemplateExpression` function), and then check if one of the `ImportSpecifiers` is `html`, and if the `source` is lit-html or lit-element

We can keep track of a `isLitHtml` variable in the scope of the `create` function, and then do something like:

```js
  create(context) {
    let isLitHtml = false;
    return {
      ImportDeclaration(node) {/* check if import is lit-html, set isLitHtml to true */}
      TaggedTemplateExpression(node) {
        if (isHtmlTaggedTemplate(node) && isLitHtml) {/* implement rule */}
      }
    }
  }
```

We should also make the source configurable; packages may re-export `html`, e.g.:
`import {html} from 'ing-web';`. We should be able to use this for that: https://eslint.org/docs/user-guide/configuring#adding-shared-settings and reference it from the `context` object passed down by the `create` function

This check should be added to _all_ rules.

AST explorer is your friend
https://astexplorer.net/#/gist/12d236f9f40aee114413e87e2a564b6b/ff4653d065bfd3f51e3e9bafd0254494e38349b8

One potential problem here could be the tests. We'd need to add the lit-html import to every single test fixture... maybe we can find a better way to mock it somehow. But its something to consider

**Comment by bennypowers** [comment]
What about reexports? `@open-wc/testing` does that, so does `@apollo-elements/lit-apollo`

Better to trust the user, I think. They can use `overrides` of there using two versions of `html`

**Comment by thepassle** [comment]
Reexports are also accounted for in the issue
