### ISSUE TITLE
add npm keywords to all the package.json files

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#191]
most of our packages do not have proper tags 🙈 

we should add some 🤗

**Comment by NioniosSpeed** [comment]
Hello! Can I pick this one up?

**Comment by Westbrook** [comment]
Thanks @NioniosSpeed!

**Comment by daKmoR** [comment]
yeah finding out which tags is sort of the task :see_no_evil: 

e.g. what are common tags for build tools? probably `build` or `building`? for `building-rollup` probably `rollup` would be good...

so maybe do a brainstorm ala writing it down like this
- building-rollup
  - rollup
  - build
  - web-components
  - ...
- es-dev-server
  - server
  - http-server
  - polyfill
  - ...

and then we can see if all those tags make sense.
Once agreed upon the next step would be to make a PR with all the changes to the package.json files.

**Comment by daKmoR** [comment]
has been done already 👍
