### ISSUE TITLE
[eslint-plugin-lit-a11y]: refactor to compose rules, test settings

### ISSUE THREAD

**Issue by bennypowers** [open-wc/open-wc#1911]
## Composing Rules

Currently, we copy logic into each rule to verify that the file imports lit-html's `html`, This is great for users but hard to maintain, as we have to remember to copy in the logic for each rule.

We can compose rules with https://github.com/not-an-aardvark/eslint-rule-composer

so, instead of adding a predicate in each rule's AST visitor, we can just compose them together:

```js
const { filterReports } = require('eslint-rule-composer');
const eslint = require('eslint');
const hasLitHtmlImport = require('../utils/hasLitHtmlImport');

const TheRule = { /*...*/ }

module.exports = filterReports(TheRule, hasLitHtmlImport);
```

Much DRYer.

-----

## Applying `settings` in tests

In tests, we map over each test case to add an import statement for lit-html's `html`. We can apply settings for a test run with:

```js
const ruleTester = new RuleTester({ settings: { myPluginSpecificSetting: ['lol'] } });
```

we could make `litHtmlSources` opt out by accepting `false` as an option, then disable checking for tests with

```js
const ruleTester = new RuleTester({ settings: { litHtmlSources: false } });
```

**Comment by bennypowers** [comment]
https://www.npmjs.com/package/eslint-rule-extender is a maintained alternative to eslint-rule-composer

**Comment by bennypowers** [comment]
from @kaicataldo, maintainer on eslint-rule-extender, when asked if we can stop a rule from reporting errors in one visitor from another (shared) visitor:

> yes - in the case of eslint-rule-extender, you’d do this by checking the reports and filtering them out. Have you looked at https://eslint.org/docs/rules/no-restricted-syntax or https://eslint.org/docs/rules/no-restricted-imports? Obviously don’t have much context here, but that might get you what you need

ostensibly we'd use `reportOverrides` for that

**Comment by kaicataldo** [comment]
If you're creating an additional `ImportDeclaration` visitor, I _believe_ you should be able to either:

1. Check the error message or analyze the node that's in the report metadata passed to `reportOverrides`
2. Add some data in the metadata (i.e. `{ isLitHtml: true }`) that is checked in `reportOverrides`. This data is generally intended for interpolation into the error message itself, but I don't think (not 100% sure without checking the code) that we enforce that all data is used in the error message. This could help avoid extra calculation overhead.

**Comment by bennypowers** [comment]
I'm going to take a crack at this today

**Comment by bennypowers** [comment]
this seems to work, without requiring any changes to rule code except for applying `ruleExtender`.

preparing a PR

```js
const HasLitHtmlImportRuleExtension = {
  /**
   * @param {import('eslint').Rule.RuleContext} context
   * @return {import('eslint').Rule.RuleListener}
   */
  createAdditionalVisitors(context) {

    /** if user set `litHtmlSources` to literal `false`, analyse all html-tagged literals */
    const userExplicitlyDisabledImportValidation =
      context.settings.litHtmlSources === false;

    /* eslint-disable no-param-reassign */

    context.parserServices.shouldAnalyseHtmlTaggedLiterals =
      userExplicitlyDisabledImportValidation

    return {
      ImportDeclaration(node) {
        const shouldAnalyseNode =
          userExplicitlyDisabledImportValidation ||
          hasLitHtmlImport(node, context)

        if (shouldAnalyseNode)
          context.parserServices.shouldAnalyseHtmlTaggedLiterals = true
      },
    };

    /* eslint-enable no-param-reassign */
  },

  /**
   * @param {import('eslint').Rule.RuleMetaData} meta
   * @param {import('eslint').Rule.RuleContext} context
   */
  reportOverrides(meta, context) {
    const { shouldAnalyseHtmlTaggedLiterals } = context.parserServices || {};
    return !!(shouldAnalyseHtmlTaggedLiterals);
  },
}
```

**Comment by bennypowers** [comment]
ok my solution relies on the `ImportDeclaration` visitor in `createAdditionalVisitors` running before the subclass rule, I hope that's a good assumption

**Comment by kaicataldo** [comment]
@bennypowers I believe that the subclass rule's visitors will [always run first](https://github.com/kaicataldo/eslint-rule-extender/blob/967e9b7f856c18398f1e48343c35364a5a09112a/lib/index.js#L70) (unless there's a bug in the code). ESLint's `:enter:`/`:exit` visitors are intended to be used if you have state you need to manage.

I hadn't considered what would happen with multiple `:enter:`/`:exit` visitors, but I think I'll punt on that for now since it seems unlikely!
