### ISSUE TITLE
[eslint-plugin-lit-a11y] check for tabIndex property

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc#1912]
Currently in rules that check tabindex, we only check the tabindex attribute. We should go through the rules, see where we check for the tabindex attribute, and also check the `tabIndex` property.

**Comment by thepassle** [comment]
Bonus points: are there other places where we check for an attribute, but not a property?

**Comment by koenvg** [comment]
Would like to take this issue. Can you assign it to me?

**Comment by thepassle** [comment]
👍

**Comment by thepassle** [comment]
Thinking on this more, I'm not sure if it makes sense to do this. We dont check the values inside expressions in lit-html templates, and setting properties kind of implies using an expression. E.g.: `<div .tabIndex=${1}/>` <- this will not be checked, because the content of the expression will be replaced by a placeholder.

It still could be valuable to see if we can do something here though.

**Comment by bennypowers** [comment]
@thepassle do we have an issue for that?

**Comment by thepassle** [comment]
For checking the contents of an expression? We dont currently, but we need to find a good way to go about it as not to mess up the reporting locations.

I think we could do something similar to what we had before I reverted it. If the content of an expression is a `Literal` node, we can instead of using a placeholder, just substitute with the literal value, but if its anything other than a `Literal` (`this.foo`, `foo`, `true ? 1 : 2`, `()=>{}`, etc), replace it with a placeholder.

But again, we really need to make sure this doesnt mess up the reporter.

**Comment by thepassle** [comment]
Created a separate issue for linting `Literal` values [here](https://github.com/open-wc/open-wc/issues/1913)

**Comment by koenvg** [comment]
Whilst looking into this more and looking at the other PR, I am not sure I understand the problem correctly.
I thought this was a problem about setting the tabIndex property via javascript like so
```
const el = document.getElementById('test');
el.tabIndex = 2;

// or in a component
this.tabIndex = 3;

// or what about this case
this.setAttribute('tabindex', 4);
```

**Comment by bennypowers** [comment]
@koenvg `HTMLElement#tabIndex` property reflects to `tabindex` attribute, e.g.

```js
const span = document.createElement('span');
span.setAttribute('tabindex', "1");
span.tabIndex; // 1
span.tabIndex = 2;
span.getAttribute('tabindex'); // 2;
```

so these two templates are functionally equivalent:

```js
html`<span .tabIndex="${2}"></span>`;
html`<span tabindex="2"></span>`;
``` 

PR #1915 (merged) fixes the problem of analyzing literal values.

**Comment by thepassle** [comment]
To summarize: 
```js
html`<div .tabIndex=${2}/>`
```

Should fail

**Comment by koenvg** [comment]
@thepassle Thank you for explaining. I see what the goal is now 😄
