### ISSUE TITLE
[Testing] componentOnReady for Stencil components issue

### ISSUE THREAD

**Issue by vogloblinsky** [open-wc/open-wc#192]
I updated to @open-wc/testing 0.9.15

I think the code for componentOnReady from Stencil (https://github.com/ionic-team/stencil/blob/fe4d3bfcf37457437d4499264f8b8c9593f1a81b/src/core/component-on-ready.ts#L8) is not just requesting the next Animation Frame in your tests https://github.com/open-wc/open-wc/blob/master/packages/testing-helpers/test/elementUpdated.test.js#L38

I need to stay on `await el.componentOnReady();`

May be enhancing the test suit with a real hello world Stencil component may help ?

**Comment by daKmoR** [comment]
uh yeah that sounds great :) could you provide a PR or the code "output" of this hello world stencil component?

**Comment by vogloblinsky** [comment]
The problem with Stencil is it outputs many files : es5 version, es6 version, a custom loader etc.
Did you think possible to setup the loading of an external WC like i do here ? : https://github.com/vogloblinsky/open-wc-stencil/blob/master/test/test-open-wc-stencil.test.js#L7

**Comment by daKmoR** [comment]
sure... for the test we only need the `dist/esm/es2017/nova.define.js` files as it will be transpiled by webpack if run through karma anyways.

**Comment by daKmoR** [comment]
can you maybe prepare a repo to reproduce this?

I just started a stencil component project copied it over and tested it here: https://github.com/open-wc/open-wc/pull/195

seems to work just fine in the browser - this build fails as it tries to recompile the already compiled stencil code

**Comment by vogloblinsky** [comment]
i have setup @open-wc/testing here https://github.com/vogloblinsky/nutrition-web-components

**Comment by vogloblinsky** [comment]
@daKmoR your test fixture should be fine. you can merge if you want

**Comment by daKmoR** [comment]
We had a bug in the testing fixture that wrongly used the sync version instead of the async one 🙈 

can you maybe retry to use just `await fixture()` (without `await el.componentOnReady()`) and see if it works?

**Comment by vogloblinsky** [comment]
Yeah, works fine now ! Thanks a lot for your great job.
