### ISSUE TITLE
[Testing] Issue with karma 3.1.4 & Safari 10.1

### ISSUE THREAD

**Issue by vogloblinsky** [open-wc/open-wc#193]
Got this issue with BrowserStack : https://github.com/karma-runner/karma/issues/3198

Seems fixed with Karma 4.0.0

Can submit a PR for that if you want.

**Comment by daKmoR** [comment]
oh cool... apparently I missed that release :see_no_evil: 
if we can easily upgrade we sure should do :+1:

**Comment by vogloblinsky** [comment]
Yes you can, juste upgraded in my project, works fine now.
The 4.0.0 has a BC on Node.js 6 : https://github.com/karma-runner/karma/releases/tag/v4.0.0
