### ISSUE TITLE
[demoing-storybook] Upgrade to version 6

### ISSUE THREAD

**Issue by michelneumann** [open-wc/open-wc#1950]
Storybook 6 was released a while ago. I would be nice to include the latest features and update the package used in the @open-wc/demoing-storybook module.

**Comment by LarsDenBakker** [comment]
We are working on an update along with some other planned updates.

**Comment by michelneumann** [comment]
Okay, thanks for the information!

**Comment by LarsDenBakker** [comment]
We are working on this as a plugin for the new dev server: https://modern-web.dev/docs/dev-server/plugins/storybook/

I'm currently testing if everything works correctly, and we still need to implement building.

**Comment by michelneumann** [comment]
Thanks for the update @LarsDenBakker!

**Comment by LarsDenBakker** [comment]
We now recommend https://modern-web.dev/docs/dev-server/plugins/storybook/ for storybook v6. The generator is updated as well.
