### ISSUE TITLE
Please consider alternatives too

### ISSUE THREAD

**Issue by WebReflection** [open-wc/open-wc#1952]
### This issue mostly regards `eslint-plugin-lit-a11y`

I am following this `@open-wc` project and I think it has a great purpose but, at the same time, a very misleading message, please allow me to expand.

### About lit-html

This library is great and popular but it's not the first, not the smallest, or even the fastest out there, but everything in the site, including this plugin, hence work related to such site, is promoted as *recommendation* for Web Components, and this is misleading for the following reasons:

 * there are various alternatives that do exactly what *lit-html* do, without any compromise when it comes to Web Components (ahem, Custom Elements) handling.
 * the *recommendation* part of this effort equation is misleading. It's not clear why other libraries are not recommended, and most of the things are about *lit-html*. If this was part of the library project there wouldn't be a single reason for me to open this issue, but since people believe this site is genuinely recommending best practices, it's not clear why everything *lit-* is in, but prior work and alternatives are ignored.
 * naming *a11y* plugins that work with every alternative as `lit-a11y` makes people think such plugin works only with *lit-html*. As this whole plugin goal is to improve accessibility for template literal DOM manipulation based libraries, and as there is also a special flag documented as useful escape for not still supported alternatives, like *htm* mentioned in the README, makes this whole effort look like promoted, or sponsored, by *lit-html* people (but AFAIK that's not the case)

### Why is this plugin name problematic?

To start with, when you name a plugin after a specific library, which simply uses a common pattern, the community around such pattern won't likely help contributing with the plugin, as it's indirectly promoting something else that's unrelated.

Imagine Ferrari Open Sourcing a *ferrari-engine-metrics* module, when everyone needs an *engine-metrics* one, and wait 'till Porsche adopts, or contributes, to that project ... it ain't gonna happen.

On top of that, new comers seem to follow your recommendation, believing *lit-html* is the only one that does what it does, so that alternative offers won't likely link, suggest, or even use, stuff that is more than welcome and surely useful for the web, like a template literal based `a11y` helper could be.

### Please stop making everything a lit-* affair

If the goal of this project is to promote best practices, it might as well stop promoting only a single library from the only team working on their paid time on such library, otherwise every other developer that is offering alternatives on their "*free time*" would just start ignoring this project goal, or give up on trying to make the Web a better place.

As summary, I believe the intent is genuine, but results are making me think this project does not want to improve `a11y` in general, it just wants to keep promoting a specific library, but that's not how *recommendations* should work.

Thanks for your understanding, to me it's just hard to contribute to anything that could work everywhere, but indirectly misleads people to believe only one library could fully benefit from it, which is *hopefully* not the case (and if it is the case, please make the "*lit-only*" flag the default, not an escape, thanks).

### Suggestion

Please rename the `a11y` related plugin as `eslint-plugin-litera11y` so that authors of other libraries can contribute as they can to make it a universal best practice for the Web, as opposite of an ad-hoc plugin for a single library.

Than you for consideration.

**Comment by thepassle** [comment]
Thank you for the feedback, Andrea 🙂

There's quite a lot to unpack here, so I'll try to take things point-by-point.

> there are various alternatives that do exactly what lit-html do, without any compromise when it comes to Web Components (ahem, Custom Elements) handling.

We have already had this discussion both on public twitter, and continued in DMs. We recognize that we seem very focused on the `lit-*` family at this point in time, and have discussed it among the team. We're currently working on a revamp of our documentation site, and we aim to be more inclusive to other parts of the web component ecosystem. 

It should also be noted that a lot of our tooling is not tightly coupled to `lit-*`, but is more broadly usable by other web component libraries. Some libraries, however, (for example lit-helper), are, because we have had a need for them.

Additionally, we want to give newcomers a good set of defaults to start out with, and not give them a bunch of libraries to browse through. 

> the recommendation part of this effort equation is misleading. 

A recommendation is opinionated by definition, we also mention that we provide opinionated tooling on our landing page, and are transparent about that.

> It's not clear why other libraries are not recommended,

This is a fair point - we can definitely try to improve here and elaborate on the fact that lit-html is not the only library 🙂

> As this whole plugin goal is to improve accessibility for template literal DOM manipulation based libraries

The fact that the eslint plugin works with other libraries is entirely coincidental (but a nice bonus! And I'm happy to hear they work flawlessly with your projects). However, while developing the accessibility plugin, I will admit I did not generally have other libraries in mind (in fact, we have a setting to guard against linting templates from other libraries in case of syntax difference, or if a project uses multiple render libraries in the same project). 

We have discussed among the team on whether or not we should extend support to include other libraries in the plugin as well, or perhaps add extended documentation on how different libraries could fork and make it work for their tagged template literal based library.

> Please stop making everything a lit-* affair

While I agree, as mentioned various times before, we're looking to improve on this. We reserve the right, however, to make recommendations as we see fit. Thats why they are recommendations.

> As summary, I believe the intent is genuine, but results are making me think this project does not want to improve a11y in general, it just wants to keep promoting a specific library, but that's not how recommendations should work.

As someone who worked a lot on the eslint plugin, I can assure you there is no hidden agenda here. Just trying to help improve accessibility.

> (and if it is the case, please make the "lit-only" flag the default, not an escape, thanks).

By default, any `html` tagged template literal is linted. The "lit-only" flag is entirely opt-in.

**Comment by WebReflection** [comment]
Thank you for your prompt answer, to which I'd like to answer too:

> Additionally, we want to give newcomers a good set of defaults to start out with, and not give them a bunch of libraries to browse through.

This is understandable, but I think everything is already out there, so that such set of defaults *could* also be inclusive, while if missing, could be a great hint for alternatives to improve, as the final goal is the same: ship Web Components out there.

> A recommendation is opinionated by definition

As long as there's a list of checks to mark in order to justify such recommendation ... I mean, I can't really recommend coffee to cook pasta for a variety of reasons, even if I love coffee, hence there must be a *reason* to recommend something, and such reason here is not clear at all to me.

> This is a fair point - we can definitely try to improve here and elaborate on the fact that lit-html is not the only library

That'd be a starting point, as long as it's clear what *lit* offers that alternatives don't, otherwise the whole project should be called *Web Components Opinionated Suggestions*, which is closer to what you're describing, or "*Lit Components*" with an implicit recommendation otherwise meaningless, if not clarified anyhow, 'cause I think *recommendations* should be backed by facts, concrete advantages, and once again *lit-html* is great, but just one of the libraries that do what *lit* does, and there are benchmarks, metrics, and whatsoever, to exclude it from being "*the best one*" for the Web Components purpose, accordingly to these metrics.

And yet, I am not saying there is a best one to recommend in general, I am saying *lit-html* does things others might do or not, *and* vice-versa.

If the goal is to recommend best practices for *Web Components*, any library should be decoupled from such practices/recommendation, as the whole point of *Web Components* is that these work everywhere, from vanilla to any helper, and using the umbrella to promote a library that's not strictly even necessary, is hard to sell as best practice, or recommendation.

I don't even care if anyone uses my library, as long as they'll try to come closer to the platform, which offers a lot already, and nothing else might be needed at all.

> I will admit I did not generally have other libraries in mind

This issue title is exactly about this, as it's obvious to me, and this great plugin is just yet another missed opportunity for contributors interested in having *a11y* helpers for their libraries too.

> perhaps add extended documentation on how different libraries could fork and make it work for their tagged template literal based library.

If the name doesn't change, forks will happen anyway, so it'd be great to hear from you that forks will be listed as recommendation too, once optimized for their own library target, but my point is: I think you're missing out in potential contributors.

If you're not interested in contributors for this project though, it's totally fine too, I'm just saying why I'd fork, rather than contribute, with that plugin, exact same way I've forked before the highlighter for template literals based libraries ... and none of this helps moving standards forward, as conflicts happens with various forks of the same project too, which is something I'd love to avoid.

> We reserve the right, however, to make recommendations as we see fit. Thats why they are recommendations.

I don't think I need to mention W3Schools here ... but of course, you can recommend whatever you like, but you have a quite **loud** domain name and project, regarding Web Components standard, so please consider not making it something people should ignore in the long term, as libraries come and go, while standards remains, reason we're all using these as much as we can, right?

And then again, having a *reason* for recommendations looks like the minimal thing you could add as documentation: what is it that other libraries are missing, so that you recommended a specific one, or mentioned another one (*htm*) and these are all from developers of the same company? Should it be clear, in case that's your position, that if it's *Google*, it's recommended? That's also a valid statement, if you ask me, as long as it's clear, and not pretending to be objective.

> Just trying to help improve accessibility.

Not at its full potential though, as you're helping a niche of developers (compared to those not using Web Components), instead of including all niches that believe in Web Components, which is my current goal: make things inclusive, please, so that everyone in this train can contribute, instead of ignoring these recommendations.

> By default, any html tagged template literal is linted. The "lit-only" flag is entirely opt-in.

I know that, which is why every library of mine works already, so let's give non *lit-* developers a chance to contribute with a fair name for such plugin that works already pretty much everywhere, thanks.

P.S. I already got the `eslint-plugin-litera11y` namespace, and I'd give it to you without blinking once if needed

**Comment by LarsDenBakker** [comment]
It would be great to have an a11y linter that works for all projects. But there are a lot of templating libraries out there which can all handle expressions differently, so we need to figure out how and if this can be done efficiently and if we can maintain this.

Your position is that we should have done this from the start. I don't think that's fair, we're all volunteers with a limited set of resources to build and maintain these implementations. We can't implement this for all libraries. So in this instance we chose to go with something that brings a lot of value to a lot of people. 

In most other instances we do create library agnostic solutions. We only have a handful of lit-html specific packages. Also our recent work on the (work in progress) custom elements manifest https://github.com/webcomponents/custom-elements-manifest and the library agnostic helpers https://github.com/open-wc/custom-elements-json will work for all custom element libraries...

Pascal already said we can do more to make other libraries more visible. Writing down a motivation why we choose lit-element as the default I think is good to add as well. But as a team we feel strongly that having a single recommendation is a good starting point for most users. That's something we'll have to disagree on it seems :)

**Comment by WebReflection** [comment]
> there are a lot of templating libraries out there which can all handle expressions differently

I think most libraries are standards-compatible, but even if each project has some specialized syntax, *a11y* within *HTML* should be pretty normalized across all offers. *uhtml* has the special *aria* case, to simplify attributes assignment through objects literals, but any standard aria attribute would work out of the box too, and I am pretty sure that's the case for *htm* and every other library

> we're all volunteers with a limited set of resources to build and maintain these implementations

what I am reading is "*due limited resources, we'd like to have more contributors*", and my point is that if you keep suggesting and/or developing solutions for a single library, either their team helps out, or alternative libraries authors help ... but why would they, if the result is mostly extra marketing for *your* library of choice?

> In most other instances we do create library agnostic solutions

one link is from *lit-html* authors/team, and the other is very experimental, but I wasn't aware of that, so thanks for bringing it out. Yet these are not recommendations, just proposals, right? Not sure how those links are relevant.

> Writing down a motivation why we choose lit-element as the default I think is good to add as well

It'd be great, and it will clarify the opinionated *recommendation* instead of current generic claim without reasoning, so thanks for considering this.

> as a team we feel strongly that having a single recommendation is a good starting point for most users

fair enough, but imagine MDN creating *best practices* documentation that lists only one library ... how would you feel, as library author?

> That's something we'll have to disagree on it seems

The only thing we disagree is that you even need a 3rd party library to create Custom Elements. It's like recommending *jQuery* to query the DOM instead of using `document.querySelectorAll` ... it might help and simplify in some case, but it's surely not a *recommendation*, neither a *best practice*.

I hope I've explained my point of view enough, but I'd be happy to expand even more, if needed.

I'm looking forward to read the reasoning around *lit-html* choice, hoping this will land soon in your pages 👋

**Comment by thepassle** [comment]
> clarify the opinionated recommendation instead of current generic claim without reasoning

Again, recommendations are opinionated by definition, and we are free to recommend as we see fit. Our recommendations may change in the future. We have always been transparent about this. 

For one last time; we do look to improve on being more inclusive to other libraries, as I have mentioned many times now. I think we should leave the discussion at that and try to move forward with the feedback you have given us.
