### ISSUE TITLE
inline-module filename does not include hash

### ISSUE THREAD

**Issue by jonmann20** [open-wc/open-wc#1959]
## Expected behavior

Expected `inline-module-[name]-[hash].js` instead of `inline-module-[name]-[index].js`.

## Actual Behavior

When using rollup-plugin-html inline modules are not hashed and results in files that are not cache busted.

## Additional context

```html
<!-- index.html -->
<script type="module">
       import 'foo';
</script>
```

```js
// rollup.config.js
{
    input: `index.html`,
    output: {dir: dest},
    plugins: [
      babel(),
      dynamicImportVars(),
      nodeResolve(),
      html()
    ],
    preserveEntrySignatures: false
}
```

```html
<!-- dist/index.html -->
<script type="module" src="./inline-module-index-0.js"></script>
```

This is an issue when the contents of the inline module in `index.html` changes.  Ideally the contents of the inline module would be hashed and that hash included in the file name rather than just the index.

**Comment by LarsDenBakker** [comment]
`@web/rollup-plugin-html` is the success of the open-wc version. This includes hashing of inlie modules: https://modern-web.dev/docs/building/rollup-plugin-html/

We're still working on feature parity, then we will update building-rollup.

**Comment by jonmann20** [comment]
Ah, thanks I will check that out.
