### ISSUE TITLE
[generators] Enterprise App Setup

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#197]
This will have a slightly different approach then the Starter App - probably way more heavy (and intimitated - definitely not starter friendly)

possible structure for `app-foo`:
```
app-foo
├── packages/app-foo
│   ├── app-foo.js
│   ├── app-helpers.js (optional)
│   └── test
│       └── app-foo.test.js
├── packages/foo-menu
│   ├── foo-manu.js
│   ├── FooController.js (example for full class)
│   ├── FooMenu.js
│   ├── stories
│   │   └── foo-menu.stories.js
│   └── test
│       ├── FooController.test.js
│       └── foo-menu.test.js
├── stories
│   └── index.stories.js (shows all stories)
├── test
│   └── index.html (to run all tests directly in the browser)
├── index.html 
├── index.js (webpack entry point)
└── ... (all the config files)
```

This should have everything:
- full linting
- full testing
- demo setup via storybook
- building via webpack
- integrated via ci
- prepared to possibly become a lerna monorepo and/or to easily extract certain parts to a separete package/repo

**Comment by LarsDenBakker** [comment]
What should we do different VS pwa-starter-kit?

**Comment by moebiusmania** [comment]
really interesting! 
but IMHO giving this modular nature, this setup best suits a kind of "library" project rather than an "Enterprise application".
