### ISSUE TITLE
Replace @open-wc/rollup-plugin-html with @web/rollup-plugin-html

### ISSUE THREAD

**Issue by abdonrd** [open-wc/open-wc#1980]
There are any plans to replace `@open-wc/rollup-plugin-html` with `@web/rollup-plugin-html` in the `@open-wc/building-rollup`? There are interesting stuff like the `absoluteBaseUrl` there.

**Comment by LarsDenBakker** [comment]
Yes we want to do this, along with `@web/rollup-plugin-polyfill-loader`.

**Comment by abdonrd** [comment]
I have started this, but I just realized that the plugin itself has changed: https://github.com/open-wc/open-wc/compare/master...abdonrd:web-rollup

**Comment by LarsDenBakker** [comment]
Yes indeed. The functionalities are still there, but we made the API simpler

**Comment by daKmoR** [comment]
I made it work for `codename rocket` by forking building-rollup... 

you can see [the code in the repo](https://github.com/daKmoR/rocket/tree/master/packages/cli/src/_building-rollup-fork).

copying parts from there will probably get you ~80% there... however, as this will be a breaking change I'm wondering if we have some other breaking changes lined up? 🤔

**Comment by LarsDenBakker** [comment]
I don't know of any other breaking changes pending. Perhaps terser if we didn't already update that.

**Comment by abdonrd** [comment]
Thanks guys!

But there is no option to minify in the new plugin?
https://github.com/open-wc/open-wc/pull/1986/files#diff-c4ef3c2ec498756a71474145d944b814adb96495ef7ea37d221af16c90b950ebL47

https://modern-web.dev/docs/building/rollup-plugin-html/#minification

**Comment by LarsDenBakker** [comment]
not stale

**Comment by abdonrd** [comment]
not stale

**Comment by stephenwade** [comment]
Not stale. Waiting on #2213.

**Comment by abdonrd** [comment]
Fixed by #2228
