### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by goatandsheep** [open-wc/open-wc#199]
What's the best way to do server-side rendering for web components? Headless chrome? How to set this up?

**Comment by daKmoR** [comment]
what would be the primary goal of SSR? SEO?

**Comment by goatandsheep** [comment]
Yes. For enterprise applications, it's important we have SEO

**Comment by btopro** [comment]
SEO and hitting really old targets with something other then a blank page. This question comes up constantly and even if it's minimal in what it targets it's a non-starter for many.

**Comment by btopro** [comment]
"there are other search engines" - someone that always brings this up when I say that ;)


Googlebot's been able to see web components for about 2 years now I believe so no I don't totally get the reasoning. screen readers now require javascript (the major ones) so not there. I hear it sometimes for non-js / much older browsers being able to be supported but... seems like a lot of effort to hit a dwindling target.

**Comment by goatandsheep** [comment]
@btopro I believe that a standard should not be more bulky than it needs to be and I suggest we _explicitly_ advise against SSR.

**Comment by aress31** [comment]
I second @btopro comment!

In fact, a simple example on why `pre-rendering` or `SSR` should be a must for SEO would be with `OpenGraph meta tags`. At the minute, the likes of LinkedIn, Facebook and Twitter are unable to parse them when they are set using JavaScript. I was facing this issue using CRA and I am now considering moving to Open WC so I believe that a note about route-based SEO should be added to the website.
