### ISSUE TITLE
Creating a new application using `npm init @open-wc` creates an application that does not work

### ISSUE THREAD

**Issue by Alos** [open-wc/open-wc#1997]
After creating an application using TS all features turned on with the initializer the result is an application what then started using `npm run start` outputs:
```
[tsc] 4:10:12 PM - Starting compilation in watch mode...
[tsc]
[tsc] ../node_modules/@types/yeoman-generator/index.d.ts(36,46): error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?
[tsc]
[tsc] 4:10:18 PM - Found 1 error. Watching for file changes.
```

These are the values used in the application setup:
```
npm init @open-wc --destinationPath /Users/my-user/my-app --type scaffold --scaffoldType app --features linting testing demoing building --typescript true --scaffoldFilesFor testing demoing building --tagName my-app --writeToDisk true --installDependencies npm
```

**Comment by LarsDenBakker** [comment]
I'm not able to reproduce this error. We don't install or use `yeoman-generator`. After running the generator, did you `cd` into the `my-app` directory?

**Comment by Alos** [comment]
```
After running the generator, did you cd into the my-app directory?
```
Yes I did. 

I tried, updating the local version of `yeoman-generator` clean and install and got the same error. I uninstalled `yeoman-generator` and tried creating a new app, same error.

**Comment by Alos** [comment]
For some reason the `node_modules` in my home directory contains a version of `@types` that has the `yeoman-generator`.  I'm not sure why the application would pull the dependencies from there tho.

¯\(°_o)/¯
