### ISSUE TITLE
[docs] 404 page regression 

### ISSUE THREAD

**Issue by danielmatthew** [open-wc/open-wc#1998]
## Expected behavior
Visit https://open-wc.org/testing/ and get a functioning 404 

## Actual Behavior
Visited https://open-wc.org/testing/ and got a 404 page. The 404 looks like this:

<img width="1728" alt="Screenshot of the broken 404 page" src="https://user-images.githubusercontent.com/111794/100447307-40848e00-30a8-11eb-94ce-2ad3f5b4240b.png">

…with huge SVG icons because the correct CSS is not being applied

Describe what happens instead.

References to scripts and styles return a 404 themselves:

<img width="1210" alt="Screenshot 2020-11-27 at 11 58 46" src="https://user-images.githubusercontent.com/111794/100447445-804b7580-30a8-11eb-98b7-067e284d0a52.png">

## Additional context

N/A

**Comment by thepassle** [comment]
Thanks for reporting!

I took a look, and... Im not sure why this is happening. I opened an issue with the folks at workbox, tracked here: https://github.com/GoogleChrome/workbox/issues/2682
