### ISSUE TITLE
[dev-server-hmr]: handle mixed type imports

### ISSUE THREAD

**Issue by bennypowers** [open-wc/open-wc#2000]
## Source

```ts
import {
  customElement,
  html,
  query,
  internalProperty,
  queryAll,
  eventOptions,
  TemplateResult,
  PropertyValues,
} from 'lit-element';
```

<details>

<summary>Config</summary>

```js
import dotenv from 'dotenv';
dotenv.config();
import { hmrPlugin, presets } from '@open-wc/dev-server-hmr';
import { fromRollup } from '@web/dev-server-rollup';

import _commonjs from '@rollup/plugin-commonjs';
import _replace from '@rollup/plugin-replace';
import _litcss from 'rollup-plugin-lit-css';
import _graphql from '@apollo-elements/rollup-plugin-graphql';
import _json from '@rollup/plugin-json';

const litcss = fromRollup(_litcss);
const json = fromRollup(_json);
const graphql = fromRollup(_graphql);
const commonjs = fromRollup(_commonjs);
const replace = fromRollup(_replace);


const excludeCSS = [
  'src/styles.css',
  '**/node_modules/leaflet/dist/leaflet.css',
  '**/node_modules/@power-elements/package-info/*.css',
];

const cjsIncludes = [
  '**/node_modules/**/*.cjs.js',
  '**/node_modules/**/*.cjs',
  '**/node_modules/bind-decorator/**/*',
  '**/node_modules/fast-json-stable-stringify/index.js',
  '**/graphql-tag/**/*',
  '**/node_modules/zen-observable/**/*',
];

import proxy from 'koa-proxies';

/** @type {typeof presets.litElement} */
const litApolloPreset = {
  decorators: [
    { name: 'customElement', import: '@apollo-elements/lit-apollo' },
  ],
  baseClasses: [
    { name: 'ApolloQuery', import: '@apollo-elements/lit-apollo' },
    { name: 'ApolloMutation', import: '@apollo-elements/lit-apollo' },
    { name: 'ApolloSubscription', import: '@apollo-elements/lit-apollo' },
  ],
};

const hmrIncludes = [
  'src/**/*.{js,json,graphql,css,html,svg}',
];

/** @type {import('@web/dev-server').DevServerConfig} */
const config = {
  nodeResolve: true,
  appIndex: 'index.html',
  port: 8000,
  rootDir: '.',
  mimeTypes: {
    'src/styles.css': 'css',
    'src/**/*.json': 'js',
    'src/**/*.css': 'js',
    'src/**/*.graphql': 'js',
  },
  middleware: [
    proxy('/files/', {
      target: 'https://dev.neuerenergy.com/api/v1/',
      changeOrigin: true,
      logs: true,
    }),
    proxy('/screenshot/', {
      target: 'http://localhost:7071/',
      changeOrigin: true,
      logs: true,
    }),
    proxy('/graphql/', {
      target: 'http://localhost:7071/',
      changeOrigin: true,
      logs: true,
    }),
  ],
  plugins: [
    litcss({ exclude: excludeCSS }),
    json({ exclude: ['/custom-elements.json', '/licenses.json'] }),
    graphql(),
    replace(REPLACEMENTS),
    hmrPlugin({ include: hmrIncludes, presets: [presets.litElement, litApolloPreset] }),
    commonjs({ include: cjsIncludes }),
  ],
};

export default config;
```

</details>

## Expected behavior

File loads

## Actual Behavior

browser console error:
> GET http://localhost:8000/src/components/sites/add-site/location/site-location.js [HTTP/1.1 500 Internal Server Error 87ms]

server terminal output:

>   TypeError: path/to/src/components/sites/add-site/location/site-location.js: Property body[0] of BlockStatement expected node to be of a type ["Statement"] but instead got "File"
      at validate (path/to/node_modules/@babel/core/node_modules/@babel/types/lib/definitions/utils.js:132:11)
      at validator (path/to/node_modules/@babel/core/node_modules/@babel/types/lib/definitions/utils.js:103:7)
      at Object.validate (path/to/node_modules/@babel/core/node_modules/@babel/types/lib/definitions/utils.js:229:7)
      at validateField (path/to/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:24:9)
      at validate (path/to/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:17:3)
      at builder (path/to/node_modules/@babel/core/node_modules/@babel/types/lib/builders/builder.js:38:27)
      at Object.blockStatement (path/to/node_modules/@babel/core/node_modules/@babel/types/lib/builders/generated/index.js:282:31)
      at NodePath.replaceExpressionWithStatements (path/to/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/replacement.js:197:53)
      at NodePath.insertBefore (path/to/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/modification.js:43:17)
      at injectRegisterClass (path/to/node_modules/@open-wc/dev-server-hmr/src/babel/inject.js:20:14)

## Additional context

```json
{
    "@web/dev-server": "0.0.25",
    "@open-wc/dev-server-hmr": "0.0.4",
}
```

### 👉  WORKING SOURCE
```ts
import type { TemplateResult, PropertyValues } from 'lit-element';
import {
  customElement,
  html,
  query,
  internalProperty,
  queryAll,
  eventOptions,
} from 'lit-element';
```

**Comment by LarsDenBakker** [comment]
@bennypowers do you know what this compiles to? We only get to see the compiled output, so I need to know what will be passed to the plugin

**Comment by LarsDenBakker** [comment]
I wonder if this is fixed byhttps://github.com/open-wc/open-wc/pull/2003

**Comment by bennypowers** [comment]
Looks like. Will reopen if needed.
