### ISSUE TITLE
Automatically load global css file

### ISSUE THREAD

**Issue by lazylazyllama** [open-wc/open-wc#201]
I just tried to use this library to build a simple website with some components, css and images.
But for me it is very important to have a additional general css file for some general layout purposes.
But I couldn't figure out how to put this file into the dist folder and also hashing its name to prevent cache issues.

So I would really like this library to have something like:
`indexCSS: path.resolve(__dirname, './src/index.css'),`
so that we can set up some general stuff like css-variables that are used by some components and so on.

**Comment by daKmoR** [comment]
interesting idea 🤗 

just to clarify using a `<style>` tag inside the `index.html` is not good enough in that case I assume?
also using a "static" `<link rel="stylesheet" href="foo.css">` is too cumbersome as we want cache busting...

I guess we could cook something up :) @LarsDenBakker any ideas?

**Comment by lazylazyllama** [comment]
Yeah using <style> inside the index.html is pretty much, what I do right now to work around it, but I would prefer to have a separate css file. :)

**Comment by LarsDenBakker** [comment]
We need to add a load for the HTMLWebpackPlugin, this will automatically detect any static assets added in your index.html and hash them for caching.

**Comment by lazylazyllama** [comment]
That would be perfect 😍

**Comment by LarsDenBakker** [comment]
For referenence we now have updated updated docs which show how to copy over static files.
