### ISSUE TITLE
Unable to attach two oneEvent handlers to the same target

### ISSUE THREAD

**Issue by michaelwarren1106** [open-wc/open-wc#2016]
## Expected behavior

Consider the following code:

```js
let myFixture;
let eventOne;
let eventTwo;

beforeEach(() => {
   myFixture = await fixture('<div></div>') // container element
  const myCustomEl = document.createElement('my-custom-element'); // element that emits two events on connectedCallback
   
   const eventOneListener = oneEvent(myCustomEl, 'myCustomEventName1');
   const eventTwoListener = oneEvent(myCustomEl, 'myCustomEventName2');

   myFixture.appendChild(myCustomEl);

   eventOne = await eventOneListener;
   eventTwo = await eventTwoListener;
})


it('should fire at least one of the event handlers', () => {
   expect(eventOne.target).toBeTruthy();
})
```

I would expect that the `resolve` function in both event listeners is fired correctly with the event contents

## Actual Behavior

NEITHER oneEvent handler's `resolve` function actually resolves, so expects on either  `eventOne` or `eventTwo` BOTH fail.

## Additional context

@open-wc/testing-helpers, lit-element (custom elements), jest for testing

if I only declare one listener for one event at a time, the resolves fire normally and the expects are successful as expected.

**Comment by michaelwarren1106** [comment]
I took a look at the code for `oneEvent` and I don’t see anything obvious in the definition, I just know that for some reason the resolve never gets fired. 

I wonder if it could somehow be related to jest? I haven’t tested this is a non-jest env, so that’s about the only thing I could imagine to prevent multiple event listeners

**Comment by michaelwarren1106** [comment]
so, as expected, something must be iffy in my testing setup.

I made this pen: https://codepen.io/michaelwarren1106/pen/oNzpjbN

and that totally proves that with a minimal setup, the `oneEvent` listeners working fine on the same element with two different events.

The only differences really between my setup and the pen are:
- the pen is jest-lite, my setup is full jest with jest-dom 16 for shadow dom support
- my fixtures are lit-element web components instead of divs
- my source code is Typescript.

So now I'm really stumped because when I try basically this same setup on my lit-element components, I always get nodejs async 5000ms timeout errors and the tests stop running.

Can anyone think of anything that might contribute? maybe jest-dom 16 somehow?

**Comment by jimmy-collazos** [comment]
In your example code; When dispatch events? after connected callback?
check the `await` instruction and event dispatchers.

**Comment by michaelwarren1106** [comment]
in my real code, and in the example, the events are dispatched in the  `connectedCallback` of the web component i'm testing. In my real code, i can verify that each event fires successfully if i only attach a single listener, but neither fire if i attach two.
