### ISSUE TITLE
[semantic-dom-diff] Option to normalize adjacent textNodes when separated by comment

### ISSUE THREAD

**Issue by kevinpschaaf** [open-wc/open-wc#2017]
## Expected behavior
Two adjacent textNodes separated only by a comment can be (optionally, if needed) treated as non-semantic.

## Actual Behavior
Currently comments are excluded from the treewalk that generates the diffable HTML, however if two adjacent textNodes are separated by a comment, this is treated as a semantic difference and are printed on separate lines.

Example:
```js
const div = document.createElement('div');
div.innerHTML = `<span>Hello, <!--ignore-me-->world!</span>`;
assert.lightDom.equal(div, `<span>Hello, world!</span>`);
```
```
      + expected - actual
      
       <span>
      -  Hello,
      -  World!
      +  Hello, World!
       </span>
```

## Additional context

Package: `@open-wc/semantic-dom-diff`

**Comment by kevinpschaaf** [comment]
There are cases in `lit-html` where we (need to) leave comment markers around `textNodes` to identify part boundaries, and it can get tedious to treat those as semantic.

**Comment by LarsDenBakker** [comment]
I think we should always merge adjacent text nodes. Since we're filtering out the comments, I don't think you could practically even assert that they are two different text nodes right now.

**Comment by kevinpschaaf** [comment]
Awesome, thank you gentlemen!
