### ISSUE TITLE
[testing-helpers] fixture does not wait for updateComplete and componentOnReady()

### ISSUE THREAD

**Issue by Lodin** [open-wc/open-wc#202]
For now asynchronous `fixture` does not wait for `updateComplete` and `componentOnReady()` despite it is described in the [documentation](https://open-wc.org/testing/testing-helpers.html#timings).

After some investigation I found an issue: it happens because `fixture` and `fixtureSync` use synchronous variants of nested fixtures, `litFixtureSync` and `stringFixtureSync`. 

I'm going to create a PR that will fix this issue.

**Comment by daKmoR** [comment]
fixed in latest release 💪
