### ISSUE TITLE
SpaConfig Dev Mode

### ISSUE THREAD

**Issue by madeInLagny** [open-wc/open-wc#2055]
## Expected behavior

Roll up is configured with devMode on.

```
const baseConfig = createSpaConfig({
  // development mode creates a non-minified build for debugging or development
  developmentMode: process.env.ROLLUP_WATCH === 'true',

```

## Actual Behavior

Build outputs minified js files.

![image](https://user-images.githubusercontent.com/54598963/105068495-4b90e480-5a81-11eb-8c5a-014b5dee3008.png)

## Expected behaviour

Comments say that 'development mode creates a non-minified build for debugging or development'

**Comment by Westbrook** [comment]
How are you calling Rollup here? You need to make sure that you actually set the env var here, `ROLLUP_WATCH=true`. I’m not sure that any of our generators call it this way be default.

**Comment by madeInLagny** [comment]
Hi @Westbrook
this is my rollup config:

`import merge from 'deepmerge';
import { createSpaConfig } from '@open-wc/building-rollup';
import copy from 'rollup-plugin-copy';
import replace from '@rollup/plugin-replace';
import dynamicImportVars from '@rollup/plugin-dynamic-import-vars';

const baseConfig = createSpaConfig({
  // development mode creates a non-minified build for debugging or development
  developmentMode: process.env.ROLLUP_WATCH === 'true',

  workbox: {
    skipWaiting: false,
    clientsClaim: false,
    runtimeCaching: [
      {
        urlPattern: new RegExp('^https://firebasestorage\\.googleapis\\.com/'),
        handler: 'StaleWhileRevalidate',
        options: {
          cacheableResponse: {
            statuses: [0, 200],
          },
        },
      },
    ],
  },
  injectServiceWorker: true,
});

export default merge(baseConfig, {
  input: './index.html',

  plugins: [
    replace({
      __version__: `${
        new Date().getFullYear() +
        (new Date().getMonth() + 1).toString().padStart(2, '0') +
        new Date().getDate().toString().padStart(2, '0')
      }-${new Date()
        .getHours()
        .toString()
        .padStart(2, '0')}${new Date()
        .getMinutes()
        .toString()
        .padStart(2, '0')}`,
      __dev__: 'prod',
    }),
    dynamicImportVars({
      exclude: 'views/template-page/template-page.js',
    }),
    copy({
      targets: [
        {
          src: 'assets/**/*.jpg',
          dest: 'dist/assets',
        },
        {
          src: 'assets/**/*.png',
          dest: 'dist/assets',
        },
        {
          src: 'assets/**/*.ico',
          dest: 'dist/assets',
        },
        {
          // copy manifest.webmanifest
          src: 'manifest.json',
          dest: 'dist',
        },
        {
          src: 'IEImage.png',
          dest: 'dist',
        },
        {
          src: 'IE.html',
          dest: 'dist',
        },
        {
          src: 'assets/locales/**/*.js',
          dest: 'dist/assets/locales',
        },
      ],
      hook: 'buildStart',
      flatten: false,
    }),
  ],
});
`

I am calling rollup using the open-wc recommended method:

npm script
`
"build": "rimraf dist && rollup -c rollup.config.js",
"start:build": "npm run build && web-dev-server --root-dir dist --app-index index.html --open --compatibility none",
`

Where should I set the ROLLUP_WATCH variable ?
