### ISSUE TITLE
Use regex which works on unix and windows systems

### ISSUE THREAD

**Issue by igomezal** [open-wc/open-wc#209]
Until https://github.com/storybooks/storybook/issues/5531 is solved, open-wc:scaffold-vanilla could use the following webpack configuration to be able to use storybook in unix and windows systems:

```
module.exports = (baseConfig, env, config) => {
  config.module.rules[0].exclude = /node_modules\/(?!(lit-html|@polymer|lit-element)\/).*/;
  return config;
};
```

**Comment by daKmoR** [comment]
thx for the issue - `@open-wc/storybook` has been replaced by `@open-wc/demoing-storybook`  and in it's latest version it uses something like this - so it should support unix and windows 👍 

PS: feel free to reopen/create a new issue if I'm not correct 🙈
