### ISSUE TITLE
How to test a mousedown event

### ISSUE THREAD

**Issue by genderev** [open-wc/open-wc#2096]
I am trying to rewrite this simple test from the starter project:

```
  it('increases the counter on button click', async () => {
    const el = await fixture(html`<custom-element></custom-element>`);
    el.shadowRoot.querySelector('button').click();

    expect(el.counter).to.equal(6);
  });
```

 but I am not sure how to rewrite it for a mousedown event. I changed `.click()` to `.mousedown()` but `.mousedown()` is not a valid event. What are the valid events besides `.click()`, `triggerFocusFor(el)`, and `triggerBlurFor(el)`? 

(I could not figure out how to use [oneEvent](https://open-wc.org/docs/testing/helpers/#testing-events), although I tried, and received errors from my terminal there also.)

**Comment by bennypowers** [comment]
```js
el.shadowRoot.querySelector('button').dispatchEvent(new Event("mousedown"))
```

this doesn't accurately simulate an actual mousedown though

**Comment by daKmoR** [comment]
there are some discussions to actually support a "real" mouse click by the browser
https://github.com/modernweb-dev/web/issues/1289

**Comment by Westbrook** [comment]
We’ve moved the conversation around “real” mouse inputs to https://github.com/modernweb-dev/web/discussions/1397 would appreciate your thoughts on the API design/usage.
