### ISSUE TITLE
Allow configuring Workbox to bypass cached fallback for configured path regex

### ISSUE THREAD

**Issue by lpellegr** [open-wc/open-wc#2101]
It's most probably not a feature request but since I am quite lost about how to configure workbox using open-wc I am opening this issue.

To summarize, I have an open-wc app deployed on Firebase Hosting. The app is bundled and packaged by open-wc with the `injectServiceWorker` and `workbox` options set to `true`. That is working very well. 

The issue I experience is related to Firebase and its reserved URLs. By default, the open-wc app seems to have a "navigation fallback" that renders a specific URL if it doesn't match a list of precached items.

As an example, I have an open-wc project deployed on a Firebase domain (fake URL): 
https://my-app.firebaseapp.com/. 

Firebase reserves the following URL to act upon authentication:
https://my-app.firebaseapp.com/__/auth/action

If you open https://my-app.firebaseapp.com, then the open-wc service-worker is activated and when you are redirected to https://my-app.firebaseapp.com/__/auth/action (upon sign-in for instance), then your app fallback page is served by the service-worker instead of invoking the Firebase action.

What I would like is to tell workbox to perform the normal request to the resources `/__/auth/*`. 

Firebase describes a solution but for the deprecated sw-precache library:
https://firebase.google.com/docs/hosting/reserved-urls

Looking at the workbox documentation, it seems there is a `navigateFallbackWhitelist` or `navigateFallbackAllowlist` option but I cannot figure out how to pass it with open-wc:
https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v4#navigation_route_changes

I tried the following "random" configuration but obviously this is not working:

```
const baseConfig = createSpaConfig({
  developmentMode: process.env.ROLLUP_WATCH === 'true',
  injectServiceWorker: true,
  legacyBuild: false,
  outputDir: 'dist',
  workbox: {
    clientsClaim: false,
    navigateFallbackAllowlist: [/^(?!\/__).*/],
    navigateFallbackWhitelist: [/^(?!\/__).*/],
    skipWaiting: false
  }
}) 
```

Is there a way to tell to workbox to perform the normal requests for the reserved URLs?

**Comment by thepassle** [comment]
You can override the default config exactly like youre doing, and any properties you add will be merged with or overwrite the default workbox configuration.

Our configuration uses `rollup-plugin-workbox` v5, which in turn uses `workbox-build` v5, so `navigateFallbackAllowlist` should work. Im not entirely sure why that option doesnt work, but this seems like an issue with workbox.

**Comment by lpellegr** [comment]
Thanks a lot for your answer. 

The configuration was not working because I specified `navigateFallbackWhitelist` that isn't a supported property. In that case, open-wc was building with no errors but the service worker file was not generated.  Using  `navigateFallbackAllowlist`, the generated service worker is working as expected.
