### ISSUE TITLE
ArgsTable in MDX not showing in Storybook

### ISSUE THREAD

**Issue by hasanirogers** [open-wc/open-wc#2102]
## Expected behavior

A table of properties to appear.

## Actual Behavior

An error saying "No inputs found for this component. Read the docs" appears.

## Additional context

I'm not sure if this is a problem with Storybook itself or the Storybook Plugin/Config for Web Dev Server. I've been trying to get Storybook to work with ArgsTable in MDX to no avail. Here's my index.stories.mdx file:

```
import { Meta, Story, Canvas, ArgsTable, Source } from '@storybook/addon-docs/blocks';
import { html } from 'lit-html';

import '../standard-element.js';


<Meta
  title="Standard Element (MDX)"
  component="standard-element"
  argTypes={{
    title: { control: 'text' },
    counter: { control: 'number' },
    textColor: { control: 'color' },
  }}
/>

export const Template = ({ title = 'Hello world', counter = 5, textColor, slot }) => {
  return html`
    <standard-element
      style="--standard-element-text-color: ${textColor || 'black'}"
      .title=${title}
      .counter=${counter}
    >
      ${slot}
    </standard-element>
  `;
}

## Stories
<Canvas>
  <Story
    name="Custom Stuff"
    args={{
      title: 'Custom Title: ',
      counter: 20,
    }}
  >
    {Template.bind({})}
  </Story>
  <Source
    language='html'
    code={`<standard-element title="Title goes here:">
  some more light-dom
</standard-element>`}
  />
</Canvas>


## API

<ArgsTable of="standard-element" />
```

`standard-element` is just an element generated by the open-wc generator without any changes. Can someone provide me some direction here? I've read the docs at Storybook but their documentation for web components are lacking imo. Not sure if I'm doing something wrong or if this is indeed a bug.

**Comment by LarsDenBakker** [comment]
You need to import it from the prebuilt storybook we use: `import { Meta, Story, Canvas, ArgsTable } from '@web/storybook-prebuilt/addon-docs/blocks.js';`. https://modern-web.dev/docs/dev-server/plugins/storybook/#docs

Can you try with that?
