### ISSUE TITLE
Could not resolve import "fs"

### ISSUE THREAD

**Issue by knuspertante** [open-wc/open-wc#2106]
Hey guys, 

currently I want to try aws amplify with open-wc template. 

I several errors, that some modules could not be resolve. 

- Error while transforming node_modules/@aws-sdk/util-body-length-node/dist/es/index.js: Could not resolve import "fs".
- Error while transforming node_modules/@aws-sdk/hash-node/dist/es/index.js: Could not resolve import "crypto".
- Error while transforming node_modules/@aws-sdk/util-user-agent-node/dist/es/index.js: Could not resolve import "os".

My aws-sdk comes with aws-amplify package. 

Node Version: 14.16.0

I tried to use in web-dev-server.config.mjs (as in this issue mentioned: https://github.com/open-wc/open-wc/issues/1534)
```
nodeResolve: {
  exportConditions: ['browser', 'development']
}
```

Or is it babel to blame? (as in this issue mentioned: https://github.com/aws-amplify/amplify-js/issues/1560)
As so, how can I fix this?

THX

**Comment by mrBaas** [comment]
Did you solve this issue?

**Comment by knuspertante** [comment]
Unfortunately no. 

I switched to use vite now. 

This issue could be closed or must be verified, that the error is still there.
