### ISSUE TITLE
ScopedElementsMixin prevents nested svg string template usage

### ISSUE THREAD

**Issue by barroudjo** [open-wc/open-wc#2112]
## Expected behavior
This should display a black circle: 
```javascript
class TestingSvg extends ScopedElementsMixin(LitElement) {
  render() {
    return html`
      <div>coucou</div>
      <svg
    width="200px"
    viewBox="0 0 200 200"
    version="1.1" xmlns="http://www.w3.org/2000/svg"
  >
    ${svg`<circle cx="50" cy="50" r="50"></circle>`}
  </svg>
    `;
  }
}

window.customElements.define('testing-svg', TestingSvg);
render(html`
  <testing-svg></testing-svg>
`, document.body);
```

## Actual Behavior

But it does not. And removing the use of `ScopedElementsMixin` fixes the problem.

## Additional context
There are no errors logged in the console. The svg is correctly inserted in the DOM, it just doesn't show.
The issue is present both on chrome and firefox.
Here is a stackblitz to reproduce the issue: https://stackblitz.com/edit/lit-html-xsno6v?file=src/index.js
Dependencies:
```json
{
    "@open-wc/scoped-elements": "^1.3.3",
    "lit-element": "^2.4.0",
    "lit-html": "^1.3.0"
  }
```

**Comment by manolakis** [comment]
Thanks for the issue @barroudjo 

I'll take a look into it.

**Comment by barroudjo** [comment]
Cool. I'm very curious to see what is the problem here.

**Comment by manolakis** [comment]
Hello @barroudjo,

Not sure why, but I saw that with scoped element mixin the svg is not executed as a `SVGTemplateResult` but a `TemplateResult`. That's the main problem.

I'm pretty sure it should work with `ScopedElementsMixin` version 2 as we delegate the scoping to the scoped registry polyfill, making the mixin a simpler way to declare components in a custom registry.

I'll try to find te cause of the issue as I'm curious about it.

**Comment by barroudjo** [comment]
Good to know @manolakis ! So do you know if the issue is solved ?

**Comment by manolakis** [comment]
The issue is solved in scoped elements v2.

**Comment by manolakis** [comment]
I just sent a fix for scoped-elements v1

**Comment by daKmoR** [comment]
judging from the discussion I assume this issue has been resolved.

will close for now - feel free to reopen if the issue persists 🤗
