### ISSUE TITLE
Unable to import Koa middleware

### ISSUE THREAD

**Issue by tkdphoenix** [open-wc/open-wc#2114]
I have delayed making this request in the hopes that my company would allow the Koa dependency into our network. I don't want to be a community member who says, "fix my issue even though there may only be 3 people who have this problem." However, I have been waiting for over 9 months for my company to allow this simple middleware which is a part of the @open-wc Storybook implementation as well as Karma. I desperately need to use Storybook and the @open-wc implementation uses Koa, which has security vulnerabilities, which admittedly are not really their issue. They have a closed ticket where they talk about the issue, and the supposed vulnerability. The problem that is explained is that they allow cross site scripting (XSS). They rightly state that handling of XSS is not the job of middleware but should be handled by the server and the development team in their code.

This aside, the package has been marked as a security risk for quite some time, and I can't seem to get around it. I am currently working on implementing Webpack or Snowpack with Storybook but Storybook's recent blog post about allowing Snowpack and Webpack 5 offers an example script that utilizes @open-wc/demoing-storybook which uses Koa. I am walking in circles, and would love to have some sort of implementation where we can add a flag to use the pre-configuration that @open-wc has worked so hard on, but doesn't require Koa, such as "--no-koa".

**Comment by LarsDenBakker** [comment]
Unfortunately it won't be possible to not use Koa, it is a core dependency of web dev server.
