### ISSUE TITLE
Storybook "No code available"

### ISSUE THREAD

**Issue by ElodiePayot** [open-wc/open-wc#2126]
## Expected behavior

When using npm init @open-wc and then npm run storybook, in the "Docs" tab of storybook we are supposed to see the "Show code" button and it should show the component code.

## Actual Behavior

Instead, I'm having a disabled button saying "No code available".
I encounter this issue on the basic starter projet when using npm init @open-wc (without changing anything) and also in my own project.

## Additional context
steps to install the project and reproduce the issue:

npm init @open-wc > Scaffold new project > Application > Linting + testing + demoing + building > No typescript > Testing + demoing + building > dependencies installed with npm

npm run storybook

Click on the "Docs" panel and see the "No code available"

**Comment by LarsDenBakker** [comment]
This is a known issue with `@web/dev-server-storybook`. We need to dig into what's causing this.

**Comment by ElodiePayot** [comment]
Ok, thank you for the answer!

**Comment by Westbrook** [comment]
Not stale, per say. @bennypowers is about to solve this at the Storybook level 🤞🏼

**Comment by bennypowers** [comment]
See https://github.com/storybookjs/storybook/pull/15337

**Comment by noelklein** [comment]
Is a solution available for the prebuilt storybook version now?

**Comment by bennypowers** [comment]
@Westbrook @noelklein  is this still relevant?

**Comment by noelklein** [comment]
@bennypowers I tried a newer version of this library and the `show code` button works there. Thanks, issue is resolved for me.

**Comment by bennypowers** [comment]
Glad to hear it
