### ISSUE TITLE
Manual install documentation

### ISSUE THREAD

**Issue by anoblet** [open-wc/open-wc#214]
I'll create a pull request for this tomorrow, but the automating tests section of /testing tells us to copy `karma.config.js` and then reference all of the package testing scripts. Those scripts reference configs which will not have been copied. I feel we should tell the user to either copy all of the configs, or not specify all of the test scripts at this point. It's more of a grammar issue than anything

**Comment by daKmoR** [comment]
thx for PR 🤗  merged via https://github.com/open-wc/open-wc/pull/222
