### ISSUE TITLE
[scoped-elements] 2.0: included polyfill has side effects but is not marked as such

### ISSUE THREAD

**Issue by lazka** [open-wc/open-wc#2156]
Here is a minimal reproducer: https://github.com/lazka/scoped-test-v2

Expected behavior:

There is no javascript error and the web components render.

Actual behavior: 

```
Uncaught TypeError: Illegal constructor.
    createRenderRoot ScopedElementsMixin.js:98
    connectedCallback reactive-element.js:6
    connectedCallback lit-element.js:6
    <anonymous> demo.js:32
ScopedElementsMixin.js:98:24
```

Passing `--no-treeshake` to rollup makes it work. I don't know if this is a rollup bug..

**Comment by lazka** [comment]
Ah, the package has `"sideEffects": false` set so bundlers throw out the unused import. Changing it to `"sideEffects": ["./src/loadPolyfill.js"]` makes it work.

@manolakis ^

**Comment by manolakis** [comment]
Thanks @lazka.

I'm going to create a PR including the side effect.

**Comment by lazka** [comment]
Thanks!
