### ISSUE TITLE
[scoped-elements] 2.0: getScopedTagName() change not ideal for porting

### ISSUE THREAD

**Issue by lazka** [open-wc/open-wc#2157]
With 1.x:

```js
this.getScopedTagName('my-internal-tag') -> 'my-internal-tag-1234'
```

With 2.x

```js
this.getScopedTagName('my-internal-tag') -> 'my-parent-tag'
```

getScopedTagName() is still there but does something completely different, it returns the tag name of the current element instead of the passed in name.

Suggestions:

* return the name that was passed in. (is there a way to validate it somehow?)
* remove the method so it's clear that this needs attention when porting

@manolakis

**Comment by LarsDenBakker** [comment]
The current logic is unexpected indeed. We should return the tag that was passed in.

**Comment by manolakis** [comment]
ouch :( Fixing it.

**Comment by lazka** [comment]
Thanks! works nicely now
