### ISSUE TITLE
[Doc] List all internal packages + npm versions in main README

### ISSUE THREAD

**Issue by vogloblinsky** [open-wc/open-wc#217]
Is it possible to list all internal packages + their npm versions with a badge in a table ?

Can submit a PR if you want.

**Comment by daKmoR** [comment]
good idea :) looking forward to a PR :)

I think if we use an npm badges the should always show the latest version right? I just want to avoid the need to manually update the version number 😀🙏

**Comment by vogloblinsky** [comment]
Result visible here : https://github.com/vogloblinsky/open-wc/tree/main-readme-list-internal-packages-badges
