### ISSUE TITLE
[scoped-elements] 2.0: defineScopedElement() sometimes doesn't work

### ISSUE THREAD

**Issue by lazka** [open-wc/open-wc#2172]
See https://github.com/lazka/scoped-test-v2/blob/main/demo.js for a minimal example.

The `SomethingDifferent` component isn't visible iff it is registered globally first and defineScopedElement() is called after the first update.

Two things:

* Removing the first `customElements.define` fixes things
* Calling `this.defineScopedElement` earlier fixes things as well

**Comment by manolakis** [comment]
Seems to be a problem in the polyfill. We should open an issue in https://github.com/webcomponents/polyfills

**Comment by manolakis** [comment]
I opened this issue https://github.com/webcomponents/polyfills/issues/442 adding your comments and example.

I'm going to close this issue.

**Comment by lazka** [comment]
@manolakis fyi, https://www.npmjs.com/package/@webcomponents/scoped-custom-element-registry has a new release now :)

**Comment by manolakis** [comment]
https://github.com/open-wc/open-wc/pull/2224
