### ISSUE TITLE
[building] consider rollup

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#221]
I'd like to look into a rollup based default config. I think we need to have measurable benefits from using rollup VS webpack, and give different recommendations for different scenarios.

I'd like to open a discussion in this issue about this.

Some areas I am interested in:

**Module output**
This is one of the obvious benefits, but how practical is it? Not all browsers which support modules, support dynamic imports. How do you make sure you distribute the right code?

**Code optimization**
Focusing on es-modules has the potential for better tree shaking, dead code elimination and minification (inlining variables etc) because it's easier for the bundler to take certain assumptions. I'd like to see if this can be measured objectively.

**Code splitting**
One thing that webpack does very well is code splitting. It is more complicated than it seems, as shared dependencies between lazy loaded chunks creates quite some coordination demands on the bundler. I'm interested in seeing how rollup stacks up against webpack in this area.

**Build tasks**
For larger apps building is more than just compiling the JS. Static assets need to be moved around, environment variables need to be set etc. How well does rollup handle these things?

**Caching**
Webpack handles caching, both short and long-term. For .js but also other assets like css and pngs. How does rollup handle this?

Does anyone have any insights in this area?

**Comment by bennypowers** [comment]
> Module Output
Rollup can output es, IIFE, cjs, amd, system, umd. you're covered

> Code Splitting
Landed stable in Rollup 1.0. I use it in my apps, and developed `rollup-plugin-modulepreload` to help devs automatically preload chunks based on a predefined or  custom predicate

> Build Tasks
There are lots of plugins for this like `rollup-plugin-cpy`. npm scripts are also good for this

**Comment by bennypowers** [comment]
I like rollup's plugin-based architecture.
I like rollup's focus on browser standards rather than kitchen-sinking.
I like the quality of rollup's generated code.
