### ISSUE TITLE
[scoped-elements] - incompatible with JSDOM 

### ISSUE THREAD

**Issue by riovir** [open-wc/open-wc#2221]
## Expected behavior

Allow apps tested with JSDOM (usually via Jest) to still work as they did with the original hashed tag solution.

## Actual Behavior

As the `window.customElements` gets swapped out, the JSDOM internals can no longer can find bookkeeping data such as `_customElementDefinitions`. 

## Additional context

This use case affects applications written with traditional frameworks (such as Vue, or React) that rely on a Design System / component pack built with webcomponents. Up until recently, the low level components of these apps could simply be tested with Jest (using JSDOM). Since components, such as [Lion Components](https://github.com/ing-bank/lion/releases/tag/%40lion%2Fcore%400.18.0) updated to v2, Jest tested applications are now breaking if they update.

Here is the stack trace after the registry has been swapped out:

```bash
TypeError: Cannot read property '_customElementDefinitions' of undefined

      at lookupCEDefinition (node_modules/jsdom/lib/jsdom/living/helpers/custom-elements.js:154:37)
      at JSDOMParse5Adapter.createElement (node_modules/jsdom/lib/jsdom/browser/parser/html.js:91:24)
      at Parser.parseFragment (node_modules/parse5/lib/parser/index.js:359:47)
      at Object.parseFragment (node_modules/parse5/lib/index.js:22:19)
      at parseFragment (node_modules/jsdom/lib/jsdom/browser/parser/html.js:207:17)
      at parseFragment (node_modules/jsdom/lib/jsdom/browser/parser/index.js:18:10)
      at HTMLBodyElementImpl.set innerHTML [as innerHTML] (node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:200:22)
      at HTMLBodyElement.call (node_modules/jsdom/lib/jsdom/living/generated/Element.js:1268:42)
      at HTMLBodyElement.set [as innerHTML] (node_modules/@open-wc/scoped-elements/src/loadPolyfill.js:346:24)
      at Window.close (node_modules/jsdom/lib/jsdom/browser/Window.js:763:39)
```

Note that even a workaround would be appreciated that would enable testing isolated components, that aren't sensitive to the scoping problem, to begin with.

**Comment by riovir** [comment]
Found a possible workaround by disabling the polyfill:

The scoped-elements polyfill is activated by checking if [ShadowRoot.prototype.createElement](https://github.com/open-wc/open-wc/blob/master/packages/scoped-elements/src/loadPolyfill.js#L7) exists. Jest allows manipulating the (JSDOM) browser environment before tests run via the `setupFiles` option. 

By taking the `document.createElement` and setting it on the ShadowRoot's prototype the polyfill is disabled. It's likely that there are multiple caveats with this approach, so it's not a suitable solution for an app that directly relies on the scoped elements. However, it may just work for those that wanted to sprinkle in some webcomponents into traditional frameworks tested via Jest.

**Comment by riovir** [comment]
Another, more involved workaround doesn't disable the polyfill, but rather tries to merge it with JSDOM's own one. Would still go in the setupFile

```
const originalCustomElements = window.customElements;
require('@open-wc/scoped-elements'); // Apply the polyfill
const scopedCustomElements = window.customElements;
window.customElements = originalCustomElements; // Restore the original JSDOM instance

// Swap out all the methods on the original customElements
classMethodsOf(scopedCustomElements)
		.forEach(overrideOn(originalCustomElements));

function classMethodsOf(instance) {
	const prototype = Object.getPrototypeOf(instance);
	const descriptors = Object.getOwnPropertyDescriptors(prototype);

	return Object.entries(descriptors)
			.filter(([/**/, { value }]) => typeof value === 'function')
			.map(entry => entry[0]);
}

function overrideOn(registry) {
	// some methods (currently only the define) checks the current registry agains the window.customElements
	// need to temporarily swap out the registry to make it work correctly, then back goes the original
	return prop => registry[prop] = (...args) => {
		window.customElements = scopedCustomElements;
		const result = scopedCustomElements[prop](...args);
		window.customElements = registry;
		return result;
	};
}
```

An honorable mention is the [@jest-runner/electron](https://www.npmjs.com/package/@jest-runner/electron), which however needs some extra work to run inside a CI pipeline as per its currently open issues.

**Comment by manolakis** [comment]
Hello @riovir,

`ScopedElementsMixin` is using polyfill provided by webcomponents project as we want the Mixin to work with the future standard of scoped registries.

I'm goign to close the issue because this is not a propblem related with the ScopedElementsMixin. 

IMHO this is a JSDom problem so I suggest to open an issue in JSDom project asking them to make their implementation compatible with the scoped registries polyfill.

Regards
