### ISSUE TITLE
[scoped-elements] Breaks css include order with Firefox

### ISSUE THREAD

**Issue by lazka** [open-wc/open-wc#2230]
Using `scoped-elements@2.0.0-next.4` and `lit@2.0.0-rc.2` on **Firefox only**:

```js
import {css, html, LitElement} from 'lit';
import {ScopedElementsMixin} from '@open-wc/scoped-elements';

class MyElement extends ScopedElementsMixin(LitElement) {
    static get styles() {
        return css`
        p {
            color: blue;
        }
        `;
    }

    render() {
        return html`
        <style>
            p {
            color: red;
            }
        </style>
        <p>This should be blue!</p>
        `;
    }
}

customElements.define('my-element', MyElement);
```

* Expected behavior: The text should be blue
* Actual behavior: The text is red

.

* This only happens if I use ScopedElementsMixin. Removing the mixin makes it work again.
* This worked correctly with old lit-element and scoped-elements

**Comment by lazka** [comment]
@manolakis

**Comment by manolakis** [comment]
Really extrange... I'll take a look into it but I'm thinking that probably it would be related with the polyfill 🤔

**Comment by lazka** [comment]
The main problem is I think, that because Firefox doesn't have adoptedStyleSheets the styles are written into the dom directly, and the order somehow is different now:

old lit-elements + scoped
```html
<!---->
<style>
    p {
    color: red;
    }
</style>
<p>This should be blue!</p>
<!----><style>
p {
    color: blue;
}
</style>
```

new lit + scoped + polyfill:

```html
<style>
p {
    color: blue;
}
</style><!---->
<style>
    p {
    color: red;
    }
</style>
<p>This should be blue!</p>
```

I hope this helps a bit.

**Comment by manolakis** [comment]
I think I know where is the problem but I don't have a clear solution right now. I'll work on it later

**Comment by lazka** [comment]
@stale

**Comment by lazka** [comment]
Progress here: #2232

(dummy comment to keep this open)
