### ISSUE TITLE
Function that exports emoji throws TypeError on npm run build

### ISSUE THREAD

**Issue by luis-pato** [open-wc/open-wc#2250]
I have used the open-wc project generator to create a project using lit (with `npm init @open-wc`).
Everything was woking great, until i created a function that returns a random emoji from an emojis array.
When i had this function on the component file, it worked well.
I moved this function to an extra file, where i export it, and now when i run `npm run start` i get a `TypeError: A.charCodeAt is not a function` Error.

## Expected behavior
I expected moving the  function to an extra file wouldn't break starting up the server

## Actual Behavior
After i moved the function to its own file and import it on my component i get a `TypeError: A.charCodeAt is not a function` Error:
![image](https://user-images.githubusercontent.com/42058106/126074761-6e74735b-d2e0-46b7-ba12-fcd41676bd0a.png)

## Additional context
this is the function i have on the `getRandomEmoji.js`file:
```js
export function getRandomEmoji() {
  const emojis = ['🚀', '📦', '🧪'];
  return emojis[Math.floor(Math.random() * emojis.length)];
}
```

i import it on my component like this:
```js
import { getRandomEmoji } from '../../helpers/getRandomEmoji.js';
````

and then i use it like this:
```js
<i class="stage__empty-emoji">${getRandomEmoji()}</i>
```

## Packages and dependencies
```json
"devDependencies": {
    "@open-wc/building-rollup": "^1.10.0",
    "@open-wc/eslint-config": "^4.3.0",
    "@open-wc/testing": "^2.5.33",
    "@web/dev-server": "^0.1.18",
    "@web/test-runner": "^0.12.20",
    "deepmerge": "^4.2.2",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^7.2.0",
    "husky": "^4.3.8",
    "lint-staged": "^10.5.4",
    "prettier": "^2.2.1",
    "rimraf": "^3.0.2",
    "rollup": "^2.53.0",
    "rollup-plugin-copy": "^3.4.0"
  }
```

and
```json
  "dependencies": {
    "lit": "*"
  }
```

## Things i have tried
If i change the emojis array into a strings array (for instance `const emojis = ['a', 'b', 'b'];`) then it works.
So i wonder if this is some kind of encoding problem, and if i can change something on the server config to fix the problem...?!

**Comment by daKmoR** [comment]
hmmm potentially an encoding problem in es module lexer... but yeah `@web/dev-server-core` uses quite an old version of https://github.com/guybedford/es-module-lexer...

maybe you can try the latest version of es module lexer? (hack it somehow - easiest is usually copying over the latest code in your node_modules)

if that works then a PR to update it in dev-server-core would be nice 🤗

**Comment by luis-pato** [comment]
good idea. i tried using the latest es-module-lexer (0.7.1), but i still get the same error on `npm run start`

**Comment by daKmoR** [comment]
maybe raise an issue with es module lexer? including a reproduction always helps 🤗

**Comment by luis-pato** [comment]
yes, i'll do that. thank you!
