### ISSUE TITLE
[Testing] Coverage Reporting

### ISSUE THREAD

**Issue by Westbrook** [open-wc/open-wc#226]
I'd like to suggest an update to the default reporting style from `text-summary` to `text`.

The following image outlines the output differences visually, but functionally the ability to see coverage by individual files along with the lines in those files that would benefit from further testing is very useful when you are looking to ensure a specific level of test coverage in your work.

![image](https://user-images.githubusercontent.com/1156657/52869502-c6be2300-3113-11e9-8efd-54c347641c90.png)

At current, the steps to alter a generated project to support this output requires either relying on the current `merge` technique available at https://github.com/open-wc/open-wc/blob/master/packages/generator-open-wc/generators/testing-karma/templates/static/karma.conf.js#L13 which would cause you to receive both versions of the report, or do something like:

```
  let customConfig = defaultSettings(config);
  customConfig.coverageIstanbulReporter.reports = ['html', 'lcovonly', 'text'];
  config.set(
    merge(customConfig, {
```
To hack the config before merging it with other local settings.

I could see a mix of alternate approaches to solving this:
- Not setting reporting by default
  - which would directly preface the need for the following
- Better config extension documentation
  - would be particularly useful if there are other things in the config that would benefit from being "replaced", but I've not seen it.
- A variant set of configs to alter the point of control in manage these settings (i.e. `default-settings`, `default-with-text`, `default-with-text-summery`, etc)
  - might lead to "if you give a mouse a cookie" syndrome, but could be externalized through community defaults if it became of interest at a larger scale

However, all of the alternate approach involve knowing a little more about usage that I'm not sure has happened at the scale necessary to support going down one of those paths at this time.

I think this fairly simple change would provide a good amount of benefit, and I'd be happy to supply a PR if the team agrees.

**Comment by daKmoR** [comment]
hey thx for reaching out 🤗 

I think it's totally fine to override specific settings if they make more sense in your case - and as it's just an object you can do in any way you prefer.

For setting the default config to `text` I am not sure if that works out... I know of projects that have like many many test files... any list with 50+ entries would probably be not useful 🙈 

We could, however, add a section explaining this and showing how to set it so so you get more details if it's useful for your codebase. Care to create a PR?

And/or if you want to see what files actually are covered and what not you probably should open the `coverage` folder within your browser instead?

**Comment by Westbrook** [comment]
Ha, for all the time I've been testing, and generating that or similar pages, I've never actually looked at the HTML report, I have no idea that it gave you so many things, especially highlighted code of what wasn't covered, etc! 😰 

To clarify, you think the right step is to document this sort of extension?
```
  let customConfig = defaultSettings(config);
  customConfig.coverageIstanbulReporter.reports = ['html', 'lcovonly', 'text'];
  config.set(
    merge(customConfig, {
```
Or, possibly just directing uses to the documentation of `webpack-merge`, which I've spent some time with since my first report that might support this goal via: https://github.com/survivejs/webpack-merge#mergestrategy-field-prependappendreplaceconfiguration-configuration

If I've misunderstood, please let me know and I'll start prepping a PR.

**Comment by Westbrook** [comment]
In my case the usage of a merge strategy with `webpack-merge` leaves me with code like:
```
merge.strategy(
      {
        'coverageIstanbulReporter.reports': 'replace',
      }
    )(defaultSettings(config), {
      files: [
        // allows running single tests with the --grep flag
        config.grep ? config.grep : 'test/**/*.test.js',
      ],

      // your custom config
      coverageIstanbulReporter: {
        reports: ['html', 'lcovonly', 'text']
      }
    })
```
A little verbose for my one change, but certainly a bit safer/more explicit were there to be others.

**Comment by daKmoR** [comment]
> I've never actually looked at the HTML report,

hihi yeah there is always stuff to learn 🤗 

I'm not sure if that is easier? config.set is also a merge but it overrides arrays... so that should have the same result... 
```js
module.exports = config => {
  config.set(
    merge(defaultSettings(config), {
      files: [
        // allows running single tests with the --grep flag
        config.grep ? config.grep : 'test/**/*.test.js',
      ],
    })
  );
  config.set({ 
      coverageIstanbulReporter: {
        reports: ['html', 'lcovonly', 'text']
      }
  });
}
```

but yeah setting a merge strategy also works... why feel easier more intuitive to you?

**Comment by Westbrook** [comment]
That's even nicer! I can add merge/replace docs using that pattern. What is actually structuring the `config` argument? Is that part of the `module.exports` process, or something else? I'd love to be able to link to documentation for that as part of this, just in case there are other special powers hidden in there that might help someone get tricky with their settings here.

**Comment by daKmoR** [comment]
config is the actual karma config class https://github.com/karma-runner/karma/blob/master/lib/config.js#L331

iirc using only config set however breaks webpack configs as they need to be "carefully" copied with keeping function in tact and such... that's why we use webpack-merge generally
