### ISSUE TITLE
[testing] how to catch an exception thrown from render?

### ISSUE THREAD

**Issue by DJCordhose** [open-wc/open-wc#228]
Say you have a component that throws when rendering, how do you catch the exception in the test? I seems it always bubbles up to the top and ends up being printed in the console. Any other way to react to it?

**Comment by DJCordhose** [comment]
here is an example for such a component

https://github.com/floreysoft/floreysoft-components/blob/master/packages/formsey-fields-native/test/StringField.spec.ts#L6

**Comment by daKmoR** [comment]
unfortunately, webcomponent are throwing exceptions in a different "context" then javascript e.g. you can NOT do
```js
try {
  const el = document.createElement('my-el');
  document.appendChild(el);
} catch (error) {
  console.log(error);
}
```

However, I think you should be able to do this: 
```js
class MyEl extends HTMLElement {
  connectedCallback() {
    if (!this.foo) { this._throwError() };
  }
  _throwError() {
     throw new Error('Exception message');
  }
}

// test
try {
  const inst = new MyEl();
  inst.connectedCallback();
} catch (error) {
  console.log(error);
}

// or if all fails probably the only thing you can do is a fake test :/
try {
  const inst = new MyEl();
  inst._throwError();
} // ... 

// or if you are ok with having the error shown in the console (which imho is not acceptable)
// then you could just add an event to the document to check if it fires
// NOTE: you will need to override Mochas default catching for it or it will result in a timeout
```

Mind you that these are just ideas 🙈 if any of them work would be nice if you could report back and/or even create a PR adding this to Development or FAQ.

**Comment by DJCordhose** [comment]
Thanks for the information, trying to find the right lifecycle method in lit-element to check for proper setup of properties. Had this in render before, but this seems plain wrong.

https://lit-element.polymer-project.org/guide/lifecycle

Where would you put it?

**Comment by daKmoR** [comment]
hmm probably in `update` as every time a property changes it could potentially be an invalid combination of "options"...

**Comment by daKmoR** [comment]
@DJCordhose did you had any luck with that? maybe we could have a documentation on how to best test these throwing errors with webcomponents?

**Comment by DJCordhose** [comment]
sorry, I dropped the ball on this, but will take care of this next week

**Comment by DJCordhose** [comment]
Did this in a test and works as expected:
```
  it("should throw when missing definition property", async () => {
    const el = new StringField();
    expect(() => el.checkProperties()).to.throw(
      "property 'definition' required"
    );
  });
```

check properties is called in update life-cycle-method as discussed.

Happy to contribute when this looks good. How would I do this?

Additionally, had an internal discussion what is the right way to react to missing/wrong properties/attributes. Surprising result: it depends. If you have a component that people would simply add to their (static) site it should fail gracefully, if not it should probably throw. I.e. if args are passed as attributes, if should fail gracefully, if as complex props it should throw. 

Is there a place for such a discussion as well?

**Comment by daKmoR** [comment]
@DJCordhose 
sorry for the looong delay 🙈 

perfect place would be the FAQs 🤗 
https://open-wc.org/faq/

https://github.com/open-wc/open-wc/tree/master/docs/faq

**Comment by daKmoR** [comment]
thanks to your contribution this is now available as a deep dive
https://open-wc.org/faq/unit-testing-custom-events.html

**Comment by DJCordhose** [comment]
@daKmoR I understand what I see in the FAQ, but this does not quite match my issue or does it? I needed to react to an exception that messes up the whole process.

**Comment by daKmoR** [comment]
@DJCordhose oh my bad I mixed that up :see_no_evil: => reopend

So if you could add something for this to the FAQ that would be awesome :hugs:

**Comment by DJCordhose** [comment]
will do!

**Comment by daKmoR** [comment]
closed by https://github.com/open-wc/open-wc/pull/332
