### ISSUE TITLE
[testing] missing documentation on chai plugins usage

### ISSUE THREAD

**Issue by rallets** [open-wc/open-wc#2284]
## Expected behavior

I would like to use a chai plugin [chai-as-promised](https://github.com/domenic/chai-as-promised) in my tests.

PS. Basically I need to check that elementUpdated throws an exception (validation error), for example:
```
expect(elementUpdated(el)).to.eventually.be.rejectedWith(...);
```
Here `eventually.be.rejectedWith` is from `chai-as-promised`.
Or maybe I'm just taking the wrong approach.

## Actual Behavior

Importing it via
```
import { fixture, expect, html, elementUpdated, oneEvent } from '@open-wc/testing';
[...]
import chaiAsPromised from 'chai-as-promised';
(window as any).chai.use(chaiAsPromised); // same with `chai.use`
```
fails with
```
SyntaxError: The requested module './../../node_modules/chai-as-promised/lib/chai-as-promised.js' does not provide an export named 'default'
```

I have also changed esModuleInterop in tsconfig.json to true
`"esModuleInterop": true,`

## Additional context

Using the latest packages available.
A repo with this issue reproduced is [here](https://github.com/rallets/open-wc-testing-issue).

**Comment by rallets** [comment]
I got feedback via Slack about this. As reference for anyone else looking into this, the solution is:
```
Check this out: https://github.com/esm-bundle/chai-as-promised

You will need to register it manually, like it is done for other chai plugins here
https://github.com/open-wc/open-wc/blob/master/packages/testing/register-chai-plugins.js
```
so basically
```
npm install --save chai-as-promised@npm:@esm-bundle/chai-as-promised
```
and then import it in the test file via
```
import chaiAsPromised from 'chai-as-promised';
chai.use(chaiAsPromised);
```

**Comment by bashmish** [comment]
@rallets I tried this approach, but didn't work for me. Do you have some working code in the Open Source where I can see a working example? Maybe you can publish your config and a test example here?

**Comment by rallets** [comment]
Hi, sorry but I don't work anymore on this project and stack, so I cannot help.
 
 
  Den ons. 27. mars. 2024 kl. 17.04 skrev Mikhail ***@***.***>:   


@rallets I tried this approach, but didn't work for me. Do you have some working code in the Open Source where I can see a working example? Maybe you can publish your config and a test example here? I'd really appreciate it.
