### ISSUE TITLE
Storybook Actions no longer working

### ISSUE THREAD

**Issue by Halt001** [open-wc/open-wc#2303]
## Expected behavior & Actual Behavior

We have defined actions in our Open WC based project and they've stopped working. It seems the action argument is now undefined. We didn't change our code, it just stopped working, possibly when OpenWC switched Storybook versions. We expect them to still work without change.

## Reproduce
To reproduce I've just created a new OpenWC generated project and added an action to the demo component. The action panel doesn't show up any actions. 

This is the link to the [test repo](https://github.com/Halt001/storybook-action-problem)

I hope someone can verify that this is a bug or that we should do something else  to make this work? Any help is appreciated.

**Comment by Westbrook** [comment]
Storybook has changed the way they manage actions. 

Try out:
```
export default {
  parameters: {
    actions: {
      handles: ['my-event', 'click']
    }
  }
}
```

NOTE: this is bound above your root element, so the events need to be `composed: true, bubbles: true...`

**Comment by Halt001** [comment]
Thanks for your reply. I have what you describe working on a per component level but can't seem to make it work on a per story level. I don't know where to add the `parameters` key without running into Typescript errors.

I'm puzzled though because the documentation shows our way and your way as a possibility. They are not the same thing. According to the [Storybook Action documentation](https://storybook.js.org/docs/web-components/essentials/actions) both should work.

**Comment by Westbrook** [comment]
Parameters should work just like args on individual stories, allowing you to do something like the following, assuming `composed/bubbles`, etc.
```
export const Regular = Template.bind({});
Regular.parameters = {
  actions: {
    handles: ['counter-increase']
  }
};
```

**Comment by Halt001** [comment]
Yeah, thanks I got it to compile, it also needed an interface change. But in the end, this doesn't do what I want because it is not the same functionality as what we had before which should still work according to the docs.

Is it possible that the adaption to make this work with web components by Open WC broke this feature?

**Comment by Westbrook** [comment]
It's possible that we did something with the ordering or similar that invalidates it, sure. I'll look deeper on this.

A similarly possible reason could be that this is built into the React version of Storybook where `on*` properties relate very closely to "events" and was never correctly ported to the web components version on their end. I'll test around with their demos to confirm that, too.

**Comment by Halt001** [comment]
Thanks in advance, just in case it wasn't clear, we 've used the Action ArgType annotation like you see here in the [documentation](https://storybook.js.org/docs/web-components/essentials/actions#action-argtype-annotation) and also in my [test repo](https://github.com/Halt001/storybook-action-problem), not the Automatically matching args (^on.*).

**Comment by Westbrook** [comment]
I think I found the issue: https://github.com/modernweb-dev/storybook-prebuilt/pull/82

**Comment by Westbrook** [comment]
This should be good to go in the latest version: https://www.npmjs.com/package/@web/storybook-prebuilt

**Comment by Halt001** [comment]
I can confirm that it works both in my test repo and with our production code. I really want to thank you for this super speedy fix.
