### ISSUE TITLE
Incorrect docs on shadow dom inheritence

### ISSUE THREAD

**Issue by lpoulter** [open-wc/open-wc#2305]
At this [link](https://open-wc.org/guides/knowledge/styling/styles-piercing-shadow-dom/) it is stated
> Do note that setting all: initial; will also reset any CSS custom properties

Based on my experience I'm pretty sure that is not correct? Perhaps it was in the past?

**Comment by bennypowers** [comment]
indeed `all` does not affect CSS Custom Properties:

https://developer.mozilla.org/en-US/docs/Web/CSS/all
