### ISSUE TITLE
Testing nested webcomponents doesn't work

### ISSUE THREAD

**Issue by liron-navon** [open-wc/open-wc#2309]
## Expected behavior

when testing nested web components, render the nested components too

## Actual Behavior

Nested web components just look like:

< ! --?lit$402775158$-- >

Instead of the normal HTML elements...

## Additional context

Which packages and versions are you using.

    "@open-wc/testing": "^2.5.33",

**Comment by thepassle** [comment]
Im unable to reproduce this. Could you create a minimal reproduction repository?
