### ISSUE TITLE
[building] link rel=preload and more...

### ISSUE THREAD

**Issue by Westbrook** [open-wc/open-wc#231]
I'm testing out the new app starter kit and particularly the `yarn build` command and as at first shocked to see a sizable decrease in performance from approaches I've used in that past:

_App Based of the Start App Repo:_
![image](https://user-images.githubusercontent.com/1156657/52920721-cbcece00-32dd-11e9-8d86-549ee363a8fc.png)

vs a roughly similar app with `polymer build`:

_Sort of "native" LitElement App:_
![lit-element-perf](https://user-images.githubusercontent.com/1156657/52920737-0d5f7900-32de-11e9-8f7b-6d4c602bec98.png)

It didn't take long to realize that this was predominately because the `polymer build` based app was build completely inline of the HTML. **I can see how a larger APP wouldn't benefit from this approach, but what do you think is the top bound for this technique? If there was a sensible boundary, could webpack be told to do one vs the other as the app size passes that boundary?**

Then I realized about the same technique as is applied in the Starter App is being delivered in a React version of the same application built from `create-react-app` defaults:

_React App via create-react-app:_
![react-todo](https://user-images.githubusercontent.com/1156657/52920789-a2627200-32de-11e9-8037-dec9deca6794.png)

I'm not sure what separates the performance between the to application, yet. Particularly, I was surprised that the decreased size of the LitElement based application was still out performed by the React based application. **Does anyone have experience or interest in spelunking into CRA/the Starter App to see if there are techniques that should be applied in the open-wc tools?**

I was able to close much of the performance gap by adding `<link rel="preload" ... />` entries for each of the parts of the app bundle:

_App Based of the Start App Repo w/ rel=preload:_
<img width="728" alt="screen shot 2019-02-17 at 6 09 06 pm" src="https://user-images.githubusercontent.com/1156657/52920849-2c123f80-32df-11e9-9f52-e2852548209f.png">

**Does anyone have insights on adding a build step in webpack that would include this sort of links in the final build?** I'm not super webpack proficient but will try to look into this some more, but were someone more a specialist here, I'd love some support. Possibly, this is something that the research work in #221 might also take into account?

I can produce extended Lighthouse reports if it would be of use to anyone in researching this further.

**Comment by LarsDenBakker** [comment]
Thanks for your investigation. One thing that I worry about is our wc polyfills loader, which is now based on dynamic imports. Your main app is always a dynamic import away, even on browsers which support web component. This is not ideal, so maybe there is something we can improve there.

Would you be able to run the same benchmark with the polyfills loader removed? Just import your app directly.

**Comment by daKmoR** [comment]
If you add the preload then it should not be a problem as it's already in the browser then the import become like a function call...

that is probably the reason why there is such a big difference when adding it

**Comment by LarsDenBakker** [comment]
With preload I feel there is still quite a difference from the polymer build. Is that all related to inlining the JS?

**Comment by Westbrook** [comment]
Things that I've confirmed post initial report:
1) If I take the exact code from the previous project and build it with the the start app repo, I get roughly the same low(er) score. _I realize that these are all pretty nice scores and there is a modicum of splitting hairs going on here..._
2) A similar form of "better" score is achieved via the use of `rel="preload"` links.
3) Combining `rel="preload"` with an inlined version of the "main" JS file gets arguably better results than I was getting previously with `polymer build`.
<img width="716" alt="screen shot 2019-02-18 at 8 48 12 am" src="https://user-images.githubusercontent.com/1156657/52955147-f8283000-3359-11e9-82b7-7623300b6a08.png">

Still unable to achieve those same scores with my new app, I decide that either means the difference between 12kB and 13.9kB is more than I thought, or something I'm doing in those 1.9kB of difference is holding me back... that is until I look a little deeper into the trace on my previous To Do app. Notice those two frames of just gradient background in the audit above? That visual indicator is actually gaming the Lighthouse score as it's showing FMP and FCP as having happened in correlation with that loading onto the page. Without it, the page score much more in line with my new app:
<img width="711" alt="screen shot 2019-02-18 at 9 04 59 am" src="https://user-images.githubusercontent.com/1156657/52956262-c49ad500-335c-11e9-9cd6-dc762c412ffa.png">

**That means the open-wc recommendations would be scoring at or around the Create React App score with the addition of the `rel="preload"` links, pointing very strongly towards the need, though I've not the understanding of webpack needed to manage that sort of addition intelligently.**

Beyond that, I'd love to hear any thoughts that might be floating around as to ways to gauge when an app should be/could be inlined so as to get back some of the difference between the approach applied here and that of `polymer build`. Though, that might be better discussed in a separate issue?

**Comment by LarsDenBakker** [comment]
Thanks for the further investigations. I'm fairly certain the preload is needed in the current setup because of the polyfills loader. That's very unfortunate though, I'd prefer if we didn't need to do that. The problem is that you can't run any web component code until the polyfills are loaded for IE11 and Edge.
