### ISSUE TITLE
Can we publish web components on GitLab

### ISSUE THREAD

**Issue by Haribabuyeliti** [open-wc/open-wc#2318]
Hi Team,

Is there any chance to publish web components  to Gitlab instead of NPM?

**Comment by thepassle** [comment]
You can host your web components projects on either github, gitlab, or anything else you prefer. Gitlab is not really a publishing platform in the way that npm is.

These kind of questions are generally better asked on Slack, you can find an invite link here: https://open-wc.org/discover/slack/
