### ISSUE TITLE
Can we develop multiple we components in Single application 

### ISSUE THREAD

**Issue by Haribabuyeliti** [open-wc/open-wc#2319]
Hi Team,

Can we develop Multiple web components in single application.

**Comment by btopro** [comment]
just need to import the files in the `/src` directory. It's not for doing multiple package publishing but you can include and ship multiple elements from the single repo

**Comment by thepassle** [comment]
Like @btopro said, yes, this is possible.

Additionally, these kind of questions are usually better asked on Slack, you can find an invite link here: https://open-wc.org/discover/slack/
