### ISSUE TITLE
Add rational for splitting class with registration

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#232]
Could be something like this:

We recommend to split class definition and custom element registration in 2 files to enable your users to extend your class without needing to pollute the custom elements registration.

Example:
foo-foo/FooFoo.js // class
foo-foo/foo-foo.js // custom element registration

I can now extends
bar-bar/BarBar.js
import { FooFoo } from 'foo-foo';
class BarBar extend FooFoo {}

bar-bar/bar-bar.js

So you can now import bar-bar without polluting the registry with the foo-foo tag

**Comment by bennypowers** [comment]
Should this be a new page under about?
or a new 'writing' section?

**Comment by daKmoR** [comment]
additions:
I don't think you should _always_ split class definition and custom element definition
it only makes sense for public components
correct... for app specific or custom element you don't think that will ever be extended it makes no sense

**Comment by daKmoR** [comment]
> Should this be a new page under about?
> or a new 'writing' section?

probably just a new section in [development](https://open-wc.org/developing/)?
