### ISSUE TITLE
Typo in `Knowledge: Attributes and properties` page

### ISSUE THREAD

**Issue by yishuolin** [open-wc/open-wc#2321]
## Expected behavior

In [Knowledge: Attributes and properties](https://open-wc.org/guides/knowledge/attributes-and-properties/), the example of _"Attributes can also be set from javascript, and will update the attribute in the DOM"_ should be
```js
myDiv.setAttribute('foo', 'not-bar');
```

## Actual Behavior

The current example use `getAttribute` instead.
```js
myDiv.getAttribute('foo', 'not-bar');
```

**Comment by thepassle** [comment]
fixed by https://github.com/open-wc/open-wc/pull/2293
