### ISSUE TITLE
Multiple versions of lit cause issues in storybook

### ISSUE THREAD

**Issue by btopro** [open-wc/open-wc#2322]
Recently when creating a application based storybook I ran into an issue with the version of lit leveraged in the default `stories/app-name.stories.js` file. There was no issue internal to my element, but it did import other elements as part of it's `package.json` [link](https://github.com/elmsln/project-two/blob/master/package.json#L25-L58). @bennypowers suggested the lit-html version might be upsetting storybook as I was getting the following error message:
```
Did you forget to return the HTML snippet from the story?
Use "() => <your snippet or node>" or when defining the story.
```
He suggested referencing `lit-html` directly and sure enough this worked.
Here is the suggested change to the storybook boilerplate:
**from** `import { html } from 'lit';` **to** `import { html } from 'lit-html';`

Here's my repo that you can test this in context of if desired to see that changing this 1 line makes or breaks storybook: https://github.com/elmsln/project-two/blob/master/stories/app.stories.js#L1

https://github.com/elmsln/project-two

Hope this helps someone in debugging if they start leveraging components in other components and run into similar issues

**Comment by Westbrook** [comment]
If anyone has a repo of this issue specifically, feel free to reopen this or a new issue with more information, but while there are cases where the wires can get crossed on your `lit-html` version in a project, I do not see any benefit from importing `html` from `lit-html` as opposed to `lit`.

**Comment by btopro** [comment]
https://github.com/open-wc/open-wc/issues/2418#issuecomment-1133061779 closed but linked to this solution as it's tooling based and relatively simple
