### ISSUE TITLE
Any reason not to use the @customElement annotation in the templates?

### ISSUE THREAD

**Issue by jlengrand** [open-wc/open-wc#2333]
## Expected behavior

This is more of a remark / question than a bug. The tutorial and most of the documentation of lit.dev mentions refers to using the `@customElement` annotation to declare custom elements.

However, generating a open-wc template with Typescript uses 2 files. One Typescript file with the custom element implementation (without annotation) , and the other one declaring the custom element (using customElements.define()).
Is there a specific reason for this? 

So in essence, I'd expect the template to be : 

```ThirdBrain.ts
@customElement('third-brain')
export class ThirdBrain extends LitElement {
  @property({ type: String }) title = 'My app';
...
```

and the index.html file to be 

```
...
  <script type="module" src="./out-tsc/src/ThirdBrain.js"></script>
...
```

## Actual Behavior

instead of 

```third-brain.ts
import { ThirdBrain } from './ThirdBrain.js';

customElements.define('third-brain', ThirdBrain);
...
```

```ThirdBrain.ts
export class ThirdBrain extends LitElement {
  @property({ type: String }) title = 'My app';
...
```

and the index.html file to be 

```
...
  <script type="module" src="./out-tsc/src/third-brain.js"></script>
...
```

## Additional context

I checked, the same happens with the Javascript templates

**Comment by thepassle** [comment]
@customElement() ties the registration of the component to the module its in, so you can never import the class without registering the component as a side effect, which you might not want when youre, for example, just extending the component, or when you need to support multiple versions of components. Depends a bit on your usecase, but we dont consider it a good default.

**Comment by jlengrand** [comment]
Ha, interesting. Good answer, I didn't think about the extension use case. 

Thanks! I'll close this
