### ISSUE TITLE
Add details for linters

### ISSUE THREAD

**Issue by stramel** [open-wc/open-wc#235]
It would be nice to know in the documentation what defaults you guys have set for prettier and what rule sets you have for eslint.

**Comment by daKmoR** [comment]
not good enough? https://open-wc.org/linting/linting-eslint.html#what-you-get

what would you expect?

**Comment by stramel** [comment]
I think seeing something like 

```
{
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: true,
  jsxBracketSameLine: false,
  arrowParens: 'avoid',
}
```

and the actual rule names

```
'import/extensions': 'off',
'no-underscore-dangle': 'off',
'import/prefer-default-export': 'off',
'import/no-extraneous-dependencies': 'error'
```

would be nice.

TBH I wasn't expecting the `bower_components` resolutions. And the Airbnb eslint config feels a bit like personal preference.

**Comment by daKmoR** [comment]
`bower_components` => should be removed
copying the actual settings would seem strange? how about a link to the file? looking forward to a PR :hugs: 

recommendations are always sort of a "personal" preferences right? :see_no_evil: 

so we currently recommend these setting which is based on Airbnb - we are open to discuss alternatives settings or changes to these settings if they make sense :hugs:

**Comment by stramel** [comment]
A link to the actual files would work.

The eslint rules (aside from airbnb's config) are pretty much already there just not their official rule name.

I'm wondering if we need the Airbnb config at all? Allowing the dev to bring whatever ruleset they want without having to deal with any potential rules not set by their ruleset that Airbnb has?

My personal preference is a slightly modified Google config.

**Comment by daKmoR** [comment]
@stramel if you have any time to improve the docs (e.g. add links) and cleanup bower_components or so that would be awesome - pretty please 🤗
