### ISSUE TITLE
Revisit the need to split elements from their definitions

### ISSUE THREAD

**Issue by 43081j** [open-wc/open-wc#236]
As mentioned to a few of you on slack, I think this should be discussed and re-visited.

The convention has always been that you tightly couple your element and define call:

```ts
class Foo extends HTMLElement {}
customElements.define('x-foo', Foo);
```

This means we can always assume the standard conventional import to define it in the browser:

```ts
import "./some-element.js";
```

From what I understand, the true reason you decided to separate the two is primarily because of some issues with angular projects in particular. So maybe it would be worth discussing how else you could tackle those problems rather than pushing an unconventional approach (which disagrees, so far, with polymer and most other libraries).

I do understand it is a recommendation and can be ignored, but the problem i see is that you'll be recommending something which conflicts with what documentation for all other projects in the community recommends.

That paired with the fact that the core reason for the separation seems to be for an angular-specific edge case makes me wonder if you could possibly tackle this problem in another way. What do you think?

It is far from ideal to have two differently cased file names and can only introduce confusion, too.

If there really is no alternative to your angular problem, maybe you must have this. However, it seems a little flaky of a basis for the recommendation I think so it would surprise me if there wasn't a cleaner solution.

Keep in mind, scoped registries will [likely] eventually be a thing too and you could consider composing elements for your angular projects instead.

**Comment by thepassle** [comment]
To clarify: I don't think the angular project is the main reason for the recommendation, but it was one of the usecases that was brought up by benny, but maybe @daKmoR can elaborate more

**Comment by odinho** [comment]
This has a followup in https://github.com/open-wc/open-wc/issues/932 it looks like.
