### ISSUE TITLE
waitUntil is typed too strictly

### ISSUE THREAD

**Issue by tpluscode** [open-wc/open-wc#2361]
## Expected behavior

The example shows the `waitUntil` function used with a function which presumably returns a truthy value

## Actual Behavior

The type declarations are strict, requiring exactly `boolean | Promise<boolean>`.

## Additional Context

For non async property I can do `waitUntil(() => !!element.foo)` but promises are more problematic

**Comment by bennypowers** [comment]
Can you give a repro?

**Comment by tpluscode** [comment]
[lit.dev](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCB7d2FpdFVudGlsfSBmcm9tICdAb3Blbi13Yy90ZXN0aW5nLWhlbHBlcnMnXG5cbkBjdXN0b21FbGVtZW50KCdzaW1wbGUtZ3JlZXRpbmcnKVxuZXhwb3J0IGNsYXNzIFNpbXBsZUdyZWV0aW5nIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBzdHlsZXMgPSBjc3NgcCB7IGNvbG9yOiBibHVlIH1gO1xuXG4gIEBwcm9wZXJ0eSgpXG4gIG5hbWUgPSAnU29tZWJvZHknO1xuXG4gIHJlbmRlcigpIHtcbiAgICB3YWl0VW50aWwoKCkgPT4gdGhpcy5uYW1lKVxuICAgIFxuICAgIHJldHVybiBodG1sYDxwPkhlbGxvLCAke3RoaXMubmFtZX0hPC9wPmA7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2ltcGxlLWdyZWV0aW5nIG5hbWU9XCJXb3JsZFwiPjwvc2ltcGxlLWdyZWV0aW5nPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

<img width="724" alt="image" src="https://user-images.githubusercontent.com/588128/144077618-3db14854-8180-405e-be0c-ff1885778813.png">

**Comment by bennypowers** [comment]
so why can't you `!!` exactly? Or `p.then(x => !!x)`?

**Comment by tpluscode** [comment]
Meh, I don't know, wasn't `!!` considered a smell in the past? And requiring `.then` is just unnecessary verbosity if the called code simply does `if(await until)`

**Comment by bennypowers** [comment]
not sure if my sense of smell is the deciding factor here :D

Ok yeah i hear what you're saying, and it makes sense since there's no runtime check for boolean.

**Comment by bennypowers** [comment]
@tpluscode do you want to make a PR?
