### ISSUE TITLE
eslint crash with private class fields/methods

### ISSUE THREAD

**Issue by tirithen** [open-wc/open-wc#2365]
## Expected behavior

After running `npm init @open-wc` and upgrading to eslint 8.3.0 (https://eslint.org/blog/2021/11/eslint-v8.3.0-released) I expect to be able to lint JavaScript code with private fields and methods on classes

## Actual Behavior

Eslint crashes with a linting error:

```bash
$ npm run lint

> test-app@0.0.0 lint
> eslint --ext .js,.html . --ignore-path .gitignore && prettier "**/*.js" --check --ignore-path .gitignore


/project-dir/src/TestApp.js
  57:3  error  Parsing error: Unexpected character '#'

/project-dir/src/test-app.js
  1:25  error  Parse errors in imported module './TestApp.js': Unexpected character '#' (57:3)  import/named
```

## Additional context

I have setup a basic `npm init @open-wc` repo with a CI pipeline setup to show at https://github.com/tirithen/open-wc-private-fields/runs/4393922608?check_suite_focus=true#step:5:1ppen

It would be great with a pull request to the https://github.com/tirithen/open-wc-private-fields with a fix for eslint private fields and methods, I think more people would benefit from a solution to this.

Any suggestions how to include class private fields/methods linting setup out of the box for `npm init @open-wc`?

**Comment by tirithen** [comment]
It seems like I found a workaround by modifying `eslintConfig` in `package.json`:

```json
  "eslintConfig": {
    "extends": [
      "@open-wc",
      "prettier"
    ],
    "parserOptions": {
      "ecmaVersion": "latest",
      "sourceType": "module"
    }
  },
```

When setting the `parserOptions.ecmaVerison` to `latest` there are no more parse errors.

Could this be added to the `@open-wc` eslint config?

**Comment by tirithen** [comment]
I added the workaround on a branch in the setup repo for reference https://github.com/tirithen/open-wc-private-fields/blob/workaround/package.json#L47

**Comment by thepassle** [comment]
fixed this in the project generator

**Comment by tirithen** [comment]
Thanks for the fix!
