### ISSUE TITLE
Storybook build run fail with react-dom and react deps

### ISSUE THREAD

**Issue by movrack** [open-wc/open-wc#2370]
## Expected behavior

Generating a new project should have a working storybook build

## Actual Behavior

run `npm init @open-wc`
-> choose storybook in options
-> install deps
run `npm run storybook:build`
run `npx http-server storybook-static`

Then at the page loading, errors occurs:
http-server console:
> [2021-12-20T15:26:20.779Z]  "GET /react-dom" Error (404): "Not found"
> [2021-12-20T15:26:20.781Z]  "GET /react" Error (404): "Not found"

chrome debugger:
>Failed to load resource: the server responded with a status of 404 (Not Found)
>react-dom:1 Failed to load resource: the server responded with a status of 404 (Not Found)
>systemjs.200c680897e2c47082fe1714c434a7c3.js:1 Uncaught (in promise) Error: react, http://127.0.0.1:8080/cd2f0b4e.js (SystemJS https://git.io/JvFET#8)
    at systemjs.200c680897e2c47082fe1714c434a7c3.js:1
    at u.x.resolve (systemjs.200c680897e2c47082fe1714c434a7c3.js:1)
    at systemjs.200c680897e2c47082fe1714c434a7c3.js:1
    at Array.map (<anonymous>)
    at systemjs.200c680897e2c47082fe1714c434a7c3.js:1
## Additional context

Which packages and versions are you using.
Current one from npm init @open-wc

**Comment by movrack** [comment]
Probably related ...
https://github.com/modernweb-dev/storybook-prebuilt/issues/105

**Comment by Westbrook** [comment]
This has been corrected in Storybook Prebuilt.
