### ISSUE TITLE
Module not found: Error: Can't resolve ...?babel-target=es5/6

### ISSUE THREAD

**Issue by StJohn3D** [open-wc/open-wc#238]
Getting this error only when trying to use `npm run build`. `npm start` works just fine.

## My Setup
company-web-components/
-  _demo/
    - index.html
    - index.js
    - my-app.js _(root web-component that imports and displays `hello-world.js` & `checkbox-vanilla.js`)_
    - web-components/
      - hello-world.js
    - webpack.config.json
    - package.json
    - node_modules/
      - company-web-components/ _(symlink install - includes the package.json & lib folder)_
  - src/
      - checkbox-vanilla.ts
  - lib/
      - checkbox-vanilla.js  _(ts compiled with es2015 target for web-components)_
 - package.json
 - tsconfig.json

If you need a full repo to look at I can throw one together but first I'm hoping the above will be enough to help someone see what I'm doing wrong.

## webpack.config.js
```js
const path = require('path');
const merge = require('webpack-merge');
const createDefaultConfig = require('@open-wc/building-webpack/default-config');

const defaultConfig = createDefaultConfig({
  indexHTML: path.resolve(__dirname, './src/index.html'),
  indexJS: path.resolve(__dirname, './src/index.js'),
});

module.exports = merge(defaultConfig, {
  module: {
    rules: [
      {
        test: /\.s?css$/,
        sideEffects: true,
        use: [
          'style-loader',
          'css-loader',
          'sass-loader'
        ]
      },
      {
        test: /\.(png|svg|jpg|gif)$/,
        use: [
          'file-loader'
        ]
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/,
        use: [
          'file-loader'
        ]
      }
    ],
  },
});
```

## tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "es2015",
    "declaration": true,
    "outDir": "./lib",
    "strict": true,
    "sourceMap": true,
    "noImplicitAny": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "allowJs": false
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules",
    "_demo",
    "**/__tests__/*"
  ]
}
```
## The Goal
I'm trying to create a library of web-components. The goal is to write the code in the `src` folder using typescript. Then that typescript is compiled to the lib folder. The package.json in the root sets the lib folder for the `files` entry and the `module` entry. Then with npm link those components can be imported in the _demo folder and used to render web-components from a symlinked npm package.

## What's happening.
I've symlinked via (npm link) the module (the lib folder) to the `_demo` folder - which is where the open-wc project is contained. I can import from the module in the my-app.js file. When I run `npm start` Chrome launches and I see the imported web-components displayed in the browser correctly (also working in FF, and Edge). The problem is when I try to do `npm run build` in the `_demo` folder.

I get this error:
>ERROR in ./src/my-app.js
Module not found: Error: Can't resolve 'company-web-components/lib/checkbox-vanilla?babel-target=es5' in 'C:\Users\me\Projects\company\company-web-components\_demo\src'
 @ ./src/my-app.js 7:0-76 24:115-130 24:146-161
 @ ./src?babel-target=es5
 @ multi core-js/es6?babel-target=es5 ./src?babel-target=es5

>ERROR in ./src/my-app.js
Module not found: Error: Can't resolve 'company-web-components/lib/checkbox-vanilla?babel-target=es6' in 'C:\Users\me\Projects\company\company-web-components\_demo\src'
 @ ./src/my-app.js 2:0-76 14:7-22 14:28-43
 @ ./src?babel-target=es6
 @ multi ./src?babel-target=es6

So my guess is that the build process for production is doing something different with web-components imported from node_modules than development.

## When ts targets es5
I'm not sure if it's tree shaking, because when I change my `tsconfig.json` to target es5 instead - the build succeeds but only the `hello-world.js` (the local one NOT from node_modules) displays correctly - for the checkbox-vanilla.js component, I get an error in the browser.

> Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new CheckboxVanillaClass (checkbox-vanilla.js:20)
    at new MyApp (my-app.js:8)
    at Module../src/my-app.js (my-app.js:16)
    at __webpack_require__ (bootstrap:63)

Thanks for reading this far and any help will be much appreciated. I'm hoping it's something simple like altering my webpack.config.js file to not ignore node_modules in production - if that's a thing?

**Comment by StJohn3D** [comment]
For anyone else with a similar issue, here is what I discovered to be the fix - at least for me.

The webpack loaders or babel are trying to import dependencies from relative paths to the file being worked on. So when it tried to transform the checkbox-vanilla.js web-component which is in a symlinked folder - it's actually looking for dependencies in the root node_modules folder (not the _Demo/node_modules).

So what I had to do was `npm i -D @babel/runtime` in the root of the project. This way when it goes to work on files that are symlinked - it can still find the dependencies it needs to transform them.

**Comment by daKmoR** [comment]
hey,

nice that you could solve it that way :)

I'm curious... wouldn't storybook be a good companion to show demos instead of having a separate build + webpack config?

**Comment by StJohn3D** [comment]
@daKmoR Thanks! Not sure if I've seen StoryBook before - I know I've researched similar things for React components in the past but wasn't aware of something for web-components. One goal for me to use it is to be able to use jsdoc comments and ts definitions to generate component documentation.
