### ISSUE TITLE
Create developer tips page

### ISSUE THREAD

**Issue by anoblet** [open-wc/open-wc#239]

**Comment by anoblet** [comment]
https://github.com/anoblet/open-wc/blob/patch-2/docs/faq/updated.md

**Comment by thepassle** [comment]
I wonder what this adds on top of the lit-element documentation though? I think we shouldnt try to have basically a duplicate documentation of the same things. I can get this information from https://lit-element.polymer-project.org/guide/lifecycle#updated as well

**Comment by anoblet** [comment]
You're absolutely correct :) Closing
