### ISSUE TITLE
Regular code snippets disappear in mdjs

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc#2393]
Given the following story:

`my-story.stories.js`:
`````md
```js script
export default {
  title: 'Foo',
};
```

# Hello

world

```js
console.log('code block doesnt show')
```

```js script
console.log('does execute')
```

`````

I would expect a code snippet to be output, but it seems like somewhere in the `mdjsToMd` function in `storybook-addon-markdown-docs` it gets removed. Interestingly, the `js script` does get executed.

![image](https://user-images.githubusercontent.com/17054057/151416112-c3827bc1-e53c-4adc-8a05-a0cc82aa4c02.png)

![image](https://user-images.githubusercontent.com/17054057/151415702-284364e0-cdb7-4b1f-91bb-b9f3db45e550.png)

I have a reproduction repo here: https://github.com/thepassle/sb-repro

## Expected behavior

Code snippets in mdjs files are output correctly

## Actual Behavior

Code snippets disappear

**Comment by Westbrook** [comment]
The MDJS pipeline for Storybook is super out of date and has a number of vulnerabilities in its dependency chain. It would be great to get @daKmoR's thoughts on how to get it up-to-date with his latest work in this area to ensure we're preparing consumers for success here.

**Comment by thepassle** [comment]
> to ensure we're preparing consumers for success here

Yeah, I'm updating some projects at work to modern web tooling, and there's quite a bit of usage of mdjs in those projects unfortunately. It'd be great not to have to refactor them to something else again.

**Comment by daKmoR** [comment]
@thepassle thank you for the reproduction repo - I would have found a solution without it.

Can you check the 1 line change and verify that it solves it for your case - if so we can do a release right away.

@Westbrook that does not update any dependencies or so... - maybe have a separate issue for that?

**Comment by thepassle** [comment]
Checked it locally and it indeed fixes it:

![image](https://user-images.githubusercontent.com/17054057/151935543-4774735c-466c-4597-aa25-54570103eac3.png)

Thanks for taking a look 🙂
