### ISSUE TITLE
Make generators slimmer

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#240]
yeoman generators are nice but they are pretty "heavy"...
if we want to have a nice experience via `npm init open-wc` or `npx create-open-wc` then we probably want to search for an alternative.

I just stumbled over this for prompts maybe it's useful: https://github.com/klaussinani/qoa

@stramel let's share ideas/concepts here

**Comment by stramel** [comment]
Yeah I took a look at that. It looks like a stripped down inquirer.js.

I was using inquirer and commander

**Comment by anoblet** [comment]
Why not gulp? prompt I think is a wrapper around inquirer. I wrote a generator for Polymer 2 back in the day (https://github.com/anoblet/generator-anoblet/blob/master/app/index.js)

**Comment by stramel** [comment]
Prompt is just a wrapper around inquirer. Plus it adds a lot of the gulp bloat that we aren't going to utilize. I think we can achieve a slimmer build just utilizing the packages directly.

**Comment by daKmoR** [comment]
Sooooo I made an inital version here:
https://github.com/daKmoR/create-open-wc

- uses babel
- only 3 pretty small dependencies
- "Menu" + Linting is implemented so far

speed is wwwwaaaayyyy better than with yoeman :)
you can try it via
```bash
# menu
npm init open-wc

# linting upgrade (needs a valid package.json file... {} is fine) 
npm init open-wc linting
```

If anyone got time to do some review or so that would be awesome :)

I wanna polish it a little and add all the other generators we have before moving it to open-wc (will also need to adopt the ci a little to allow for auto-publishing via babel)

**Comment by daKmoR** [comment]
I think the inital step is done
```
$ npm init open-wc
npx: installed 14 in 2.43s
What would you like to do today?
  > Scaffold a new project
    Upgrade an existing project
    Nah, I am fine thanks! => exit
```

And it's super small...

Time till interactive:
~5 Seconds (new - custom generator) 🎉 
vs
~30 Seconds (current using yomen)

=> same output for Starter-App, Testing, Linting, Building
(Demoing and some scaffolding is yet done)

**Comment by stramel** [comment]
I would suggest if building it for this org, using the package name `@open-wc/create` which would allow a user to run `npm init @open-wc` (which is equivalent to `npx @open-wc/create`).

Finally got some time to dig back into this, sorry for being absent.

**Comment by stramel** [comment]
Qoa is 100x smaller (min+gzip) than Inquirer.js but has no validation or color support :/

**Comment by daKmoR** [comment]
validation you can easily be done with a do while loop like here... https://github.com/daKmoR/create-open-wc/blob/master/src/generators/barebone-app/index.js#L15

for colors... not sure if it's worth ~4 times the size?

https://bundlephobia.com/result?p=qoa@0.2.0  (2.2KB)
https://bundlephobia.com/result?p=prompts@2.0.3 (8.1KB)

I really like the 2 second install time now 😬 maybe the added 6KB will not make it much difference? ... probably not (as we currently have a 300KB svg in there 🙈 - probably should replace this or so)

so if you wanna do a try with prompts it sounds good to me :)

for `npm init @open-wc` or `npm init open-wc`... I feel like without the `@` it looks nicer... but for that we could probably do a vote?

**Comment by stramel** [comment]
😱 300KB svg?! that's larger than the entire inquirer lib lol

WRT the `npm init @open-wc` vs `npm init open-wc`, it would be easier to additionally add other generators. (ie. `npm init @open-wc`, `npm init @open-wc/linters`, or `npm init @open-wc/testing`)

I will take a look at the install time differences. According to BundlePhobia, in "Emerging 3G" networks it adds 120ms.

**Comment by daKmoR** [comment]
coming to think of it - apparently what takes time is resolving nested packages and not the download of the main package... so small dependencies is still king (e.g. they should not have many nested dependencies)
so pure size it not everything :see_no_evil:  (it's apparently never easy :rofl: )

I think for the most part we will stay with one generator and try to guide users to the correct decision... all within that generators (to prevent extra download steps)

but true having the possibility to add extra separate generators to the same "group" seems like a good thing :) e.g. if we would have a generator that's too big to add the default stuff... (like full features demo applications, or code mods like probably needed for something like this https://github.com/open-wc/open-wc/issues/254)

soo good idea :+1:

**Comment by daKmoR** [comment]
so now we have `@open-wc/create` 🤗  and you use it via `npm init @open-wc` 💪 

I think the generator system itself came out really nice and we could even move the functionality in its own package and promote it as a standalone tool? (as it's really really small and offers almost the same functionality as yeoman [at least for what we where needing])

There would still be some open questions like
- name? 
- way more documentation
- add some more features before moving it
  - abstraction of prompting
  - possibly use prompts npm package
  - template system for files? is it worth it?
  - virtual file system? didn't find anything small... is it worth it?
  - ...
- quite some cleanup/polish, tests, ...
- own homepage or a section in open-wc?
- ...

so if anyone wants to work on this I would be more then happy to help 🤗  (how about it @stramel?)

PS: closing this fore now as this is a whole different topic...
