### ISSUE TITLE
EsLint disallow too large dependencies

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#241]
For frontenend you typically do not want to use very big dependencies.

Should we add a rule to discourage
- moment.js
- ... any other suggestions?

or is this too opinionated?

idea from

> Tip: Disallow known large imports from JavaScript projects with ESLint & the `no-restricted-imports` rule: https://bit.ly/disallow-imports … ~ great for helping teams avoid specific imports & recommending alternatives.

https://twitter.com/addyosmani/status/1098487367084593152

**Comment by syu93** [comment]
IMO we shouldn't target specific library but enhance the documentation to point out JavaScript bloat and encourage people to take care of the choice of library by giving some links and tooling like bundlephobia
