### ISSUE TITLE
Render problem

### ISSUE THREAD

**Issue by GHNewbiee** [open-wc/open-wc#242]
Hi!

I have installed `open-wc` successfully by following your instructions. I can see the initial page.

Next, I add in the same file (right below), the `01-basic-setup` **component**. I can see the extra `Hello world!`. So far, so good!

Next, I add in the same file again, the `02-manage-properties` **component**. Unfortunately I do not get the extra lines:

```
The message is: Hello world, count is: 0
The reversed message is: dlrow olleH
```

In general, any **component** more complicated than `01-basic-setup` fails to get rendered in any way either as additional in the initial page or individually as a separate project.

Looking forward reading your advice.

Tia

**Comment by thepassle** [comment]
It's a little unclear to me what your setup is, do you have a repo I could take a look at?

**Comment by GHNewbiee** [comment]
@thepassle Thanks for your interest and help. Please have a look at https://github.com/GHNewbiee/temporary. I have included only main files. `webpack` files (index.js and index.html) are missing since they do not play any important role, do they? I concluded in that, since the initial two components (`open-wc-yo.js` and `open-wc-logo.js`) are normally displayed despite of the content of those `webpack` files. Tia

**Comment by thepassle** [comment]
You'll still need something to resolve your imports, you can use the `owc-dev-server` for this, instructions: https://open-wc.org/developing/owc-dev-server.html

And as described in: https://github.com/open-wc/open-wc/issues/244 as well. If you don't mind, i'll close this in favor of #244

**Comment by GHNewbiee** [comment]
@thepassle `owc-dev-server` is already installed. There is also `"start": "owc-dev-server --open"` at `package.json` `scripts`. As regards the other server options, I suspect that the default one is also correct since the initial two components (`open-wc-yo.js` and `open-wc-logo.js`) are normally displayed. What I just do is to add additional components in the end. Anyway, #244 instructions gave me a "working" env. Thanks for your help.
