### ISSUE TITLE
@open-wc/testing doesn't work with node 17

### ISSUE THREAD

**Issue by NingenJanai** [open-wc/open-wc#2424]
## Expected behavior

npm test to work

## Actual Behavior

After updating node from version 16 to 17, @open-wc/testing seems to have a breaking issue.

Now npm test will try to start chrome headless but it will always timeout, I think it's related to @open-wc/karma-esm, because if I remove the esm framework then karma seems to start chrome successfully.

## Additional context

 "@open-wc/testing": "^3.0.0-next.5",
 "@open-wc/testing-helpers": "^2.0.0-next.3",
 "karma": "^6.3.17",

**Comment by thepassle** [comment]
We recommend using @web/test-runner instead of karma
