### ISSUE TITLE
[Upgrade Request] Update chai-dom from v1.9.0 to v1.11.0

### ISSUE THREAD

**Issue by giamir** [open-wc/open-wc#2447]
The latest version of chai-dom includes few more assertions such as `focus` and `checked`. It would be great if they could be bundled with the next release of `@open-wc/testing`.
I expect the effort of upgrading to be extremely low since there are no breaking changes but only addition of few assertions.
https://github.com/open-wc/open-wc/blob/master/yarn.lock#L5706
https://github.com/nathanboktae/chai-dom/releases/tag/v1.11.0
https://www.npmjs.com/package/chai-dom/v/1.11.0

If one of the maintainer gives me the ok I could open a small PR.
Thanks.

**Comment by Westbrook** [comment]
We'd be happy to accept a PR with this update!

**Comment by giamir** [comment]
Done: https://github.com/open-wc/open-wc/pull/2448 😊

**Comment by giamir** [comment]
@Westbrook Any chance this PR could be merged? https://github.com/open-wc/open-wc/pull/2448
Thanks
