### ISSUE TITLE
Vulnerability Found

### ISSUE THREAD

**Issue by Westbrook** [open-wc/open-wc#245]
Run `yarn audit` and you get the following:

![image](https://user-images.githubusercontent.com/1156657/53174990-12ac1480-35b9-11e9-8d3f-227b7c1972ff.png)

I'm sure I'm doing something wrong, but I'm pretty sure that this is preventing me from publishing work to Netlify. 😖 

Can look to make a PR later, but must head to the office... 😢

**Comment by Westbrook** [comment]
Correcting PR has been merged at the Karma level: https://github.com/karma-runner/karma/issues/3269 actual release pending...

**Comment by daKmoR** [comment]
with the release of karma 4.0.1 this should be solved 🤗 

pls reopen if this is still an issue
