### ISSUE TITLE
`@open-wc/testing-helpers` not playing well with TypeScript 4.7 node16 module

### ISSUE THREAD

**Issue by mgenware** [open-wc/open-wc#2453]
## Expected behavior

Created a [repo](https://github.com/mgenware/lit-element-starter-ts-node16-issues) with repo steps.

## Actual Behavior

Run into multiple errors:

```
node_modules/@open-wc/testing/index.d.ts:3:22 - error TS7016: Could not find a declaration file for module '@open-wc/testing-helpers'. '/Users/m/lit-element-starter-ts/node_modules/@open-wc/testing-helpers/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/open-wc__testing-helpers` if it exists or add a new declaration (.d.ts) file containing `declare module '@open-wc/testing-helpers';`

3 export { html } from '@open-wc/testing-helpers';

...
```

**Comment by jpzwarte** [comment]
@mgenware See https://github.com/open-wc/open-wc/pull/2454, which is for `@open-wc/scoped-elements`, but the same can probably be applied to `@open-wc/testing-helpers`.

**Comment by thepassle** [comment]
seems like this was fixed in https://github.com/open-wc/open-wc/pull/2507
