### ISSUE TITLE
webpack.config.js does not pass commit linting

### ISSUE THREAD

**Issue by Westbrook** [open-wc/open-wc#246]
The following lint errors occur when trying to commit webpack.config.js. Not sure if there's something requiring this, so they should use some sort of `ignore` commenting, or just a bunch of removals to be made here.

![image](https://user-images.githubusercontent.com/1156657/53175143-5f8feb00-35b9-11e9-9bbb-6c2da6b21821.png)

Will try to confirm later and put together a PR.

**Comment by daKmoR** [comment]
yes we probably should add `**/*.config.js` here: https://github.com/open-wc/open-wc/blob/master/packages/eslint-config/index.js#L15

that way you can use devDependencies in these config files 👍

**Comment by Westbrook** [comment]
Cool, I can follow up with that PR later tonight or tomorrow.

**Comment by Westbrook** [comment]
Closed via #249
