### ISSUE TITLE
`@open-wc/building-rollup` fails to recognize the package.json `exports` field

### ISSUE THREAD

**Issue by eKoopmans** [open-wc/open-wc#2461]
## Expected behavior

Rollup (using config from `@open-wc/building-rollup`) should be able to build projects that include dependencies using [subpath exports](https://nodejs.org/api/packages.html#subpath-exports), and more generally the [exports field](https://nodejs.org/api/packages.html#exports).

## Actual Behavior

When a project attempts to import from a dependency that uses subpath exports:
- if the subpath exactly matches the actual location in the repo (e.g. `"./src/submodule.js": "./src/submodule.js"`), it works fine
- otherwise, the dependency is not found:
  > Error: 'example/file.js' is imported by src/index.js, but could not be resolved – treating it as an external dependency

This indicates the `exports` field in `package.json` is being ignored entirely.

## Additional context

**The solution** is to upgrade `@rollup/plugin-node-resolve` to its latest version.

We are using `@open-wc/building-rollup v1.10.0`, but the issue is still present in v2. It's caused by using an old version of `@rollup/plugin-node-resolve`, [which is set to `^7.1.1`](https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/package.json#L66). We have resolved the issue on our end by explicitly adding the latest `@rollup/plugin-node-resolve` (v13.3.0) to our Rollup config, and setting `nodeResolve: false` in building-rollup.

Some discussion on Rollup's support of the `exports` field: https://github.com/rollup/plugins/issues/208.

**Comment by web-padawan** [comment]
Updated `@rollup/plugin-node-resolve` to v13 in #2192 and released in `@open-wc/building-rollup` [2.2.0](https://github.com/open-wc/open-wc/releases/tag/%40open-wc%2Fbuilding-rollup%402.2.0). Closing.
