### ISSUE TITLE
Netlify logo src not found in readme file

### ISSUE THREAD

**Issue by shubhraj** [open-wc/open-wc#2470]
## Expected behavior
the Netlify logo should be visible
on the [README.md](https://github.com/open-wc/open-wc#readme) the logo of netlify is not visible due to broken link.
## Actual Behavior

Describe what happens instead.

## Additional context

Which packages and versions are you using.
<img width="949" alt="Screenshot 2022-07-14 at 8 35 29 PM" src="https://user-images.githubusercontent.com/6896791/179014642-7faa807c-30e5-4207-9247-ceb83ca65e53.png">

**Comment by shubhraj** [comment]
would somebody please provide a working link for the logo? so I could update the [README.md](https://github.com/open-wc/open-wc#readme)

**Comment by shubhraj** [comment]
pull request : https://github.com/open-wc/open-wc/pull/2471

**Comment by Westbrook** [comment]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/1156657/196038894-f259e04f-8aca-4cb8-8bc6-448d6e8b7f4c.png">
