### ISSUE TITLE
Inconsistency on using "." @ boolean properties with constant values

### ISSUE THREAD

**Issue by GHNewbiee** [open-wc/open-wc#248]
*Example: `07 Conditional rendering`*

1) The component boolean properties `showMessage` and `disabled` should work without "**.**" since `false` and `true` are constant values, shouldn't it?
2) Either with "**.**" or not, the behaviour of both boolean properties is not consistent!
- Both `disabled=false` & `.disabled=true` AND
- Both `showMessage=false` & `.showMessage=true`
do not behave as expected. Check that into [stackblitz](https://stackblitz.com/edit/open-wc-lit-demos?file=01-basic%2Fbasic-demos.js), too.

*index.html*
```html
...
<conditional-rendering
      message="Hello world!"
      showMessage=true
      disabled=true>
</conditional-rendering>
```

Looking forward to reading your comments.
 
Tia

**Comment by LarsDenBakker** [comment]
Your confusion is regarding the differences in the way HTML and Javascript work. In HTML a boolean attribute is 'true' when it is present. So `<div disabled="false">` actually means that `disabled` is true. That's just how HTML works. 

This is why:

```
<div .disabled=${false}>
```

and 

```
<div disabled="false">
```

produce different results.

**Comment by GHNewbiee** [comment]
@LarsDenBakker Oh I see! **Thanks a lot** for the clarification. So, a boolean property does appear when true is to be passed or, does not at all when false is to be passed. Value does not play any role at all. That's clear!

One more clarification, please. It is generally true that:
```html
<tag attribute="${variable}" .property="${variable}" ?checked="${variable}"></tag>
```
where `property` is NOT any of the element `attributes` (global or specific).

But you wrote: `<div .disabled=${false}>` without *" "*. I know that quotes can be omitted. So, you mean `<div .disabled="${false}">`, don't you? Or I miss something?

Tia om.

**Comment by LarsDenBakker** [comment]
Quotes for properties are optional. Quotes for attributes are optional too but I think not all browsers handle that correctly.
