### ISSUE TITLE
Storybook doesn't work after generating @open-wc

### ISSUE THREAD

**Issue by Pickra** [open-wc/open-wc#2485]
## Expected behavior
I want to generate an instance of `@open-wc` and run storybook, local dev, respectively.

### Workflow
- Run `npm init @open-wc`
  - typescript
  - storybook
  - tests
- Run `npm run storybook`
- Storybook displays example web component

## Actual Behavior
The generator appears to be working but storybook is mad. Maybe related to this [issue](https://github.com/open-wc/open-wc/issues/2378), but it looks like that fix has been released and I attempted this today(Aug 15, 2022).
- `DevTools failed to load source map`
  - related to this [issue](https://github.com/open-wc/open-wc/issues/2445)?
- `Unable to load story '*'`
  - no idea
- `Couldn't find any stories in your Storybook. Please check your stories field of your main.js config.`
  - I didn't change the generated code, and it didn't work any better when I did.
```js
// main.js
module.exports = {
  stories: ['../dist/stories/**/*.stories.{js,md,mdx}'],
};
```

<img width="1654" alt="Screen Shot 2022-08-15 at 3 02 13 PM" src="https://user-images.githubusercontent.com/5226549/184700223-61a62de7-3a69-4f60-85e0-37812fc2b2cb.png">

## Additional context
OS: Mac
node : v14.17.0
npm : 6.14.13

"@custom-elements-manifest/analyzer": "^0.4.17",
"@open-wc/scoped-elements": "2.1.2",
"@open-wc/testing": "3.1.6",
"@web/dev-server": "^0.1.28",
"@web/dev-server-storybook": "0.5.1",
"@web/test-runner": "next",
"concurrently": "^5.3.0",
"lit": "2.2.7"
"lit-html": "2.2.6",
"tslib": "^2.3.1",
"typescript": "^4.5.2"

I feel like I'm missing something obvious. Thank you for your time.

**Comment by thepassle** [comment]
This was fixed in https://github.com/modernweb-dev/web/pull/2018

**Comment by Pickra** [comment]
Thanks @thepassle.
I saw you posted the same comment [here](https://github.com/open-wc/open-wc/issues/2378), which I reference above. I can see that the PR is merged but I can't tell if it was released. It's unclear what I need to do to fix the issue, please advise.

**Comment by Westbrook** [comment]
If you move to these versions, you should be good to go! https://github.com/modernweb-dev/web/pull/2026

**Comment by Pickra** [comment]
That worked! Thank you @Westbrook
