### ISSUE TITLE
Open WC Website: Search Broken

### ISSUE THREAD

**Issue by enqueue** [open-wc/open-wc#2489]
## Expected behavior

Find relevant results when searching for documentation. Example: Find "Semantic Dom Diff" article when entering "Semantic" in the search box and triggering the search.

## Actual Behavior

Search results popup shows "No results found"

![Screenshot_20220826_070152](https://user-images.githubusercontent.com/5407006/186825830-05a214e2-351f-4369-abee-0592c7b4b44a.png)

## Additional context

I have tried this using Firefox 104 on Linux, Chrome 103.0.5112.102 on Windows.

**Comment by olkras03** [comment]
Hi, I am looking for my first open source issue, and would like to try this one. Is it still relevant? I have tried to replicate, it looks like it still doesn't work.

**Comment by thepassle** [comment]
I think @daKmoR should be able to give you some pointers about this 🙂

**Comment by olkras03** [comment]
@thepassle Hi Pascal, I think @daKmoR is busy, do you think someone else could help?

**Comment by web-padawan** [comment]
Looks like the search works now. Closing the issue, please create a new one if the problem persists.

<img width="488" alt="Screenshot 2022-11-17 at 14 18 54" src="https://user-images.githubusercontent.com/10589913/202444478-42f767e1-2fff-44b1-b068-01392bebfd69.png">
