### ISSUE TITLE
Netlify Logo link is not working

### ISSUE THREAD

**Issue by AliFahed** [open-wc/open-wc#2494]
**In README.md file "Supported by" section, the Netlify Logo link is not working.**

![image](https://user-images.githubusercontent.com/90851899/195992894-bcdc3209-b6ee-4760-a992-adc2b1e5c82d.png)

**Comment by Westbrook** [comment]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/1156657/196038731-1573a56f-d774-4dd4-9a11-144feea55055.png">

Fixed! Thanks for pointing this out.
