### ISSUE TITLE
Support Rollup v3.x.x

### ISSUE THREAD

**Issue by michalica** [open-wc/open-wc#2504]
## Expected behavior

Support for rollup v3 and later

## Actual Behavior

Support only v2

## Additional context

is there a plan to support rollup v3? I could not find any issue related to this in the repo.

**Comment by tirithen** [comment]
What is the status on Rollup 3 support?

**Comment by web-padawan** [comment]
Unfortunately, most of us are busy with other projects at the moment. We would need to get together to discuss this.

Personally, I don't have much experience with Rollup internals, although I'd love to learn more and dive into the topic.
But without proper plan and at least some tentative agreement on what to do, I don't know how to approach this.

@daKmoR @LarsDenBakker @thepassle @Westbrook @43081j would you be ok to have a call on Rollup 3 plans?

**Comment by thepassle** [comment]
Support rollup v3 in what, exactly? Is anything particularly blocked on not using rollup v3? The breaking changes in rollup v3 are very minimal, most things should just kind of work with it.

**Comment by web-padawan** [comment]
I'm mostly talking about Web Dev Server and its internals (that also affect Web Test Runner), there are some issues there.
Especially this one https://github.com/modernweb-dev/web/issues/1700 is basically a blocker for newer versions of `@rollup/plugin-commonjs`.

**Comment by thepassle** [comment]
Im confused, those are modern web projects (not open-wc) and those dont necessarily have anything to do with updating to rollup v3?

**Comment by 43081j** [comment]
> I'm mostly talking about Web Dev Server and its internals (that also affect Web Test Runner), there are some issues there. Especially this one [modernweb-dev/web#1700](https://github.com/modernweb-dev/web/issues/1700) is basically a blocker for newer versions of `@rollup/plugin-commonjs`.

even older versions are broken now afaik. the commonjs support in modernweb is extremely lacking, probably due to the mw team not using commonjs themselves anymore i suspect.



> Im confused, those are modern web projects (not open-wc) and those dont necessarily have anything to do with updating to rollup v3?

pretty sure its meant to be a modernweb issue.

dropping openwc and moving everything into modernweb would solve such confusions, just saying :D

**Comment by web-padawan** [comment]
I'd be happy to transfer the issue but looks like it can't be done across different GitHub organisations. Let me create a new one instead.

**Comment by svanherk** [comment]
> I'm mostly talking about Web Dev Server and its internals (that also affect Web Test Runner), there are some issues there.

It looks like these now require rollup `v3` as of Friday:
https://github.com/modernweb-dev/web/releases/tag/%40web%2Fdev-server%400.2.0
https://github.com/modernweb-dev/web/releases/tag/%40web%2Ftest-runner%400.16.0

When I try to use the new versions above with `@open-wc/building-rollup`, `@web/dev-server` and `@web/test-runner` will install their own local copies of `rollup`. 

@Westbrook @koddsson I noticed https://github.com/open-wc/open-wc/pull/2663, will the `rollup` version also be bumped as part of the upcoming release?

**Comment by koddsson** [comment]
> @Westbrook @koddsson I noticed #2663, will the `rollup` version also be bumped as part of the upcoming release?

That's the plan! See https://github.com/open-wc/open-wc/pull/2649 by @Westbrook for the actual change. https://github.com/open-wc/open-wc/pull/2663 was a PR to that PR.
