### ISSUE TITLE
Migration from CustomElements v0 to v1 Spec

### ISSUE THREAD

**Issue by dogoku** [open-wc/open-wc#254]
I'm not sure if you guys are involved at all with CustomElements v0, but there's a decent amount of people (myself included) out there that have been using the v0 spec (in production) and are only now attempting to migrate to the v1 spec, due to Chrome's deprecation warning or limitations in babel.

There are **a lot** of challenges that come with that and I wanted to discuss the potential of documenting some of the challenges and maybe even share some of the tooling to help with such a task.

The 3 main pain points that I have found are:

1. **CustomElements v1 only support ES2015 Classes**. This is a pain point for anyone supporting older browsers like IE11, which is the reality for anyone working in enterprise or finance. Babel 7 is finally able to correctly transpile code correctly, but at the expense of performance and bundle size. The problem can be slightly reduced by having multiple builds (modern+legacy) and esmodule support detection, but it is still to the detriment of older browsers that will still have to run the bloated transpiled code.

2. **No tooling to migrate CustomElement v0 to v1**. I have started working on a set of [codemods](https://github.com/dogoku/ce-codemods) that can be run using jscodeshift, that work for a few common v0 patterns and will transform a custom element written in v0 ES5 to v1 ES2015+. It is still far from perfect, but I'm willing to contribute this to open-wc if it will help others. Honestly most of the heavy lifting of ES5>ES2015 is done by [lebab](https://github.com/lebab/lebab) I'm just adding the extra transforms relevant to custom elements.

3. **Breaking change in specification during element creation**. The v0 spec allowed us to edit attributes and add/remove children elements inside the createdCallback. The v1 spec does not allow that in the constructors. **This is probably the biggest problem for anyone that has a non-trivial v0 codebase**, as there a countless of cases where a custom element would create a child custom element that would initialise itself with some children or attributes (and so on...) all within a createdCallback. I currently could not find a solution for this, other than re-writing your code to not initialise elements during construction...

The internet has very little information about this, outside of spending hours going over github discussion. In summary, it would be good to at least try and document some of the solutions. I'd love to hear your thoughts on this.

Thanks

**Comment by daKmoR** [comment]
hey, that sounds pretty nice - and we are definitely interested in a setup with code mods :)

we probably can't help out much in this particular case as our focus is more on the v1 spec => but we are more than happy to provide a platform for it :hugs: 

what would you see as the next steps? create an intial markdown documentation file? where how would you see it linked?

**Comment by dogoku** [comment]
> hey, that sounds pretty nice - and we are definitely interested in a setup with code mods :)

Yeah sure, I can help with a codemod setup, based on what I have done on my own. 

I have tried a couple of different parsers [using astexplorer.net](https://astexplorer.net/) but in the end I chose jscodeshift because it seems to preserve codestyle a bit better, without having to add another transform like prettier or eslint at the end and because their API and CLI was straightforward to use.

On top of that I setup a test framework using Jest Snapshots, which are a perfect match for testing this sort of programs that have no side effects and you only need to worry about the output.

I am not sure how you could integrate something like this into your existing tooling, especially if I'm hearing talks about generators 😨, but maybe you have a bigger picture in mind. 

> what would you see as the next steps? create an intial markdown documentation file? where how would you see it linked?

I could come up with a draft markdown (based on my rant from above), but I am not sure where it could go. Maybe under Introduction section or part of FAQ.

**Comment by thepassle** [comment]
Id say this is a better fit for the FAQ rather than the introduction

**Comment by stramel** [comment]
There are a few things that are really easy to transform but it could easily just be a section talking about how to migrate.

I had implemented some rules in Polymer linter to handle a few things. https://github.com/Polymer/tools/issues/1051

Here was the checklist gist that I came up with at my last company to help us during the conversion of Polymer v1 to v2. Some of these things are more Polymer specific but it also covers v0 to v1 things. https://gist.github.com/stramel/e552fe3e951d2185342a989918c31e33

**Comment by dogoku** [comment]
> Id say this is a better fit for the FAQ rather than the introduction

@thepassle sure, that sounds like the right place to me too. It'll probably take me a few days to get time to write something up (this weekend I'm running tests on Canary 74, which deprecated v0 spec on Friday)

@stramel thanks for your reply, that's helpful and it would be good to have a second pair of eyes that worked on a migration like this.

By the way, we found a workaround for the 3rd problem I mentioned above, which involves using `innerHTML` or `insertAdjacentHTML` to create elements, instead of `document.createElement` which seems to bypass the limitations (no attribute/children changes in constructor). Here's a [fiddle](https://jsfiddle.net/2fbsnc3w/1/) with a basic example, but the important code is: 

```js
var root = document.createElement('div');
function createElement(n) {
  root.insertAdjacentHTML('afterbegin', `<${n}></${n}>`);
  return root.removeChild(root.firstElementChild);
}
```
I have tested this, by upgrading a few of our components to v1, then instantiated the elements in various ways (inline html, calling constructor, createElement from above) and so far everything is working fine. 

Can anyone think of any cases this would breakdown? Or any reason to avoid this? (e.g performance)

**Comment by daKmoR** [comment]
as additional info you can register for chrome origin trial to get extended support for webcomponents v0 if you need.

Some details here: https://github.com/GoogleChrome/OriginTrials
registration here: https://developers.chrome.com/origintrials/#/trials/active

**Comment by daKmoR** [comment]
how about adding this as another deep dive to the FAQ section?
https://open-wc.org/faq/
