### ISSUE TITLE
Quick question, does this library can work in purely Angular webapps?

### ISSUE THREAD

**Issue by dani-oropeza-nic** [open-wc/open-wc#2545]
I would like to know if this library can work in purely Angular web applications. I saw in the description that is says that works with lit-html templates and custom elements. I mean, right now, I'm trying to add some accessibility linter rules to our Angular webapps, I would like to know if with eslint-plugin-lit-a11y that can be possible. We're not using lit-html at all, just normal Angular apps.

**Comment by web-padawan** [comment]
The `eslint-plugin-lit-a11y` internally uses the `TemplateAnalyzer` API from [eslint-plugin-lit](https://github.com/43081j/eslint-plugin-lit/blob/master/src/template-analyzer.ts) that supports Lit templates (tagged literal expressions). If you're writing templates in Angular, you might need another plugin, see [this blog post](https://dev.to/bitovi/angular-a11y-eslint-rules-2fjc).

**Comment by dani-oropeza-nic** [comment]
In our app we are not using literal expression at all. It is just Angular, so we're saying that eslint-plugin-lit-a11y does not work without literal Lit templates?

**Comment by web-padawan** [comment]
> eslint-plugin-lit-a11y does not work without literal Lit templates?

Yes, it's not going to work for Angular templates. Closing this issue as this is out of the scope for the plugin.
