### ISSUE TITLE
Typescript dependency too low

### ISSUE THREAD

**Issue by DaveStein** [open-wc/open-wc#2557]
## Expected behavior
When I run `npm init @open-wc` for a typescript project, it should use the right eslint versions. The ones that work with the generated app are:

```
"@typescript-eslint/eslint-plugin": "^5.48.0",
"@typescript-eslint/parser": "^5.48.0",
```

## Actual Behavior

The app starts with:

```
"@typescript-eslint/eslint-plugin": "^4.33.0",
"@typescript-eslint/parser": "^4.33.0",
```

Therefore it does not properly detect when `@property` decorator is used within generated sample files.

## Additional context

Found the solution via https://stackoverflow.com/questions/73591752/eslint-wong-error-is-defined-but-never-used-warning-in-nestjs-for-all-decorato

**Comment by thepassle** [comment]
thanks, fixed
