### ISSUE TITLE
live, spread, and spreadProps are missing from NPM

### ISSUE THREAD

**Issue by break-stuff** [open-wc/open-wc#2576]
## Expected behavior

I installed the `lit-helpers` package (`npm i @open-wc/lit-helpers@next`) so I could use the `spread` directives.

## Actual Behavior

I was getting an error that `spread` was not an exported member of the `lit-helpers` package. After inspecting my `node_modules` I found that only the `ReadOnlyPropertiesMixin` was present.

![image](https://user-images.githubusercontent.com/31320098/216668692-55fa22f9-880c-4763-9d2d-73a89d589b69.png)

**Comment by thepassle** [comment]
Which version are you using? I see a lot more files on unpkg: https://unpkg.com/browse/@open-wc/lit-helpers@0.5.1/src/

**Comment by break-stuff** [comment]
Interesting. Running `npm i @open-wc/lit-helpers@next` installs `0.4.0-next.1` and running `npm i @open-wc/lit-helpers` installs `0.4.1`

**Comment by Westbrook** [comment]
That also not the most recent version of that package. Please try installing: https://www.npmjs.com/package/@open-wc/lit-helpers/v/0.5.1

**Comment by break-stuff** [comment]
After running `npm i @open-wc/lit-helpers@0.5.1` I see them in there. I wonder why npm is giving me those old versions. That happened on two separate machines - one was on a VPN and the other was not.

**Comment by Westbrook** [comment]
`0.5.0` is technically a breaking change away from `0.4.0`, so it wouldn't resolve between the two of them without manual intervention.
