### ISSUE TITLE
show reactions diagram somewhere

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#259]
https://andyogo.github.io/custom-element-reactions-diagram/

**Comment by thepassle** [comment]
I'd say this is a great one for the faq as well

**Comment by daKmoR** [comment]
jup it's a good place for it 👍

**Comment by LarsDenBakker** [comment]
maybe we should have general web component basics docs?

**Comment by daKmoR** [comment]
> maybe we should have general web component basics docs?

question is... is that something we wanna do or should this be with lit-element documentation or so?

**Comment by daKmoR** [comment]
added to FAQ
