### ISSUE TITLE
@open-wc/building-rollup has rollup-plugin-terser as dependency

### ISSUE THREAD

**Issue by michalica** [open-wc/open-wc#2684]
## Expected behavior

**@open-wc/building-rollup** should not have **rollup-plugin-terser** as dependency. This library is no longer maintained. 

## Actual Behavior

**@open-wc/building-rollup**  has **rollup-plugin-terser** as dependency 

## Additional context

**rollup-plugin-terser** has peerDep. rollup version 2. Therefore, we can't update to rollup version 3.

**Comment by ca-d** [comment]
Could https://www.npmjs.com/package/@rollup/plugin-terser be used instead?

**Comment by svanherk** [comment]
> Could https://www.npmjs.com/package/@rollup/plugin-terser be used instead?

It looks like a PR to do just that was [opened back in April](https://github.com/open-wc/open-wc/pull/2664), but it hasn't received a review or any comments on what needs to be done to get it merged.

This is also blocking us from moving to `rollup` v3.

**Comment by thepassle** [comment]
Fixed via https://github.com/open-wc/open-wc/pull/2664#issuecomment-1629675993

**Comment by svanherk** [comment]
Amazing, thanks @thepassle and @koddsson!
