### ISSUE TITLE
building-rollup: No matching version found for @open-wc/building-utils@^3.0.0

### ISSUE THREAD

**Issue by palash2601** [open-wc/open-wc#2685]
Installation of `@open-wc/building-rollup` version 3.0.0 fails as requisite transitive dependency @open-wc/building-utils@^3.0.0 is not available

## Expected behavior

`npm i @open-wc/building-rollup` should work

## Actual Behavior

`npm i @open-wc/building-rollup` fails with below error

> No matching version found for @open-wc/building-utils@^3.0.0

## Additional context

`@open-wc/building-utils@^3.0.0` should be published to npm

**Comment by lion7** [comment]
Probably caused because of https://github.com/open-wc/open-wc/actions/runs/5217175202/jobs/9416724427#step:6:105

**Comment by thepassle** [comment]
Looks like something went wrong with the publish of the package indeed. I just released 3.0.1, so this should be fixed
