### ISSUE TITLE
Bump lit-helpers to support lit@3

### ISSUE THREAD

**Issue by alexgagnon** [open-wc/open-wc#2713]
Hi, anything I can do to get this released to support Lit 3?

**Comment by Westbrook** [comment]
A PR moving `^2.0.0` listings to `^2.0.0 || ^3.0.0` would be a great start. 

Any thoughts you’d have on a testing path for both versions would be great to hear as well!

**Comment by jitendraP-ashutec** [comment]
When we can expect you will merge this PR and we get updates.

Thanks
