### ISSUE TITLE
New project doesn't work

### ISSUE THREAD

**Issue by alexei** [open-wc/open-wc#2754]
Initialising a new project with `npm init @open-wc` sets up a project that doesn't work.

When running `yarn install`, one gets warned that two packages are missing:

- `@babel/core`, required by `@rollup/plugin-babel` and `@babel/preset-env`
- `esbuild`, required by `rollup-plugin-esbuild`

Then `yarn run lint` and `yarn run format` have missing packages as well, and one has to run the commands repeatedly to figure out the next package they should install:

- `eslint-plugin-wc`
- `eslint-plugin-lit-a11y`
- `eslint-plugin-lit`
- `eslint-plugin-html`
- `eslint-plugin-no-only-tests`
- `eslint-plugin-import`
- `@babel/plugin-syntax-import-assertions`

`yarn run test` requires `@web/test-runner-playwright` and `playwright` which are of course missing. Besides, the template seems to create a `web-test-runner.config.js` and a `web-test-runner.config.mjs`, though only one is needed. Perhaps one should be warned that `web-test-runner.config.mjs` takes priority and updating `web-test-runner.config.js` while keeping around the other has no effect. On another note, the imports in the config file are commented out for some reason.

`yarn run analyze` doesn't work: `sh: cem: command not found`. Only God knows what `cem` is! I suppose it has to do with `@custom-elements-manifest/analyzer`, which exists as a dependency, but somehow doesn't provide a `cem` command. And because `yarn run build` and some other coomands also run `analyze`, they fail too.

`yarn run storybook` doesn't work either, even if you drop the `analyze` part: a `prismjs` package is missing, and two required files don't exist, `.storybook/server.mjs` and `.storybook/main.js` respectively. I initialised them using the sample code at https://modern-web.dev/guides/dev-server/storybook/ and I got yet another error:

```
Error: require() of ES Module .../.storybook/main.js from .../node_modules/@web/dev-server-storybook/dist/shared/config/readStorybookConfig.js not supported.
```

I've no idea what that means and at this time I'm too tired to look it up on the Internet.

Are there any plans to making it work?

**Comment by Westbrook** [comment]
@najikahalsema has been looking at catching up various version and configs herein. Hopefully have an update in the next couple of weeks.

**Comment by AntonyF-Andreani** [comment]
This looks that problem of peerDependencies ? (yarn doesnt install automatically)

**Comment by Kikketer** [comment]
Thanks @AntonyF-Andreani that worked.

**Comment by Westbrook** [comment]
The Storybook build in the template has been updated quite extensively. If you encounter new issues in this area, please feel free to open a new issue. However, for now, be sure to use `npm init @open-wc@latest` to break any local cache you may have create when initializing previous projects.

**Comment by alexei** [comment]
Thanks for the follow-up @Westbrook My original comment was not about Storybook, but about the fact that the initial project didn't work at that time. None of the messages in this thread even remotely attempt to acknowledge that. They all seem to be about Storybook. As you can image, I've decided on 28 November 2023 that open-wc was a mess and I should stay away from it. But thanks for sharing 7 months later that Storybook finally works.
