### ISSUE TITLE
types are not correct for esm usage

### ISSUE THREAD

**Issue by philkunz** [open-wc/open-wc#2781]
@open-wc/semantic-dom-diff/chai-dom-diff-plugin.d.ts (3,29): Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './get-diffable-html.js'?

This is an issue all across @open-wc modules.

**Comment by Westbrook** [comment]
Closed by #2777
