### ISSUE TITLE
Missing building-rollup generator

### ISSUE THREAD

**Issue by mario-aleo** [open-wc/open-wc#279]
`npm init @open-wc building-rollup` is throwing an error:
`Could not find generator at /<npm init path>/.npm/_npx/1497/lib/node_modules/@open-wc/create/dist/generators/building-rollup/index.js`

I took a look at the master branch and it's really missing the rollup-building folder at open-wc/packages/create/src/generators.

![image](https://user-images.githubusercontent.com/13382278/54124532-6acc7e80-43e1-11e9-9126-b63984de0441.png)

**Comment by daKmoR** [comment]
oh it seem we have been a little eager with adding that info... it does not exist yet 🙈

maybe you could help out adding it? 🤗

**Comment by mario-aleo** [comment]
Yeah, sure, I'll be glad to help :D

**Comment by daKmoR** [comment]
thx for the contribution it's now released 💪
