### ISSUE TITLE
[building-rollup] example npm build command doesn't work

### ISSUE THREAD

**Issue by budajeff** [open-wc/open-wc#283]
After following the "Building Rollup" instructions I ran "npm run-script build" and got this output:

jeff@jeff:~/git/lit4$ npm run-script build

> lit4@1.0.0 build /home/jeff/git/lit4
> rimraf dist && rollup

rollup version 1.6.0
=====================================

Usage: rollup [options] <entry file>

Basic options:

-c, --config <filename>     Use this config file (if argument is used but value
                              is unspecified, defaults to rollup.config.js)`

Which to me means the "build" command in package.json is not correct such that rollup can't find the config file.

I modified that build command in my `package.json` to be `rimraf dist && rollup -c rollup.config.js` and I got this error:

`jeff@jeff:~/git/lit4$ npm run-script build

> lit4@1.0.0 build /home/jeff/git/lit4
> rimraf dist && rollup -c rollup.config.js

[!] SyntaxError: Unexpected token import
/home/jeff/git/lit4/node_modules/@open-wc/building-rollup/modern-config.js:1
(function (exports, require, module, __filename, __dirname) { import resolve from 'rollup-plugin-node-resolve';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)`

I've never used rollup before. Any ideas on how to get the example working?

**Comment by thomasd** [comment]
I'm having the same problem.
Also changed the build command to `rimraf dist && rollup -c`
Just a slightly different error message:

> [!] SyntaxError: Unexpected identifier
> c:\\...\node_modules\@open-wc\building-rollup\modern-and-legacy-config.js:1
> import resolve from 'rollup-plugin-node-resolve';
>        ^^^^^^^
> 
> SyntaxError: Unexpected identifier
>     at Module._compile (internal/modules/cjs/loader.js:743:23)
>     at Module._extensions..js (internal/modules/cjs/loader.js:810:10)
>     at Object.require.extensions..js (c:\\...\node_modules\rollup\bin\rollup:1132:17)
>     at Module.load (internal/modules/cjs/loader.js:666:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:598:3)
>     at Module.require (internal/modules/cjs/loader.js:705:19)
>     at require (internal/modules/cjs/helpers.js:14:16)
>     at Object.<anonymous> (c:\\...\rollup.config.js:7:43)
>     at Module._compile (internal/modules/cjs/loader.js:799:30)

**Comment by rbjarnason** [comment]
I have exactly the same problem.

**Comment by LarsDenBakker** [comment]
Thanks for the reports guys.

Running rollup without a config file specified means it will try to find it in the current working directory as `rollup.config.js`. Perhaps it's good to always specify it in the examples.

Which version of node and rollup are you guys using? `node -v` and `npx rollup -v`

And could you list the the rollup config you guys are using?

**Comment by rbjarnason** [comment]
Thanks for quick reply.

Node: v10.15.3
Rollup v1.6.0

I needed to provide the -c flag for rollup to look in the current directory, I added that to get the import error.

rollup.config.js
import createDefaultConfig from '@open-wc/building-rollup/modern-and-legacy-config';
export default createDefaultConfig({ input: './index.html' });

**Comment by djlauk** [comment]
I have the same issue.

- node: 10.15.2
- yarn: 1.13.0
- rollup: 1.6.0
- @open-wc/building-rollup: 0.1.2

I also had to change the invocation to `rollup -c`. From what I understand, Rollup requires the `-c` option even for the default config file name and location. Just running `rollup` will only print usage instructions.

**Comment by LarsDenBakker** [comment]
Rollup supports writing your config as an es module, but apparently it doesn't support it when it's imported from node_modules.

We will have to rewrite our configs as regular common js modules, and update the readme to always specify the config file. Will do that ASAP

**Comment by LarsDenBakker** [comment]
We've released @open-wc/building-rollup: 0.1.3, please test and see if it works for you.

**Comment by djlauk** [comment]
v0.1.3 works for me, Rollup started its work now:

```sh
$ yarn run build
yarn run v1.13.0
$ rimraf dist && rollup -c

./index.html → dist...
```

The last line did not appear until the update. 🎉

The build still breaks down the road, but that seems to have to do with our code. Rollup previously did not even make it into our code base...

Huge thank you!

**Comment by djlauk** [comment]
One more thing: It trips over the dynamic import polyfill.
As per discussions on slack: I'll prepare a PR with a suggested fix.

**Comment by rbjarnason** [comment]
Works for me as well now.

**Comment by LarsDenBakker** [comment]
Thanks guys. I'll close this now !
