### ISSUE TITLE
[create] npm init @open-wc: 'command failed: command -v yarn'

### ISSUE THREAD

**Issue by jorenbroekema** [open-wc/open-wc#284]
## Description
This is on node v10.15.3 and npm v6.9.0

I tried to do `npm init @open-wc` and install barebone or starter app. Both fail due to an error when firing `command -v yarn`

### Windows 10
```
Installing dependencies...
This might take some time...
{ Error: Command failed: command -v yarn
'command' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'command -v yarn',
  stdout: '',
  stderr:
   '\'command\' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n' }
```

### Linux Ubuntu 16.04
```
Installing dependencies...
This might take some time...
{ Error: Command failed: command -v yarn

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 127,
  signal: null,
  cmd: 'command -v yarn',
  stdout: '',
  stderr: '' }
```

Here is where it fails https://github.com/open-wc/open-wc/blob/master/packages/create/src/core.js#L107

If I run `command -v yarn` in my bash terminal it works just fine both for windows 10 and linux and prints the installation path of my yarn. So it seems like it not working has something to do with node trying fire it.

I did some googling but couldn't really find the problem, and since the command is literally command it's quite hard to find good search results haha.

Let me know if you guys have some suggestions on how to fix, I'm happy to try to test out suggestions and make MR if it works.

**Comment by daKmoR** [comment]
this is "just" the last step if doing an automatic npm install so everything should be fine... you would only need to do the npm install yourself...

still strange that it fails...

**Comment by jorenbroekema** [comment]
Ah I guess if it's the last step, that's a good workaround for now :P

**Comment by jorenbroekema** [comment]
Btw, perhaps this is unrelated, but I tried doing `npm init @open-wc linting` and, as expected, it gives the same error, but it also does not add the config files 
```
husky.config.js
.eslintignore
.eslintrc.js
commitlint.config.js
.prettierignore
```

**Comment by Biggisb** [comment]
Hey there, some problem in windows 10, it only crates /src and package.json. 
So manuell npm/yarn install or npm/yarn start works but my "Demo server" is not working so i guess some files are "missing"
