### ISSUE TITLE
[demoing] improve docs

### ISSUE THREAD

**Issue by bennypowers** [open-wc/open-wc#289]
Having run through a fairly involved lerna/storybook project, I feel like i have what to contribute to the demoing docs. This issue serves as a dumping ground for partially-formed ideas until I have the headspace to organize a proper docs revision.

## what and why
- storybook is for showing off components in isolation. 
- helps for 'storybook driven development'
- can be useful in catching bugs that unit tests wouldn't
- can produce rich documentation sites
- you can use 'knobs' to interact your components API
- QUESTION: how can you easily two-way bind component apis to knobs? events?
- NB: lit-html is part of storybook core. cool!

## withTemplate
tiny abstraction to DRY out story files
```js
import '../src/fc-autocomplete';
import { FcAutocomplete } from '../src/FcAutocomplete';

const withTemplate = (template, overrides) => withClassPropertiesKnobs(FcAutocomplete, { template, overrides });
```

## deep array serialize in knobs:
also shows off withtemplate, and how to show component output onscreen if it's not immediately rendered. `withClassPropertiesKnobs` applies `array` knob to props with type array. array knob assumes scalar values. `object` knob however de/serializes with json.parse/stringify. use `overrides` to use object knob.

```js
function complexData() {
  const onSelect = ({ detail: { value }}) =>
    document.querySelector('output').innerText = value;

  return html`${withTemplate(html`
    <fc-autocomplete
        @select="${onSelect}"
        .items="${[
          { key:'Forter', value: 1 },
          { key:'Components', value: 2 },
          { key:'for you', value: 3 },
        ]}"
    ></fc-autocomplete>
  `, el => [
    { key: 'items', fn: () => object('items', el.items, 'Inherited') },
  ])}
  <dl>
    <dt>Selected Value</dt>
    <dd><output></output></dd>
  </dl>
  `;
}
```

## css custom properties
```js
function hoverable() {
  return html`
    <style>
    fc-icon {
      --fc-icon-fill-hover: ${color('--fc-icon-fill-hover', 'orange')};
    }
    </style>
    ${withTemplate(html`
      <fc-icon hoverable></fc-icon>
    `)}
  `;
}

(storiesOf('<fc-icon>', module)
  .addDecorator(withKnobs)
  .add('Hoverable', hoverable, docs)
);
```

**Comment by daKmoR** [comment]
@bennypowers any chance you can do something for it in any time soon?

**Comment by bennypowers** [comment]
@daKmoR Thanks for the reminder. I've been pretty busy. With Passover just finished, I hope to have some time to get on this. I'll try to get something out the door, even something minimal, by the end of the week.
