### ISSUE TITLE
[building-webpack] Index.html script undefined

### ISSUE THREAD

**Issue by jorenbroekema** [open-wc/open-wc#342]
Currently, using building-webpack, it is not properly bundling my entry point js and linking it in the entry point html. 

I used `npm init @open-wc building-webpack` in the root folder of my app.

Setup:
Windows 7
Node: 10.15.1
NPM: 6.9.0
Yarn: 1.13.0

Folder structure:
```
my-app
| -- dist
    | -- legacy
    | -- polyfills
    | -- index.html
    | -- main.[chunkhash].js
    | -- main.[chunkhash].js.map
| -- packages
    | -- my-app/src
        | -- index.html
        | -- my-app.js 
| -- .browserslistrc
| -- package.json
| -- webpack.config.js
| -- yarn.lock
```

`webpack.config.js`:
```js
const { resolve } = require('path');
const createDefaultConfig = require('@open-wc/building-webpack/modern-and-legacy-config');

// If you don't need IE11 support, use the modern-config instead
// import createDefaultConfig from '@open-wc/building-webpack/modern-config';

module.exports = createDefaultConfig({
  entry: resolve(__dirname, './packages/my-app/src/my-app.js'),
  indexHTML: resolve(__dirname, './packages/my-app/src/index.html'),
});
```
src/my-app.js
```js
import { LionLitElement, html } from 'ing-web/core';

class MyApp extends LionLitElement {
  render() {
    return html`
      <h1>Hello world!</h1>
    `;
  }
}

customElements.define('my-app', MyApp);
```

src/index.html
```html
<html>
  <head></head>
  <body>
    <my-app></my-app>
  </body>
</html>
```

dist/index.html
```html
<html>
  <head><link rel="preload" href="main.0f31193ba01e5fb5d98e.js" as="script"></head>
  <body>
    <my-app></my-app>
  <script src="polyfills\babel.js" nomodule></script><script>undefined</script></body>
</html>
```
^ Especially this one gives unexpected results. 

When running `"http-server dist/ -o"` I get the following console error in latest Chrome:
![image](https://user-images.githubusercontent.com/36734656/55334034-baf6a800-5498-11e9-9894-56d594b2c7fd.png)

Another unrelated buggy thing is that `http-server` is not part of the devDependencies of building-webpack package.json, while it is used in one of the scripts. That should probably also be fixed.

**Comment by jorenbroekema** [comment]
Update: This seems to be a Windows only bug. I tested this just now on Windows 10, same issue where it doesn't build properly.

On MacOS (Mojave) however, it works completely fine..

**Comment by LarsDenBakker** [comment]
This is definitely an issue. This is where we create the script: https://github.com/open-wc/open-wc/blob/master/packages/building-webpack/src/modern-web-webpack-plugin.js#L200

My guess is that terser returns undefined because it did not receive valid code. Usually this is a path related issue. I'm using `/` all over the place, it's posible this is creating an issue somewhere...

Unfortunately, I don't have a windows machine to debug this :(

**Comment by daKmoR** [comment]
hmmm I use windows10 (with WLS ubuntu) and that works fine as well...
so I guess only a problem on a pure windows...
