### ISSUE TITLE
Hot reload / watching-files-during-develop-and-reload-in-browser not present?

### ISSUE THREAD

**Issue by frederikhors** [open-wc/open-wc#363]
I'm wrong or no `hot reload` mechanism is available using start as `npm init @open-wc my-app`?

I would love to see the changes in browser as I edit my js files.

NOTE: I'm developing using `npm start`. **Is this correct?**

**Comment by daKmoR** [comment]
hey, yes I'm afraid that is a missing feature which has been on our ToDo list for a long time 🙈 

it should actually not be too hard to integrate https://www.browsersync.io/ into the owc-dev-server... care to take a stab at it?

**Comment by LarsDenBakker** [comment]
You could look into https://github.com/phaux/es-serve, I've been meaning to look into that as well

**Comment by daKmoR** [comment]
implemented in the latest release 💪
