### ISSUE TITLE
Problem with a SPA and owc-dev-server (--app-index)

### ISSUE THREAD

**Issue by frederikhors** [open-wc/open-wc#368]
I'm having troubles using the default `start` script in `package.json`.

The default one is:

```json
"start": "owc-dev-server --open ./src"
```

but I'm building a SPA (single page application) and I changed it to:

```json
"start": "owc-dev-server --app-index ./src/index.html"
```

adding also in `index.html`'s `<head>`:

```html
<base href="/">
```

But now the problem is:

```html
<script type="module" src="./my-app.js"></script>
```

In browser's console I got this error:

```error
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

I need to change it like this to work:

```html
<script type="module" src="./src/my-app.js"></script>
```

adding `./src` before `/my-app.js`.

The problem now is using `npm run build`: it doesn't find `my-app.js` during build.

I'm wrong somewhere, but where?

**Comment by LarsDenBakker** [comment]
If you have a `<base href>` files are resolved relative to that. So in this case your `base` is `/` so `<script type="module" src="./my-app.js"></script>` is resolved from `/my-app.js` in your project. If you set your `base` to `/src/` things will start working for you.

Serving SPAs is quite a mind mending game of going back and forth between file paths, web server paths, browser URLs and the way each of these systems resolves paths. I need to do a deep dive to see how this can be documented in a good way, and how we can ahve better defaults for this.

In general it's recommended to put your `index.html` in the root of your project, that makes it easy to find your `node_modules` folder and creates the least amount of issues. @daKmoR @thepassle I think our generator is off here.

**Comment by frederikhors** [comment]
Stale, I hate you!

**Comment by LarsDenBakker** [comment]
We've moved the index.html to the root of the project now, so this should work correctly now right?

**Comment by snelson25** [comment]
Putting index.html in the root of the generated starter app project now breaks the "npm run start" command with the error:

`Cannot GET /src/`

**Comment by LarsDenBakker** [comment]
You need to adjust the open path on the start command to / and adjust the import of your js files to reflect the move

**Comment by snelson25** [comment]
Sure, I can easily make the change on my system to get everything working.

I offered the comment because newcomers who diligently follows the instructions on https://open-wc.org/init/#usage to generate the starter app will see the error instead of the starter app.   Not a good first experience.

**Comment by LarsDenBakker** [comment]
Yes indeed, I fully agree. Ive fixed the scaffold to set it up correctly now!

**Comment by LarsDenBakker** [comment]
Closing this as it's fixed and we're using es-dev-server now.
