### ISSUE TITLE
Webpack config does not preserve template casing

### ISSUE THREAD

**Issue by tpluscode** [open-wc/open-wc#372]
I have a binding lit-html like `.featureStyle="${this.getStyle}"`.

When built in production mode, this turns to `.featurestyle="${this.getStyle}"`. (property becomes all lower case, which of course breaks all usage of case sensitive properties.

To fix that, `caseSensitive: true` should be added to `htmlMinifier` config object as mentioned in cfware/babel-plugin-template-html-minifier#11

https://github.com/open-wc/open-wc/blob/master/packages/building-webpack/modern-config.js#L86

**Comment by LarsDenBakker** [comment]
I looked into this, and it's indeed an issue. Adding `caseSensitive: true` sounds like the right approach.
