### ISSUE TITLE
[docs] Update Generators page

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc#374]
https://open-wc.org/developing/create.html#available-scaffold-generators

Is out of date, we should check for inconsistencies and update; e.g.: it says the starter-app still uses building-webpack (it uses building-rollup), and there might be other things that have gotten out of sync recently.

In case anyone wants to pick this up, you can check which individual generators a generator uses by going to `open-wc/packages/create/src/generators/<some-generator>/index.js` and seeing which mixins it uses:  https://github.com/open-wc/open-wc/blob/master/packages/create/src/generators/starter-app/index.js#L9

So for example, the [starter-app generator](https://github.com/open-wc/open-wc/blob/master/packages/create/src/generators/starter-app/index.js#L9) uses:
- Building
- Testing
- Linting

In turn, the [linting generator](https://github.com/open-wc/open-wc/blob/master/packages/create/src/generators/linting/index.js#L7) uses:
- Commitlint
- Prettier
- Eslint

etc etc

**Comment by daKmoR** [comment]
generators got quite refactored 💪  not sure if this still holds true - gonna close it for now... if there is something concrete to do feel free to reopen or create a new issue
