### ISSUE TITLE
[docs] add non standard syntax warning

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc#385]
https://open-wc.org/building/building-webpack.html#_1-babel

- Add non standard syntax warning: "We do not recommend non-standard syntax(link to rationale?), however, if you do want to use it... etc etc"
- remove backtics
- change: "Supporting `LitElement`'s **`@customElement` and `@property`**" to "Supporting LitElement's **decorators**"

**Comment by LarsDenBakker** [comment]
There is already a warning above this section:
```
Some extensions add non-native syntax to your code, which can be bad for maintenance longer term. We suggest avoiding adding plugins for using experimental javascript proposals or for importing non-standard module types.
```

Agreed we should change the name. I think it can be even more generic saying something like 'supporing decorators'.
