### ISSUE TITLE
Webpack production: camelCase properties in tagged template literal lowered cased in prod build

### ISSUE THREAD

**Issue by ggriffithsIDBS** [open-wc/open-wc#388]
I've been using the "building-webpack" package  1.3.0 and i'm seeing that when i run a prod build my properties in lit-html html`` are getting lower cased:

example
![image](https://user-images.githubusercontent.com/30403877/56134066-b399c900-5f85-11e9-8f8b-6de9622d368e.png)
output:
![image](https://user-images.githubusercontent.com/30403877/56134117-d88e3c00-5f85-11e9-812a-f64bd3d2aa0c.png)

(development mode is fine)

Workaround: i went into the config and removed this babel plugin:
```
         !development && [
                  'template-html-minifier',
                  {
                    modules: {
                      'lit-html': ['html'],
                      'lit-element': ['html', { name: 'css', encapsulation: 'style' }],
                    },
                    htmlMinifier: { collapseWhitespace: true, removeComments: true },
                  },
                ]
```
doing this caused the issue to go away, any ideas? is this a defect?

**Comment by LarsDenBakker** [comment]
Thanks for your report!

Please update to building-webpack 1.3.3, we fixed this in: https://github.com/open-wc/open-wc/pull/383

**Comment by ggriffithsIDBS** [comment]
@LarsDenBakker  best news ever!

**Comment by ggriffithsIDBS** [comment]
Sorry for the duplicate, my searching wasn't quite good enough
