### ISSUE TITLE
Building generator is broken.

### ISSUE THREAD

**Issue by jorenbroekema** [open-wc/open-wc#390]
https://github.com/open-wc/open-wc/tree/master/packages/building-webpack  installation instructions are wrong. Upgrade -> Building -> Webpack is not a thing. You can only select Upgrade -> Building, and then nothing happens.

also, `npm init @open-wc building-webpack` used to work 2 weeks ago but now I get:

```
$ npm init @open-wc building-webpack
npx: installed 29 in 15.997s
C:\<user>\AppData\Roaming\npm-cache\_npx\15292\node_modules\@open-wc\create\node_modules\command-line-args\dist\index.js:1345
        throw err
        ^

UNKNOWN_VALUE: Unknown value: building-webpack
    at commandLineArgs (C:\<user>\AppData\Roaming\npm-cache\_npx\15292\node_modules\@open-wc\create\node_modules\command-line-args\dist\index.js:1342:21)
    at Object.<anonymous> (C:\<user>\AppData\Roaming\npm-cache\_npx\15292\node_modules\@open-wc\create\dist\generators\app\index.js:72:48)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\<user>\AppData\Roaming\npm-cache\_npx\15292\node_modules\@open-wc\create\dist\create.js:12:14)
```
Additionally the manual setup doesn't work out of the box either:
```
npm i -D @open-wc/building-webpack webpack http-server webpack-dev-server
```
because it should say `webpack-cli` instead of `webpack` .

Actually I found another issue:
```js
const { resolve } = require('path');
const createDefaultConfig = require('@open-wc/building-webpack/modern-and-legacy-config');

// If you don't need IE11 support, use the modern-config instead
// import createDefaultConfig from '@open-wc/building-webpack/modern-config';

module.exports = createDefaultConfig({
  input: path.resolve(__dirname, './src/index.html'),
});
```
This is the code snippet from the manual setup from the docs, the very first line should be `const path = require('path');`

This is on Windows 7, node v10.15.1, npm v6.9.0

With the amount of bugs regarding the generators I've faced in the last few weeks, it really bugs me that this keeps happening, and I would really encourage you guys to write thorough tests for them :\

**Comment by daKmoR** [comment]
I'm afraid the api changed quite a bit :see_no_evil: 
in short `npm init @open-wc building-webpack` is no longer supported... it's an option based workflow now (without separate entry points for everything).

If you don't want to upgrade feel free to use the "old" version :hugs: 
unfortunately, it seems `npm init` does not allow to specify a version it will always pick the latest one... but you can just use `npx`
```
npx @open-wc/create@0.7.1 building-webpack
```

**Comment by daKmoR** [comment]
>  Upgrade -> Building -> Webpack is not a thing. You can only select Upgrade -> Building, and then nothing happens.

just tested it in window10 powershell (where I could reproduce windows bugs before)
works fully for it...

maybe you just hit enter on the features screen?
![building-upgrade](https://user-images.githubusercontent.com/24378/56247005-be4a8000-60a3-11e9-854f-d32a3524d952.PNG)

this is now a multi select and you need to use space to select 1-4 options - e.g. make sure you have the checkmark in front of building. Then you should also see the step to selecting "Webpack".


For testing - we now have tests but unfortunately, they only run on a linux machine as that's what circleci offers => if you know a free for open source service that allows us to run tests on a windows machine just let us know 🤗 

PS: for the docs changes I am going to prepare a PR 👍
