### ISSUE TITLE
Newbie stuck when client is in a subdirectory.

### ISSUE THREAD

**Issue by akc42** [open-wc/open-wc#392]
I have a project which has both client and server parts to it and therefore has a client (and server) directory.  Node_modules at the project root.  I make small alterations to `karma.conf.js` to reflect that fact - and change the `npm run test` to `npm run test:client`.

But something fundamental is wrong.  The first test fails as soon as it hits the import statement `import { fixture, expect } from '@open-wc/testing';` complaining about the curly brackets.

I made a minimal example repository, where the only commands to run to get set up is
```
yarn add lit-element
npm run test:client
```
This is at https://github.com/akc42/problem_testing.git

Can someone highlight what I am doing wrong.

**Comment by daKmoR** [comment]
by default the karma preprocessors are only put on `*.test.js` files...

so simply renaming your `client/test/pas-address-card.js` to `client/test/pas-address-card.test.js` should be all you need (or at least you will have failing tests then)

**Comment by akc42** [comment]
Thanks - that has got me on my way.
