### ISSUE TITLE
[semantic-dom-diff] needs preprocessor for partial dom (like tr)

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#395]
when comparing "parts" of a dom e.g. only tr of a table
```js
expect(el.shadowRoot.querySelector('table thead')).lightDom.to.equal(`
  <tr>
     <th>foo</th>
     <th>bar</th>
  </tr>
`);
```

then the browser parser will say `tr` is not allows on it's own so these tags will be ignored and you will compare only `foo\n    bar` so there is missing information and the indentions are wrong..,

Possible solution:
pass on a preprocessor
```js
expect(el.shadowRoot.querySelector('table thead')).lightDom.to.equal(`
  <tr>
     <th>foo</th>
     <th>bar</th>
  </tr>
`, { preProcessor: html => `<table>${html}</table>` });
```

**Comment by LarsDenBakker** [comment]
Couldn't you just do:

```
const dom = el.shadowRoot.querySelector('table thead');
expect(`<table>${dom}</table>`).lightDom.to.equal(`
  <tr>
     <th>foo</th>
     <th>bar</th>
  </tr>
`);
```

**Comment by daKmoR** [comment]
I'm afraid no... 
1. string + dom nodes don't mix that well (only works with lit-html => but even then we would need to render a new fixture and pass the resulting node)
2. `.lightdom` takes a dom node and not a string
3. the right side also gets parsed so you need "valid" browser dom there as well

I tested it adding `preProcesser` is like 4 lines of additional code :grimacing: 
```
const processedHtml = typeof options.preProcessor === 'function' ? options.preProcessor(html) : html;
// then replace usage of html with processedHtml
```

**Comment by LarsDenBakker** [comment]
You wouldn't use `.lightDom` in this case, but just `.dom`. `get-diffable-html` does support a string now: https://github.com/open-wc/open-wc/blob/master/packages/semantic-dom-diff/get-diffable-html.js#L204

So it would be:

```
const dom = el.shadowRoot.querySelector('table thead').innerHTML;
expect(`<table>${dom}</table>`).dom.to.equal(`
  <tr>
     <th>foo</th>
     <th>bar</th>
  </tr>
`);
```

But we could add a preprocessor as well I'm fine with that.
