### ISSUE TITLE
import.meta.url appears not to be working in Windows(7)

### ISSUE THREAD

**Issue by akc42** [open-wc/open-wc#410]
In https://github.com/open-wc/open-wc/issues/397#issuecomment-485110374

it was suggested I switch my code to using
`<img src="${new URL('../images/pas-icon-32.png', import.meta.url)}">`

which I duly did, and it solved my problems.  I run Linux on my development environment.

This morning, for the first time since I did this, I have had to switch to a windows 7 development environment (I am at the client that the whole project is for) and tried to run the tests again.  The output is full of messages about this url being incorrect correct and not found.

Putting a console.log to output `import.meta.url` in the `render` function shows that its complete rubbish  this is the value
`'http://localhost:9876/C:UsersAlan.Chandlerpasv5/C:UsersAlan.Chandlerpasv5clientcomponentspas-app.js`
(my testing directory is `C:Users\Alan.Chandler\pasv5` and the module is `client/components/pas-app.js`)

**Comment by LarsDenBakker** [comment]
Running into this as well, will look into fixing this
