### ISSUE TITLE
IDE plugin recommendations

### ISSUE THREAD

**Issue by e111077** [open-wc/open-wc#414]
Hello, on the [IDE plugin recommendations](https://open-wc.org/developing/ide.html#configuration), I see that you recommend both [lit-html](https://marketplace.visualstudio.com/items?itemName=bierner.lit-html) and [vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components).

I personally have been using [lit-plugin](https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin) which handles both html and css tagged templates and has many more features such as, attribute/prop type checking, intellisense for element definitions (and the option to fix it by importing the file for you), `@slot` jsdoc support, and much more.

I suggest y'all give it a try and and determine whether it's a good replacement for these two suggested plugins.

(I didn't have any involvement in developing the plugin, but I'm a huge fan)

**Comment by LarsDenBakker** [comment]
@thepassle you had some experience using this plugin. should we recommend it?

**Comment by thepassle** [comment]
I have tried it for some time now, and I have a really good experience with it. I think we should

**Comment by daKmoR** [comment]
I'm using it now as well works great so let's recommend it 💪 anyone up for a PR 🤗
