### ISSUE TITLE
Create helpers to create simple string with html/css/... for tests

### ISSUE THREAD

**Issue by bashmish** [open-wc/open-wc#415]
I often want to create a string, rather than a template, e.g. in tests, and want to make use of the code highlighting and autocomplete in code editors. I think a simple yet quite logical way to do this with current plugins in VSCode and alike it to use an object with properties for html and others. Example:

```js
export const str = {
  html = () => { /* just concatenate everything */ },
  css = () => { /* just concatenate everything */ },
};

const myHtmlString = str.html`<!-- HTML code -->`;
const myCssString = str.css`/* CSS code */`;
```

## Proposal

Add documentation on how to define such helpers in your files:

```js
const str = { html: String.raw, css: String.raw };
```

## Old proposal for history:

```js
// foo.test.js
import * as str from '@open-wc/testing-helpers/str.js';

// TODO: write a good test example here
const myHtmlString = str.html` // works as if it is just html literal, but creates a string
`;
```

Why not
- just html? because it will conflict with lit-html it the same test file quite often
- `strhtml` or `strHtml` or another similar name? because all text editors atm search specifically for `html` pattern

**Comment by daKmoR** [comment]
nice idea 🤗 

only having a separate entry point is probably annoying 🤔 especially as we would like to export it via `@open-wc/testing` as well 🤔 

how about exporting an object directly so you could do

```js
import { str } from '@open-wc/testing';

const myHtmlString = str.html`...`;
```

another thought is `str` descriptive enough? possible alternatives `strings`, `strHelpers` or `text`?

**Comment by bashmish** [comment]
@daKmoR sure, that was assumed. Can be a good first issue for someone to pick up and get familiar with the project.

**Comment by Viniter** [comment]
I looked into implementing this, but then I realized, there's no reason to implement the `html` function. If what you need is essentially "untagged" template literal functionality, then you can use the native function that implements it - [`String.raw()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw).

You can do just do this:
```js
const str = { html: String.raw };

str.html`<b>This ${'works'}</b>`
```

Is it still worth to add that as a helper, since the implementation is about as long as the import statement? Maybe it would be better to just mention it in docs.

**Comment by bashmish** [comment]
I would say let's transform this issue from `feature request` into `documentation update needed` and put this example into the docs:

```
const str = { html: String.raw, css: String.raw };
```

**Comment by Viniter** [comment]
I played around with this a bit more and I found out, that `String.raw()` is not entirely equivalent to an untagged template literal. `String.raw()` doesn't process escape sequences (which is kind of it's point).  
```js
`foo\nbar` !== String.raw`foo\nbar`
```
It's still a neat hack, but considering this I'd probably caution against it.

I still wonder if it can be done with a one-liner... :thinking:

**Comment by LarsDenBakker** [comment]
Going to close this one since it didn't generate much interest in a year's time. Anyone is free to come up with a PR for this one though.
