### ISSUE TITLE
Prettier-config: should not add eslint-config-prettier as dependency?

### ISSUE THREAD

**Issue by jhuesos** [open-wc/open-wc#416]
Installing `prettier-config` also installs `eslint-config-prettier` as dependency. I am not sure if that is the right choice because, in theory, you could be using prettier without eslint, so that dependency could be installed for nothing.

What do you think?

**Comment by daKmoR** [comment]
do you mean the install instructions? 

or you mean we should make a split for the configs?

we could split it like this
```js
packages/linting-eslint (rename eslint-config)  // depends on eslint + config
packages/linting-prettier (rename prettier-config) // depends only on prettier
packages/linting (new) // depens on eslint + config + prettier + eslint-prettier
// also a nice package to create would be
packages/linting-lit (or linting-lit-html)
```

**Comment by jhuesos** [comment]
No, I was referring to the npm dependencies.

If you open `config-prettier` `package.json` you will see this: 

```
    "eslint-config-prettier": "^3.3.0",
```

So it assumes that if I use prettier I will also be using Eslint. If that is not the case, I am getting an extra not needed dependency in my project.
