### ISSUE TITLE
SASS with Rollup

### ISSUE THREAD

**Issue by andjimrio** [open-wc/open-wc#419]
Hi!

Thank you for the project! It is more usefull. I migrated my factory of WebComponents to your software from [WebComponentFactory](https://github.com/elmsln/WCFactory). Your project is simplier. However, I have to doubts according to WCFactory:

**First**
Is it possible separate HTML, CSS, JS and properties in diferentes files? I think that it is better for programming. It is the model of Angular's Components. But it is not essential.

**Second**
I want to use SCSS. I saw the module [rollup-plugin-scss](https://www.npmjs.com/package/rollup-plugin-scss) and I tried to include in my `rollup.config.js` with this format.

     import createDefaultConfig from '@open-wc/building-rollup/modern-config';
     import scss from 'rollup-plugin-scss';
     
     const config = createDefaultConfig({ zinput: './src/index.html' });
     config.plugins.push(scss());
     
     export default config;

But fails: `in ./src/style.scss 1:0; Module parse failed: Unexpected token (1:0); You may need an appropriate loader to handle this file type.`

**Comment by LarsDenBakker** [comment]
I am a bit confused, because that sounds like a webpack error. When are you seeing this error?

**Comment by andjimrio** [comment]
When I import a rollup module for CSS Processor, it fails. My question is: Is it possible to add SASS in open-wc?

**Comment by thepassle** [comment]
This should work:

```
import createDefaultConfig from '@open-wc/building-rollup/modern-config';
import scss from 'rollup-plugin-scss';

const config = createDefaultConfig({ input: './src/index.html'});

export default {
  ...config,
  plugins: [
    ...config.plugins,
    scss({
      output: 'dist/styles.css'
    }),
  ],
};
```

**Comment by LarsDenBakker** [comment]
If that works, lets add it to the readme 😁

**Comment by thepassle** [comment]
It's pretty much what's under [extending-the-rollup-config](https://open-wc.org/building/building-rollup.html#extending-the-rollup-config) though, so it would be duplicate

**Comment by andjimrio** [comment]
OK, and how to use in a Web Component? It means...
- the correct import in the main.js: `static get styles()` or `render()`.
- check in development: it generates .css in dist, when you run `yarn build`.

In the other hand, why doesn't open-wc bring it by default?

**Comment by LarsDenBakker** [comment]
`open-wc` is very strict about build tools, we recommend that your code should run as is in the browser without any build tool requirements. Then build tools can be used for optimizing for production.

We did document how to add custom plugins to the build tools, but from there on we can't offer much help in how to configure these plugins.

**Comment by andjimrio** [comment]
Ok, thanks! But I think that SASS adds a huge valor to your framework. But it is your decision, not mine. Despite of, thanks for all!

If you don't know how to configure and use SASS in open-wc, close the issue and thanks for the comment: https://github.com/open-wc/open-wc/issues/419#issuecomment-490170656.

**Comment by lkraav** [comment]
https://github.com/web-padawan/aybolit/ is a SASS-based WC framework alternative.

**Comment by daKmoR** [comment]
hey, I'm closing this as it seems the question has been answered.

Feel free to reopen or create another issue if there are still questions 🤗

**Comment by andjimrio** [comment]
FYI:

I found this magic library: https://github.com/bennypowers/rollup-plugin-lit-css

Why don't you integrate with your framework? Indeed, you could adding support to SASS.

I see this integration in the follow example: https://github.com/web-padawan/aybolit

**Comment by LarsDenBakker** [comment]
We're not a framework, only a collection of tools.

We don't include it by default because your code will no longer run in the browser without building, which is what we don't recommend. For power users we do explain it in the readme: https://open-wc.org/building/building-rollup.html#import-css-files-in-lit-html

**Comment by andjimrio** [comment]
Jajaja, really thank you @LarsDenBakker !

I read your docummentacion, but not this section.

No comments in longer.
