### ISSUE TITLE
[Testing] Migrating to @open-wc/testing-karma-bs - Access denied

### ISSUE THREAD

**Issue by vogloblinsky** [open-wc/open-wc#420]
I just migrate an open-source projet from @open-wc/testing-karma from version v0.x to v1.x

I got an Access denied error : https://travis-ci.org/vogloblinsky/nutrition-web-components/builds/527672899

I have checked my BROWSER_STACK_USERNAME and BROWSER_STACK_ACCESS_KEY.

Any idea ?

Thanks

**Comment by daKmoR** [comment]
hey, sorry for the late reply... 🙈 

is this still an issue? seems to work from what I see?
