### ISSUE TITLE
Too many tools for a starter project

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#427]
In the starter project we add a lot of tools and scripts:
```
  "scripts": {
    "start": "owc-dev-server --open src",
    "lint:eslint": "eslint --ext .js,.html .",
    "format:eslint": "eslint --ext .js,.html . --fix",
    "lint:prettier": "prettier \"**/*.js\" --list-different || (echo '↑↑ these files are not prettier formatted ↑↑' && exit 1)",
    "format:prettier": "prettier \"**/*.js\" --write",
    "lint": "npm run lint:eslint && npm run lint:prettier",
    "format": "npm run format:eslint && npm run format:prettier",
    "test": "karma start --coverage",
    "test:watch": "karma start --auto-watch=true --single-run=false",
    "test:update-snapshots": "karma start --update-snapshots",
    "test:prune-snapshots": "karma start --prune-snapshots",
    "test:legacy": "karma start --legacy --coverage",
    "test:legacy:watch": "karma start --legacy --auto-watch=true --single-run=false",
    "test:bs": "karma start karma.bs.config.js --legacy --coverage",
    "site:build": "npm run storybook:build",
    "storybook": "start-storybook -p 9001",
    "storybook:build": "build-storybook -o _site -s storybook-static",
    "start:dev": "webpack-dev-server --mode development --open",
    "start:dev:legacy": "webpack-dev-server --mode development --legacy",
    "start:prod": "http-server dist/ -o",
    "build": "webpack --mode production",
    "build:stats": "webpack --mode production --profile --json > bundle-stats.json"
  },
```

this seems like a lot, especially when we intend to promote a tool-free development setup.

I propose the following changes:

Apps and component init:
- Remove prettier. In my opinion it doesn't add significant benefit and is not worth the extra overhead for the average developer. It also doesn't format template literals correctly, which is used a lot with web component.
- Remove storybook. I think storybook is suitable for design systems and element collections. It has no use in apps and for single small/medium size component projects it seems quite overkill. We could add an extra init option for a design system which includes storybook.

Component init:
 - Remove rollup/webpack. Components should not be built/bundled.

**Comment by thepassle** [comment]
Yeah, this wasn't the case before (see starter-app repo). Starter-app should already come without storybook, so something is off here.

**Comment by drBenway** [comment]
would it be possible to change the amount of scripts based on choises in the genarator?
For Polymer I also used to add addtional scripts for my team. 
An exaple would be 'npm run codereview'. This would trigger a complete reinstall of the dependencies.

    "//clean": "removes the node_modules folder",
    "clean": "FOR /d /r . %d in (node_modules) DO @IF EXIST \"%d\" rm -rf \"%d\"",

**Comment by bennypowers** [comment]
Let's revisit this

**Comment by daKmoR** [comment]
any idea how?

**Comment by LarsDenBakker** [comment]
Some suggestions I made before:

Make prettier optional besides eslint.
Make commitlint optional, or maybe keep it out entirely.
Offer choice of simple vanilla demo besides storybook

**Comment by LarsDenBakker** [comment]
Putting some of the configs in the package.json really helps with this too so thats a great move I think.

**Comment by Westbrook** [comment]
Commitlint does put some special pressure on a new dev...
