### ISSUE TITLE
[init] difference between starter app and application is unclear

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#429]
In init we prompt users to choose between `Starter app` and `Application` but the difference between them is not clear.

Can we come up with a clearer distinction? Maybe `App boilerplate` or `Basic app` and `Example app` ?

**Comment by thepassle** [comment]
I agree, or just go back to using `Barebone app` and `Starter app` like we had? I think that was pretty clear

**Comment by LarsDenBakker** [comment]
Still need to do something here

**Comment by thepassle** [comment]
I'll take a look at this somewhere this week
