### ISSUE TITLE
Update babel-plugin-template-html-minifier used by builder-webpack

### ISSUE THREAD

**Issue by coreyfarrell** [open-wc/open-wc#439]
A few days ago I published babel-plugin-template-html-minifier@3.0.0.  This is a semver-major release only because it drops node.js 6 which shouldn't be a problem here since node.js 8 is already required by babel-plugin-bundled-import-meta.

The main benefit is this new version now uses babel to produce an exception when html-minifier breaks the template literal.  This means that when it throws `html-minifier deleted something major, cannot proceed.` the exception shows the code babel was processing, rather than just being a normal JS exception with a backtrace to the babel plugin.

Another note cfware/babel-plugin-template-html-minifier#24 was the result of open-wc default settings using `removeComments`.  It think this probably a good option to use since it causes an error to be reported in the following situation:

```js
html`<!-- <div>${functionWithSideEffects()}</div> -->`
```

The user might assume they've commented out the call to `functionWithSideEffects()` but they have not.  I documented this in my plugin but figure I'd mention it here as well in case you want to document this somewhere.

**Comment by LarsDenBakker** [comment]
Really appreciate you letting us know. Indeed comments in lit html templates are quite a footgun!
