### ISSUE TITLE
[semantic-dom-diff] snapshotting slot assigned nodes

### ISSUE THREAD

**Issue by tpluscode** [open-wc/open-wc#442]
## Description
I would like to test slot distribution using snapshots. Currently assigning nodes to slots does not affect the shadowDom snapshot at all.

## Details

In my element I could have a slot, named or otherwise. For example simply

```html
<div>
  <slot></slot>
</div>
```

In test, I would create a fixture with some nodes in the light Dom

```js
const el = await fixture(`<my-el><span>Slotted</span></my-el>`)

expect(el).shadowDom.to.equalSnapshot()
```

## Expected behavior

The snapshot should place the distributed nodes in the `<slot>` node.

```html
<div>
  <slot>
    <span>Slotted</span>
  </slot>
</div>
```

This would mimic the actual browser behaviour and prevent slot typos etc

## Current behavior

The slots in snapshot are always empty

```html
<div>
  <slot>
  </slot>
</div>
```

**Comment by LarsDenBakker** [comment]
We could walk the assigned nodes of a slot (another great benefit of using native browser parser) but I'm not sure if it's worth the cost. Why not just snapshot the `shadowDom` and `lightDom` separately?

**Comment by tpluscode** [comment]
> Why not just snapshot the `shadowDom` and `lightDom` separately?

Ah, yes, @daKmoR asked the same question on Slack.

Consider this test.

```js
it('tests lightDom snapshot', async () => {
   const el = await fixture('<my-element><div slot="header"></div></mu-element>')

   expect(el).lightDom.to.equalSnapshot()
})
```

It doesn't really test anything, does it? The fact that I mistype the slot name or maybe accidentally remove the `<slot name="header">` from Shadow DOM does not change anything about the Light DOM. 
Assuming that the hypothetical `my-element` does not reflect any props to attributes or does not append any Light DOM nodes, I'd interpret the above as a glorified `string.equals`. The fixture and actual `expect(el).lightDom` are essentially the same markup.

Same goes for Shadow DOM snapshots. If `<my-element><div slot="header"></div></mu-element>` and `<my-element></mu-element>` produce the exact same snapshot, I'd say something is amiss.

**Comment by daKmoR** [comment]
I would say testing light and shadow dom separate is a good thing... as this it's how it actually "works"...
the node still resides in light dom it's just referenced

for checking if the slots are filled you could do something like this?
e.g. check if there are assigned nodes?

```js
expect(el.shadowRoot.querySelector('slot[name=header]').assignedNodes().length).to.equal(1);
```

**Comment by tpluscode** [comment]
> as this it's how it actually "works"... the node still resides in light dom it's just referenced 

Indeed this is one way to view it. My reasoning was that effectively to the observer, the distributed nodes appear as if they were in place of the slot. Hence the temptation to treat them as such in snapshot.

I understand though how snapshot is indeed only taken from "real" DOM. Maybe I'm wrong to expect such a feature. It just felt natural at first.
