### ISSUE TITLE
Component library - gh time-elements

### ISSUE THREAD

**Issue by robrez** [open-wc/open-wc#445]
Thoughts about adding github/time-elements to the component library page?

https://github.com/github/time-elements

**Comment by daKmoR** [comment]
@thepassle what do you think? should we add "individual" elements there as well?

**Comment by thepassle** [comment]
It's kind of a slippery slope, i prefer to only have a list of libraries/sets rather than single components. If we're gonna post every single component separately it'll quickly become a manually managed webcomponents.org/catalog

**Comment by robrez** [comment]
Understood

**Comment by lkraav** [comment]
Yeah, I also became curious whether GH has some kind of an element collection defined, but it doesn't seem like it.

**Comment by thepassle** [comment]
Oops, I have to rectify myself. I thought it was a single component, but it's actually a set of multiple elements. My bad. In that case I think we can list it yeah. @robrez would you be willing to PR it? You can find the file [here](https://github.com/open-wc/open-wc/blob/master/docs/faq/component-libraries.md). Please note that the list is ordered alphabetically.
