### ISSUE TITLE
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry

### ISSUE THREAD

**Issue by andjimrio** [open-wc/open-wc#453]
Hi!

I wanted to test my Web Components in a single file out of my project. I tried with this method: https://github.com/open-wc/open-wc/issues/299 and works.

```html
<body>
    <form>
        <wc-input label="Input"></wc-input>

        <wc-radio-button>No seleccionado</wc-radio-button>
        <wc-checkbox>No seleccionado</wc-checkbox>

        <wc-button label="Botón"></wc-button>
    </form>

    <script type="module" src="./wc-button/dist/wc-button.js"></script>
    <script type="module" src="./wc-input/dist/wc-input.js"></script>
    <script type="module" src="./wc-radio-button/dist/wc-radio-button.js"></script>
    <script type="module" src="./wc-checkbox/dist/wc-checkbox.js"></script>
    <script type="module" src="./wc-dropdown/dist/wc-dropdown.js"></script>
    <script type="module" src="./wc-progress/dist/wc-progress.js"></script>
    <script type="module" src="./wc-badge/dist/wc-badge.js"></script>
    <script type="module" src="./wc-image/dist/wc-image.js"></script>
    <script type="module" src="./wc-icon/dist/wc-icon.js"></script>
    <script type="module" src="./wc-tabs/dist/wc-tabs.js"></script>
</body>
```

My problem now is the following: when run the HTML, four components does not render with this error:
```js
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at http://127.0.0.1:5500/wc-input/dist/wc-input.js:1:35510
index.html#:1 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at http://127.0.0.1:5500/wc-badge/dist/wc-badge.js:1:35520
index.html#:1 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at http://127.0.0.1:5500/wc-tabs/dist/wc-tabs.js:1:35520
```
The link to the shows always this line (1:35520): `customElements.define("dom-module",xe);`

The Web Components: wc-button, wc-input, wc-badge and wc-tabs, use another: paper-input, iron-input, paper-badge and paper-tabs. And the first, works property and the others fails, because they try import the same libraries of paper or iron elements.

I was looking for the solution in StackOverFlow and said that I must change the npm install and the imports of components. Is it coherence with your framework.

**Reference:**
- https://stackoverflow.com/questions/51661041/polymer-3-0-5-domexception-failed-to-execute-define-on-customelementregis
- https://stackoverflow.com/questions/50355644/polymer-3-0-uncaught-dom-exception-when-using-paper-input

**Comment by daKmoR** [comment]
is there a chance you can provide a reproduction via stackblitz or so?

My guess would be either you load multiple times the same component via different urls? (maybe one from dist one from src?)
or you have duplicate dependencies and those get installed nested - which leads to the same problem e.g. 2 versions of the same component on different url

Note: es module import only use the url as an identifier so the same file on the file system accessible via different urls will get loaded multiple times.

**Comment by andjimrio** [comment]
You could close my issue. The problem is that not solved, but I read about it. The community said that Polymer 3 and LitElement, both with ES Modules, are not compatible with Polymer 1 and 2: HTML Modules.

https://github.com/Polymer/lit-element/issues/48#issuecomment-388295130

Then, I redo my components using only pure HTML, and not old Polymer Components.

Thanks you for the support.
