### ISSUE TITLE
Do you plan add autoprefixer to rollup legacy build?

### ISSUE THREAD

**Issue by JosefJezek** [open-wc/open-wc#454]
Do you plan add autoprefixer to rollup legacy build?

https://github.com/postcss/autoprefixer

**Comment by daKmoR** [comment]
We do not have a plan to do this. 2 particular reasons stand out for it
- Vendor prefixes are sort of deprecated - quote "Browser vendors are working to stop using vendor prefixes for experimental features." from  https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix
- it is probably not that easy to integrate given the dynamic nature of css template literals e.g. they can be composed via js.

Given this information, the net gain for using autoprefixer is probably small. Therefore we recommend writing the prefixes (and there is hopefully a very very low number) manually if needed.

I am going to close this - if you have any more question please feel free to reopen or create another issue 🤗
