### ISSUE TITLE
Support expressions in css literal string

### ISSUE THREAD

**Issue by JosefJezek** [open-wc/open-wc#456]
Code
```
import { cssFit, cssFlexCenterCenter, cssFlexVertical } from '../styles/layout-mixins';
static get styles() {
return css`
  section {
    ${cssFit}
    ${cssFlexVertical}
    ${cssFlexCenterCenter}
    background-color: transparent;
  }
`;}
```

I get this code after rollup modern build
```
section{","","","background-color:transparent}
```

**Comment by thepassle** [comment]
Could you provide a minimal reproduction?

**Comment by LarsDenBakker** [comment]
I doubt this has anything to do with the rollup build. This looks like template literals compiled to a regular array. The values are elsewhere, so that's fine.

Did you run the code? Did you run the code without compiling? What errors are you getting?
