### ISSUE TITLE
Generated demo app uses incorrect property for the sample component attribute 'heading'

### ISSUE THREAD

**Issue by harunhasdal** [open-wc/open-wc#463]
The demo app uses `header` while the component declares `heading`

https://github.com/open-wc/open-wc/blob/4ec95baa487b9718d9143b7ac81540f887800af3/packages/create/src/generators/wc-lit-element/templates/static/demo/index.js#L6

https://github.com/open-wc/open-wc/blob/4ec95baa487b9718d9143b7ac81540f887800af3/packages/create/src/generators/wc-lit-element/templates/_MyEl.js#L16

**Comment by daKmoR** [comment]
thank you for fixing it :+1:
