### ISSUE TITLE
[Meta] Documentation generation issue

### ISSUE THREAD

**Issue by goatandsheep** [open-wc/open-wc#470]
I think there's [a problem with the documentation generated](https://github.com/open-wc/open-wc/tree/master/packages/testing-karma-bs#usage) for the testing-karma-bs readme

**Comment by daKmoR** [comment]
can you elaborate in what you mean by that?

looks fine to me?
https://open-wc.org/testing/testing-karma-bs.html#manual

**Comment by goatandsheep** [comment]
Oh okay! Sorry: just wasn't sure since I saw the script tag on the markdown.
