### ISSUE TITLE
[building][rollup] Modules imported to main module not appended at `rel=preload`

### ISSUE THREAD

**Issue by Westbrook** [open-wc/open-wc#472]
When building for modern and legacy and relying on dynamic imports, it is possible to for Rollup to create a chunk that is required in both the main module and the dynamically imported module, in this case the chunk is not registered as `isEntry` and will not be added to the HTML via `<link rel="preload" />`.

*Reproduction steps:*
1. Clone https://github.com/Westbrook/minesweeper/tree/2bec691f54708e3bb6eb83755139ffbd144c9a20
2. Install with `yarn`
3. Build `yarn build`
4. See lack of secondary `<link rel="preload" />`

*Expected results:*
The `<link rel="preload" />` is available and ensures the earliest request for this asset.

*Actual results:*
There is no `<link rel="preload" />` and the developer needs to add it manually for optimal performance.

**Comment by Westbrook** [comment]
Here's where I think there might be a false assumption:

https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/plugins/rollup-plugin-modern-web/rollup-plugin-modern-web.js#L230

```
      const entryModules = Object.keys(bundles)
        .filter(key => bundles[key].isEntry)
        .map(e => `./${e}`);
```

`entryModules` are later fed into the code that writes `<link rel="preload" />`, however `isEntry` doesn't seem to be the correct test for this. As per https://rollupjs.org/guide/en#this-getmoduleinfo-moduleid-string-moduleinfo:

```
{
  id: string, // the id of the module, for convenience
  isEntry: boolean, // is this a user- or plugin-defined entry point
  isExternal: boolean, // for external modules that are not included in the graph
  importedIds: string[], // the module ids imported by this module
  hasModuleSideEffects: boolean // are imports of this module included if nothing is imported from it
}
```

`isEntry` doesn't mean "entry" module, like it might read, but "user-defined" module.

I think want needs to happen is take this list of modules, and then traverse the `importedIds` therein to make a more complete list to set as `entryModules`. Does that compute with anyone else?

**Comment by LarsDenBakker** [comment]
We can look up static imports and add those as preload as well. This wouldn't work for dynamic imports, as we're not certain whether it will be dynamically imported straight away.

I am still curious on why this happens though, could you reproduce this scenario in the demo that we have?

**Comment by Westbrook** [comment]
I'll have to see if there's a good way to tell the difference between static and dynamically imported modules if they both appear in `importedIds`...

**Comment by LarsDenBakker** [comment]
There is also https://developers.google.com/web/updates/2017/12/modulepreload which apparently on some browser traverses dependencies. I haven't tried it yet

**Comment by Westbrook** [comment]
🤔 I will try both! Thanks for the reminder, legacy browsers likely don't support anything preload anyways.

As for the demo, can you point me to it @LarsDenBakker? Still getting a hand of all the tools here!

**Comment by LarsDenBakker** [comment]
It's in the building-rollup repo: https://github.com/open-wc/open-wc/tree/master/packages/building-rollup/demo/js I use it to regression test the build configuration

**Comment by Westbrook** [comment]
Gonna look deeper into getting the repro together, should I just replace what's there in a new branch?

But for now, this is looking good for my use case!

```
      const entryModules = Object.keys(bundles)
        .filter(key => {
          return bundles[key].isEntry;
        })
        .reduce((acc, e) => {
          acc.push(`./${e}`);
          const imports = bundles[e].imports || [];
          imports.map(i => {
            if (!acc.includes(`./${i}`)) {
              acc.push(`./${i}`)
            }
          });
          return acc;
        }, []);
```

**Comment by LarsDenBakker** [comment]
Yeah just add to the existing code. I'm interested to see what rollup does to a simple module that's imported in the entrypoint and in a dynamic import.

**Comment by Westbrook** [comment]
I didn't change the demo at all and when it builds the static imports in that file are not included in the preload list.

Static imports of `./demo-app.js`:
```
import{a as o,b as t,c as e,d as n,e as s,f as r}from"./chunk-65f19c97.js";import{a as c}from"./chunk-28b1b130.js";
```

rel="preload":
```
<link rel="preload" as="script" crossorigin="anonymous" href="./demo-app.js"><link rel="preload" as="script" crossorigin="anonymous" href="./meta-url-test-2.js">
```

When I update the plugin with the above code the rel="preload" list is as follows:
```
<link rel="preload" as="script" crossorigin="anonymous" href="./demo-app.js"><link rel="preload" as="script" crossorigin="anonymous" href="./chunk-65f19c97.js"><link rel="preload" as="script" crossorigin="anonymous" href="./chunk-28b1b130.js"><link rel="preload" as="script" crossorigin="anonymous" href="./meta-url-test-2.js">
```

Which is as I would expect. Thoughts?

**Comment by Westbrook** [comment]
Also, I'm seeing little to no specific load/performance difference between `rel="preload" as="script" crossorigin="anonymous"` and `rel="modulepreload"` other than if you chose to ship more modules initially you'd begin to get fractional size benefits for less HTML attributes 🤷‍♂❓

**Comment by LarsDenBakker** [comment]
Ah I see, so it was already broken :) Definitely an improvement then.

I think the different is that `preload` only preloads the network call, whereas `modulepreload` also parses the code (and potentially start downloading transitive dependencies?).

For now we can stick to preload as far as I can tell...
