### ISSUE TITLE
[building-webpack] polyfill files should contain hash in their names

### ISSUE THREAD

**Issue by jhuesos** [open-wc/open-wc#475]
At this moment, polyfill files are copied into `/dist/polyfills/` folder and their filenames do not contain a hash in their names. This could be a problem if the server where the website is running is configured with a very-long-cache expiration period (as it is considered a best practice) and a new version of polyfills need to be pushed for security or bug fixing.

I propose all files under dist/ should contain filenames:

```
dist/
   polyfills/
      url.xvndsoyr43985.js
```

Hash should be content-based, so as long as the polyfill files do not change, the hash value should remain unchanged.

**Comment by LarsDenBakker** [comment]
Yes you're right
