### ISSUE TITLE
[Testing] Tests succeed when running locally but fail on BS/SL - missing dependency

### ISSUE THREAD

**Issue by jarrodek** [open-wc/open-wc#480]
One of my components has problem when running tests on Sauce Labs and Browser Stack. It seems to be the same problem as the output is the same for both tests.

The component imports a dependency which is PouchDB. This library does not have actual ESM interface but it "exports" to window object. And this works with demo page, with local tests, and with Polymer build. However, when I try to run automated tests I am receiving bunch of errors for every browser saying: `ReferenceError: PouchDB is not defined`. There is also one other error which I don't really understand: `TypeError: Super expression must either be null or a function`.
So I am thinking that when the component is being built by webpak for tests it somehow ignores PouchDB. Is there a way to configure the build behavior so I can experiment with fixing this issue?

**Comment by jarrodek** [comment]
As an update, after removing `--legacy` option from the test command it actually started working. So there is an issue with a transformer running when this option is set and legacy packages (like PouchDB) cannot export their constructors to the window object.

**Comment by LarsDenBakker** [comment]
How are you loading these packages? Webpack has magic behavior where it transforms UMD modules to es modules. Probably that's what's happening with these packages, and it's quite a mess. You can configure webpack to some extent to handle this: https://github.com/webpack-contrib/imports-loader

The other solution is to load them with a regular script...

**Comment by jarrodek** [comment]
It's just a simple web component (based on LitELement). It follows the instruction on open-wc website for testing. 
This is a base class for other elements: https://github.com/advanced-rest-client/arc-models/blob/3.0.0-preview/base-model.js It imports PouchDB. Then other elements extends this base.

I was just looking for some guidance for this issue. I will try configuration options when I get back to this component's development.

**Comment by LarsDenBakker** [comment]
We no longer use `karma-webpack`, it should work correctly now as we properly polyfill modules in older browsers. Please reopen if you still have this problem.
