### ISSUE TITLE
Use "basePath" to resolve node_modules

### ISSUE THREAD

**Issue by nicojs** [open-wc/open-wc#481]
Hi there 👋 love this initiative. This issue is about the testing helpers and karma plugin. 

As far as I can see, running karma-esm plugin only supports resolving node_modules relative to the current working directory:

https://github.com/open-wc/open-wc/blob/56dfc680a767871a4d5ca12716dc899820154e77/packages/karma-esm/src/middleware.js#L51

Karma has something called a basePath: https://karma-runner.github.io/4.0/config/configuration-file.html. Would it be possible to resolve node_modules from the basePath instead of cwd?

It would be nice to be able to run karma inside a sub-dir. Without this, we cannot support it with [Stryker, the JavaScript mutation testing framework](https://stryker-mutator.io). See https://github.com/stryker-mutator/stryker/issues/1573

**Comment by LarsDenBakker** [comment]
This is something we want to support. I am working on some other things right now, so I dont know when I can get to this. Open to PRs

**Comment by nicojs** [comment]
Ok, I will try to open a PR. I've got some experience with Karma plugins and middlewares. 

I might choose a different solution with regards to the basePath, since that might have some undesired consequences.

Thanks for the fast reply.

**Comment by LarsDenBakker** [comment]
I have some upcoming changes to our karma setup which will incorporate this

**Comment by LarsDenBakker** [comment]
This was implemented in https://github.com/open-wc/open-wc/pull/562 !
