### ISSUE TITLE
Choosing yarn leads to npm recommendations :)

### ISSUE THREAD

**Issue by jlengrand** [open-wc/open-wc#495]
Heyo, 

A small one, but nonetheless.

During the init process, I choose `yarn`. Result is as expected, I get a `yarn.lock` file. 

However, at the very end of the process : 

```
All you need to do is run:
  cd under-cover
  npm run start
```

I'm being asked to use npm :).

**Comment by LarsDenBakker** [comment]
I don't really mind this, probably it's a lot of work to customize all these messages. Defaulting to npm is fine I think.

**Comment by jlengrand** [comment]
It's most likely not gonna lead to any big errors. It's just counterintuitive. Can be closed if you don't intend to do anything with it
