### ISSUE TITLE
appIndex must be provided if using watch mode on web component Scaffold

### ISSUE THREAD

**Issue by midesweb** [open-wc/open-wc#500]
"npm run start" script throws this error:  

_"Error: appIndex must be provided if using watch mode"_.

It happens in a new Web Component Project, created by doing this steps:

- npm init @open-wc
- Scaffold a new project > Web Component
- Choosing: Buiding, linting, demoing
- Installing dependencies by npm 

And Later:
- cd project-name
- npm run start 

I am using Mac OS X, Node V10.15.3 and npm 6.9.0

It seems that the problem is the lack of the -app-index argument in the npm "start" script. But placing that argument do not solve the script problem. In that case the problem appears in the browser: a 404 error when fetching the component Javascript file.

**Comment by LarsDenBakker** [comment]
Thanks we will look into this

**Comment by LarsDenBakker** [comment]
I fixed this in https://github.com/open-wc/open-wc/pull/503, just adding `--app-index` looks to solve it. You mention it doesn't work for you, can you try again and see if it works now?

**Comment by midesweb** [comment]
Yes, is solved now. Thanks
