### ISSUE TITLE
Fetch polyfill doesn't work on IE11

### ISSUE THREAD

**Issue by Viniter** [open-wc/open-wc#501]
Since version 3.0.0 package `whatwg-fetch` contains ES module `export` statements. The package also contains UMD build, which should be included in the legacy build instead. See discussion to this issue: https://github.com/github/fetch/issues/656

Since IE11 doesn't support ES modules, this kind of defeats the purpose of the polyfill. It essentially breaks the legacy build, which according to [docs](https://open-wc.org/building/building-webpack.html#browser-support) should target IE11.

The project's maintainer also recommends to...
> Parse the `package.json` of whatwg-fetch to determine the file referenced by the `main` property, and serve that to browsers.

I'm using the `building-webpack` package and it's `modern-and-legacy-config`, but I have the feeling this might affect the rollup builds as well.

**Comment by LarsDenBakker** [comment]
Thanks we will look into this

**Comment by Viniter** [comment]
Turns out it's a pretty quick fix, I have taken the liberty of opening a PR. It seems to work in my use case.

**Comment by LarsDenBakker** [comment]
Thanks for the PR
