### ISSUE TITLE
Test files are included into coverage by default

### ISSUE THREAD

**Issue by jarrodek** [open-wc/open-wc#504]
When running test command (`karma start --coverage`) generated coverage report contains test files. This is rather unexpected and I believe by default the configuration should exclude those from the coverage. It may cause the result to be a failure while it is not really a failure.

**Comment by LarsDenBakker** [comment]
By default test files are excluded from coverage. What do your test files look like?

**Comment by jarrodek** [comment]
As suggested, `component-name.test.js`.

**Comment by LarsDenBakker** [comment]
Sorry for the delay.. can you show me your karma config and your folder structure?

**Comment by jarrodek** [comment]
Hi. I must have messed up something in the configuration files. It didn't happen with other projects I am maintaining. I gonna close this and fix the config on my side.

**Comment by icsaba** [comment]
Hi,

it happens to me as well, my folder structure is like, i have a `src/ui` folder, that includes my components, and next to the components, i have the test files as well with name `component.test.js`.
My `karma.conf.js`: 
`const { createDefaultConfig } = require('@open-wc/testing-karma');
const merge = require('deepmerge');

module.exports = config => {
  config.set(
    merge(createDefaultConfig(config), {
      files: [
        { pattern: config.grep ? config.grep : 'src/ui/**/*.test.js', type: 'module' },
        { pattern: 'web_modules/**/*.js', included: false }
      ],

      reporters: ['junit'],

      coverageIstanbulReporter: {
        thresholds: null,
        reports: ['html', 'cobertura', 'text-summary']
      },

      junitReporter: {
        outputDir: './junit',
        outputFile: 'ui.xml',
        useBrowserName: false,
        suite: 'ui-components',
      },
      basePath: '',

      esm: {
        nodeResolve: true,
      },
    }),
  );

  return config;
};
`

**Comment by icsaba** [comment]
well, i realised that it excludes the tests if they are in the `test` folder only. Are there any way to exclude them anyway? I mean, i dont really want to move all of my tests into a test folder :S
