### ISSUE TITLE
Build Fails for Legacy Browser Support

### ISSUE THREAD

**Issue by Paitum** [open-wc/open-wc#506]
### Problem
Following the [webpack](https://open-wc.org/building/building-webpack.html#configuration) instructions for legacy [browser support](https://open-wc.org/building/building-webpack.html#browser-support) fails to properly build.

### Steps to Reproduce
1. `npm init @open-wc`
2. Answer Questions as follows:
```
√ What would you like to do today? » Scaffold a new project
√ What would you like to scaffold? » Web Component
√ What would you like to add? » Linting, Testing, Demoing, Building
√ What would you like to use for Building? » Webpack
√ Would you like to scaffold examples files for? » Testing, Demoing, Building
√ What is the tag name of your application/web component? ... my-component
√ Do you want to write this file structure to disk? » Yes
√ Do you want to install dependencies? » Yes, with npm
```
3. `cd my-component`
4. Edit the `webpack.config.js` and switch the `createDefaultConfig` assignment from `modern-config` to `modern-and-legacy-config`
```
// const createDefaultConfig = require('@open-wc/building-webpack/modern-config');
const createDefaultConfig = require('@open-wc/building-webpack/modern-and-legacy-config');
```
5. `npm run build`

### Error
```
C:\dev\git\my-component>npm run build

> my-component@0.0.0 build C:\dev\git\my-component
> webpack --mode production

[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
[WebpackIndexHTMLPlugin]: Waiting for legacy build to finish before generating output index.html...
Error: [WebpackIndexHTMLPlugin]: Did not find any legacy entries in output dir C:\dev\git\my-component\dist\legacy within 600000 ms. You can increase the timeout with the legacyTimeout option. Note that legacy is not supported with webpack-dev-server.
    at createError (C:\dev\git\my-component\node_modules\@open-wc\webpack-index-html-plugin\src\utils.js:5:10)
    at compiler.hooks.emit.tapPromise (C:\dev\git\my-component\node_modules\@open-wc\webpack-index-html-plugin\webpack-index-html-plugin.js:115:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-component@0.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
```
### My Environment
```
OS: Windows 10
Console: cmd
node: v10.15.3
npm: 6.4.1
```

**Comment by LarsDenBakker** [comment]
Thanks for the bug report. I've tried it out and it works fine for me. However I am on a mac so likely this is another windows path issue.

Looking at the error message it does seem to be looking in the correct output directory. Just to verify, can you check the `C:\dev\git\my-component\dist` folder during the build and see if there is a `legacy` directory created and see what's inside it?

**Comment by Paitum** [comment]
The contents of dist are two files:
```
dist\legacy\src\my-component.dd50743a266bb68146e4.js
dist\legacy\src\my-component.dd50743a266bb68146e4.js.map
```

**Comment by Pupix** [comment]
I encountered the same problem and fixed it by using WSL to build the project. So it may indeed be a problem with windows pathing.

**Comment by Paitum** [comment]
Are there any next steps? I am interested in taking my first steps with Web Components using the open-wc toolset, but supporting IE11 is a requirement. Naturally, I am developing in Windows in order to verify modern and legacy (IE11 & Edge) browsers. I understand that open-wc doesn't support direct-development in Legacy mode (just like other frameworks like Angular and React), and understand I will need to build my project in order to review legacy behavior. Unfortunately, that build process appears broken, as explained.

**Comment by LarsDenBakker** [comment]
Hi there! Yes we will definitely fix this ASAP, sorry about that. 

The rollup build should work too, and is our default recommendation.

**Comment by Paitum** [comment]
I just tried the rollup approach and encountered a different problem. The `dist/index.html` has `System.import("./legacyopen-wc-component-rollup.js")` resulting in an IE11 error of `Unhandled promise rejection Error: Error loading http://127.0.0.1:8080/legacyopen-wc-component-rollup.js`

Manually changing the `dist/index.html` replacing `legacyopen` with `legacy/open` fixes this.

**Comment by LarsDenBakker** [comment]
Can you guys try if it works now with `@open-wc/building-webpack@2.1.2` and  `@open-wc/webpack-index-html-plugin@1.1.2` ?

@Paitum I will check the rollup error. I got a windows setup now, so that I can test these things before releasing something :) 

The IE11 dynamic import error is harmless, it's how we feature detect dynamic import support.

**Comment by Pupix** [comment]
Can confirm that now it build properly on windows.
