### ISSUE TITLE
[build] safari 10.1 fails to load

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#507]
safari 10.1 loads the legacy bundle, while it has support for web components. this requires us to load the es5 adapter. we should add this in the polyfills loader

**Comment by Pupix** [comment]
I ran into this problem too. It just shows a bunch of errors with no message.
![image](https://user-images.githubusercontent.com/4929965/60505383-e8373a00-9cc3-11e9-9a69-a01fb17c9249.png)

Tracking it down and wrapping the line of code inside a try/catch shows up this
![image](https://user-images.githubusercontent.com/4929965/60505848-d5713500-9cc4-11e9-8aa6-08c4e93ac806.png)

Is there any ETA on this?

**Comment by LarsDenBakker** [comment]
I've fixed it as part of https://github.com/open-wc/open-wc/pull/520, will pull it out separate if that PR takes much longer.

**Comment by Pupix** [comment]
damn 146 files 😄

**Comment by LarsDenBakker** [comment]
It's merged to master now!
