### ISSUE TITLE
[build] lit-element css not minified correctly

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#508]
lit-element contains partial css, which breaks the minifier

**Comment by LarsDenBakker** [comment]
We still need to fix this

**Comment by LarsDenBakker** [comment]
I'm working on this in a couple of PRs to the minifier plugin.
https://github.com/cfware/babel-plugin-template-html-minifier/pull/33, https://github.com/cfware/babel-plugin-template-html-minifier/pull/34 and https://github.com/cfware/babel-plugin-template-html-minifier/pull/35

**Comment by coreyfarrell** [comment]
Sorry for the delay on this one I just reviewed the PR for partial CSS.
