### ISSUE TITLE
[ci] run node tests in CI

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#511]
currently we run only browsers tests in the CI, we should also run the node tests for tools

**Comment by daKmoR** [comment]
we do run `test:ci` so if you want the ci to run your node tests just add a `"test:ci": "npm run test"`
https://github.com/open-wc/open-wc/blob/master/.circleci/config.yml#L33

**Comment by LarsDenBakker** [comment]
I think that's more for specific tests that should run 'only' in the CI. Ideally the CI just runs `yarn test` so that you can also do this locally, right? currently `yarn test` only runs the browser tests.

**Comment by daKmoR** [comment]
The idea is to have `yarn test:ci` for node and `yarn test` for karma.

you can run both of them locally 👍

**Comment by LarsDenBakker** [comment]
what about `yarn test:node` and `yarn test:browser`, and `yarn:test` which runs both browser and node? that's also how we have linting and format

**Comment by daKmoR** [comment]
sure we can change that 🤗 it will mean to release every package we have (for the package.json change)

let's do it after the release of all the open stuff? rollup plugin, import maps stuff

**Comment by LarsDenBakker** [comment]
Yeah, sure.
