### ISSUE TITLE
testfixture using `fixture(html`...`)` returns undefined

### ISSUE THREAD

**Issue by funglaub** [open-wc/open-wc#516]
Hi there,

I'm using version 1.0.3 of `@open-wc/testing` and noticed a weird behaviour when using `fixture` and `html` inside.

The following code returns `undefined`:

```
      const tagName = defineCE(SomeComponent);
      testFixture = await fixture(html`<${tagName} value="-1" .formatter=${formatter}></${tagName}>`);
      console.log(testFixture);
```

If I discard the `html` the property is not set, but the textFixture is present:

```
      testFixture = await fixture(`<${tagName} value="-1" .formatter=${formatter}></${tagName}>`);
```

From what I've seen in the docs, the combination should be working. Is this probably caused by `definceCE`?

**Comment by daKmoR** [comment]
lit-html does not support using dynamic tag names by default - we have a directive that allows it for tests (e.g. do not use it in production - it has a bad performance)
```js
const tag = unsafeStatic(tagName);
```

you can see more here
https://open-wc.org/testing/testing-helpers.html#test-a-custom-class-with-properties

for your code it should be like this
```js
const tagName = defineCE(SomeComponent);
const tag = unsafeStatic(tagName);
testFixture = await fixture(html`<${tag} value="-1" .formatter=${formatter}></${tag}>`);
console.log(testFixture);
```

**Comment by funglaub** [comment]
Your suggestions works! Thank you!

**Comment by daKmoR** [comment]
nice 🤗
