### ISSUE TITLE
@open-wc/webpack-import-meta-loader web worker support

### ISSUE THREAD

**Issue by kkimdev** [open-wc/open-wc#517]
@open-wc/webpack-import-meta-loader converts "import.meta" code to use "window. ..." instead.  However, web worker doesn't have "window. ..."

**Comment by LarsDenBakker** [comment]
We now recommend using https://www.npmjs.com/package/babel-plugin-bundled-import-meta instead of the import meta loader. Will that work for you?

**Comment by kkimdev** [comment]
Thanks for the information!  Though I couldn't configure babel-plugin-bundled-import-meta to work.  And I've decided to just not use import.meta until webpack supports by default for my project.

**Comment by LarsDenBakker** [comment]
You could also look into rollup which has better support for import.meta.url. I haven't worked with workers yet, so I don't know how rollup handles that.

**Comment by LarsDenBakker** [comment]
Did that work for you? do you want to keep this issue opened or can we close it?

**Comment by kkimdev** [comment]
Yeah we removed import.meta from our codebase instead.
