### ISSUE TITLE
webpack modern-legacy-config, partial html is not valid as template

### ISSUE THREAD

**Issue by askbeka** [open-wc/open-wc#526]
We have use case where supplied html is not full html, but just a a partial that is used in server to construct full html.

webpack build does not work with this format right now, I haven't checked it for rollup

**Comment by bennypowers** [comment]
Are you passing this partial to the index-html plugin?

**Comment by askbeka** [comment]
@bennypowers updated title, I passing a path to input property for config

**Comment by LarsDenBakker** [comment]
We parse the HTML in order to inject elements into it. In what sense is your HTML partial? Is it still valid HTML?

**Comment by askbeka** [comment]
it is valid html, but woithou html, body or head tags like
```html
<x-component></x-component>
<script type="module" src="./my-component.js"></script>
```

**Comment by LarsDenBakker** [comment]
That's an interesting use case...

Are you expecting polyfills etc. to be injected here, or do you just need a bundled JS output?

**Comment by askbeka** [comment]
Yes, I need polyfills too
Can I do so by providing a template to index html plugin configuration?

**Comment by LarsDenBakker** [comment]
Yep, then providing the template should work out. Let me know if it works for you.

**Comment by LarsDenBakker** [comment]
Closing this as there is no actionable item. Providing the template manually should work here.
