### ISSUE TITLE
[building-rollup] dynamic imports broken

### ISSUE THREAD

**Issue by kasperstorgaard** [open-wc/open-wc#534]
I just updated to 0.7.1 and got an issue with `__dynamicImport__ is not defined` when I run my app.

The same thing can be reproduced in the open-wc repo:
- cd to packages/building-rollup
- `npm run build:modern`
- `npm run build:start`
- open demo webpage
- click `lazy load` button

<img width="1176" alt="Screenshot 2019-07-03 at 11 25 27" src="https://user-images.githubusercontent.com/3033516/60580830-0e251300-9d86-11e9-8723-462df4ea35ac.png">

**Comment by LarsDenBakker** [comment]
Sorry about that, something got mixed up in a merge. Fixing it now!

**Comment by kasperstorgaard** [comment]
cool, thanks for fixing it so fast
