### ISSUE TITLE
[build-webpack]: output.publicPath is not being respected

### ISSUE THREAD

**Issue by askbeka** [open-wc/open-wc#536]
```js
.map(config => merge(config, {
  output: {
    publicPath: `/features/${featureName}/`,
  },
}));
```
public path is not being respected, assets have a relative path:
```html
<html>
<head>
<link rel="preload" href="index.62bdde1e63136d426e8f.js" as="script"></head>
<body>
<cpa-quick-links></cpa-quick-links>
<script src="polyfills/core-js.7ca91f6b0231c95b468b2436196952c1.js" nomodule=""></script><script src="polyfills/regenerator-runtime.61c01f337f4241bb46c77e10a7e01300.js" nomodule=""></script>
<script src="loader.dda0588c758eb4f02c07ca53353af135.js"></script></body>
</html>
```

**Comment by LarsDenBakker** [comment]
When I try a vanilla webpack configuration, `publicPath` doesn't do that either. You can set the `path` property to change the output directory.

**Comment by askbeka** [comment]
hi, no. `publicPath=/features/my-feature` does change asset path in a way like
```html
<script src="/features/my-feature/loader.js"></script>
```
And just webpack does that, that it is the purpose of that property https://webpack.js.org/guides/public-path/

Maybe it is a bug in webpack, I will check later, for now I have found a workaround on our side.

**Comment by askbeka** [comment]
Hey, this is striking back again,

I think webpackIndexhtml plugin should include publicPath, option, so that I could set relative path
for files from where they need to be loaded

**Comment by askbeka** [comment]
setting just `path` just moves files to different folder, but what i need is the urls to change
