### ISSUE TITLE
[semantic-dom-diff] Support Chai assert API

### ISSUE THREAD

**Issue by AdamVig** [open-wc/open-wc#537]
`semantic-dom-diff`'s Chai plugin supports the `expect` and `should` APIs, but not `assert.

I prefer to use the `assert` API over the other two because it reads a bit more clearly.

[`chai-as-promised`](https://github.com/domenic/chai-as-promised) [supports the Assert API](https://github.com/domenic/chai-as-promised/blob/39bfd34988132e443d703c8547fef4e2fbfa7a21/lib/chai-as-promised.js#L314-L355). This may not be the exact approach you want to take, but it is useful to see how others in the community have implemented this. It could be more idiomatic to add methods like `assert.lightDomEqual`, `assert.shadowDomNotEqual`, etc.

I'm happy to implement this if one of the maintainers could validate the use case and provide feedback on the `assert.lightDom.equal` vs `assert.lightDomEqual` question.

**Comment by LarsDenBakker** [comment]
We'd be happy to review a PR which adds support for assert :)

**Comment by AdamVig** [comment]
Some more research: `sinon` has a method [`sinon.assert.expose`](https://sinonjs.org/releases/v7.3.2/assertions/#sinonassertexposeobject-options) that puts all of the Sinon assertions on the given `assert` object. [Here is the source.](https://github.com/sinonjs/sinon/blob/afc077fe56a127bf4f8b018a6937fb24ff4b4014/lib/sinon/assert.js#L153-L170)

I guess that is not necessarily relevant here, but I found it interesting anyways.

@LarsDenBakker Can you give feedback on whether you would prefer `assert.lightDom.equal` or `assert.lightDomEqual` as an `assert` API?

If you don't have a preference, I will go with `assert.lightDom.equal` to follow the example of `chai-as-promised`.

**Comment by LarsDenBakker** [comment]
`assert.lightDom.equal` is good, keeps it in line with the way we do it for `expect`.
