### ISSUE TITLE
TypeScript types should work out of the box

### ISSUE THREAD

**Issue by AdamVig** [open-wc/open-wc#538]
I am using a couple of packages from this project in my TypeScript project and I am forced to import them using `require()` instead of `import` because the types do not work out of the box.

Based on #302, I tried adding `"node_modules/@open-wc/testing-helpers/*.js"` to the `includes` in the `tsconfig.json` for my test files and it did not work.

In #277, it looks like there is some hesitance around switching to TypeScript across the project as a whole. I think that would be a good idea.

I think it is important that TypeScript types work by default on packages published from this project.

**Comment by LarsDenBakker** [comment]
@daKmoR do you have any insights here?

**Comment by AdamVig** [comment]
Closing in favor of #572.
