### ISSUE TITLE
[build-webpack] changes to input html are not watched

### ISSUE THREAD

**Issue by askbeka** [open-wc/open-wc#539]
Changes to input html are not watched, even after reload
Rerunning webpack-dev-server is required to see changes

**Comment by LarsDenBakker** [comment]
this would be good to add, but not high my priority list since webpack-dev-server is not a goal for us, we will advice using `es-dev-server` for local development when it's finished.

**Comment by LarsDenBakker** [comment]
Closing this. We suggest `es-dev-server` for regular development. If someone wants to use webpack dev server, we can accept a PR for adding this feature in but we don't need to track it as an issue.
