### ISSUE TITLE
[building-rollup] how to disable minification in production mode?

### ISSUE THREAD

**Issue by newbornfrontender** [open-wc/open-wc#543]
Or how to change babel-plugin-template-html-minifier settings or remove this plugin?

**Comment by LarsDenBakker** [comment]
I'm curious to know why you want to disable this minification. Are you running into a bug somewhere?

In this case it's better to copy over our config and make your own adjustments. We don't want to expose too many option on our default configuration, otherwise it becomes a bit unclear when we have configuration to configure the configuration :)

**Comment by newbornfrontender** [comment]
This is due to the postcss. I use postcss-nesting, but this is an invalid syntax. Therefore, after minification, I get only the first line.

Before:
```
h1 {
  color: red;

  span {
    color: blue;
  }
}
```

After:
```
h1{color:red;}
```

**Comment by Westbrook** [comment]
Where are you adding the postcss processing to your CSS?

**Comment by newbornfrontender** [comment]
Here is an example: https://github.com/newbornfrontender/wc-postcss-minify-sample

If you run `yarn build:watch` then all works, because css minification is disabled

**Comment by LarsDenBakker** [comment]
Can you try running postcss before running the plugins from the default config? Then the minifier received valid CSS and it should work properly

**Comment by newbornfrontender** [comment]
This is work if not using decorators or private fields. If use `babel -> postcss -> ...config.plugins`, them it's works. But I do not know whether it is right

**Comment by LarsDenBakker** [comment]
probably that will run babel twice? I'm not sure if rollup deduplicates plugins.

Why would decorators and private fields give issues with postcss though, that should run on your css files right?

**Comment by newbornfrontender** [comment]
Problem in Acorn. He doesn't understand decorators syntax. If using Babel for AST, then its will be working. Thanks for helping
