### ISSUE TITLE
[build-rollup] app-shell import wrongly uses relative path

### ISSUE THREAD

**Issue by rwestlund** [open-wc/open-wc#564]
When building a SPA with an app-shell using the default (modern) rollup config, the app shell import in index.html is rewritten to be dynamically imported by relative path. E.g.:

Original index.html:
```html
<script type="module" src="/src/my-app.js">
```
Becomes:
```js
window.importShim("./my-app.js")
```
When it should be:
```js
window.importShim("/my-app.js")
```

This is breaking refresh on a non-home page. For example, if I navigate to /users in my app and then refresh, my server responds with index.html and the dynamic import looks for /users/my-app.js, which is wrong.

The preload link is also relative.

**Comment by LarsDenBakker** [comment]
Indeed it looks like we don't cover absolute paths right now, will fix this one.

**Comment by LarsDenBakker** [comment]
I think the current behavior is correct, the output files reference the new location of the files relative to index.html. We can't preserve the original file's location, as rollup will output everything in a flat tree.

If you have a SPA and use history API routing, you need to set a `<base href="...">` in order to tell the browser where to resolve resources relatively to.

**Comment by rwestlund** [comment]
Okay, `<base href="/">` is working. I'm switching from polymer-cli, where paths in index.html were absolute and were preserved during build. Thanks for the tip!

I suggest adding this line to the auto-generated app (possibly commented out) because it will be necessary for PWAs built this way.

**Comment by LarsDenBakker** [comment]
I think that's a good suggestion @thepassle what do you think?

**Comment by thepassle** [comment]
Yep, I agree. Started working on the generators yesterday, will make sure to include this :)

**Comment by LarsDenBakker** [comment]
This has been added to the genrator :)

**Comment by rwestlund** [comment]
@LarsDenBakker This may not work after all. I've discovered that Safari ignores `<base href="/">` when using dynamic imports (tested on current Safari, both MacOS and iOS). This breaks refresh on a non-home page, as described above.

My current workaround is to stick this in the end of my build script:
```sh
sed -i '' -e 's@\./@/@g' dist/index.html
```
Which changes:
```js
window.importShim("./my-app.js")
```
to:
```js
window.importShim("/my-app.js")
```
Because Safari doesn't respect the base URL in `import()`, this is the only cross-browser way I'm aware of to handle refresh in a PWA when the app shell is dynamically imported.

**Comment by kasperstorgaard** [comment]
I had the same issue as @rwestlund, with the same workaround, and also needed for all imports in generated chunks

**Comment by LarsDenBakker** [comment]
It's really unfortunate to hear that safari doesn't respect the base href. I never experienced this myself, will check into it. But it sounds like something that needs to be resolved at the level of rollup then.
