### ISSUE TITLE
[build-rollup] doctype html is stripped with default config

### ISSUE THREAD

**Issue by rwestlund** [open-wc/open-wc#565]
Using the default (modern) rollup config, the `<!doctype html>` comment at the top is stripped. This line is important:
https://developer.mozilla.org/en-US/docs/Glossary/Doctype

**Comment by LarsDenBakker** [comment]
Hi there! Thanks for posting this issue, this is definitely not expected. Will look into it.

**Comment by LarsDenBakker** [comment]
I'm not able to reproduce this issue:

```bash
npm init @open-wc
-> choose starter app
cd my-app
yarn build
```

`dist/index.html` output is:

```
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="Description" content="Put your description here."><style>body,html{margin:0;padding:0;font-family:sans-serif;background-color:#ededed}</style><title>my-app</title><link rel="preload" href="my-app.js" as="script" crossorigin="anonymous"></head><body><my-app heading="Hello world!"></my-app><script>window.importShim=i=>import(i);</script><script>!function(){function e(e){return new Promise(function(o,t){var n=document.createElement("script");n.onerror=t,n.onload=o,n.src=e,n.defer=!0,document.head.appendChild(n)})}var o=[];function t(){window.importShim("./my-app.js")}"noModule"in HTMLScriptElement.prototype&&!("importShim"in window)&&o.push(e("polyfills/dynamic-import.b745cfc9384367cc18b42bbef2bbdcd9.js")),"attachShadow"in Element.prototype&&"getRootNode"in Element.prototype||o.push(e("polyfills/webcomponents.88b4b5855ede008ecad6bbdd4a69e57d.js")),!("noModule"in HTMLScriptElement.prototype)&&"getRootNode"in Element.prototype&&o.push(e("polyfills/custom-elements-es5-adapter.551c76d38426de62c33d8c61995c1d0f.js")),o.length?Promise.all(o).then(t):t()}();</script></body></html>
```

can you check if it's something on your side?

**Comment by rwestlund** [comment]
Finally found it. The build process can't handle the presence of a Byte Order Mark. If you add a BOM (in vim, it's :set bomb) to index.html in the sample project, you get this build output:
```html
<html lang="en"><head><link rel="preload" href="my-app.js" as="script" crossorigin="anonymous"></head><body>﻿<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="Description" content="Put your description here."><style>body,html{margin:0;padding:0;font-family:sans-serif;background-color:#ededed}</style><title>my-app</title><my-app heading="Hello world!"></my-app><script>window.importShim=i=>import(i);</script><script>!function(){function e(e){return new Promise(function(o,t){var n=document.createElement("script");n.onerror=t,n.onload=o,n.src=e,n.defer=!0,document.head.appendChild(n)})}var o=[];function t(){window.importShim("./my-app.js")}"noModule"in HTMLScriptElement.prototype&&!("importShim"in window)&&o.push(e("polyfills/dynamic-import.b745cfc9384367cc18b42bbef2bbdcd9.js")),"attachShadow"in Element.prototype&&"getRootNode"in Element.prototype||o.push(e("polyfills/webcomponents.88b4b5855ede008ecad6bbdd4a69e57d.js")),!("noModule"in HTMLScriptElement.prototype)&&"getRootNode"in Element.prototype&&o.push(e("polyfills/custom-elements-es5-adapter.551c76d38426de62c33d8c61995c1d0f.js")),o.length?Promise.all(o).then(t):t()}();</script></body></html>
```
Notice that the output strips `<!doctype html>` and prematurely ends `<head>`, putting `<meta>` tags in `<body>`. There's a <U+FEFF> after the opening body tag that isn't printed above. Here's what I think is happening:

- The parser encounters the U+FEFF BOM before `<!doctype html>`.
- It assumes it's the start of the body's content.
- It prepends the prefetch link in a `<head>` that it adds to the very top.
- All other content (including the U+FEFF) gets dumped into the `<body>`.
- Because `<!doctype html>` isn't first, it gets stripped like a normal comment.

I'm not an encoding expert, but it seems like either:
- The parser should be BOM-aware
- It should be automatically stripped before parsing, as in https://github.com/TrySound/rollup-plugin-string/pull/8/files
- Users should be responsible for not having BOMs on source files

In any case, silently producing a corrupt build is not a good outcome. I'm guessing the BOM in my index.html was unintentionally added by a former dev who developed on Windows. I've been building with polymer-cli for the past few years without issue.

**Comment by LarsDenBakker** [comment]
I see... we rely on https://www.npmjs.com/package/parse5 for parsing HTML and https://www.npmjs.com/package/html-minifier for minifying. I suspect one of these two tools is not handling this properly.
