### ISSUE TITLE
[webpack-import-meta-loader] __webpack_public_path__ is not being taken into account

### ISSUE THREAD

**Issue by tmsns** [open-wc/open-wc#569]
When using the `webpack-import-meta-loader` plugin to rewrite `import.meta` to a correct fixed url, the [__webpack_public_path__](https://webpack.js.org/guides/public-path/#on-the-fly) variable is not being taken into account. This variable (dynamically) defines the root path of the project.

**Comment by tmsns** [comment]
I'll try to whip up a PR for this. :-)

**Comment by LarsDenBakker** [comment]
What's the public path intended for? I tried it out before, but it didn't seem to change the build output.

**Comment by tmsns** [comment]
> What's the public path intended for? I tried it out before, but it didn't seem to change the build output.

The public path is used to define the http path of the root of your build output.
In some cases the (static) build output (js,css,images, ..) is stored on a different path than the bootstrap html. Some use cases:
- using a cdn for the assets
  ```bash
  # bootstrap html
  https://www.example.com/path/to/page
  # asset url
  https://cdn.example.com/my-project/2.0.0/bootstrap.js
  ```
- the same bootstrap html is used under different paths
  ```bash
  # bootstrap html
  https://www.example.com/path/to/page
  https://www.example.com/path/to/sub/page
  # asset url
  https://www.example.com/bootstrap.js
  ```

The default way to solve this is to use the `base` tag to change the `baseURI`. Unfortunately this will also change the behavior of relative anchor tags. When defining the Public Path, you define the root (eg. `https://cdn.example.com/my-project/2.0.0/`) of the project. This allows WebPack to resolve dynamic modules correctly. The definition can be done at build time or at runtime.

`import.meta` however is often used to get the root of some component, but doesn't take into account these different paths.

> Happy to accept a PR, but in the interest of honesty we're also looking to deprecate the import meta loader in favor of the babel import meta plugin.
> We already use this babel plugin for production builds, but use the import meta loader during development because it's faster than running babel just for the import meta rewrite. Since we're going to start promoting https://open-wc.org/developing/es-dev-server.html for development, we might as well drop the meta loader as well especially since we run into quite some limitations with it.

We will probably switch the babel import meta plugin as well, but we'd like to finish our first production build as well first, before changing again. :-)
When using babel to transform `import.meta` and keep the same functionality, we'll need to investigate how to support the dynamic examples of above.

**Comment by LarsDenBakker** [comment]
that's pretty interesting  stuff, but I'm not sure if that should be within the scope of any tool that handles import.meta. 

The goal of the webpack and babel plugin is to preserve the `import.meta.url` value from before bundling, and to mimick the same behavior as if you would use `import.meta.url` natively in the browser. If you use `import.meta.url` in a native module it would also not know about the public path, right?

**Comment by tmsns** [comment]
> The goal of the webpack and babel plugin is to preserve the `import.meta.url` value from before bundling, and to mimick the same behavior as if you would use `import.meta.url` natively in the browser. If you use `import.meta.url` in a native module it would also not know about the public path, right?

Indeed the plugins are there to  mimick the same behavior to be able to use `import.meta.url` as if it was natively. The issue is that the value of `import.meta.url` cannot completely be known at build time. Let me take  `https://cdn.example.com/assets/project/src/file.js` as an example.

- The part that can be known at build time is the path within the project `./src/file.js`. This file could have been generated by bundling multiple modules together. Let's call it the "local path".
- The part before it (`https://cdn.example.com/assets/project/`) is only known at runtime. Let's call this the "prefix".

Both the prefix and the local path are needed to have the full url. So, a native module would intrinsically know about the prefix. And the way webpack allows to set/use this dynamic prefix, is to define `__webpack_public_path__`. So, when using webpack, I feel this could be a way to make sure the value is correct.

**Comment by LarsDenBakker** [comment]
My point is that if you would use the native browser module system and have import.meta.url in there, would it take into account the webpack public path?

**Comment by tmsns** [comment]
The polymer cli will create the `import.meta.url` url by combining at runtime:
- a runtime part: the `meta.url` 
This serves as base url and is the absolute url of the (combined) amd script file.
`meta` is an amd dependency inherently [provided by the esm-amd-loader](https://github.com/Polymer/tools/blob/master/packages/esm-amd-loader/src/esm-amd-loader.ts#L281). 
- a static / build part, the path to the original module
This path is relative to the build (combined) script file. It's computed at build time by [polymer-build and babel](https://github.com/Polymer/tools/blob/dc391830fec747bb6164109157cd3a24302e346a/packages/build/src/babel-plugin-import-meta.ts).
