### ISSUE TITLE
Generator CLI input line covers up with warning on mac terminal

### ISSUE THREAD

**Issue by petecarapetyan** [open-wc/open-wc#575]
This may be particular to my setup, but when I run the generator with
>npm init @open-wc

The bottom or input line is not visible, but instead is covered up with this text:

`⸨░░░░░░░░░░░░░░░░░░⸩ ⠴ : verb config Skipping project config: /Users/myusername/.npmrc. (matches userconfig)`

It confused me at first because I wasn't seeing all my options for each of the steps, but then when I got to the choice of webpack vs rollup I could barely see the webpack line blink so that's the only way I could even figure out what was going on.

LMK if I can help debug this.

**Comment by LarsDenBakker** [comment]
That message comes from npm itself. Do you get this only when using `npm init @open-wc` ? What if you just do `npm init`?

**Comment by petecarapetyan** [comment]
If I run `npm init` it runs the standard package.json creation routine, seems to work perfectly.

Is there a reason my setup makes me the only one that reports this problem? Should I be using something other than terminal? Is the documentation describing `npm init @open-wc` correct?

**Comment by daKmoR** [comment]
we now updated to the latest version of `prompts` - could you verify if the problem still persists? if so I guess it's probably in this package we are using 🙈

**Comment by petecarapetyan** [comment]
It appears to still be a problem, although I am becoming pretty talented in using the arrow keys to make the bottom line 'flash' just enough to keep using the interface. I finally got through the whole process, now - that is better than before.

Still wondering why others aren't reporting this, will post to slack for more discussion.

**Comment by petecarapetyan** [comment]
Workaround if you're on a mac and you use VSCode, and Mac's terminal for your npm shell work:

Instead, use VSCode's internal terminal.
