### ISSUE TITLE
is it possible to use @open-wc/testing for a project not scaffolded by open-wc tool?

### ISSUE THREAD

**Issue by jimisdrpc** [open-wc/open-wc#589]
Basically I am getting TypeError: Failed to resolve module specifier “@open-wc/testing”. Relative references must start with either “/”, “./”, or “../” following https://open-wc.org/testing/#setup. I just created a question in stackoverflow adding the whole code used https://stackoverflow.com/questions/57066106/typeerror-failed-to-resolve-module-specifier-open-wc-testing-relative-refer. I guess the must relevant info is that I didn't used the open-wc scaffold tool for such prokect. May I lost tsome dependency? And I install it via npm instead of yarn

**Comment by LarsDenBakker** [comment]
If you are using a 'bare import' you will need to resolve this somehow, as the browser doesn't understand where to find `@open-wc/testing` it only understand file paths.

What does your karma config look like? You can check https://open-wc.org/testing/testing-karma.html#new-project to see how to set up karma, and specifically our karma plugin: https://open-wc.org/testing/karma-esm.html#testing-typescript 

With our plugin you need to configure `nodeResolve` to true.

**Comment by jimisdrpc** [comment]
Kindly, you can find my karma config at https://github.com/jimisdrpc/basic-vanilla-webcomponent/blob/master/karma.conf.js and the test import is:

> 
> import {
>   html,
>   fixture,
>   expect,
> } from '@open-wc/testing';

. Meanwhile I will check the links you sent me above.

**Comment by jimisdrpc** [comment]
I noticed that I can succesfully import and @open-wc/testing in my test file if I use the karma.conf.js scaffolded by open-wc tool but I can't when trying with project created manually. I noticed alson that in karma.conf.js there is "const { createDefaultConfig } = require("@open-wc/testing-karma");" and createDefaultConfic is passed to deepmerge warraper before setup karma config. Is this really necessary if I want to use @open-wc/testing? Can you compare my karma.conf.js created without open-wc tool (https://github.com/jimisdrpc/basic-vanilla-webcomponent/blob/master/karma.conf.js) with other karma.conf.js created by open-wc scaffold tool (for instance: https://github.com/jimisdrpc/openwc-testing-vanilla-webcomponent/blob/master/karma.conf.js)? I guess only adding @open-wc/testing dependency will fail when importing it in my test file if I don't include it in karma.conf.js. Does it make sense to you? If so, how could I fix my karma.conf.js?

**Comment by daKmoR** [comment]
the reason is that `createDefaultConfig` abstracts away quite some settings.

So basically you run the function which returns a valid karma config and then merge in your own settings.

if you prefer to have everything in your own file then you probably should start by copying the config from [this file](https://github.com/open-wc/open-wc/blob/master/packages/testing-karma/src/create-default-config.js).
Mind you you really need most of those plugins to do for example the bare module resolution, transpilation for older browsers, coverage, ...
Mind you if we change something or fix a bug in `createDefaultConfig` you will not get that update...
therefore I would not recommend that method

**Comment by LarsDenBakker** [comment]
You don't need our config to use `@open-wc/testing`, but you need something to process your javascript before serving it to the browser. There are two primary issus:

- Karma doesn't allow using the es module loader in the browser (that's what the `karma-esm` plugin is for
- The browser can't resolve `import foo from 'bar'`, we also fix that in `karma-esm`.

You could for instance use `karma-webpack` to do the same for you. You can also use `karma-esm` standalone outside of our config.

**Comment by LarsDenBakker** [comment]
Closing this as there does not seem to be anything actionable here. Reopen if you still need any help with this.
