### ISSUE TITLE
[linting] Add prettier

### ISSUE THREAD

**Issue by web-padawan** [open-wc/open-wc#59]
Let's consider adding `prettier` to the list of recommendations.

Pros:
- Supports `html` tagged literals and HTML syntax in general starting from v1.15, see [blog post](https://prettier.io/blog/2018/11/07/1.15.0.html#html-vue-angular)
- Supports `css` tagged literals being used by `lit-css` and `styled-lit-element`

Also worth mentioning:
- `eslint-config-prettier`
- `stylelint-config-prettier`
- `stylelint-processor-styled-components`

There is working example in https://github.com/web-padawan/lit-components

**Comment by LarsDenBakker** [comment]
Had my eye on prettier for a while. What are the differences in rules VS our current setup?

**Comment by web-padawan** [comment]
Will submit a PR with a proposal so we could discuss it. 

One more note regarding HTML: prettier/prettier#5501 is needed for more flexible formatting

**Comment by LarsDenBakker** [comment]
Any progress on this? I'm quite interested :)

**Comment by web-padawan** [comment]
Sorry, was a bit busy with the [webcomponents-the-right-way](https://github.com/mateusortiz/webcomponents-the-right-way) project 😃 

Will submit the PR today.
