### ISSUE TITLE
npm run start:compatibility not working in older browsers

### ISSUE THREAD

**Issue by lakshay35** [open-wc/open-wc#592]
Every time I run the start:compatibility command, the server is unable to server the polyfills as shown in the image:
![image](https://user-images.githubusercontent.com/10873132/61385163-e5ba1000-a87f-11e9-9b13-6ac667af23ba.png)

**Comment by LarsDenBakker** [comment]
Hi there! Whats your version of es dev server, and the full command you are using?

**Comment by lakshay35** [comment]
the latest - 1.6.4

**Comment by LarsDenBakker** [comment]
I just tested it, and it works fine for me. On mac chrome and IE11 VM:

<img width="1368" alt="Screen Shot 2019-07-17 at 5 27 42 PM" src="https://user-images.githubusercontent.com/11994993/61389058-8a584400-a8b8-11e9-9258-8d0411c02d03.png">

There are some 404s for sourcemaps, which we still need to fix.

What OS are you on? Do you also get a 404 on chrome? There it should request es-module-shims as well.

**Comment by lakshay35** [comment]
I am on windows 10 and yes I do get a 404 on chrome for es-module shims

**Comment by LarsDenBakker** [comment]
looks like another windows file path bug, fixing it now :(

**Comment by lakshay35** [comment]
Thank you so much. It is working now. Additionally is there a specific reason why watch does not function in IE11 and EDGE?

**Comment by LarsDenBakker** [comment]
Thats because they dont support EventSource for server sent events.
