### ISSUE TITLE
replace all uses of webpack-merge with deepmerge

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#600]
we no longer use webpack in any of our tools unless specifically using it build your app, but we still use `webpack-merge` in many places.

we should replace this with `deep-merge` which does the job just as well, but with less complexity.

what do you think @daKmoR ?

**Comment by daKmoR** [comment]
at some point, we used the [webpack-merge strategies](https://www.npmjs.com/package/webpack-merge#merging-with-strategies) but apparently, we no longer do.

if deep-merge does the job sure why not 👍  (last published 5 years ago... not sure if that is a bad or a good sign 😅 🤣 )

**Comment by LarsDenBakker** [comment]
Actually I meant `deepmerge`, not `deep-merge`. `deepmerge` was last updated 10 days ago :)

`webpack-merge` is 9.4k and `deepmerge` is 664b with 0 dependencies. I know they're not browser libraries, but I still want to try and keep our tools as light as possible.

**Comment by daKmoR** [comment]
make sense 👍
