### ISSUE TITLE
[es-dev-server] Create a createServer separate from startServer

### ISSUE THREAD

**Issue by usergenic** [open-wc/open-wc#608]
Right now I'd love to wire up a configured `es-dev-server` as a middleware but I can't do that because the big `startServer` function does everything including the `listen()` call.

Would be nice if this was designed to be used as a library as well as dev-server launcher.  Recommend a `createServer` or `setupServer` or `buildServer` function, maybe that gets delegated to by `startServer`.

**Comment by LarsDenBakker** [comment]
Yeah, makes sense I'll add that in.

We can break it up into creating the middlewares, creating the server and starting the server.

**Comment by LarsDenBakker** [comment]
There are some more aspects to consider when programmatically using the dev server, for example when I created `karma-esm` I can't let `es-dev-server` take care of my index.html and have to do all the polyfill work and loading libraries like systemjs myself.

It would be good to gather some use cases, and think of some good generic solutions. Right now the dev server takes quite some assumptions that might not always be valid.
