### ISSUE TITLE
[es-dev-server] service worker caching

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#610]
Currently in the dev server we cache based a last-modified check. Each time a file is requested we check if it hasn't changed and the server returns a 403. This requires a server request for each file, which still has some overhead. When building an unbundled application, the amount of requests can be quite large.

We could investigate if we can add a service worker which keeps received notifications from the server when files change. If a file hasn't change, the service worker can serve the file from cache instead of needing to contact the server.

**Comment by daKmoR** [comment]
how will this work if the user has its own service worker? as far as I know, there can only be on service worker at the root of a domain 🙈
