### ISSUE TITLE
Working with monorepo

### ISSUE THREAD

**Issue by clementlemarc-certua** [open-wc/open-wc#612]
Hi,
I have some issue setting up tests in an existing monorepo and I'm not sure with if it is me or something missing in the documentation.

**Setup**
We use yarn workspaces to manage our monorepo. Structure is the following
```
node_modules
|_ @open-wc/
packages
|_ packageA
    |_ lib
        |_ index.js 
    |_ test
        |_ foo.test.js
    |_ karma.conf.js
```
- index.js is built using rollup and aggregates several custom elements in a library (provided to third parties)

The test is really basic
```js
import { html, fixture, expect } from '@open-wc/testing';

import '../lib/index.js';

describe('Foo test empty', () => {
  it('has by default an empty string as label', async () => {
    const el = await fixture('<foo-element></foo-element>');
    expect(el.label).to.equal('');
  });
});
```

Karma config is the following:
```js
const createDefaultConfig = require('@open-wc/testing-karma/default-config');
const merge = require('webpack-merge');

module.exports = config => {
  config.set(
    merge(createDefaultConfig(config), {
      files: [
        // runs all files ending with .test in the test folder,
        // can be overwritten by passing a --grep flag. examples:
        //
        // npm run test -- --grep test/foo/bar.test.js
        // npm run test -- --grep test/bar/*
        { pattern: './packages/packageA/test/**/*.test.js', type: 'module' },
      ],
      basePath: '../../',
      // you can overwrite/extend the config further
      esm: {
        nodeResolve: true,
        // moduleDirectories: ['./../../node_modules'],
      },
    }),
  );
  return config;
};
```
* I followed documentation and use _basePath_ to point to the monorepo root folder
  * If I don't, it tries to resolve `packages/packageA/node_modules/@open-wc/testing/index.js` and fails
* I had to update the _pattern_ to indicate the full path in the monorepo (`packages/packageA/test`) for the test file to be detected. It doesn't seem to be documented.

The esm middleware is logging some weird things when I run tests:
```
22 07 2019 17:46:27.498:ERROR [middleware.esm]: 
File does not exist: /Users/.../repo/packages/packageA/node_modules/@open-wc/testing/index.js
 at ./node_modules/@open-wc/testing/index.js

22 07 2019 17:46:27.499:ERROR [middleware.esm]: 
File does not exist: /Users/.../repo/packages/packageA/packages/packageA/lib/index.js
 at ./packages/daas-elements/lib/index.js

HeadlessChrome 76.0.3809 (Mac OS X 10.14.5) ERROR
  Uncaught SyntaxError: Unexpected identifier
  at node_modules/@open-wc/testing/index.js:3:6
  
  SyntaxError: Unexpected identifierHeadlessChrome 76.0.3809 (Mac OS X 10.14.5) ERROR
  Uncaught SyntaxError: Unexpected identifier
  at node_modules/@open-wc/testing/index.js:3:6
  
  SyntaxError: Unexpected identifier
Finished in 0.119 secs / 0 secs @ 17:46:27 GMT+0100 (British Summer Time)
```
* For the _@open-wc/testing_ import, it doesn't seem to use the _basePath_ 
* For the _../lib/index.js_ it is using twice the path to the package: `packages/packageA/packages/packageA`

I have been trying to use the _moduleDirectories_ options for esm but it is not well documented and I'm currently reading the esm middleware source code to understand what's going on. 

Not sure if it's me or not but any help would be appreciated :)

Thanks!

**Comment by LarsDenBakker** [comment]
What version of `@open-wc/testing` and `@open-wc/testing-karma` and `@open-wc/karma-esm` are you on?

Here is an example configuration in our own monorepo which works: https://github.com/open-wc/open-wc/blob/master/packages/testing-karma/demo/karma.conf.js

**Comment by clementlemarc-certua** [comment]
Thanks for your quick answer!

From the package.json
```json
    "@open-wc/testing-karma": "^2.0.0",
    "@open-wc/testing-karma-bs": "^1.0.0",
    "@open-wc/testing": "^0.11.1"
```
I used the _npm init_ to add testing to the project but maybe that's the issue. I'll have a look at the monorepo demo to understand better how it works :)

**Comment by LarsDenBakker** [comment]
Yeah that's probably the issues. You can see the latest versions of these packages on https://github.com/open-wc/open-wc. We're updating our generators asap.

**Comment by clementlemarc-certua** [comment]
OK! I'll reset my repo and will try the manual approach

**Comment by LarsDenBakker** [comment]
@clementlemarc-certua were you able to make it work? The generators are updated too now.

**Comment by clementlemarc-certua** [comment]
@LarsDenBakker 
Sorry for not coming back to you sooner.

Manual installation/configuration did solve my issue! I'm going to setup a new projects in the coming weeks, I will try again the generators then :)

Many thanks! Great work 👍
