### ISSUE TITLE
[webpack] Add support for just import.meta

### ISSUE THREAD

**Issue by redbugz** [open-wc/open-wc#62]
The recommended way of using `import.meta.url` with Polymer seems to be to add a getter for `import.meta` [1]. Should the webpack import-meta-loader support this use case as well in case you try to load a Polymer3 component?
Or is this more for people not using Polymer?

[1] https://polymer-library.polymer-project.org/3.0/docs/upgrade (see item 6)

**Comment by daKmoR** [comment]
uh that's a tough one I would say 🙈 

I mean we could replace `import.meta` and return an object with 
```
return import.meta;
// return ({  url: /*generated url*/ });

return import.meta.url;
// return ({  url: /*generated url*/ }).url;
```

but on native browsers (supporting it) there might be other import.meta properties which we will then override.

Still probably a good idea to implement it (maybe via a second "forked" loader) so you can easily opt in/out.

what do you think?

**Comment by daKmoR** [comment]
@redbugz pls test and it let us know if it works for you :)
