### ISSUE TITLE
Build: Add Safari 10.1 nomodule fix

### ISSUE THREAD

**Issue by abdonrd** [open-wc/open-wc#623]
Safari 10.1 supports modules, but does not support the `nomodule` attribute - it will load `<script nomodule>` anyway.

Reference: [Modern Script Loading](https://jasonformat.com/modern-script-loading/)

>First, there's the [Safari Fix](https://gist.github.com/samthor/64b114e4a4f539915a95b91ffd340acc). Safari 10.1 supports JS Modules not the `nomodule` attribute on scripts, which causes it to execute both the modern and legacy code (yikes!).
>
>Thankfully, Sam found a way to use a non-standard `beforeload` event supported in Safari 10 & 11 to polyfill `nomodule`.

**Comment by LarsDenBakker** [comment]
Are we loading something that's broken on safari 10.1, or are we just shipping extra code unnecessarily?

In the former we should fix it, if the latter we could add an option to opt in to adding the safari fix.

**Comment by abdonrd** [comment]
Download and execute both, the modern and legacy code. Because Safari 10.1 supports modules, but does not support the `nomodule` attribute, so it will load `<script nomodule>` anyway. This Safari Fix snippet solve this problem.

Note also that `nomodule` is supported in later versions of Safari - it's just 10.1 that omits this attribute.

**Comment by LarsDenBakker** [comment]
We don't use `<script nomodule>` for loading the application though, we use a check in javascript so it won't load both versions right?

**Comment by abdonrd** [comment]
You are right Lars, it only apply to the polyfills!
I see `core-js`, `systemjs` and `regenerator-runtime`.

**Comment by LarsDenBakker** [comment]
In my humble opinion that's ok, we should focus on pushing performant code to modern browsers and functioning code to older browsers. Most apps are actually shipping all these things to all users on any browsers :)

Happy accept a PR though if this is important to anyone.
