### ISSUE TITLE
How to access runtime variables in deployment

### ISSUE THREAD

**Issue by sbryan** [open-wc/open-wc#626]
What are the recommendations or common practices for accessing runtime config options/variables in a deployed state for an SPA built using rollup/webpack?

In the past, my apps were served by an express instance running in deployment and we could set keys, certs, tokens and other runtime configs via terraform scripts, or from cli exposed environment variables.

I’m now working with a Cloud Foundry instance which has a concept of “environments” that provides collections of variables that will be available to the runtime at start, but, considering that now all I’m deploying is an SPA with an index.html and bundles… I’m kinda at a loss as to what/how I can access the available runtime variables that CF exposes for me from within my app context?

Stated another way… Live services have keys (API service tokens, and Auth service API tokens, certs, etc?) that will need to accessed/read at runtime, but, for obvious security reasons, absolutely *CAN NOT* be compiled into my bundles using babel or rollup replacement plugins… They need to be able to read at startup from **_somewhere?!?!_** from within the apps JS context.

This issue is really just a request for some new/additional documentation that covers this real world need and maybe serve as a collection point for those recommendations from which docs can be seeded.

**Comment by bennypowers** [comment]
you can use [`rollup-plugin-replace`](https://github.com/rollup/rollup-plugin-replace) to copy data from the node context to your bundle at build time.

Anything more complicated than that should probably rely on some secret store over the network

```js
// pseudo app.js

login()
  .then(fetchKeysWithSession)
  .then(initializeStateStoreWithKeys)
  .then(lazyLoadAppComponents)
```

**Comment by abdonrd** [comment]
One option might be:

- Have a `src/config/` folder with `development.js`, `staging.js` and `production.js` files.
- The `index.js` file import the `development.js` file by default:
```javascript
import config from './development.js';

const sharedConfig = {
  // ...
};

export default { ...sharedConfig, ...config };
```
- The `development.js`, `staging.js` and `production.js` files export a config object.
```javascript
export default {
  // ...
};
```
- With Rollup change the default `development.js` import using the `process.env.NODE_ENV` and `rollup-plugin-replace`.
```javascript
const ENVIRONMENT = process.env.NODE_ENV || 'development';

// ...
    plugins: [
      replace({
        include: 'src/config/index.js',
        development: ENVIRONMENT
      })
    ]
// ...
```

**Comment by tpluscode** [comment]
There are plugins to easily inject env variables into bundles: [dotenv-webpack](https://github.com/mrsteele/dotenv-webpack) and [rollup-plugin-dotenv](https://github.com/Andarist/rollup-plugin-dotenv)

Like @bennypowers said, anything that is sensitive should be handled with care.
