### ISSUE TITLE
[es-dev-server] won't resolve paths to node_modules correctly

### ISSUE THREAD

**Issue by jarrodek** [open-wc/open-wc#630]
Very recently (like 2 days ago) my demo pages stopped working with latest version of `es-dev-server`. 

**This used to work**
```html
<script type="module" src="../node_modules/@polymer/paper-toggle-button/paper-toggle-button.js"></script>
```

But now the console says 
```
GET http://localhost:8080/demo/.node_modules/@polymer/paper-toggle-button/paper-toggle-button.js net::ERR_ABORTED 404 (Not Found)
```

It **will** work if I'll put dependencies into `index.js` file and import that from there but it will be impossible to rewrite all my demo pages (> 300 web components) just to fix this issue.

This is my regular demo page:

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1, initial-scale=1, user-scalable=yes">
    <title>star-rating demo</title>
    <!-- A helper to render demo pages -->
    <script type="module" src="../node_modules/@advanced-rest-client/arc-demo-helper/arc-demo-helper.js"></script>
    <!-- This module -->
    <script type="module" src="../star-rating.js"></script>
  </head>
  <body>
    <div class="vertical-section-container centered">
      <h3>Rating with value</h3>
      <arc-demo-helper>
        <template>
          <star-rating value="3"></star-rating>
        </template>
      </arc-demo-helper>
    </div>
  </body>
</html>
```

**Comment by LarsDenBakker** [comment]
Looking at the code we never supported stepping up in the file path (`../`) in compatibility mode, so that's something to add.

I'm curious why it did work for you before, what command are you using to run the server?

Short term this could work inline if you have the node resolve option:
```js
<script type="module">
  import '@advanced-rest-client/arc-demo-helper/arc-demo-helper.js';
</script>
```

Will make sure to add support for this in

**Comment by jarrodek** [comment]
My configuration on which this worked (just tested it):

```
"devDependencies": {
  "es-dev-server": "^1.5.0"
},
"scripts": {
  "start": "es-dev-server --app-index demo/index.html --node-resolve --open --watch",
}
```

and demo file: https://github.com/advanced-rest-client/google-drive-browser/blob/stage/demo/index.html

**Comment by jarrodek** [comment]
Also, this 
```javascript
<script type="module">
  import '@advanced-rest-client/arc-demo-helper/arc-demo-helper.js';
</script>
```
won't work as I tried it as well.

**Comment by LarsDenBakker** [comment]
It should work again now, it was indeed a regression between 1.5.0 and later.
