### ISSUE TITLE
[karma-esm] remove @types/deepmerge

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#634]
when doing `yarn install`  on a project just initialized I do get

> warning @open-wc/testing-karma > @open-wc/karma-esm > @types/deepmerge@2.2.0: This is a stub types definition. deepmerge provides its own type definitions, so you do not need this installed.

seems we can just get rid of it?

**Comment by LarsDenBakker** [comment]
Yes seems like it
