### ISSUE TITLE
compatibility all mode not adding polyfills anymore in EDGE and IE 11

### ISSUE THREAD

**Issue by lakshay35** [open-wc/open-wc#639]
I pulled down the new updated es-dev-server @LarsDenBakker and am not getting the import path url bug anymore. However, when running with compatibility all mode in EDGE 42 and IE 11 on a windows 10 machine, I get two different errors:

1. IE
a. The import is not being initated as a module (i.e. not pulling down the import statements inside the requested file as resources), which it was doing in earlier versions (1.6.6).

2. EDGE
a. Polyfill errors with ```customElements``` not being found. I believe both browsers are not getting the polyfill files anymore.

**Comment by LarsDenBakker** [comment]
@lakshay35 I just tested and it works fine for regular projects.

I think in your case you are requesting your resource from another web server on another port, so the request is not handled by `es-dev-server`. We can't realistically do anything to handle that.
