### ISSUE TITLE
[demoing-storybook] No matching version found for @storybook/api@5.1.9

### ISSUE THREAD

**Issue by dbsdragon** [open-wc/open-wc#643]
encounter the following error whilst doing init or manual install for demoing via npm 

```
npm i @open-wc/demoing-storybook@latest
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @storybook/api@5.1.9
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@storybook/addon-actions'
npm ERR! notarget
```

**Comment by bennypowers** [comment]
seems odd, since addon-actions does specify api as a dependency

https://github.com/storybookjs/storybook/blob/master/addons/actions/package.json

Try ```rm -rf node_modules && npm install```

**Comment by dbsdragon** [comment]
> seems odd, since addon-actions does specify api as a dependency
> 
> https://github.com/storybookjs/storybook/blob/master/addons/actions/package.json
> 
> Try `rm -rf node_modules && npm install`

this was a fresh install in a new directory that resulted in this, also remains the same if clearing node_modules and package-lock.json

**Comment by dbsdragon** [comment]
its ok, figured out, we're behind a corporate firewall using nexus as a mirror to npm registry and there seems to be stale resolution there resulting in api/5.1.0 still.
