### ISSUE TITLE
Build: add polyfills in rollup configuration

### ISSUE THREAD

**Issue by Tansito** [open-wc/open-wc#647]
We are using the Rollup `createCompatibilityConfig` as a base to build our projects, but we couldn't figure out how to add custom polyfills by ourselves like a [plugin](https://open-wc.org/building/building-rollup.html#extending-the-rollup-config) but without touch the `indexHTML`. How can you add them?

**Comment by LarsDenBakker** [comment]
It's not that well described in the docs yet (so let's keep this issue open as a reminder). But basically you can configure `rollup-plugin-index-html` to add polyfills: https://open-wc.org/building/rollup-plugin-index-html.html#polyfills

You can pass the index.html configuration to `createCompatibilityConfig` using a propery, see: https://open-wc.org/building/building-rollup.html#common-extensions

**Comment by Tansito** [comment]
Wow, thanks for being so fast Lars I will take a look
