### ISSUE TITLE
[Testing] provide elementUpdated function through @open-wc/testing

### ISSUE THREAD

**Issue by SampsonCrowley** [open-wc/open-wc#649]
I believe it would be useful and promote more complete testing practices if `elementUpdated` from `testing-helpers` was also provided by default from the main `testing` package. this way users can test attribute changes are reflected in components correctly

**Comment by daKmoR** [comment]
when you are writing a test it's probably better to use the specific update check your base element provides? seems to be more specific

```js
// lit-element
it('reflects property fooBar to attribute foo-bar', async () => {
  const el = fixture('<my-el></my-el>');
  el.fooBar = true;
  await el.updateComplete;
  expect(el.hasAttribute('foo-bar')).to.be.true
});

// stencil
it('reflects property fooBar to attribute foo-bar', async () => {
  const el = fixture('<my-el></my-el>');
  el.fooBar = true;
  await el.componentOnReady();
  expect(el.hasAttribute('foo-bar')).to.be.true
});
```

would you see a benefit of using `await elementUpdated(el)` instead?

**Comment by SampsonCrowley** [comment]
@daKmoR yes, you could do that. but the code is already written in elementUpdated to already handle it for you, AND provide fallbacks.

it already exists in the `testing-helpers`, and half the functions from the template-helpers are already exported as part of `testing` anyways

I much prefer the idea of using already written wrapper code `await elementUpdated(el)` (in fact that is **exactly** the line in my test) to inserting library specific code into the web component tests. It's even marketed already in the docs that `fixture` handles that for you during element setup, so why not also provide the main function that handles waiting for you for testing attribute changes and property updates, ya know?

If it wasn't already written, I'd probably be writing the wrapper myself

If i leave it up to the wrapper, than it's also easier in the future to switch Element libraries

**Comment by SampsonCrowley** [comment]
example test:

```
import {
  html,
  fixture,
  expect,
} from '@open-wc/testing';

import {
  elementUpdated,
} from '@open-wc/testing-helpers';

import '../../src/register-template-helper.js';

```
describe('Attributes', () => {
  describe('.title', () => {
    ...
    it('is is bound to the `title` attribute', async () => {
      const el = await fixture('<template-helper title="test"></template-helper>');
      expect(el.title).to.eq('test');

      el.title = "test 2"
      await elementUpdated(el)

      expect(el).dom.to.equal(`<template-helper title="test 2"></template-helper>`);
    });
    ...
  })
});
```

**Comment by daKmoR** [comment]
sounds good to me 🤗 

could you provide a PR that adds the additional export to `@open-wc/testing` - pretty please 🤗

**Comment by SampsonCrowley** [comment]
can do!

**Comment by SampsonCrowley** [comment]
#653

**Comment by SampsonCrowley** [comment]
@daKmoR off-topic, but are you aware of what the failing CI builds are about? I was gonna dive in and get it up and running again, but haven't looked at the causes yet

**Comment by daKmoR** [comment]
thanks to your contribution https://github.com/open-wc/open-wc/pull/653 it is now available 🤗 

thx 👍
