### ISSUE TITLE
[docs] how to publish component to NPM

### ISSUE THREAD

**Issue by SampsonCrowley** [open-wc/open-wc#650]
The only docs currently available on publishing components are for hosting applications. I want to use web components across ALL of my projects, so I need to know what the open wc recommendations are for publishing the web component scaffold as an NPM module

**Comment by SampsonCrowley** [comment]
I also think telling people, "go pay for netlify" is far from the proper solution. 99% of JS developers use NPM, it's free, and there's no reason we should be pushing for a whole new registry service that Open-Source devs have to pay to make their stuff available for free

**Comment by daKmoR** [comment]
publishing, in this case, is meant to be for publishing a web site 🙈 and we recommend netlify for it as it's free and super simple to setup.

for publishing npm package we currently do not have any guidance. But sounds like a good thing to add 🤗 

from the top of my head, I would say it should be something like
- publish to npm
- have a `module` property in your `package.json`
- publish the source code as "vanilla" es6 (e.g. not transpiled)
- publish only the source code (e.g. no test files or so)

what do you think? care to write a file probably `docs/publishing/web-components.md`? and add it via a PR?

**Comment by SampsonCrowley** [comment]
@daKmoR That's the basics I have so far.

I want to make sure the components are both available as a compiled legacy code the just works<sup>TM</sup>(e.g. in their main entry just `import "@web-helpers/my-component"` and add the HTML tags) when people keep `node_modules` as `excludes` in their build, and importable directly as source for users that know how/what they are building

Once I've worked out the dirty details with a test component or two, I'll put together a PR with the instructions

**Comment by daKmoR** [comment]
under legacy compiled code I understand - es5 code (e.g. no es modules, no classes, no spread, ...)
=> this is something we probably can not recommend as this would require essentially to compile all your dependencies as well... which would lead to lots of duplicate code

you should "compile" decorators and such but stay with es6
=> so it will just work for evergreen browsers

if you need to serve older browser then you can compile the es6 source to whatever is needed (but ONLY the application should do that)
components usually should not be distributed compiled (for the mentioned constraints)

**Comment by SampsonCrowley** [comment]
That should simplify things, only publish as ES6, and let the end user handle compiling to ES5.

I mostly just think it would help move the ball forward for global adoption if there were also precompiled and polyfilled versions that devs without webpack/rollup experience can use through UNPKG or importing directly as ES5.

That might make things more complicated than it's worth though I guess

**Comment by SampsonCrowley** [comment]
TODO:

- add default `pkg.module` to @open-wc/create for NPM publishing support
- add default `pkg.jsnext:main` to @open-wc/create for more tooling support with published modules
- add docs for publishing to NPM

**Comment by LarsDenBakker** [comment]
Should we also update the netlify publishing page to clarify it's not a guide for publishing npm packages?

**Comment by SampsonCrowley** [comment]
@LarsDenBakker good idea, added to my PR todo list

**Comment by SampsonCrowley** [comment]
After digging deeper, it seems the _easiest_ solution would be to add a new `defaultConfig` (maybe `defaultNpmPackageConfig`?) option that basically targets `node >= 6.5` (version might need to be tweaked, but the key being that ESM is fully supported in Node 6.5+) instead of a browserslist and outputs an identical file structure as the input target in a `package` directory (so you can publish the sub folder directly, avoiding users to require files in the format `my-module/sub-entry` instead of `my-module/src/sub-entry`

**Comment by SampsonCrowley** [comment]
thoughts?

**Comment by SampsonCrowley** [comment]
@LarsDenBakker @daKmoR Here's the repo I'm using to work the bugs out (please ignore lack of tests, at this point it's just seeing what works and what doesn't for importing at the end-user side): https://github.com/SampsonCrowley/web-helpers

**Comment by justinfagnani** [comment]
Just saw this go by and thought I'd share my personal checklist:

1.  Publish standard ES2017
2.  Publish standard JS modules
3.  Only publish one version - do not publish multiple builds
4.  package.json:
  a.  Add "type": "module"
  b.  Set "main" to the main entry point
  c.  Set "module" to same file as "main"
  d.  Include polyfills needed for tests/demos "devDependencies", not "dependencies"
4.  Do not bundle
5.  Always self-define elements
7.  Export element classes
8.  Do not import polyfills into JS modules
9.  Do import dependencies with bare module specifiers
10.  Always include file extensions in import specifiers
11. Publish a custom-elements.json file

**Comment by LarsDenBakker** [comment]
Why es2017 and not es2018? Or rather es[current year] ?

**Comment by justinfagnani** [comment]
Mainly because Edge doesn't support object spread or async iterators.

**Comment by SampsonCrowley** [comment]
@LarsDenBakker plus, if you kept it ES7+ (I never remember which year is what number, can we stop calling it by the year it started and just use integer intervals?) then devs consuming it expecting ES6 targets, would need to know to include the necessary Babel plugins. Better to transpile to down to ES6

**Comment by SampsonCrowley** [comment]
@justinfagnani not sure I agree with #6, shouldn't naming/registering the element should be left up to the end-user to prevent conflicts?

**Comment by justinfagnani** [comment]
@SampsonCrowley there is no reasonable way to let consumers define a class they don't own. As soon as you have more than one consumer it breaks down. If both try to define the element, the second will cause an error. If the first chooses a different-than-expected name other code that relies on the name will break. The only viable solution is to define the classes you own, and if you want to use a different tag name, use a trivial subclass instead.

**Comment by justinfagnani** [comment]
@SampsonCrowley there's no such thing as "ES7". After ES5 we should refer to the year name: ES2016, ES2016, etc.

**Comment by justinfagnani** [comment]
ES2015 doesn't include async functions. Native async functions are much smaller and faster than compiled, so we should not compile them away. Also, if we get stuck on ES2015 like we were on ES5, then we haven't improved the situation all that much.

You don't need to know what Babel plugins to configure specifically based on the language level that a library uses. You need to know what plugins to use based on your _target platforms_. All current browsers support ES2017, so the default is _no build at all_. If you target IE11 then you need to include a bunch of things.

**Comment by SampsonCrowley** [comment]
@justinfagnani how so? letting them register the element is as simple as not registering it for them.

if my library contains:
```
export class MyComponent extends LitElement { ... }
```
without defining the element, it is exactly as easy for the end-user to do
```
import { MyComponent } from '...'
window.customElements.define('whatever-tag-they-want', MyComponent)
```
as it is for me to register it for them.

**Comment by LarsDenBakker** [comment]
I agree we should publish modern code, and indeed async functions can be a big problem when compiled.

I hope we can find some kind of objective metric though. Personally I'd love to stay ship only code that's been officially announced in some ecmascript year, though I'm not sure if babel can catch up with that quickly enough. 

Regarding element registration, until there is some form of registry scoping we will indeed need to ship self registering components. You can only register the same class once, so re-registering would create problems. It's quite an annoying situation we're in with that :(

**Comment by SampsonCrowley** [comment]
@LarsDenBakker was not aware of that; why is that even a restriction? that makes zero sense

**Comment by SampsonCrowley** [comment]
It seems to me the target should be all browsers that natively support ES Modules https://www.ecma-international.org/ecma-262/6.0/#sec-modules

**Comment by SampsonCrowley** [comment]
The proper way to transpile is probably to skip rollup altogether and use a pure Babel solution
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "esmodules": true
        }
      }
    ]
  ]
}
```

**Comment by justinfagnani** [comment]
@SampsonCrowley 

module-a.js:
```js
import { MyComponent } from '...';
window.customElements.define('whatever-tag-they-want', MyComponent);
```

module-b.js:
```js
import { MyComponent } from '...';
window.customElements.define('some-other-tag-name', MyComponent);
```

Whichever module loads second will lose.

**Comment by SampsonCrowley** [comment]
@justinfagnani yeah didn't know there was a 1-1 mapping between constructors and tags until today. guess that makes sense for how the browser would handle appending to the DOM if not done with markup. I thought the only way to use custom elements was through markup and document.createElement

didn't know browsers let you do:
```
const el = new MyComponent()
document.appendChild(el)
```

**Comment by justinfagnani** [comment]
@LarsDenBakker 

> I hope we can find some kind of objective metric though.

What's shipping in the big 4 (soon to be big 3) is a pretty good metric.

> Personally I'd love to stay ship only code that's been officially announced in some ecmascript year, though I'm not sure if babel can catch up with that quickly enough.

Babel actually runs ahead of that by a very large margin. The problem is browsers that lag behind, and why I don't recommend publishing ES2018 yet.

There is a slight different between syntax and API though. Edge doesn't support object rest/spread, so you really shouldn't publish that. It also doesn't support `Array.prototype.flat`, but that's polyfillable, so maybe you could and document it.

The ES year labels are the most useful label we have though, so I would tend to say stick to a standard language level and publish that level once all the major environments support it.

**Comment by SampsonCrowley** [comment]
@justinfagnani 

> The ES year labels are the most useful label we have though, so I would tend to say stick to a standard language level and publish that level once all the major environments support it.

how do you target a specific year? The only way I'm aware of is to target a specific browser for that year, or to use `"esmodules": true` which compiles to ES2015 as far as I'm aware, since that's the first year for ES Modules being supported

**Comment by justinfagnani** [comment]
@SampsonCrowley 
> how do you target a specific year?

You don't. You need to target specific browsers. You need to know what to compile _to_ more than you know what to compile _from_. You don't just compile out classes for instance, you do that only if you're targeting a browser that doesn't support them.

**Comment by SampsonCrowley** [comment]
We're not targeting any specific browsers at all, we need to target a standard, so all devs following Open WC recommendations have a reasonable assumption that Components, following the Open WC guidelines, published to NPM are transpiled to that standard.

You wouldn't expect because the library author likes using the `class properties` proposal in development, that the end-user would need to know to include that babel plugin just to use the library; You'd expect the library to be compiled down to a specific standard before being published.

**Comment by SampsonCrowley** [comment]
This whole issue is ONLY about publishing components for re-use, applications using those components are who decide what browsers to target

**Comment by justinfagnani** [comment]
@SampsonCrowley sorry, I thought you were talking about how apps should compile packages, which depends on the app's target environments.

For packages, you can just write in ES2017, or choose whatever compiler options/plugins will target it. TypeScript let's you just set the target to `"es2017"` and be done with it. I'm not sure what preset gives you the same behavior in Babel.

**Comment by SampsonCrowley** [comment]
@justinfagnani so we have a typescript target, that's a start. but since I expect Babel is going to be the transpiler of choice for at least a large chunk of any potential authors, we still need to narrow down what the standard Babel target should be; I still lean towards `esmodules` as that guarantees any ES Module compliant end-point should be able to consume the package, unless anyone has a better standard target.

**Comment by SampsonCrowley** [comment]
nevermind on "esmodules", looks like that removes any `import ...` statements and defines and `exports` property with Object.defineProperty(exports, "__esModule", {
  value: true
});

No sure why

**Comment by LarsDenBakker** [comment]
The problem with esmodules babel target is that it is a choice that's frozen in time, it doesn't evolve. In a few years it's just as bad as compiling to es5 as browser support will have come along much further.

If we say that people should ship whatever is implemented in Chrome, Safari, Firefox and Edge we can use babel preset-env and target the latest versions of those browser. That will scale along. We should create some configuration helpers for that.

That' for syntax only, polyfills should still be implemented by an app.

**Comment by SampsonCrowley** [comment]
@LarsDenBakker I'm not missing how the base standard for every new ECMA release (ES6 is basically the last numbered release, from now on, releases are just individual __features__ and at names like ES2017 are just a collection of what features were added over the year. `Array.prototype.includes` is technically it's own ECMA-262 target) is a bad target for **libraries** and published components. **Applications** can then target whatever browsers they need to support without fear of the **libraries** containing newer non-standard code that they need to include plugins to use. JavaScript will **_always_** need a specific standard to use as a base to build on, just like the vast majority of published modules available now are published as CJS modules in ES5. Then when ES6 is gets to be the equivalent of what ES5 is now, we update the recommendation to use the newer base standard

**Comment by LarsDenBakker** [comment]
babel preset-env doesn't use ecmascript years, it goes by what's supported in the browser.

**Comment by SampsonCrowley** [comment]
@LarsDenBakker which is why `esmodules` is the most standard target available right now

**Comment by SampsonCrowley** [comment]
either that or something like:
```
module.exports = function (api) {
  api.cache(false);

  const presets = [
          [
            "@babel/preset-env",
            {
              targets: {
                browsers: [
                  "chrome >= 61",
                ]
              },
              spec: true,
              modules: false,
              loose: false
            }
          ]
        ],
        plugins = [
          [ "@babel/plugin-proposal-class-properties", { loose: false } ]
        ];

  return {
    presets,
    plugins
  };
}
```
where `chrome 61` is the first version to support `import` statements

**Comment by LarsDenBakker** [comment]
How is targeting a browser from september 2017 more standard than targeting the latest versions of the major browsers?

**Comment by SampsonCrowley** [comment]
It's not? it's just a reasonable target for `webcomponents` I highly disagree that **libraries** should always be targeting the **latest** browsers. they should be targeting the base ECMAScript that webcomponents are available on. `webcomponents` aren't only for the latest and greatest standards being used all the time

**Comment by SampsonCrowley** [comment]
we need to decide on a _base_, whether that's a minimum version in each of the Big 4 or simply recommending `esmodules`, then when that _base_ is outdated, update the recommendations

**Comment by LarsDenBakker** [comment]
The responsibility of authors of reusable packages is to publish standard javascript that runs in the browser. This means the code doesn't contain any experimental syntax, proposals etc.

The responsibility of applications authors (or any other way of shipping that code to production) is to ensure it's compatible with whatever browsers they target.

If library authors prematurely target legacy browsers, they are taking away the opportunity for application authors to optimize their applications. For example compiling away async functions significantly increases filesize. It's a problem currently with libraries which all compile to es5.

**Comment by SampsonCrowley** [comment]
> The responsibility of authors of reusable packages is to publish standard javascript that runs in the browser. This means the code doesn't contain any experimental syntax, proposals etc.

which one?

There are browsers now that will run webcomponents without any polyfills whatsoever. They're still going to be out of date eventually. Doesn't mean the reusable components should stop working for them in 6 months. Very few end-users can actually afford to not support every browser easily possible to do so.

The only way to make an actual ecosystem for shareable components is to have a base standard for authors to target.

**Comment by LarsDenBakker** [comment]
You didn't read my second paragraph.

**Comment by SampsonCrowley** [comment]
I did. it doesn't make `standard javascript that runs in the browser` any less ambiguous for what library authors should use as the new standard

**Comment by SampsonCrowley** [comment]
It's seems pretty clear to that the base standard should be `ES2017` right now. so the question is what target best produces a _standard_ ES2017 output

**Comment by SampsonCrowley** [comment]
@LarsDenBakker ok, thinking about it a little more, how about telling library authors to target the last two _major_ versions of the Big 4 at any point for a release. To me at least, it seems like a decent tradeoff of standard support with minimal compilation. Then if consumers need older browser support, they can downgrade to an older version of the library

**Comment by SampsonCrowley** [comment]
```
module.exports = function (api) {
  api.cache(false);

  const presets = [
          [
            "@babel/preset-env",
            {
              targets: {
                browsers: [
                  "last 2 Chrome major versions",
                  "last 2 Edge major versions",
                  "last 2 Firefox major versions",
                  "last 2 Safari major versions",
                ]
              },
              spec: true,
              modules: false,
              loose: false
            }
          ]
        ];

  return {
    presets,
  };
}
```

**Comment by SampsonCrowley** [comment]
gotta remove Edge, it doesn't support Tagged Template Literals

```
module.exports = function (api) {
  api.cache(false);

  const presets = [
          [
            "@babel/preset-env",
            {
              targets: {
                browsers: [
                  "last 2 Chrome major versions",
                  "last 2 Firefox major versions",
                  "last 2 Safari major versions",
                ]
              },
              spec: true,
              modules: false,
              loose: false
            }
          ]
        ];

  return {
    presets,
  };
}

**Comment by LarsDenBakker** [comment]
I think some version of Safari has a bug wth tagged template literal caching, which causes babel to compile.

I think we should start with the rationale behind what we publish, then look at the tools we use for that. If the rationale is that people should publish features which are shipped in the latest versions of the major browsers then we should pick last 1 in babel not last 2.

**Comment by SampsonCrowley** [comment]
> I think we should start with the rationale behind what we publish, then look at the tools we use for that

Completely agree. Personally, I think the Open WC recommendations for publishing reusable components should target the minimum browser capable of natively supporting webcomponents; however, there are definitely arguments to be made about supporting what ever the current **major** version of the big browsers support.

> If the rationale is that people should publish features which are shipped in the latest versions of the major browsers then we should pick last 1 in babel not last 2.

Last 2 was just to give developers consuming the published package a little bit of breathing room. mostly to keep existing tooling setups from breaking too often when the big three adopt standards ahead of the ECMA-262 schedule (since at least 2 of them **have** to implement it before it even becomes a part of the standard)

**Comment by SampsonCrowley** [comment]
@LarsDenBakker I also added Last 2 because I included `shippedProposals` so this way new proposals will not be transpiled _if_ all of the major browsers have supported the feature for at least a full major version

**Comment by SampsonCrowley** [comment]
also anything in `shippedProposals` shouldn't need a plugin for babel to handle it on the end-user side.

the main things I'm trying to target are:

1. application developers don't need any additional babel plugins to import the code
2. the code _can_ work out of the box by directly importing as a script module in _at least_ the newest big 3
  - `<script src="https://unpckg.../my-library/my-component"></script>`
3. application developers don't need to refactor their tooling every time there's a new version of the module

**Comment by LarsDenBakker** [comment]
Yes I think those are good points, we should add that in the documentation. Not sure yet about latest 1 or latest 2... 3 browsers don't implement something without a flag within a short timespan. I'm curious to see what the the feature gap would be between latest 1 and 2 today.

**Comment by SampsonCrowley** [comment]
Maybe the MDN compatibility tables can shed some light there, or browserslist website

**Comment by SampsonCrowley** [comment]
https://caniuse.com/#compare=firefox+68,firefox+69,firefox+70,chrome+77,chrome+78,chrome+79,safari+11,safari+12,safari+13
https://caniuse.com/#search=ES2017
https://caniuse.com/#feat=custom-elementsv1

**Comment by SampsonCrowley** [comment]
@LarsDenBakker it looks like Safari is the only one to really make JS changes in every major version. Chrome and firefox versions are more about security features and reorganization a lot of the time. and have a lot more major versions to compare from.

It looks like both chrome _and_ firefox haven't had a real JS support change since the 3rd newest version

**Comment by SampsonCrowley** [comment]
@LarsDenBakker what if instead of always targeting the current browser versions, the new `createDefaultNPMPackageConfig` I proposed earlier accepted an `targetYear` option that automatically used a open-wc-tailored list of browser targets for that specific ES release year? then as new year releases become available, we add a browserslist target that compiles to that year?

**Comment by SampsonCrowley** [comment]
We could include those pre-crafted browserslists in a table in the docs so users wanting to DIY it still have a recommended target to aim for

**Comment by justinfagnani** [comment]
> Yes I think those are good points, we should add that in the documentation. Not sure yet about latest 1 or latest 2... 3 browsers don't implement something without a flag within a short timespan. I'm curious to see what the the feature gap would be between latest 1 and 2 today.

I think we should consider _why_ we might want a package to support 1 or 2 latest versions out-of-the-box first.

My personal recommendation of ES2017 (for the moment) is derived from the fact it's the most recent commonly-used standard label for a set of language features that is commonly supported. It's mostly about the communication, so that downstream tools configuration is easy, and keeping the recommendation up-to-date is easy.

I think the "latest version" standard is fine for this purpose, and I'm not sure what "2 latest versions" would buy us. Once you start talking about broader browser support, tools come into play and an application can fairly easily target the 2 latest versions if needed.

**Comment by SampsonCrowley** [comment]
@justinfagnani I don't think anyone disagrees that 2017 should be the current target for libraries and reusable components right now, it's just a question of how we should standardize that target. also 2 **major** versions, not 2 latest versions.

Again, the **application** targets are completely irrelevant. they can target whatever they want. what they **can't** do is easily use published library components that don't conform to **some sort** of standard.

If application developers have to start reading into what individual language level every single pre-published component uses, then that's even worse then the fragmented ecosystem that is the browser. We need a **standard** recommendation for library developers to target

**Comment by SampsonCrowley** [comment]
@justinfagnani 

> I think the "latest version" standard is fine for this purpose, and I'm not sure what "2 latest versions" would buy us.

It buys consuming developers a broader range of end-users that support the libraries components out of the box. if people on the internet always had the latest up-to-date browser, we wouldn't even have Babel in the first place.  Library authors building shareable and reusable components should still be recommended to support a minimum level of browser compatibility.  Last 2 **major** versions of the big three guarantees: `ES2017+, a decent sized default user-base for out-of-the-box support, and minimal tradeoffs between transpilation and current language features

**Comment by SampsonCrowley** [comment]
I just want to make sure we're keeping in mind these recommendations should be specifically for building and publishing `webcomponents` with the minimal effort possible for applications to use those packages today, not `how to use the latest ECMAscript in your library`

and as such the recommendations should grow relative to the custom-element API, not specifically with ECMA-262

Because if this organizations' recommendations aren't specifically built around helping people use `webcomponents`, then why make them at all?

**Comment by SampsonCrowley** [comment]
I went through all of the compatibility tables for features introduced in ES2017 and came up with the following minimum browser versions:

Chrome: 76
Firefox: 68
Safari: 12.1

**Comment by daKmoR** [comment]
hey, lot's of good discussion going on here 🤗 

So generally we should recommend to "just" write code that runs natively on around latest Chrome, Firefox and Safari. e.g. this will mean no build step when developing and when publishing
so github sourcecode === npm artifact code

if you write code that does not run in these browsers (example right now would be decorators, optional chaining, ...) then it is up to you to bring the code to a format that is supported... (as you are doing something we do not recommend you will be on your own...)

In all cases as an application, you can decide to support more/older browser by applying a build step.

What we could do is add a page (or even api?) that show which browser version we recommend. The code you write/distribute should run natively in those. 

So it could be by default
```
Chrome: latest
Firefox: latest
Safari: latest
```

but if there is a bug (or for other reasons mentioned by @SampsonCrowley)  we could also say 
```
Chrome: 74
Firefox: latest
Safari: latest
```

sounds good? if so how to best bring this to paper?

**Comment by SampsonCrowley** [comment]
@daKmoR I think that pretty accurately sums things up. I've been using the discussions here to steer the direction of the library I linked above. Once I have a package structure together that makes it easy to distribute, test, and demo (through storybook, etc.) I'll post it here and see what everyone thinks.

Then we can look at whether it's better to just document the recommended best practices, or to add a scaffold geared specifically towards library components

**Comment by SampsonCrowley** [comment]
it might even be as easy as modifying the scaffold to make the main `build` script: ` "build": "rimraf package && babel --out-dir package src"` and adding a default `babel.config.js` to get authors started

where the default `babel.config.js` is something along the lines of (I don't think `latest` is an option in browserslist):
```
module.exports = function (api) {
  api.cache(false);

  const presets = [
          [
            "@babel/preset-env",
            {
              targets: {
                browsers: [
                  "last 1 Chrome major versions",
                  "last 1 Firefox major versions",
                  "last 1 Safari major versions",
                ]
              },
              spec: true,
              modules: false,
              loose: false,
              shippedProposals: true,
            }
          ]
        ],
        plugins = [];

  return {
    presets,
    plugins,
  };
}
```

**Comment by SampsonCrowley** [comment]
@daKmoR @justinfagnani @LarsDenBakker 

https://lit-element.polymer-project.org/guide/publish#transpiling-with-babel

what do you think about not specifying a target at all?

**Comment by SampsonCrowley** [comment]
or since `LitElement` is recommended here anyways, just deferring directly to the LitElement docs on publishing?
