### ISSUE TITLE
component init missing eslint dependency

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#651]
The component init doesn't have eslint as a dependency

**Comment by daKmoR** [comment]
it's a dependency of `@open-wc/eslint-config` so not needed to be an explicit dependency right?

**Comment by LarsDenBakker** [comment]
In my case eslint ended up being installed within `@open-wc/eslint-config` and not at the root. npm does that sometimes, often when you are adding a new package to an existing installed `node_modules` folder. 

I'd say any command you execute should be a direct dependency. Probably a config shouldn't need to depend on eslint directly. What do you think?

**Comment by daKmoR** [comment]
fixed via #710 and https://github.com/open-wc/open-wc/pull/734
