### ISSUE TITLE
[create] allow organization standards when creating a project

### ISSUE THREAD

**Issue by jarrodek** [open-wc/open-wc#652]
First of all I think it is great that someone thought about creating standards for WC and a CLI tool to bootstrap a project applying them by default.

The problem starts when you have to create a project for your organization. Then you probably have different coding standards. This ends up using `npm init @open-wc` and replacing configuration files after that. Obviously an organization should afford to have own tool to do this but I would argue that `@open-wc` is great and is worth using it instead internal tool that will be written once and never maintained. 

I would like to see a configuration option to install different modules for `prettier`, `eslint`, and  commits. Or maybe the tool would detect a globally installed module that has required configuration files that will be applied to generated project and the user selects the template in the CLI UI. I think the later is a better UX for developer than configuration option.

**Comment by LarsDenBakker** [comment]
This would be really useful, how should the public API for this look like?

**Comment by jarrodek** [comment]
If that would be only the CLI configuration options than it would accept a name of a npm package to install instead of predefined ones. So for example instead of default prettier configuration it could be used like this:

```sh
npm inint @open-wc --prettier @other/prettier-config
```
and then it would create the following `prettier.config.js`:
```javascript 
module.exports = require('@other/prettier-config');
```

However, giving that you have to use this command each time when creating a project (which could be done by using aliases) I would try to detect a globally installed packages and suggest an appropriate option in the CLI UI. 
So for example, if you have a package installed globally called `open-wc-create-prettier-other`
it would ask you if you want to use prettier "other" instead of default one. This package would contain the definition for the prettier in the main file. The CLI would add this package to the list of dev dependencies and generate `prettier.config.js` file. Similarly `yo` generator works when creating templates for it.

**Comment by SampsonCrowley** [comment]
This will get really messy really fast. Personally I think it would be better to add docs on how to modify the config or create your own generator based off of this one. there are way too many variables to try to predict end-user custom configs and tooling preferences

**Comment by jarrodek** [comment]
Would be grate to reuse existing generator and extend it in some way. I was thinking about forking it but then maintaining it would be quite painful. Hence I am asking for options :)
