### ISSUE TITLE
[create] proposal for full app generator output

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#666]
Repo: https://github.com/daKmoR/proposal-app-output
Build output: https://sleepy-fermat-110b5d.netlify.com/

Todo:
- [x] Testing files update
- [x] Rename storybook entry points (`index.stories.js` to `page-main.stories.js`)
- [x] Create PR for create

**Comment by LarsDenBakker** [comment]
I think it looks good. We should open an issue to brainstorm about more things to demonstrate in the app scaffolding. It really helps people to have something to get started.

I don't think we should use a monorepo for apps, a monorepo is useful for things that get published separately but that is not the case here.

In the app generator can we separate the choices between a simple demo and the storybook demo?

**Comment by daKmoR** [comment]
this has since been applied 🤗
