### ISSUE TITLE
[rollupConfig] error trying to import a customPolyfill

### ISSUE THREAD

**Issue by Tansito** [open-wc/open-wc#669]
Related with the issue #647 I was trying to add a custom polyfill, for example:
```
indexHTMLPlugin: {
    polyfills: {
      customPolyfills: [
        {
          name: 'requestAnimationFrame',
          test: "'requestAnimationFrame' in window",
          path: path.resolve(__dirname, './requestAnimationFrame.js')
        }
      ]
    }
```
This configuration works partially but the problem is that the original `indexHTML` configuration is overrided due to the next lines:
https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/modern-config.js#L44
and
https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/modern-and-legacy-config.js#L53
Those lines override the `polyfills` object because `customPolyfills` is inside `polyfills`. In my case deleting those lines solves my problem and I can create a PR with those changes but I'm not totally sure if you use them for something or is simply a bug.

**Comment by LarsDenBakker** [comment]
Looks like the order is reversed, it's trying to carefully merge in the user's `polyfills` section and then stomps over it completely again use a regular spread.

It should do the generic spread first, and then apply the polyfills section afterwards:

```js
      indexHTML({
        ...(options.indexHTMLPlugin || {}),
        polyfills: {
          ...((options.indexHTMLPlugin && options.indexHTMLPlugin.polyfills) || {}),
          dynamicImport: true,
          webcomponents: true,
        },
      }),
```

If you're able to create a PR that would be great!

**Comment by LarsDenBakker** [comment]
By the way I feel sorry that you need to polyfill `requestAnimationFrame`, you need to target < IE 9? 😱

**Comment by Tansito** [comment]
Hahaha oh my, no I don't need it. I was just testing how can I add a custom polyfill and that was the first polyfill that I found
