### ISSUE TITLE
[docs] component distribution

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#674]
We should have recommendations on different strategies for distributing components. Right now we basically tell people to publish their source and let apps bundle, but that doesn't cover all use cases. Not everyone targets a fancy PWA, some need to integrate with legacy applications or target multi-page apps or a CMS. I think we can help with those use cases too.

**Comment by SampsonCrowley** [comment]
@LarsDenBakker is this separate from my issue about missing docs for publishing components?

**Comment by SampsonCrowley** [comment]
Sorry, still working on it
