### ISSUE TITLE
[es-dev-server] can't import CJS modules

### ISSUE THREAD

**Issue by SampsonCrowley** [open-wc/open-wc#682]
es-dev-server doesn't allow importing CJS modules

in my component file i have
`import dateFns from 'date-fns'`

this results in:
```
Uncaught SyntaxError: The requested module '../../node_modules/date-fns/index.js' does not provide an export named 'default'
```

**Comment by SampsonCrowley** [comment]
@LarsDenBakker any tips?

**Comment by daKmoR** [comment]
by default es dev server does not do any code transforms - for cjs you would most likely need babel to convert it to es modules...

however, luckily in this case `date-fns` already offers an es module version in `esm/index.js`

so changing your import to
```js
import dateFns from 'date-fns/esm/index.js';
```
should work without any extra steps 👍

**Comment by LarsDenBakker** [comment]
`es-dev-server` is just a static file server, so this is by design. The browser doesn't understand CJS modules.

**Comment by SampsonCrowley** [comment]
@daKmoR ESModules are only in the date-fns@2 which is still in beta and decided to break a lot of libraries by

1. not providing a default export anymore
2. completely changing their date formats, in a way that current formats conflict with directly

Unfortunately Not a version that I want to use any time soon. super disappointing for a package so highly regarded. especially while still in beta

**Comment by SampsonCrowley** [comment]
^ and I mean that about `date-fns` not es-dev-server

**Comment by SampsonCrowley** [comment]
also for v2, you can just `import { individual, functions, because, there's, no, default } from 'date-fns'` you don't need to specify `esm/index.js`

**Comment by SampsonCrowley** [comment]
What the heck is `number` for the `babel` option supposed to mean [here](https://github.com/open-wc/open-wc/tree/master/packages/es-dev-server#code-transformation)? the current major version?

**Comment by LarsDenBakker** [comment]
That should be a boolean.

**Comment by SampsonCrowley** [comment]
that makes more sense

**Comment by kilgarenone** [comment]
Would anyone please advise on how to make `es-dev-server` to work with third-party npm packages specifically [pell](https://www.npmjs.com/package/pell) whose dist file is in `umd` format?

**Comment by LarsDenBakker** [comment]
You can ask the library author to ship a browser compatible module format. This isnt a bug in the dev server.
