### ISSUE TITLE
[es-dev-server] remove advocating http2 option

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#684]
The http2 option requires self-signed certificates. When this is enabled, chrome does not do any caching of fetch requests (which is used by `es-module-shims`) and when requesting a lot of scripts it also does not do this for script requests.

Request 304 caching by far outweighs the http2 request multiplexing, so we should stop advocating the option and including it by default in the generator.

We can keep the option available in case we find a use for it later.

**Comment by SampsonCrowley** [comment]
@LarsDenBakker Why do we want caching at all in development?

**Comment by LarsDenBakker** [comment]
Because there is no reason to send a file over the wire if it hasn't changed. With caching reloads are much faster.

**Comment by SampsonCrowley** [comment]
it's not really over-the-wire in development though; obviously caching is faster than not caching, but of localhost-only it should be pretty negligible.

Either way, where are you seeing files not cache? using self-signed certificates shouldn't have anything to do with caching... I test my companies' servers locally and specifically for cache reliability all the time using nothing but self signed certificates and have never had a problem from the certificates.

**Comment by LarsDenBakker** [comment]
It's not negligible. I mentioned when I'm not seeing caching in the issue above :)

**Comment by SampsonCrowley** [comment]
Are you sure you don't have something else invalidating the cache? Fetch requests aren't special cases for how the browser handles caching

**Comment by SampsonCrowley** [comment]
Unless of course you set the cache key in the fetch options
