### ISSUE TITLE
[es-dev-server] No longer throws when port is in use

### ISSUE THREAD

**Issue by jorenbroekema** [open-wc/open-wc#694]
My port 8080 is always in use on my machine, and es-dev-server would usually throw an error warning about this. Since patch 1.10.1 this no longer happens, and the process just exits without any notice if the default port is already in use.

Reverting to 1.10.0 fixes it for me. 

Additionally would be cool to enhance it where the server doesn't throw, but sends a prompt to the user asking if it's okay to use port `default + 1` (8080 -> 8081) or something like that, similar to how Storybook's cli does it.

**Comment by LarsDenBakker** [comment]
Indeed I ran into the same. Will fix it.

Grabbing another port would be a good feature to add.
