### ISSUE TITLE
[testing-karma] running karma with lerna on default config, results in an error

### ISSUE THREAD

**Issue by askbeka** [open-wc/open-wc#698]
For some reason it does not happen with open-wc config

when I run
```sh
lerna exec karma start -- -c karma.conf.js
```
I get, which is not very helpful
```sh
01 08 2019 12:56:06.661:ERROR [karma-server]: UncaughtException
```

But when run with limited concurrency,  it works
```
lerna exec --concurrency=1 karma start -- -c karma.conf.js
```
I have hunch, that it might be related to ports.
Karma server by default tries to find open ports before starting server
I do not see explicit setting of a port in open-wc config, but not sure why it does not work

**Comment by LarsDenBakker** [comment]
I've seen this error too and I've been trying to debug it. Concurrency is a good lead, I will check into that.

**Comment by askbeka** [comment]
I have checked running 
```sh
lerna exec karma start -- -c karma.conf.js --logLevel=DEBUG
```

I see that resulting configs all have the same port 9876

**Comment by askbeka** [comment]
works with simple karma config.

**Comment by askbeka** [comment]
Narrowed down to esm-middleware.

Tried to define a port myself using `portfinder` on my config side by:
```js
const portFinder = require('portfinder');

module.exports = config => {
  portFinder.getPortPromise()
    .then((port) => {
      config.set(
        merge(createDefaultConfig(config), {
          port,
          files: [
            // ....
```
But I get
```sh
06 08 2019 15:11:40.180:ERROR [karma-server]: Server start failed on port 8000: Error: No provider for "framework:esm"! (Resolving: framework:esm)
06 08 2019 15:11:40.181:ERROR [karma-server]: Server start failed on port 8001: Error: No provider for "framework:esm"! (Resolving: framework:esm)
```

So finding new port works but, something is wrong in setup

**Comment by askbeka** [comment]
So I believe esm-middleware, should use portfinder or something to start the server

**Comment by LarsDenBakker** [comment]
Thanks for the investigation, I'll see if I can do that tonight. 

I didn't look into / consider karma concurrency yet. Did you do anything special to turn on the concurrency mode, or is it always on by default?

**Comment by daKmoR** [comment]
are you sure you wanna use multiple same browsers at the same time? services like browserstack also do not allow this (e.g. you can run chrome and firefox at the same time but not 2x chrome [unless they are different versions])

we actually had exactly this setup before and it does not scale well... it's waaaaayyy faster to have on karma that runs all tests for the full monorepo... (you can still run multiple different browsers at the same time)

imho lerna concurrency is a bad fit for running multiple browser tests at once

**Comment by askbeka** [comment]
Yeah. turned out not to be an issue with karma itself it is able to set free port. issue was in esm-middleware where karm.port + 1 is used.

So when I run
```sh
npx lerna exec -- karma start -c karma.conf.js
```
and I have 3 packages in my monorepo

it creates 3 child processes, but seems like karma is able to allocate ports wihtout conflicts, using `9876 + 1` logic by default, according to official documentation.

But the problem is that [`èsm-middleware also uses `+1``](https://github.com/open-wc/open-wc/blob/master/packages/karma-esm/src/esm-middleware.js#L16),  creating a conflict with spawned karma server.

If I change devServer port to `+100` it works:) this can be quick fix

Or using something like [`portfinder`](https://www.npmjs.com/package/portfinder) should do the trick

**Comment by askbeka** [comment]
@daKmoR Problem is that, I have packages some of which are in typescript:) requiring different setup.

Thats why have started doing this. but I agree. karma already can handle many tests.
I am in process of figuring out the setup, what works best by trying. So this option turned out to be not working because of the technical issues, not the workflow

**Comment by askbeka** [comment]
And with lerna I could run tests optionally, say:
I want to run tests only for packages that have changed since master

```
lerna exec --since master -- karma start
```

**Comment by askbeka** [comment]
so workaround for now is:
```js
const getPortNumber = () => {
  try {
    const configs = glob.sync(path.join(__dirname, './packages/**/karma.conf.js'));
    return configs.indexOf(path.join(process.cwd(), 'karma.conf.js')) * 10 + 8000;
  } catch (error) {
    console.error(error);

    throw new error;
  }
};

module.exports = config => {
  const port = getPortNumber();

  // eslint-disable-next-line no-param-reassign
  config.port = port;
```

**Comment by askbeka** [comment]
also, error handling would help: otherwise it is being swallowed
And I have to run 
```js
process.on('uncaughtException', (err) => {
  console.error(err);
});
```

**Comment by daKmoR** [comment]
I see... it can work but yeah I guess it will need to be `concurrency=1` as karma just can not handle multiple browser sessions to the same browser at once (we had this even before karma-esm was a thing)

overall just spinning up karma + launching browser takes soooo much more time than executing some extra tests so that it will probably not be worth it...

regarding the different setups in each individual package inside a mono repo - that is something I would not recommend as that basically begs the question why use a mono repo at all then?
But yeah if that is your requirement I think that is probably the only reason why executing multiple karma instances at once

**Comment by askbeka** [comment]
@daKmoR Performance is not noticeable, at least for now. headless chrome is up  quite fast.
But yeah performance is going to get slower with package added.

Actually, I am thinking now to have two configurations one for typescript files and another for normal. Should work since pattern will just not match

**Comment by LarsDenBakker** [comment]
If you use the babel plugin for compiling typescript you could run it all in one karma instance.

We should fix this bug anyhow

**Comment by LarsDenBakker** [comment]
Regarding the error handling, karma is notorious for swallowing errors and stack traces :(

**Comment by askbeka** [comment]
Great!
