### ISSUE TITLE
[testing-karma] Import SASS with Karma

### ISSUE THREAD

**Issue by quentin29200** [open-wc/open-wc#701]
Hello,
I use lit-scss-loader to import my SASS files in my component. 
It's work fine with Webpack. 
For testing component, I use @open-wc/testing-karma, but when I run it, the import of scss files is not supported. 

```
SyntaxError: my-component.js: Could not resolve './style.scss'.
import { html, LitElement, customElement, property } from 'lit-element';
> import style from './style.scss';
```
my-component.js and style.scss are in the same folder.

Such as Webpack lit-scss-loader plugin, how configure testing-karma to use import scss ? 

My karma.conf.js

```js
const { createDefaultConfig } = require('@open-wc/testing-karma');
const merge = require('deepmerge');

module.exports = config => {
  config.set(
    merge(createDefaultConfig(config), {
      files: [
        { pattern: config.grep ? config.grep : 'build/components/**/*.test.js', type: 'module' },
      ],
      // see the karma-esm docs for all options
      esm: {
        nodeResolve: true,
      },
    }),
  );
  return config;
};
```

In package.json
```
"@open-wc/testing": "^2.1.2",
"@open-wc/testing-karma": "^3.1.2",
```

**Comment by LarsDenBakker** [comment]
`karma-esm` supports what the browser support, which doesn't know about `scss` or `css` modules. 

It can't use webpack or rollup plugins, but it can use babel. Is there a babel plugin available that does this transformation? See an example of adding a typescript plugin: https://open-wc.org/testing/karma-esm.html#testing-typescript

**Comment by quentin29200** [comment]
Ok, so I tried transform-scss-import-to-string Babel plugin, but it not working fine with Karma preprocessor. 

So I bypass this problem to delete import scss for testing.
I add this script in my package.json : 

`find ./build-testing -name \"*.ts\" -exec sed -i 's/.*.scss.*/const style= css``;/' {} +`

It replaces import style from './style.scss; by const style= css`` and it works fine !
