### ISSUE TITLE
Allow for-of loop

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#703]
Our linter calls for-of loops restricted syntax. This is because of the regenerator transformation babel does, but that doesn't apply to us since we don't ship es5 to modern browsers.

**Comment by daKmoR** [comment]
so you mean it's ok to make it slower for non-modern browsers?
can be a valid choice depending on your/our goal => so jup agree we should focus on evergreen browsers and allow it... 

if people have a primary need to support older browser they should add it to their custom eslint rules 👍

**Comment by LarsDenBakker** [comment]
If you're using async functions (which you should) you already need the regenerator transform.

The suggestion made sense for a long time, but I think we can move past it now.

**Comment by daKmoR** [comment]
ah right... sounds even better than 🤗

**Comment by LarsDenBakker** [comment]
This has been fixed now.
