### ISSUE TITLE
[testing] Shared Behaviors best practices

### ISSUE THREAD

**Issue by noelmace** [open-wc/open-wc#715]
The testing packages use Mocha, which [discourages](https://mochajs.org/#arrow-functions) passing arrow functions.

**When creating [shared behaviors](https://github.com/mochajs/mocha/wiki/Shared-Behaviours
), using the Mocha Context seems mandatory**. Devs need to rewrite all their callbacks using function statements instead of arrows as soon as they want to share some test behaviors between files.

Therefore, **unless we find some other way to write shared behaviors** with ES modules, and share the related recommendations, it may be a good idea to use the function statements everywhere in the example tests.

https://github.com/open-wc/open-wc/blob/master/packages/testing/README.md#example-tests

Here is an example:
:point_right: https://github.com/noelmace/devcards/blob/test/test/open-wc/components/card-stack.test.js

Related external issues & documentations:
https://github.com/meteor/guide/issues/318
https://github.com/mochajs/mocha/issues/1856

If you can confirm that this is an issue, I'm willing to work on this myself

**Comment by LarsDenBakker** [comment]
You're right that a regular function is necessary for some of the mocha functionality. 

Personally I think that using `this` to share state/functionality across tests is generally a bad practice, and no longer necessary with modern javascript. As far as I can tell, all these things except for timeouts can easily be done using functions or storing data in a variable in a test, suite or module.

In your example isn't it much easier to read and understand when you pass the variables to `testRenderCollection` ?

For timeouts there is no replacement, and sometimes I need those as well. In those cases I just use a regular function instead. We can add a notice in the docs about this, though it's easy to spot for a newbie as using `this.timeout` in an es module will throw an error :) 

Interested to see what other people think about this.

**Comment by justinfagnani** [comment]
My 2¢: Given that the closures for suites and tests can add a lot of noise, arrow functions read much, much better.

**Comment by noelmace** [comment]
@justinfagnani how would you write shared behaviors then?

**Comment by justinfagnani** [comment]
Shared behaviors as described in the docs seem like a really bad idea. Why not just export plain functions from modules? The example on the Mocha wiki could be simply rewritten to accept a `user` argument rather than rely on `this`.

**Comment by noelmace** [comment]
Thx @justinfagnani, now I think I understand your point. In order to be clear, I rewrote the example from the Mocha wiki in order to accept a `user` argument like you suggested: https://github.com/noelmace/devcards/tree/a71365558139fafa878f1bd0840a606f07cd88ac/test/vanilla-chai/shared-behaviors/minimal)

It indeed avoids writing too complex shared behaviors.
I suppose this is why you say the example from the docs seems like a really bad idea?

For my part, I also think it makes these tests easier to read! This could go in open-wc documentation as a recommendation in order to avoid most complex shared behaviors.

Yet, it doesn't permit to cover the use case I talked about here: defining shared behaviors (plural, meaning, one function = several tests), following Chai documentation.

If you were thinking about an alternative for this use case too, it would be really nice of you to provide your own example based on the example from Mocha wiki, because I can't see any.

This is a really common use case: Jasmine is covering exactly the same, the same way. To paraphrase the section ["Sharing Behaviors - Caveats"](https://jasmine.github.io/tutorials/sharing_behaviors#caveats) from Jasmine documentation: with great power comes great responsibility ... but it doesn't mean that nobody should have this power :wink:

**Comment by daKmoR** [comment]
puh sharing a behaviour while keeping the `this` context seems rather "complex" and I would see that getting out of hand pretty easily 🙈 

imho you can get the same feature by keeping the functions "pure" and passing the context

taking the mocha example and modifying it

```js
// helpers.js
export function shouldBehaveLikeAUser(user) {
  it('should have .name.first', () => {
    user.name.first.should.equal('tobi');
  })

  it('should have .name.last', () => {
    user.name.last.should.equal('holowaychuk');
  })

  describe('.fullname()', () => {
    it('should return the full name', () => {
      user.fullname().should.equal('tobi holowaychuk');
    })
  })
};

// user.test.js
import { User, Admin } from '../src/user.js';
import { shouldBehaveLikeAUser } from './helpers.js';

describe('User', () => {
  let user;
  beforeEach(() => {
    user = new User('tobi', 'holowaychuk');
  })

  shouldBehaveLikeAUser(user);
})

describe('Admin', () => {
  beforeEach(() => {
    user = new Admin('tobi', 'holowaychuk');
  })

  shouldBehaveLikeAUser(user);

  it('should be an .admin', () => {
    user.admin.should.be.true;
  });
})
```

**Comment by noelmace** [comment]
Thx @daKmoR but like I said previously, even if I would prefer this solution too, it doesn't work, because `shouldBehaveLikeAUser` is called after `beforeEach`, but before the callback of beforeEach. So `user` is undefined in `shouldBehaveLikeAUser`.

In order to be sure, I reproduced the exact same code in my project: https://github.com/noelmace/devcards/commit/0908d058e3b6c121236f26b5a21c63b32ef748ee

Here is the output:

```
npm run vanilla-test -- --verbose=false

> flashcards-app@0.0.0 vanilla-test /home/noel/git/web-on-fire/flashcards-app
> karma start karma.owc.conf.js --coverage --grep 'test/vanilla-chai/**/*.test.js' "--verbose=false"


START:
16 08 2019 13:27:24.357:WARN [filelist]: Pattern "/home/noel/git/web-on-fire/flashcards-app/__snapshots__/**/*.md" does not match any file.
16 08 2019 13:27:24.369:INFO [karma-server]: Karma v4.2.0 server started at http://0.0.0.0:9876/
16 08 2019 13:27:24.370:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
16 08 2019 13:27:24.373:INFO [launcher]: Starting browser ChromeHeadless
16 08 2019 13:27:24.655:INFO [HeadlessChrome 76.0.3809 (Linux 0.0.0)]: Connected on socket fgpyQ4sLKKTU_K_GAAAA with id 41202211
  by daKmoR
    User
      ✖ should have .name.first
HeadlessChrome 76.0.3809 (Linux 0.0.0) by daKmoR User should have .name.first FAILED
        TypeError: Cannot read property 'name' of undefined
            at Context.name (test/vanilla-chai/shared-behaviors/dakmor/helpers.js:3:10)
            at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)
      ✖ should have .name.last
HeadlessChrome 76.0.3809 (Linux 0.0.0) by daKmoR User should have .name.last FAILED
        TypeError: Cannot read property 'name' of undefined
            at Context.name (test/vanilla-chai/shared-behaviors/dakmor/helpers.js:7:10)
            at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)
      .fullname()
        ✖ should return the full name
HeadlessChrome 76.0.3809 (Linux 0.0.0) by daKmoR User .fullname() should return the full name FAILED
        TypeError: Cannot read property 'fullname' of undefined
            at Context.fullname (test/vanilla-chai/shared-behaviors/dakmor/helpers.js:12:12)
            at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)
    Admin
      ✖ should have .name.first
HeadlessChrome 76.0.3809 (Linux 0.0.0) by daKmoR Admin should have .name.first FAILED
        TypeError: Cannot read property 'name' of undefined
            at Context.name (test/vanilla-chai/shared-behaviors/dakmor/helpers.js:3:10)
            at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)
      ✖ should have .name.last
HeadlessChrome 76.0.3809 (Linux 0.0.0) by daKmoR Admin should have .name.last FAILED
        TypeError: Cannot read property 'name' of undefined
            at Context.name (test/vanilla-chai/shared-behaviors/dakmor/helpers.js:7:10)
            at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)
      ✖ should be an .admin
HeadlessChrome 76.0.3809 (Linux 0.0.0) by daKmoR Admin should be an .admin FAILED
        TypeError: Cannot read property 'be' of undefined
            at Context.be (test/vanilla-chai/shared-behaviors/dakmor/user.test.js:23:25)
            at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)
      .fullname()
        ✖ should return the full name
HeadlessChrome 76.0.3809 (Linux 0.0.0) by daKmoR Admin .fullname() should return the full name FAILED
        TypeError: Cannot read property 'fullname' of undefined
            at Context.fullname (test/vanilla-chai/shared-behaviors/dakmor/helpers.js:12:12)
            at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)

Finished in 0.045 secs / 0 secs @ 13:27:26 GMT+0200 (GMT+02:00)

SUMMARY:
✔ 0 tests completed
✖ 7 tests failed

FAILED TESTS:
  by daKmoR
    User
      ✖ should have .name.first
        HeadlessChrome 76.0.3809 (Linux 0.0.0)
      TypeError: Cannot read property 'name' of undefined
          at Context.name (test/vanilla-chai/shared-behaviors/dakmor/helpers.js:3:10)
          at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)

      ✖ should have .name.last
        HeadlessChrome 76.0.3809 (Linux 0.0.0)
      TypeError: Cannot read property 'name' of undefined
          at Context.name (test/vanilla-chai/shared-behaviors/dakmor/helpers.js:7:10)
          at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)

      .fullname()
        ✖ should return the full name
          HeadlessChrome 76.0.3809 (Linux 0.0.0)
        TypeError: Cannot read property 'fullname' of undefined
            at Context.fullname (test/vanilla-chai/shared-behaviors/dakmor/helpers.js:12:12)
            at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)

    Admin
      ✖ should have .name.first
        HeadlessChrome 76.0.3809 (Linux 0.0.0)
      TypeError: Cannot read property 'name' of undefined
          at Context.name (test/vanilla-chai/shared-behaviors/dakmor/helpers.js:3:10)
          at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)

      ✖ should have .name.last
        HeadlessChrome 76.0.3809 (Linux 0.0.0)
      TypeError: Cannot read property 'name' of undefined
          at Context.name (test/vanilla-chai/shared-behaviors/dakmor/helpers.js:7:10)
          at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)

      ✖ should be an .admin
        HeadlessChrome 76.0.3809 (Linux 0.0.0)
      TypeError: Cannot read property 'be' of undefined
          at Context.be (test/vanilla-chai/shared-behaviors/dakmor/user.test.js:23:25)
          at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)

      .fullname()
        ✖ should return the full name
          HeadlessChrome 76.0.3809 (Linux 0.0.0)
        TypeError: Cannot read property 'fullname' of undefined
            at Context.fullname (test/vanilla-chai/shared-behaviors/dakmor/helpers.js:12:12)
            at Test.apply [as run] (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)


=============================== Coverage summary ===============================
Statements   : 4.55% ( 2/44 )
Branches     : 0% ( 0/7 )
Functions    : 0% ( 0/6 )
Lines        : 4.76% ( 2/42 )
================================================================================
16 08 2019 13:27:26.510:ERROR [reporter.coverage-istanbul]: Coverage for statements (4.55%) does not meet global threshold (80%)
16 08 2019 13:27:26.510:ERROR [reporter.coverage-istanbul]: Coverage for lines (4.76%) does not meet global threshold (80%)
16 08 2019 13:27:26.510:ERROR [reporter.coverage-istanbul]: Coverage for branches (0%) does not meet global threshold (80%)
16 08 2019 13:27:26.510:ERROR [reporter.coverage-istanbul]: Coverage for functions (0%) does not meet global threshold (80%)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flashcards-app@0.0.0 vanilla-test: `karma start karma.owc.conf.js --coverage --grep 'test/vanilla-chai/**/*.test.js' "--verbose=false"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flashcards-app@0.0.0 vanilla-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/noel/.npm/_logs/2019-08-16T11_27_26_541Z-debug.log
```

**Comment by daKmoR** [comment]
@noelmace oh if beforeEach is needed you need to do it a little bit different

```js
// helpers.js
import { expect } from "@open-wc/testing";

export function shouldBehaveLikeAUser(generateUser) {
  let user;
  beforeEach(() => {
    user = generateUser();
  });

  it("should have .name.first", () => {
    expect(user.name.first).to.equal("tobi");
  });

  it("should have .name.last", () => {
    expect(user.name.last).to.equal("holowaychuk");
  });

  describe(".fullname()", () => {
    it("should return the full name", () => {
      expect(user.fullname()).to.equal("tobi holowaychuk");
    });
  });
}

// User.test.js
import { expect } from "@open-wc/testing";

import { User, Admin } from "../src/User.js";
import { shouldBehaveLikeAUser } from "./helpers.js";

describe("User", () => {
  shouldBehaveLikeAUser(() => {
    return new User("tobi", "holowaychuk");
  });
});

describe("Admin", () => {
  function generateAdmin() {
    return new Admin("tobi", "holowaychuk");
  }
  shouldBehaveLikeAUser(generateAdmin);

  let user;
  beforeEach(() => {
    user = generateAdmin();
  });

  it("should be an .admin", () => {
    expect(user.admin).to.be.true;
  });
});
```

I actually coded it now and it works 💪 

https://github.com/daKmoR/open-wc-715/blob/master/test/User.test.js

@noelmace would you care writing a blog post about it? maybe even under [open-wc](https://dev.to/open-wc)? or add it to the [FAQs](https://open-wc.org/faq/)?

**Comment by noelmace** [comment]
@daKmoR It would be my pleasure to write this blog post and maybe a PR with a summary for the FAQ. I sent you an email in order to avoid to pollute this issue too much.

I don't know why I supposed it was impossible to add a beforeEach to the shared behavior :man_facepalming:  It's a great solution!

Yet, from my point of view, Shared Behaviors essentially permits to tests the same behaviors in different contexts. In other words different "Given-When" with the same "Then". The need to include all the beforeEach forbid to do that.

I feel like we're trying very hard to find an alternative approach to the most common and well-accepted (but old-fashioned) practice. For some (very few) cases, using the Mocha context stay relevant. But we should avoid to use it as much as possible.

Therefore, it's the same with function statements: arrow function is a good way to show that most your `before`, `beforeEach` & `it` does not support the Mocha "this" context.

Now, It may be necessary to open the same issue in Mocha and Jasmine in order to understand the opposite point of view :stuck_out_tongue:

**Comment by noelmace** [comment]
I created a demonstration project using `@open-wc/testing` [noelmace/mocha-shared-behaviors](https://github.com/noelmace/mocha-shared-behaviors) and wrote a blog post about this.

@daKmoR You can contact me by email or [twitter](https://twitter.com/noel_mace) in order to review the blog post and, if you want, give me the secret key in order to join the open-wc organization on dev.to.

**Comment by daKmoR** [comment]
We still want to add a link to the blog post somewhere?

@noelmace care to make a PR?

**Comment by noelmace** [comment]
Will do next week :+1:

**Comment by thepassle** [comment]
We have a section for blogposts [here](https://open-wc.org/about/blog.html)
