### ISSUE TITLE
[IDE docs] Jetbrains (IntelliJ, Webstorm) syntax highlighting

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#720]
It would be great to have some docs on how to add html/css in template literals syntax highlighting for the Jetbrains IDEs. Does anyone know how to do this?

**Comment by maartenst** [comment]
Is this still an issue? For me it seems to work out of the box in IntelliJ Ultimate 2019.2, see attached screenshot. Or am I not understanding the issue..
<img width="524" alt="Screenshot 2019-10-04 at 19 25 43" src="https://user-images.githubusercontent.com/431224/66227240-1706e700-e6dd-11e9-8f90-be9255861d6f.png">

**Comment by LarsDenBakker** [comment]
It used to not do this out of the box, maybe it changed?

**Comment by jlengrand** [comment]
Seems to work for me too 

<img width="591" alt="Screen Shot 2019-10-10 at 5 45 22 PM" src="https://user-images.githubusercontent.com/921666/66584628-c8969400-eb85-11e9-8b84-ab0dd886685e.png">

**Comment by LarsDenBakker** [comment]
Thanks, ill close this one then!

**Comment by LarsDenBakker** [comment]
I'm reopening this one, we should at least mention on this page: https://open-wc.org/developing/ide.html#visual-studio-code that it works with the JetBrains IDEs

**Comment by jlengrand** [comment]
Bit more than tonight, but here's a MR : https://github.com/open-wc/open-wc/pull/886
