### ISSUE TITLE
[es-dev-server] Enable file compression

### ISSUE THREAD

**Issue by grvsooryen** [open-wc/open-wc#723]
Can you enable file compression to know the actual transferred data in browser and better performance

**Comment by LarsDenBakker** [comment]
This is something we could add, though I'm wondering if it will actually make development faster when seving from local?

**Comment by grvsooryen** [comment]
Development would be fine but **It would improve lighthouse results in regular testing**
![image](https://user-images.githubusercontent.com/16348876/62877070-eb522b00-bd43-11e9-8fc3-be80aa69f03e.png)

**Comment by LarsDenBakker** [comment]
Yeah, that makes sense

**Comment by grvsooryen** [comment]
Also I have noticed that sourcemap and prettify is enabled by default. Are there options to disable it?

**Comment by LarsDenBakker** [comment]
It's just a static file server, so if you're writing pretty code you will see pretty files.

Sourcemaps are created when using any of the code transformation options, like `node-resolve`, `babel`, `compatibility modern/all`. 

If you're testing a production build, I recommend turning these off.

**Comment by justinfagnani** [comment]
Another reason to enable compression, that convinced me with polyseve, is that people are using sample repos to judge "frameworks" and without compression libraries that aren't pre-minified and compressed will appear larger than they are. 🤷‍♂

**Comment by LarsDenBakker** [comment]
@justinfagnani did polyserve do compression by default? Or was it a flag?

**Comment by LarsDenBakker** [comment]
I still want to add this

**Comment by LarsDenBakker** [comment]
Not stale

**Comment by LarsDenBakker** [comment]
Not stale

**Comment by bennypowers** [comment]
working on an implementation
