### ISSUE TITLE
[es-dev-server][feature-request] provide app-index programmatically

### ISSUE THREAD

**Issue by askbeka** [open-wc/open-wc#725]
Provide html template programmatically,

For development of applications that are consumed in runtime, and are not consumed as html but as es modules.

I want to provide a html in a config similar to [webpackIndexHtml.template](https://open-wc.org/building/webpack-index-html-plugin.html#non-index-html-entrypoints), for development purposes only.

But production version will no contain any html similar to https://github.com/open-wc/open-wc/issues/724

**Comment by LarsDenBakker** [comment]
You can already provide the config programmatically, right? What would you want to be different?

**Comment by askbeka** [comment]
@LarsDenBakker in build configurations but not in es-dev-server

**Comment by askbeka** [comment]
@LarsDenBakker we can [provide config](https://open-wc.org/developing/es-dev-server.html#configuration-files), file but there we should indicate the path to `index.html`

So that, I could do this:
```js
module.exports = {
  port: 8080,
  watch: true,
  nodeResolve: true,
  appIndex: () => `<html><head><body></body></head></html>`,
  moduleDirs: ['node_modules', 'custom-modules']
}
```

**Comment by LarsDenBakker** [comment]
Ah I see. You could do this right now with a middleware. I think this should work:

```js
module.exports = {
  middlewares: [
    function serveIndexMiddleware(ctx, next) {
      if (ctx.url === '/') {
        ctx.body = '<html><head><body></body></head></html>'
      }
       
      return next();
    }
  ]
}
```

not sure if this is something we want/should support in the dev server.

**Comment by LarsDenBakker** [comment]
Actually, I think it would be interesting to build support for `virtual files` where you can define fake files and their contents:

```js
module.exports = {
  virtualFiles: {
    '/index.html': '<html> .. </html>',
    '/node_modules/foo/foo.js': ' ... ',
  }
}
```

I have some use cases like this myself when I need to temporarily patch some file.

**Comment by askbeka** [comment]
Cool. I can make use of this too.

**Comment by LarsDenBakker** [comment]
Not stale

**Comment by LarsDenBakker** [comment]
We added `responseTransformer` to `es-dev-server`, which allows for serving virtual files.
