### ISSUE TITLE
[semantic-dom-diff] expect.dom.to.not.equal is not possible

### ISSUE THREAD

**Issue by SampsonCrowley** [open-wc/open-wc#731]
whether `not` is chained or not, the test **always** checks the dom **is** equal.  this is true for `dom`, `lightDom`, and `shadowDom`

**Comment by bennypowers** [comment]
Oh stale, never change.

**Comment by rodrigo-garcia-leon** [comment]
Hey, is this issue still relevant? and if so can I work on it? 🧐

**Comment by LarsDenBakker** [comment]
Yeo go ahead

**Comment by rodrigo-garcia-leon** [comment]
Coolio 😎
