### ISSUE TITLE
rollup-plugin-lit-css do not work in IE

### ISSUE THREAD

**Issue by lamianbu** [open-wc/open-wc#732]
follow this page 
https://open-wc.org/building/building-rollup.html#import-css-files-in-lit-html

rollup-plugin-lit-css/rollup-plugin-lit-html-style/rollup-plugin-postcss-lit/rollup-plugin-inline-lit-element

Chrome is OK,but IE throw the same error:

because output legacy/index.js file:
var myStyles = css`#root {
    text-align: left;
    color: var(--theme-primary);
}`;;

other not use rollup-plugin-lit-css ,output:
css(_templateObject$8());

**Comment by LarsDenBakker** [comment]
I'm not sure if this is anything to do with `open-wc`. Probably best to open an issue at the plugin.

**Comment by lamianbu** [comment]
I have resovle it，use rollup-plugin-postcss-lit

please close it
