### ISSUE TITLE
[es-dev-server] Node module resolution should be enabled by default

### ISSUE THREAD

**Issue by justinfagnani** [open-wc/open-wc#737]
This makes the out-of-box experience just a bit nicer, since you always need this for LitElement and most other npm libraries with dependencies.

The one downside is that this means a particular Node resolution mode has to be the default, and the only workable default right now is "classic" or "require-style" resolution. Once "module-style" resolution lands and enough modules start using it the default could change to that in a breaking change.

**Comment by LarsDenBakker** [comment]
I can see how its more convenient, but then we do have to teach people not to use it when testing performance.

It depends on how long we think until (and if) import maps become mainstream enough.
