### ISSUE TITLE
[testing-karma-bs] Improve BrowserStack recommendations

### ISSUE THREAD

**Issue by bashmish** [open-wc/open-wc#740]
Looks like `testing-karma-bs` is outdated (latest Firefox version points at version 64) and does not follow best practices (no `index.js` of the package). Also I don't see why it contains open-wc specific name in `browserStack.project` config options.

Besides that, I think there is a better way to choose browsers and environments for testing based on the `browserslist` standard - https://github.com/xeroxinteractive/browserslist-browserstack. I'm working now on my own project and want to explore this possibility there and later on maybe contribute a generic config with it here. As always would be nice to first see your opinion about the idea  👀

**Comment by LarsDenBakker** [comment]
Seems like a good approach to me. What do you think @daKmoR ?

**Comment by bashmish** [comment]
I created [karma-browserstack-browserslist-launchers](https://www.npmjs.com/package/karma-browserstack-browserslist-launchers) 💪 It glues together 3 things:

- https://www.npmjs.com/package/browserslist
- https://www.npmjs.com/package/@xerox/browserslist-browserstack
- https://www.npmjs.com/package/karma-browserstack-launcher

Besides some flakiness of the BrowserStack itself sometimes, it works super smoothly and really removes the burden of thinking about which versions of browsers to run tests against 🥳 

I had some issues with `es-dev-server` and IE11 in `.browserslistrc`. Although it is not caused by my changes, it is important to be fixed to be able to put IE11 in `.browserslistrc`. I will create a separate bug report.

Please test it out and share your feedback 🤗 

PS: I discussed a couple of times with @daKmoR that some things should not be part of open-wc because they are way more generic and not WC specific, and this new `karma-browserstack-browserslist-launchers` is one of them, so I would prefer to keep it separately from open-wc. But I can and want to improve the config, scaffoldings tools and docs to include it with specific recommendations for WC.

**Comment by daKmoR** [comment]
that looks very promising 🤗 

I'm just wondering how we will make it possible to have different browsers for testing and building... (we are using .browserslistrc for es-dev-server/testing/building-webpack/building-rollup)

e.g. I assume it should be possible to say that I test in `latest Chrome/Firefox` and I want to build for `latest 2 versions of chrome/firefox/safari and IE11`... should I use 2 `.browserslistrc` files then?

what would be our best practice? (e.g. it needs to be posible but it is more a documentation need - I would say generally you will want to test in what your support and also build I guess)

**Comment by bashmish** [comment]
> what would be our best practice? (e.g. it needs to be posible but it is more a documentation need - I would say generally you will want to test in what your support and also build I guess)

I believe the `.browserslistrc` is for what you support. That implies the need to test for those browsers and to build for them, so there should no difference.

In reality there are some exceptions always. For this I have [an option to filter certain browsers if needed](https://github.com/bashmish/karma-browserstack-browserslist-launchers#processing-of-capabilities). I was also thinking about providing another option in the config with different browserslist queries specifically for testing, but not sure if this is really a good idea.
