### ISSUE TITLE
[semantic-dom-diff] expect(el).dom.to.equal() types

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#745]
When working with typescript you may notice that the types are not correct for
```js
expect(el).dom.to.equal('<div>Hey</div>', {
  ignoreTags: ['my-custom-element']
});
```

e.g. the 2nd parameter is expected to be a string. Unfortunately, we currently can not change this.
For now you will need to ignore types if you want to provide extra options.
```js
// @ts-ignore
expect(el).dom.to.equal('<div>Hey</div>', {
  ignoreTags: ['my-custom-element']
});
```

We probably want to introduce a new syntax in a breaking release?
```js
expect(el).domToEqual('<div>Hey</div>', {
  ignoreTags: ['my-custom-element']
});
```

**Comment by bennypowers** [comment]
Generally, chai-dom-equals should ship with .d.ts

**Comment by bennypowers** [comment]
Is this still relevant @daKmoR
