### ISSUE TITLE
[webpack-index-html-plugin] Cannot read property 'resolve' of null ( on seccond build with watcher)

### ISSUE THREAD

**Issue by sanguino** [open-wc/open-wc#747]
Hi, 

I'm new with webpack and open-wc, so please correct me if this is not an issue and I have made a mistake in my config.

When working with `webpack --watch`, the second time the build is done, the `webpack-index-html-plugin` fails:

```bash
｢wdm｣: TypeError: Cannot read property 'resolve' of null
    at compiler.hooks.emit.tapPromise (***/node_modules/@open-wc/webpack-index-html-plugin/webpack-index-html-plugin.js:116:37)
```
I think the problem is that in [line 136](https://github.com/open-wc/open-wc/blob/8d26f71ffe68f9cba58e8d8eb6a095819525969f/packages/webpack-index-html-plugin/webpack-index-html-plugin.js#L136) the `deferredLegacyBuildResult` is set to null. It is created on the constructor, so it will not be created again on the next build.

A possible solution could be to move the creation of the deferredObject to a `watchRun` hook:

``` js
    compiler.hooks.watchRun.tap(PLUGIN_NAME, () => {
      if (this._config.multiBuild && this._config.legacy) {
        deferredLegacyBuildResult = createDeferredPromise();
      }
      this.emitted = false;
    });
```
Also I reset `this.emitted` to emit the `tapPromise` hook on each run too.

I could create a pull request if you think this is a good solution.

**Comment by LarsDenBakker** [comment]
We don't use webpack during development, so we didn't cover these use cases. It sounds like you're in the right track here, if you create a PR we can look at it.

**Comment by sanguino** [comment]
I did all mentioned below and added a reset to `entries` and `entryNamesForVariations` and added test for each case using watcher.

**Comment by sanguino** [comment]
Resolved: https://github.com/open-wc/open-wc/pull/770
