### ISSUE TITLE
[building] rollup-plugin-node-resolve dedupe option

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#748]
We should document the new dedupe option from `rollup-plugin-node-resolve`, and set up some defaults.

**Comment by bennypowers** [comment]
not stale

**Comment by bennypowers** [comment]
I can grab this. Assuming we want to default to deduping `lit-html`?

**Comment by LarsDenBakker** [comment]
This was implemented.

**Comment by JosefJezek** [comment]
@LarsDenBakker where it is implemented?
