### ISSUE TITLE
[es-dev-server] dedupe / singleton packages

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#749]
[rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve) offers a dedupe option. it would be good to offer this in `es-dev-server` too for an end-to-end solution.

**Comment by bennypowers** [comment]
not stale

**Comment by bennypowers** [comment]
still not stale

**Comment by LarsDenBakker** [comment]
Still not stale :) I'd like to do this along with a setting for es-dev-server.

**Comment by bennypowers** [comment]
Seems like we'd need to write our own logic for this?

Maybe we should upstream it to https://github.com/nodecg/express-transform-bare-module-specifiers ?

**Comment by LarsDenBakker** [comment]
We cant because they are using babel for this. We use our own implementation for performance.

**Comment by LarsDenBakker** [comment]
This was implemented.
