### ISSUE TITLE
[testing] register chai plugins type error

### ISSUE THREAD

**Issue by acuevas91** [open-wc/open-wc#750]
Hi!

Since the last minor version `2.3.0`, where there is an update of using chai plugins, it throws an error  whenever you try to execute the tests with `npm run test` command.

This is the error I mention:

`
TypeError: Cannot read property 'use' of undefined
    at Module../node_modules/@open-wc/testing/register-chai-plugins.js (http://localhost:9876/absoluteC:/Users/AppData/Local/Temp/_karma_webpack_/commons.js?75a6c001bc3dabe4571a9762f775846886fba511:27698:13)
    at __webpack_require__ (http://localhost:9876/absoluteC:/Users/AppData/Local/Temp/_karma_webpack_/runtime.js?c38d51cd4af62e9eacd04bb5dfbfbac27880397b:85:30)
    at Module../node_modules/@open-wc/testing/index.js
`

I do not know if there is any config missing I have to include due to this update, but it is failing when it tries to use those plugins as `window.chai` seems not to be registered well.

This is the line I mention in `register-chai-plugins.js` file: `window.chai.use(chaiDomDiff);`

Thanks in advance!!

**Comment by daKmoR** [comment]
are you maybe using karma and karma-webpack directly?

can you make a reproduction? using it in our recommended default way with es-dev-server works fine... so I am not sure what goes wrong...

**Comment by daKmoR** [comment]
ah reading it again I can see `karma-webpack` in the error message...

@bennypowers you have a similar setup right? how did you solve it now?

**Comment by daKmoR** [comment]
if you are using `karma-webpack` you can try to add `chai/chai.js` to your files in the `karma.conf.js`

```
files: [
  { pattern: require.resolve('chai/chai.js' }, 
  // other files
]
```

if that solves your problem would you be willing to add this information to our documentation via a PR? 🤗

**Comment by bennypowers** [comment]
I had a similar problem and solved it by adding this to karma's `files` config array

```js
{ pattern: require.resolve('chai/chai.js'), watched: false },
```

and by removing any instances in my test files where I `import { chai } from '@open-wc/testing'`, then by referencing `chai` on `window`

```js
window.chai.use(sinonChai);
```

**Comment by acuevas91** [comment]
Many many thanks! It was solved with that!

> if you are using `karma-webpack` you can try to add `chai/chai.js` to your files in the `karma.conf.js`
> 
> ```
> files: [
>   { pattern: require.resolve('chai/chai.js' }, 
>   // other files
> ]
> ```
> 
> if that solves your problem would you be willing to add this information to our documentation via a PR?

Sure, I will create a PR updating the doc with it :)

**Comment by jarrodek** [comment]
I run into similar problem. I have own plugin to run tests on SauceLabs. After recent update I have to add both `chai` and `axe-core` to the fist of files. Naturally I can do this in my base configuration but this generally means that something wrong is with the testing library that ignores this files in the first place.

**Comment by LarsDenBakker** [comment]
Something is wrong with webpack in this case :/
