### ISSUE TITLE
[semantic-dom-diff] class attributes changes give unexpected results

### ISSUE THREAD

**Issue by tmsns** [open-wc/open-wc#756]
Some unexpected test results are popping up when using `semantic-dom-diff` and the class attribute:

## Case 1:
Direct usage of the plugin and different class attributes doesn't fail the test.
```bash
$ npm init @open-wc
# select web component -> testing => name: foo-bar
$ cd foo-bar
# update test/foo-bar.test.js:22 to `<button class="foo bar">increment</button>`
# update src/FooBar.js:33 to `<button class="bar foo bar">increment</button>`
$ npm t
```
Expected to fail as the attributes are different, but doesn't. Although both attribute classes will instruct the css to do the same (afaik), the attribute values are different. These values might be checked by other parts of the code.

## Case 2:
Snapshot usage show too many errors. 
```bash
$ npm init @open-wc
# select web component -> testing => name: foo-bar
$ cd foo-bar
# replace test/foo-bar.test.js:20-23 by `expect(el).shadowDom.to.equalSnapshot();`
# update src/FooBar.js:33 to `<button class="bar foo bar">increment</button>`
$ npm t
# snapshot created, and passes tests
# add some attribute for h2 on src/FooBar.js:32 =>`..<h2 test>..`
$ npm t
```
Three issues are shown instead of one, but with some extra weirdness
![image](https://user-images.githubusercontent.com/17364880/63426518-4c988f00-c413-11e9-9fe3-cfe9c1ec4e9b.png)
- the original classname is not shown `bar foo bar`, only `bar foo`.
- the snapshot shows `foo bar` as classname, and marks it as an error, although it wasn't an error before
- for some reason, the `</button>` tag also wants to show an error 🙈

**Comment by LarsDenBakker** [comment]
Regarding case 1: this is because we use the element's `classList` where the class names are already de-duplicated by the browser. (maybe it should be a `classSet` :)). We could change this, but since this is *semantic* diffing this might be fine too. 

Regarding case 2: I'm not sure what's going wrong here, what we is iterate all the elements of the rendered dom, and create a string. Then we just do a chai string equals so we get nice line-by-line diffing.

**Comment by tmsns** [comment]
Case 1: Yeap, depending how you look at it, it should be fine. If you consider just how css applies the classes to an element, it is ok. If you have code (css attribute selectors, or javascript checking the `class` attribute or `className` property), you might run into trouble.
TBH I only stumbled on case 1 when investigating case 2. But I can imagine people could get confused by the behavior. Maybe some options, or documentation on it would be enough? Or maybe the test could warn people?

Case 2: yeah it's a strange one. It does seem that the snapshot html does not go through the same cleaning than the original element.
