### ISSUE TITLE
[es-dev-server] regular scripts are not compiled

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#758]
We only compile modules with babel, if you have regular scripts they are not handled. This is currently by design, but it can break some use cases.

**Comment by LarsDenBakker** [comment]
I'm working on this in a larger refactoring of compatibility mode.

**Comment by e111077** [comment]
+1 on this btw. Loving `es-dev-server` so far with our mwc elements and we're using it with our glitch demo, but this is the only issue we're running into as demos tend to have inline scrips where we instinctively use es6

**Comment by LarsDenBakker** [comment]
@e111077 what would you expect here in terms of behavior of polyfills and babel helpers. We load module scripts after the polyfills, and can inject babel helper imports. We could delay scripts until after polyfills, but people might rely on scripts to run at a specific time in the HTML.

**Comment by e111077** [comment]
I'm sorry I'm not too familiar with the polyfill and babel injection order. Is it currently:

1. non-module scripts
2. polyfills and helpers
3. module scripts

and you're suggesting

1. polyfills and helpers
2. non-module scripts
3. modules scripts

If so, I think your suggestion would be what I would expect. If someone needs specific handling of script timing, I would provide a way for the user to disable non-transform-related polyfill injection and do

1. babel / transform helpers
2. user's non-module scripts (they must provide wc polyfills etc.)
3. module scripts

I think providing the polyfills and libraries are helpful, but sometimes a low-level escape hatch is needed. That was a common problem we ran into when we created Webcomponent Tester which provided every library you would need like sinon and lodash by default. It was useful in most situations, but made it a hassle for intricate cases.

**Comment by LarsDenBakker** [comment]
@e111077 should work now with the latest es-dev-server

**Comment by e111077** [comment]
Ace job! thanks!
