### ISSUE TITLE
[es-dev-server] Failed to resolve module specifier "lit-html"

### ISSUE THREAD

**Issue by jarrodek** [open-wc/open-wc#763]
After last update fresh bootstrap of a web component using `npm init @open-wc` the following errors are thrown after running `npm start`

```
Uncaught TypeError: Failed to resolve module specifier "lit-html". Relative references must start with either "/", "./", or "../".
Could not resolve module imports in /demo/inline-module-0.js?source=%2Fdemo%2Findex.html: Unable to parse the module, this can be due to experimental syntax or a bug in the parser.
```

Not sure what is happening but it definitely worked yesterday.

**Comment by jarrodek** [comment]
The workaround is to run `npm run start:compatibility`

**Comment by LarsDenBakker** [comment]
Thanks a lot of reporting this! Apparently `es-module-lexer` 0.3.7 just got released which breaks a lot of things. Pinning the version to 0.3.6 makes things work again!

**Comment by LarsDenBakker** [comment]
It works again now with es-dev-server 1.15.1

**Comment by jarrodek** [comment]
sweet! I could deal with demo page but I got worries when tests couldn't start as well.
Now it all works again <3
