### ISSUE TITLE
[es-dev-server] imports with a . are not resolved

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#771]
As a performance optimization we don't resolve imports to files with a `.`. However this is not correct in all cases, some files may contain a `.` and the user might not including the actual file extension. We may need to let go of this optimization.

**Comment by daKmoR** [comment]
you mean something like
```js
import { foo } form './utils/foo.baz';
// vs?
import { foo } form './utils/foo.baz.js';
```
?

**Comment by LarsDenBakker** [comment]
Yeah, I actually ran into a case like this:

```js
import { foo } form './axe/axe.min';
// vs?
import { foo } form './axe/axe.min.js';
```

Adding a file extension will become required with import maps, but we can't assume every library to already use it. 

It's a shame, because it was a really nice performance optimization :)

**Comment by bashmish** [comment]
@LarsDenBakker if I understood correctly, maybe keep the optimisation for `.js` which will cover 99% of cases?

**Comment by LarsDenBakker** [comment]
That's a good suggestion

**Comment by LarsDenBakker** [comment]
Actually, we already have an array of file extensions we want to resolve to (default .mjs and .js). We can just use that array.
