### ISSUE TITLE
Tests flaky on Edge

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#781]
Our tests are flaky on Edge because of es-module-shims doesn't guarantee execution order of modules with side effects on Edge. Because we started exporting chai from a global, we are relying on a side effect.

Let's wait for https://github.com/guybedford/es-module-shims/pull/55 to see if we need to solve this on our end somehow.

**Comment by tpluscode** [comment]
@LarsDenBakker can I somehow help get this shipped?

**Comment by LarsDenBakker** [comment]
You can update the version of es module shims in the building-utils package. I started working on it, but the CI was failing I didnt check into why. A bit short on time this week, sorry!
