### ISSUE TITLE
[semantic-dom-diff] whitespace treated as semantic for some values of `class`

### ISSUE THREAD

**Issue by bennypowers** [open-wc/open-wc#782]
Today I received the following test failure:

```
+ expected - actual

-<button
-
-  id="button"
->
+<button id="button">
   <fc-icon
     id="icon"
     size="18"
   >
```

This indicates to me that something is off in the package's handling of whitespace.

the template in question is 
```js
return html`
  <button id="button"
      class="${classMap({ active })}"
      aria-label="${ifDefined(label)}"
      ?disabled="${disabled}"
      ?active="${active}">
    <fc-icon id="icon"
        icon="${ifDefined(icon)}"
        size="${ifDefined(iconSize)}"
    ></fc-icon>
  </button>
`;
```

This appears to be to do with the `class="${classMap({ active })}"` attribute, as removing it removes the errors.

Similarly, setting `class` to `class="${ifDefined(active ? classMap({ active }) : undefined)}"` also negates the issue.

**Comment by LarsDenBakker** [comment]
I'm not sure if the issue with whitespace, we always create our own HTML string representation.

You can check what you're sending to the differ by logging innerHTML or outerHTML whatever you're putting into the chai expect and then compare that with the markdown file on disk.

**Comment by bennypowers** [comment]
@LarsDenBakker Thanks for getting back to me on this.

Here's what I receive when I log the input HTML string alongside the expected HTML string, before asserting with `expect(element).shadowDom.to.equal(html)`


```html
LOG: 'EXPECTED HTML', '
<button id="button">
  <div class="layout-align-space-between-center layout-row">
    <div
      class="layout-align-center-center layout-row mrg-item"
      style="width: 100%"
    >
      <span class="capitalize mrg-item">
        <slot>
        </slot>
      </span>
    </div>
  </div>
</button>
'
LOG: 'INPUT HTML', '<!---->
      <button id="button" class="">
        <div class="layout-row layout-align-space-between-center">

          <!-- loading -->


          <!-- Icon -->


          <!-- Label -->
          <div class="layout-row layout-align-center-center mrg-item" style="width: 100%">
            <span class="mrg-item capitalize">
              <slot></slot>
            </span>
          </div>

          <!-- Right Icon -->

        </div>
      </button>
    <!---->'
```

So it appears that comparing an empty `class=""` input with a non-existent class attr in the expected HTML string causes this problem.

Investigating further with some logs in `getAttributeString`, I noticed this:

```
LOG: 'start', '', [class="", id="button"]
LOG: 'after itteration i=0', '
 '
LOG: 'after itteration i=1', '

  id="button"'
```
So it looks like when an attr covered by `shouldStripAttr` is empty, it's not passing the `isIgnoredAttribute` predicate as expected. PR incoming
