### ISSUE TITLE
building-rollup.html#supporting-legacy-browsers IE11 index.html throw error

### ISSUE THREAD

**Issue by lamianbu** [open-wc/open-wc#783]
follow the website
https://open-wc.org/building/building-rollup.html#supporting-legacy-browsers

dist/index.html include arrow express, throw error in IE11

`<script>window.importShim=i=>import(i);</script>`

@open-wc\building-rollup "version": "0.9.27"

**Comment by LarsDenBakker** [comment]
This script is to feature detect dynamic import support. The error is harmless, is it causing any problems for you?

**Comment by lamianbu** [comment]
It is causing no problem

In a complex project, CSS style is not show in IE , but I can't find reason

**Comment by JosefJezek** [comment]
@LarsDenBakker arrow function is not supported on IE11, this error is stopping JS parser...

**Comment by LarsDenBakker** [comment]
Its a one line script for feature detection, thats the intended behavior.
