### ISSUE TITLE
[question][building] bundling non-esm depndencies

### ISSUE THREAD

**Issue by jarrodek** [open-wc/open-wc#784]
I have a project that uses non-esm dependencies which should be included into the web app before the components. I naturally can do something like this:

```html
<script src="./node_modules/dependency.js"></script>
```
This script will be unchanged in the final output. However dependencies declared this way are unprocessed (which is documented). 
I am wondering how to create a bundle of such dependencies (there are few of them) with my application build? So for I got to using `cpy` to just copy the files. However I would like to bundle and minify them to a single file. I never used rollup and configuration is overwhelming so I am asking question here hoping someone did this already.

**Comment by LarsDenBakker** [comment]
You can configure rollup to handle none-esm dependencies, for example with the commonjs plugin

**Comment by jarrodek** [comment]
I will try to use it. thanks

**Comment by jarrodek** [comment]
I ended up building own plugin to handle this as my use case was quite unusual.
Also, for bundling this particular dependencies I just added another configuration which did what I wanted.
