### ISSUE TITLE
[es-dev-server] add HMR

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#787]
Since we're serving unbundled code, replacing modules at runtime on the fly can be implemented pretty easily.

There is a lot of complexity around this, so I'd like to evaluate first whether this adds any value before promoting it in any way. But I suspect we can create a pretty good user experience around editing CSS and HTML.

**Comment by LarsDenBakker** [comment]
Related: https://github.com/systemjs/systemjs/pull/2014 and https://github.com/Polymer/lit-element/issues/673

**Comment by bennypowers** [comment]
should check this out with https://www.npmjs.com/package/custom-elements-hmr-polyfill

**Comment by LarsDenBakker** [comment]
Going to close this one, this isn't a goal in the short or mid term.

**Comment by justinfagnani** [comment]
@LarsDenBakker FYI, I would love to help design and build this into es-dev-server in a way that doesn't require compiling modules away. I have several ideas here, and it would help with @rictic's goal of landing our LitElement HMR support.

**Comment by LarsDenBakker** [comment]
It would be great if we can figure out something that doesn't require compiling modules away. I thought about some different solutions, but it all gets rather complicated. Interested to hear your ideas.

**Comment by Tiberriver256** [comment]
Possibly useful:
https://gist.github.com/treshugart/3b8ee09c16efcbb43453f3f78e59d575

**Comment by FredKSchott** [comment]
Relevant: https://github.com/pikapkg/esm-hmr

It should be relatively plug-and-play for something like es-dev-server to integrate, and open to any feedback if you have time to collaborate / work on it with us

**Comment by rictic** [comment]
@Tiberriver256 I've been working on a roughly similar design, but with the ability for individual webcomponent classes and base classes to define a callback that opts them into handling the details of hot reloading: https://github.com/Polymer/lit-element/pull/802

I've spent a little time with snowpack and esm-hmr today, and I like the design much better than any other HMR system I've seen. For one thing, the code that you write works outside of a bundler (no reliance on an implicit `module` object).

**Comment by LarsDenBakker** [comment]
@rictic what are the plans for publishing this somewhere? 

@FredKSchott I saw it, and it looks relatively straightforward. 

Initially my thoughts for HMR were to create a general reloading system that didn't require any extra work on the side of the user. This isn't possible with ESM since you can't really look into the module loader, so I started working on it in system js (https://github.com/systemjs/systemjs/pull/2014) but then I got sidetracked with other things :)

From what I can tell what we can do for reloads in ESM is either let users write reload code manually and have them export let and var, or inject some code when we know they're using a certain rendering framework or library.

I think the latter is the most interesting case, but how do we handle cases where your template is composed out of imports from other modules. That would still require effort on the user's side to make it reload properly?

**Comment by FredKSchott** [comment]
i don't have a LitElement specific answer for you, but ESM-HMR is specifically designed to support this usecase in a purely ESM world (No System.js needed).

In the example above that would be:

```js
import { css, html, LitElement } from 'lit-element';
import { fooStyles } from './foo.styles.js';

class MyElement {
  static styles = [fooStyles];
  render() {
    return html`
      <div>Foo</div>
   `;
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(['./foo.styles.js'], ({module, deps}) => {
    const [newFooStylesModule] = deps;
    MyElement.styles = newFooStylesModule.fooStyles;
  });
}
```

**Comment by LarsDenBakker** [comment]
Is that something we expect users to write manually, or would it be injected using analysis? With analysis I'm not sure we could handle all types of dependencies.

es-dev-server is not lit-element specific, so we would need to have a general solution as well as specific plugins for certain frameworks or libraries. So I'm curious how this is handled for other libraries, also how this handled for non-view related code.

**Comment by FredKSchott** [comment]
HMR is just the lower-level tool exposed by the server. frameworks can hook into this to power something like Preact’s Prefresh it React Fast Refresh. Or, you as the app creator can write a 1-2 accept handlers yourself to handle a basic HMR usecase.

The nice thing about ESM-HMR is that you wouldn’t have to implement all this yourself, and then those framework authors wouldn’t need to build a whole new integration just for es-dev-server’s custom HMR interface.

**Comment by rictic** [comment]
> @rictic what are the plans for publishing this somewhere?
@LarsDenBakker 

I'm working to get something released now, starting at https://github.com/PolymerLabs/hot-elements/pull/1, and will follow up with a LitElement integration.

**Comment by daKmoR** [comment]
@rictic any update on HMR for Lit Element? 🤔

@justinfagnani potentially supported by default in lit-element 3? 🙏

**Comment by FredKSchott** [comment]
Yes! Still interested for Snowpack as well :)

**Comment by LarsDenBakker** [comment]
Since es-dev-server is replaced by web-dev-server, we're tracking this in https://github.com/modernweb-dev/web/issues/501 with an implementation started at https://github.com/modernweb-dev/web/pull/685
