### ISSUE TITLE
[building-rollup] missing hash in file name of js module in index.html

### ISSUE THREAD

**Issue by JosefJezek** [open-wc/open-wc#793]
The index.html doesn't contain file names with hash of js modules after rollup build.
I tried `createDefaultConfig` and `createCompatibilityConfig`.

`index.html`
```
<script type="module" src="./src/index.js" crossorigin></script>
<script type="module" src="./src/components/app-shell.js" crossorigin></script>
```
`index.html` after the build
```
<link rel="preload" href="index.js" as="script" crossorigin="anonymous">
<link rel="preload" href="app-shell.js" as="script" crossorigin="anonymous">

HTMLScriptElement.prototype?["./index.js","./app-shell.js"]
window.importShim(e)})):["./legacy/index.js","./legacy/app-shell.js"]
```

**Comment by JosefJezek** [comment]
@LarsDenBakker We need the hash in file names for revalidate http cache on the client. Could you fix this issue?

**Comment by JosefJezek** [comment]
@LarsDenBakker Do you know any solution?

**Comment by LarsDenBakker** [comment]
Rollup has an option for this, we need to add it. PRs welcome for this one.

**Comment by Aebrathia** [comment]
This issue has been solved in #838.

**Comment by daKmoR** [comment]
thx 🤗

**Comment by JosefJezek** [comment]
thx :+1:
