### ISSUE TITLE
[building-rollup] a relative paths to js modules have issue on Safari

### ISSUE THREAD

**Issue by JosefJezek** [open-wc/open-wc#794]
The rollup build set js modules paths to relative paths.

Error on Safari after reload the path `https://my.app/results`
`[Error] Failed to load resource: the server responded with a status of 404 https://my.app/results/app-shell.js`

Chrome and Firefox are without a error.

`index.html`
```
<base href="/">
<script type="module" src="src/components/app-shell.js" crossorigin></script>
```
`index.html` after the build
```
<base href="/">
<link rel="preload" href="app-shell.js" as="script" crossorigin="anonymous">

HTMLScriptElement.prototype?["./app-shell.js"]
window.importShim(e)})):["./legacy/app-shell.js"]
```

**Comment by rwestlund** [comment]
I ran into this too. See #564. I'm currently using `sed` to make it an absolute path after building :/

**Comment by LarsDenBakker** [comment]
Thanks for reporting, looking into it!

**Comment by JosefJezek** [comment]
@rwestlund The relative paths of imports are in all files of my app. I can't use `sed`. :-(

**Comment by LarsDenBakker** [comment]
Unfortunately I'm not able to reproduce this, do you have some more info? A minimal project setup would be ideal.

What URL are you hosting your application on? `https://my.app/results/app-shell.js` throws a 404, the request should be `https://my.app/app-shell.js` ?

**Comment by LarsDenBakker** [comment]
It's really disappointing that safari implements this incorrectly. I've found a clever workaround though, in order to feature detect dynamic import we already wrap them in a function like this:

```
window.importShim = source => import(source);
```

so we can resolve the URL using the document's base uri (which respects the base path), before running the dynamic import on safari:

```
window.importShim = src => import(src.startsWith('.') ? new URL(src, document.baseURI) : src)
```

**Comment by LarsDenBakker** [comment]
tracking bug for future reference https://bugs.webkit.org/show_bug.cgi?id=201692

**Comment by LarsDenBakker** [comment]
Let me know if this fixes the issue for you guys

**Comment by JosefJezek** [comment]
@LarsDenBakker This solution is working. Thank you! :+1:
