### ISSUE TITLE
WebpackIndexHTMLPlugin customisation with `createCompatibilityConfig`

### ISSUE THREAD

**Issue by funglaub** [open-wc/open-wc#797]
Hey guys,

I'm trying to ship a custom tailored webcomponents polyfill without ShadyCSS (since I don't have shadow DOM).

relevant parts of my webpack config are:

```
const configs = createCompatibilityConfig({
  input: path.resolve(__dirname, './index.html'),
});

const newConfigs = configs.map((config) =>
  merge(config, {
    module: {
      rules: [
        {
          test: /\.s?[ac]ss$/,
          use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'],
        },
        {
          test: /\.(woff|woff2)$/,
          use: {
            loader: 'file-loader',
            options: {
              name: '[name].[ext]',
              outputPath: './webfonts',
            },
          },
        },
      ],
    },
    plugins: [
      new MiniCssExtractPlugin({
        filename: '[name].css',
        chunkFilename: '[id].css',
      }),
      new CopyWebpackPlugin([
        {
          from: 'assets',
          to: 'assets',
        },
      ]),
      new WebpackIndexHTMLPlugin({
        multiBuild: true,
        polyfills: {
          coreJs: true,
          regeneratorRuntime: true,
          webcomponents: true,
          fetch: true,
        },
      }),
    ],
  }));

module.exports = newConfigs;
```

Removing the last plugin, the build works, it ships two versions with the bundled polyfills for legacy.

If I add the last plugin, the build fails with:

```
TypeError: Cannot read property 'resolve' of null
    at compiler.hooks.emit.tapPromise (/Users/fnunglaub/Code/some-repo/node_modules/@open-wc/webpack-index-html-plugin/webpack-index-html-plugin.js:117:37)
    at _next1 (eval at create (/Users/fnunglaub/Code/some-repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:17)
    at _err1 (eval at create (/Users/fnunglaub/Code/some-repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
    at Promise.all.catch.then (/Users/fnunglaub/Code/some-repo/node_modules/copy-webpack-plugin/dist/index.js:90:9)
```

Any ideas?

**Comment by LarsDenBakker** [comment]
You need to pass in a boolean flag which tells the plugin whether you're running the modern or legacy version of the build. https://github.com/open-wc/open-wc/blob/master/packages/building-webpack/modern-and-legacy-config.js#L133

You can pass custom configuration to the index html plugin by passing an options object when you create the config: https://open-wc.org/building/building-webpack.html#common-extensions

Also, it's possible to add custom polyfills so you could load the web component polyfills without shady css support. You can read more about it here: https://open-wc.org/building/webpack-index-html-plugin.html#polyfills

**Comment by funglaub** [comment]
Hey Lars,

thanks for the infos.

I also noticed that merge does not overwrite the default plugin which comes from `createCompatibilityConfig`. My custom plugin will simply be appended. I replaced the plugins array in both configs manually now and this weird Promise rejection will be gone then. I'll keep you updated.

**Comment by funglaub** [comment]
I managed to achieve what I wanted now :)

Here's my webpack config FYI: https://gist.github.com/funglaub/7d63f2300dd9031027471977318c32e9
