### ISSUE TITLE
Possibility to change the filename of polyfills

### ISSUE THREAD

**Issue by funglaub** [open-wc/open-wc#800]
Hi there,

is there any possibility to change the emitted filename of polyfills? I can customise the output filename of my bundle through `output: { filename: '[name]'.js}`, but I can't find a place where to change the filename of polyfills. I would like to get rid of the file hash in the filename.

Thank you
Florian

**Comment by LarsDenBakker** [comment]
Not right now, whats your use case for this?

**Comment by funglaub** [comment]
Hi @LarsDenBakker,

I know that the hash is for caching, but my usecase is, that the assets will be served from a directory having the version in it. I'd like to integrate some components into a server side rendered CMS system and changing templates to reference new hashed asset files requires me to change the templates upon each release.

**Comment by LarsDenBakker** [comment]
Ah I see, something we need to add indeed. Open to a PR for this as well :)

**Comment by LarsDenBakker** [comment]
We would need to add an option to the configuration here: https://github.com/open-wc/open-wc/blob/master/packages/building-utils/index-html/create-index-html.js#L64

And read it to not set the hash here: https://github.com/open-wc/open-wc/blob/master/packages/building-utils/index-html/create-index-html.js#L125

This util is used by the webpack plugin, you can test your changes here: https://github.com/open-wc/open-wc/tree/master/packages/webpack-index-html-plugin

**Comment by funglaub** [comment]
This can be closed from my side. PR was merged.

**Comment by daKmoR** [comment]
closed via https://github.com/open-wc/open-wc/pull/808
