### ISSUE TITLE
[es-dev-server] compatibility flag not working with port flag

### ISSUE THREAD

**Issue by jdvivar** [open-wc/open-wc#803]
Steps to reproduce

1. Start a new wc with this straightfoward script:
```bash
npm init @open-wc --type scaffold --scaffoldType wc --features  --tagName test-wc --writeToDisk true --installDependencies npm
```
2. Run the compatibility script
```bash
cd test-wc
npm run start:compatibility
```
3. Add a port flag to the script, say 8090:
```json
...
"start:compatibility": "es-dev-server --app-index demo/index.html --compatibility all --node-resolve --open --watch --port 8090"
...
```
3. Run the compatibility script again, check console errors:
```bash
npm run start:compatibility
```
<img width="695" alt="Screenshot 2019-09-17 at 11 04 30" src="https://user-images.githubusercontent.com/690017/65027671-0e6f8c00-d93b-11e9-9cbf-f806581bf7b7.png">

**Comment by thepassle** [comment]
Hey Daniel!

I have not been able to reproduce this yet locally. Would it be possible to share a github repo?

![Screenshot 2019-09-18 at 09 29 56](https://user-images.githubusercontent.com/17054057/65126190-fd845080-d9f6-11e9-9ece-4eeff3f3ded4.png)

**Comment by jdvivar** [comment]
I'm not able to reproduce it today either. Yesterday I checked the steps in completely pristine setups on 2 computers, just doing the steps described... oh well! 🤷‍♂
