### ISSUE TITLE
[prettier] Use it to format/order package.json

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#804]
There is a Plugin for it 💪 
https://www.npmjs.com/package/prettier-plugin-package

🤗

**Comment by CodingMagesty** [comment]
Hey, I would like to PR my solution, but I get 403, trying to push my branch to the repo. Any suggestions on what to do?

**Comment by CodingMagesty** [comment]
Hey, please review my PR for this issue. https://github.com/open-wc/open-wc/pull/841

**Comment by LarsDenBakker** [comment]
Closing, since this was implemented.
