### ISSUE TITLE
Use Rollup resolvers in es-dev-server

### ISSUE THREAD

**Issue by ashubham** [open-wc/open-wc#806]
`es-dev-server` is great and its good to see tooling pushing us closer to the platform.

However, its hard to make it work with a project already using a bundler (rollup in our case) where we already have non-js files like `.html`, `.json` etc imported as modules within code.

Also, there are some inconsistencies in the way imports work sometimes, like no `default` exports in `lodash` seems to be handled specially (it might be just the way I am importing it).

Anyways, the point is it would be great if we could use `rollup` resolvers/plugins as middleware to `es-dev-server`. This will provide us with best of both worlds. I tried migrating our app off rollup in the dev loop and this is a middleware config I had reached before giving up on `lodash` exports which work fine with rollup bundler.

```js
middlewares: [
    function transforms(context, next) {
      if(!context.url.includes('.')) {
        context.url += '.js';
      }
   
      return next().then(() => {
        if(context.url.includes('.html') && context.url !== '/app/index.html') {
          context.body = `export default ${JSON.stringify(context.body)};`
          context.response.type = `application/javascript`;
        };
        if(context.url.match(/.*\.json$/)) {
          context.body = `export default ${context.body};`
          context.response.type = `application/javascript`;
        }
    })}
```

Wanted to check if this is a viable idea, before diving into it or if someone has already tried something similar.

**Comment by LarsDenBakker** [comment]
I think it's interesting and worth investigating, but we need to be careful not to bloat the dev server too much. We already support babel for single file transforms, I hope we can standardize on babel for transformations rather than bundler specific plugins for single file transforms.

Bundlers also support acting on multiple files or an entire module graph, this is something that could never work with the dev server. 

HTML, CSS and JSON modules can work as babel plugins I actually use the dev server with a babel plugin for transforming old html imports to es modules myself. Also interesting to note here is that `es-module-shims` and `systemjs` are working on supporting json, css and html modules.

**Comment by ashubham** [comment]
The reasoning is actually this issue https://github.com/Polymer/tools/issues/608 

Without supporting these non ES6 module packages, it will be hard to get adoption on unbundled servers.

**Comment by LarsDenBakker** [comment]
Supporting non es modules is a slippery slope, there are many conventions and its quite confusing for most people.

I think adding a generic transformation hook would be good, that way you can plug in any tools you like. It would be easy to write an adapter that uses rollup plugins there.

For module transformation specifically, a babel plugin would be better than a bundler plugin. Ive seen some but I havent tried it yet.

**Comment by ashubham** [comment]
@LarsDenBakker Is there a workaround I could do today ?

**Comment by LarsDenBakker** [comment]
You can try https://github.com/tbranyen/babel-plugin-transform-commonjs and see if that works. 

The code snippet you showed above is similar to how a transform hook would work, except that you don't get any caching. You can do any custom transformations there if you want.

https://github.com/systemjs/systemjs is also an option, you could compile all your modules types to systemjs using https://babeljs.io/docs/en/babel-plugin-transform-modules-systemjs. Systemjs is much better at supporting the quirks of the different module formats than es modules.

Also in the case of rollup you mentioned above, you can look into `lodash-es`.

**Comment by ashubham** [comment]
Awesome thanks @LarsDenBakker  let me try the babel-transformer.

FWIW I was able to repurpose `rollup-plugin-commonjs` for use as a Koa middleware(like above) and currently trying if I have some luck there. In the absence of a generic `transform` hook I am using middlewares.

We used `SystemJS` for the last couple of years, with Typescript compiling to `System.register` format. We even shipped code to prod using SystemJS since ES6 modules were not mainstream. It worked great in the Dev setup since no bundling and thats what I miss now. I swapped it with `rollup` since we can now ship native ES6 to browsers. I do not want to complicate our build process bringing it back.

Well `lodash-es` might work, but there are a ton other deps we have which are cjs.

**Comment by LarsDenBakker** [comment]
Rollup also supports outputting systemjs, systemjs changed quite a bit in v2. It's not a faithful polyfill for es modules, but allows hooks for lots of custom module formats. This way it's really flexible.

**Comment by ashubham** [comment]
What `rollup` really should support is just outputting unbundled transformed es6 modules which can run directly in the browser without any middleware. 

The dev cycle of bundling in rollup is really slow for our huge app.

**Comment by LarsDenBakker** [comment]
We now have `responseTransformers` as an option in `es-dev-server`. I'd like to see if it's easy to hook up a rollup plugin for per-file transformation.

**Comment by ashubham** [comment]
I am currently using this for my project which somewhat works. This still uses the generic `middleware`.

https://gist.github.com/ashubham/b33fb1c6c1621ce90af56b77ee356457

**Comment by daKmoR** [comment]
so we now `Use Rollup resolvers in es-dev-server` so that is done... we still wanna add documentation for it so we will leave it open for now 👍

**Comment by LarsDenBakker** [comment]
Using rollup resolvers is a pretty specialist use case, I don't think we can add general documentation for it. It's a case by case thing, so I'll close this issue for now.
