### ISSUE TITLE
[webpack-index-html-plugin] output script src prevents single-page dev server

### ISSUE THREAD

**Issue by tpluscode** [open-wc/open-wc#807]
## Description 

It is currently impossible to deploy and debug single-page applications because the entrypoint script's URL is relative.

## Current behaviour

In the `index.html` it might be `<script type="module" src="./components/my-app.js"></script>`.

Both in production build as well as with webpack-dev-server this will result in a relative script like `<script src="./my-app.44645eba9e3994eab753.js">`

This breaks single-page apps because when requesting any non-root URL like `/some/virtual/path` the script (as well as dynamically loaded chunks) will be fetched from `/some/virtual/my-app.44645eba9e3994eab753.js` which responses with a `404` status.

## Expected behaviour

The generated script should be absolute. In the example above is should only mean to remove the dot => `/my-app.44645eba9e3994eab753.js`.

## Workaround for dev server

I managed to tweak the dev server and output config to get the local server running smoothly by explicitly rewriting the entry point scripts and setting the `publicPath` (necessary to get correct URL to chunks):

```
devServer: {
  publicPath: '/',
  historyApiFallback: {
    rewrites: [{ from: /my-app.js$/, to: '/my-app.js' }],
  },
},
output: {
  publicPath: '/',
},
```

Apparently the only change necessary for the deployed build is to change the script paths in `index.html`. The chunks are otherwise already loaded correctly.

**Comment by LarsDenBakker** [comment]
Using absolute urls has downsides as it makes the entire url system quite rigid. If you're building a SPA I suggest adding a `<base href="/">` so that URLs are resolved relatively. Not just the generated scripts, but also urls in CSS, fetch requests, anchor tags etc.

**Comment by tpluscode** [comment]
Mm, I was thinking about `<base>` but it did not occur to me that it can be used without the domain name.

**Comment by LarsDenBakker** [comment]
I'm quite surprised that a lot of people don't know about it. We could consider using absolute urls in the dev server, but I don't know if that will just create more problems.

**Comment by tpluscode** [comment]
What if the plugin injected a base tag as `<base href="${config.output.publicPath}">` if the tag is not otherwise present in the source index?

**Comment by LarsDenBakker** [comment]
We could do that, but then after running a build it would stop working. Throwing an error would probably be better here.

**Comment by tpluscode** [comment]
By "stop working" you mean that a deployed app may live in `/app-path` while the dev server is running from root like "localhost:8080/"?

If so, then I think it should be handle individually in the config. Something like 

```
{
  publicPath: process.env.NODE_ENV === "production" ? "/app-path" : "/"
}
```

Something to put in the docs although it's not open-wc-specific and thus it would be best to link to a good example online.

**Comment by LarsDenBakker** [comment]
No I mean if we inject a base path in the dev server, you gain the illusion that your app works. When it is deployed on a web server which doesnt inject a base path, it then stops working.

**Comment by tpluscode** [comment]
Well yes. The base tag would have to be injected both in dev server as well as in production build.

If there are issues I don't see then let's at least add a paragraph to the guide. Think about it and let me know how you'd like to proceed.
