### ISSUE TITLE
Storybook fails when the component is using a mixin

### ISSUE THREAD

**Issue by midesweb** [open-wc/open-wc#810]
I'm having errors in storybook when using a component that uses a mixin.

The error i get is like my this:

> Uncaught TypeError: Class constructor  cannot be invoked without 'new 

Sounds like there is some transpilation of the code and is not applied the custom-elements-es5-adapter.js 

My component class declaration is this:

```
export class DileTopMessage extends DileSlideDownMixin(LitElement) {`
```

The mixin (DileSlideDownMixin) code looks like this:

```
export const DileSlideDownMixin = (SuperClass) => {
  return class extends SuperClass {
     // some methods
  }
}
```

When I remove the mixin (my class component only extends from LitElement and copy-paste the mixin methods inside the component), the demos from storybook start to run without errors.

Somebody has an idea of what can i do to solve this issue? Thanks!

**Comment by bennypowers** [comment]
if you're bringing your mixin in from node modules, you need to add the package to `transpilePackages`

**Comment by midesweb** [comment]
Thanks Benny! that was the reason.

If someone needs to know how to add the package to `transpilePackages`, this is a configuration placed in the webpack.config.js file at .storybook project folder.

Now my code looks like this:

```
module.exports = ({ config }) => {
  return defaultConfig({ config, transpilePackages: ['lit-html', 'lit-element', '@open-wc', 'dile-slide-down-mixin'] });
};
```

**Comment by bennypowers** [comment]
Closing as it seems you're sorted.
