### ISSUE TITLE
[es-dev-ser] Problem with multiple slashes in the route

### ISSUE THREAD

**Issue by Tansito** [open-wc/open-wc#817]
We were having problems with the `es-dev-server` serving components in routes with more than one slash. An example could be:
- `http://localhost:8000/about`: it works perfectly
- `http://localhost:8000/about/something`: generates the next error

![Screen Shot 2019-09-25 at 11 45 38 AM](https://user-images.githubusercontent.com/9059044/65594077-4fe2e580-df92-11e9-9c5f-fc86a1d20551.png)

As you can see we don't know why but the route of the `app-shell` (as the rest of the resources), instead to be in the root path `es-dev-server` is looking for below the **/about** path.

The way that we launch the es-dev-server is the next:
`es-dev-server --app-index index.html --file-extensions .ts --node-resolve --babel --watch --open`

Do we have to configure something when we launch the server or is there a problem related with slashes in the routes?

**Comment by LarsDenBakker** [comment]
You are probably missing a base element, the docs explain how to set this up. This is needed for SPA routing.

**Comment by Tansito** [comment]
Totally @LarsDenBakker , after adding the base element it worked, thanks!
