### ISSUE TITLE
webpack-import-meta-loader invalid browser path

### ISSUE THREAD

**Issue by JeffThe** [open-wc/open-wc#818]
Hi, 

I am trying to use webpack-import-meta-loader as a workaround for:
`Add @babel/plugin-syntax-import-meta (https://git.io/vbKK6) to the 'plugins' section of your Babel config to enable parsing.`

I've configured it like in example:
```js
module: {
  rules: [
    {
      test: /\.js$/,
      loader: require.resolve('@open-wc/webpack-import-meta-loader'),
    },
  ],
},
```
And it works, except of that it is providing invalid paths. 

For example:
`/ules/ace-builds/src-min-noconflict/theme-eclipse.js`
When correct path looks as follows:
`webpack:///../node_modules/ace-builds/src-noconflict/theme-eclipse.js`

**Comment by LarsDenBakker** [comment]
the import meta loader rewrites the imports to valid browsers paths. `webpack:///../node_modules/ace-builds/src-noconflict/theme-eclipse.js` is not a valid browser path, so I don't expect that as output.
