### ISSUE TITLE
Storybook withClassPropertiesKnobs only exports the first element in the template

### ISSUE THREAD

**Issue by NickdeK** [open-wc/open-wc#820]
Using the `withClassPropertiesKnobs` function only returns the first element in the template. This prevents developers from passing a custom-element with a HTML element to interact with the custom-element.

The first element [is selected here](https://github.com/open-wc/open-wc/blob/9232b38d6db0fb13eb9b199187da287487da82ae/packages/demoing-storybook/withClassPropertiesKnobs.js#L35) and [eventually returned here](https://github.com/open-wc/open-wc/blob/9232b38d6db0fb13eb9b199187da287487da82ae/packages/demoing-storybook/withClassPropertiesKnobs.js#L89). Shouldn't the whole wrapper be returned with only the custom-element in it replaced with applied knobs?

Example on what I was trying to do:
```
import {storiesOf, html, withKnobs, withClassPropertiesKnobs, select} from '@open-wc/demoing-storybook';
import {DraggableDrawer} from "./draggable-drawer";

storiesOf('Core UI', module)
  .addDecorator(withKnobs)
  .add(
    'Dragable Drawer Top',
    () => withClassPropertiesKnobs(DraggableDrawer, {
      overrides: el => [
        {
          key: 'align',
          fn: () => select('align', ['left', 'right','top','bottom'], el.align, 'Inherited'),
        }
      ],
      template: html`
        <draggable-drawer align="${'top'}">
          <h1>Drawer</h1>
          <ul>
            <li>List 1</li>
            <li>List 2</li>
            <li>List 3</li>
          </ul>
        </draggable-drawer>
        <button onclick="document.querySelector('draggable-drawer').open()">Open Drawer</button>        
        `
    }),
    { notes: 'Test' , options: { selectedPanel: 'storybooks/knobs/panel' }}
  );
```

**Comment by bennypowers** [comment]
See also #833

**Comment by LarsDenBakker** [comment]
@daKmoR is this something we want to fix/improve/throw an error?

**Comment by daKmoR** [comment]
this helper function got replace with a storybook decorator... for a migration please see
https://open-wc.org/demoing/MIGRATION.html#replaced-withclasspropertiesknobs-with-a-decorator-withwebcomponentsknobs
