### ISSUE TITLE
lit-html templates not resolving repeaters during dev and prod builds

### ISSUE THREAD

**Issue by Pupix** [open-wc/open-wc#821]
Hello,
I encountered this strange bug after updating the dependencies of my project with `yarn upgrade`.

This is what a repeater generates on the webpage instead of `1, 2, 3, 4, 5`.
![repeat-b](https://user-images.githubusercontent.com/4929965/65686179-12e72380-e064-11e9-8863-54fedc939ff3.png)

Running the same upgrade command multiple times seems to fix the problem after a few tries. Also manually running `yarn add lit-html` after the upgrade fixes the problem 100% of the time.
I don't know if this is a problem with dependencies fighting or something else but seems quite strange.

I can provide more info if need be.

The package.json is as follows:
```json
{
  "name": "project",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@open-wc/building-webpack": "2.3.2",
    "babel-core": "6.26.3",
    "babel-loader": "8.0.5",
    "babel-preset-env": "1.7.0",
    "copy-webpack-plugin": "5.0.3",
    "css-loader": "3.0.0",
    "eslint": "5.15.3",
    "eslint-config-airbnb-base": "13.1.0",
    "eslint-plugin-import": "2.16.0",
    "eslint-plugin-node": "8.0.1",
    "eslint-plugin-security": "1.4.0",
    "extract-loader": "3.1.0",
    "file-loader": "4.0.0",
    "jest": "24.5.0",
    "lit-scss-loader": "1.0.0",
    "node-sass": "4.12.0",
    "sass-loader": "7.1.0",
    "webpack": "4.36.0",
    "webpack-cli": "3.3.6",
    "webpack-dev-server": "3.7.2",
    "webpack-merge": "4.2.1",
    "workbox-webpack-plugin": "4.3.1"
  },
  "engines": {
    "node": ">=10.0.0"
  },
  "scripts": {
    "build": "webpack --mode production --progress",
    "dev": "webpack-dev-server --mode development --host 0.0.0.0 --history-api-fallback --open --progress"
  },
  "dependencies": {
    "@material/button": "3.0.0",
    "@material/card": "3.0.0",
    "@material/checkbox": "3.0.0",
    "@material/data-table": "3.0.0-alpha.0",
    "@material/dialog": "3.0.0",
    "@material/drawer": "3.0.0",
    "@material/fab": "3.0.0",
    "@material/form-field": "3.0.0",
    "@material/icon-button": "3.0.0",
    "@material/linear-progress": "3.0.0",
    "@material/list": "3.0.0",
    "@material/menu": "3.0.0",
    "@material/menu-surface": "3.0.0",
    "@material/radio": "3.0.0",
    "@material/ripple": "3.0.0",
    "@material/select": "3.0.0",
    "@material/snackbar": "3.0.0",
    "@material/tab-bar": "3.0.0",
    "@material/textfield": "3.0.0",
    "@material/theme": "3.0.0",
    "@material/top-app-bar": "3.0.0",
    "@material/typography": "3.0.0",
    "date-fns": "1.30.1",
    "html-loader": "0.5.5",
    "lit-element": "2.2.0",
    "lit-html": "1.1.2",
    "lodash-es": "4.17.11",
    "markdown-loader": "5.0.0",
    "prpl-server": "1.4.0",
    "pwa-helpers": "0.9.1"
  }
}
```

Cheers,
Pupix

**Comment by Westbrook** [comment]
This likely originated at your use of  the following. 

```
    "lit-element": "2.2.0",
    "lit-html": "1.1.2",
```

Pinning your versions of lit-element and lit-html can lead to NPM resolving your dependencies to multiple versions and lit-html requires it be deployed as a singleton in order to cache your templates correctly. I’d reset these values to something more like:

```
    "lit-element": "^2.2.0",
    "lit-html": "^1.0.0",
```

In order to reduce the possibility of the issue emerging in your project. 

In some cases `yarn dedupe`/the yarn resolution functionality can also be used to benefit here, or you can rely on the aliasing available in your bundled when using `webpack` or `rollup`.

**Comment by Pupix** [comment]
So by using the caret you imply that both would get the latest version of `lit-html` and the dedupe will make it be shared? What happens if `lit-element` starts using `lit-html` 2.0.0? Wouldn't the same problem arise again?

**Comment by Westbrook** [comment]
Not “the latest versions”. The latest version without changing a major version, a la https://docs.npmjs.com/about-semantic-versioning.

If you don’t actually use lit-html directly, you can exclude it in your dependencies, as it’s really a lit-element dependency. However, the likelihood that lit-element uses a new major version of lit-html, given the Singleton situation, is pretty low. 

Here’s a great tool for visualizing the versions a specific string will return https://semver.npmjs.com/

**Comment by Pupix** [comment]
Yes, that's what I meant, latest in the given version range.
I do use lit-html currently, for directives such as `repeat`, so I can't remove it.

You got a reference for this singleton situation? I wanna read up on it.

**Comment by Westbrook** [comment]
I think this is the definite issue on the subject: https://github.com/Polymer/lit-html/issues/320 You have to follow the thread to see if the context made the full documentation somewhere. As this is a lit-html issue, I’m going to close the open-WC issue here. Please feel free to reopen if you find something you’d like to see addressed in this are via our tools.

**Comment by Pupix** [comment]
Aight, thanks. I see they got the same problem and someone from the polymer team seen and responded to the issue.
