### ISSUE TITLE
Using es-dev-server and express

### ISSUE THREAD

**Issue by vdegenne** [open-wc/open-wc#825]
Is there any way to pass a `js` file representing an express server to the `es-dev-server` process ?
Basically something like `es-dev-server --app server.js` would be nice because usually the server that treats some back requests is the same server that provides these front-end interfaces.

Thanks

**Comment by LarsDenBakker** [comment]
In the docs there is a section on how to set up middlewares for the server, from there you can proxy to an express server or add your own middlewares.

The server is written in koa, which is a much better dev experience than express so I'd really recommend it. There are plugins however which let you adapt express middlewares for use with koa.
