### ISSUE TITLE
Setup markdown linting

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#826]
probably something like here https://github.com/ing-bank/lion/pull/205/commits/c23fc22061678bc9b70e2c0ad5a56aee6e94afc2

**Comment by Ania-chan** [comment]
Hi! Can I try doing this issue? 🙏

**Comment by thepassle** [comment]
Sure thing :)

**Comment by Ania-chan** [comment]
Thanks! I'll try to make pull request in the first week of October

**Comment by jlengrand** [comment]
How's progress going @Ania-chan ?

**Comment by daKmoR** [comment]
closed via https://github.com/open-wc/open-wc/pull/830
