### ISSUE TITLE
[es-dev-server] feature request: --compatibility auto

### ISSUE THREAD

**Issue by e111077** [open-wc/open-wc#831]
Heya, one of the nice features I liked in Polyserve was that it will automatically compile for browsers that need it but not compile for those that did not. It makes a great tool for public demos and tests as inspecting the source is very useful, but so is showing off that it works in IE.

Cheers!

**Comment by LarsDenBakker** [comment]
Hey @e111077 this is definitely on our todo list. I want to be careful to not penalize the development experience on modern browsers, for example I don't want to run babel on chrome if it's not needed. To do this properly we need to refactor some parts of the server which we're working on at the moment.

In a way `--compatibility all` will get you there part of the way, it doesn't serve es5 to all browsers. But it's not perfect.

**Comment by e111077** [comment]
Thanks for taking my suggestion into account! Y'all're doing really great work!

**Comment by LarsDenBakker** [comment]
Not stalr

**Comment by e111077** [comment]
Another use case is easily automating testing the minimal compilation needed for several browsers. E.g. testing chrome stable but only needing to compile for IE and Chrome 41,

**Comment by LarsDenBakker** [comment]
Absolutely! I've been working on this, I think I'll be able to wrap it up this weekend. :)

**Comment by e111077** [comment]
Perfect timing for us TBH! I was really just responding to unstale it.

Thanks for all the hard work!

**Comment by LarsDenBakker** [comment]
@e111077 give it a try, let me know if you run into any issues

**Comment by e111077** [comment]
Thanks a lot for all the hard work. Unfortunately I just left for vacation, but I let my other teammates know that this change went through. Will definitely get back to you at least by early December
