### ISSUE TITLE
require is not defined for all test files

### ISSUE THREAD

**Issue by lakshay35** [open-wc/open-wc#840]
when i run npm test I get the error "ReferenceError: require is not defined" for each test file I have.  A short while ago my tests were running but I am not sure what is wrong anymore.

Karma.config.js
![image](https://user-images.githubusercontent.com/10873132/66347027-6a697700-e921-11e9-8980-7aa81baed5f6.png)

.babelrc
![image](https://user-images.githubusercontent.com/10873132/66347045-748b7580-e921-11e9-806d-ddd7925897f1.png)

A test file
![image](https://user-images.githubusercontent.com/10873132/66347079-7fdea100-e921-11e9-811b-8e49631969f3.png)

Error in console
![image](https://user-images.githubusercontent.com/10873132/66347134-9a187f00-e921-11e9-8a1d-9778ecb108af.png)

devdependencies
![image](https://user-images.githubusercontent.com/10873132/66347202-c6340000-e921-11e9-90fe-c2820e6c9925.png)

I would appreciate all the help and will provide any information needed

**Comment by daKmoR** [comment]
babel-plugin-transform-es2015-modules-commonjs

> This plugin transforms ES2015 modules to CommonJS.

so this plugin generates commonjs code which does not natively run in the browser.

so probably best to remove it?

**Comment by lakshay35** [comment]
Still getting the same error

**Comment by lakshay35** [comment]
I figured it out. Class properties in js weren't appreciated when testing and were causing the error. I configured typescript as of now and have a separate issue where I can't seem to directly test spec.ts files despite following the steps outlined on https://open-wc.org/testing/karma-esm.html#usage. Any help from @LarsDenBakker or @daKmoR  would be greatly appreciated.

**Comment by bennypowers** [comment]
@lakshay35 I'm glad your issue with commonjs was resolved.  😁

If your problem with `.spec.ts` files is still occurring, please open a new issue for it.
