### ISSUE TITLE
[testing] how to handle dependencies with `require()`

### ISSUE THREAD

**Issue by funglaub** [open-wc/open-wc#843]
I have added `ajv` to my project and use this to validate responses in one of my webcomponents. `ajv` sources use node's `require` internally. 

This is handled by babel in my webpack configuration, so it works when I start the project. 

The test for that component is included in the `karma.conf` `files`-Array. Now I get a message from Chrome that `require() is not defined` which makes sense.

I tried enabling babel in the `esm` section, but nothing changes. Preprocessors don't work with esm, so using webpack there is not an option either.

Can someone give me hint?

Thanks

**Comment by LarsDenBakker** [comment]
You can try looking for a babel plugin which transforms the commonjs modules to es modules, but we generally recommend sticking to es modules.

**Comment by funglaub** [comment]
I'd like to get around this package too, but it's hard to find any alternatives.

I enabled babel now and added https://github.com/tbranyen/babel-plugin-transform-commonjs (should do what I want) to my .babelrc: 

```
{
  "plugins": ["transform-commonjs"]
}
```

Do I need to do anything more? I still have the initial error.

**Comment by LarsDenBakker** [comment]
You need to make sure you have the babel flag enabled too in karma.

Beyond that I'm not sure, this isn't really what our setup is built for so it will be quite rough around the edges.

**Comment by LarsDenBakker** [comment]
Closing this, a custom babel setup is the solution here. We don't have explicit support for this.

**Comment by blikblum** [comment]
For the record, using https://github.com/tbranyen/babel-plugin-transform-commonjs does not work when the cjs module is in node_modules.

**Comment by blikblum** [comment]
A second record. With [importMap feature](https://open-wc.org/testing/karma-esm.html#importmap), i managed to write an ES module to act as a bridge between ES import and commonjs module.

See this [commit](https://github.com/blikblum/lit-element-mobx-realworld-example-app/commit/75988ad3ce9e92da9a65d8533655d54fce58da1e). 

To this workaround work the commonjs package needs to provide an UMD bundle that works standalone in browser; sets a global variable and the UMD wrapper must be well written, i.e., do not assume this is defined.
