### ISSUE TITLE
Error in TypeScript instructions

### ISSUE THREAD

**Issue by simonh1000** [open-wc/open-wc#852]
I created a typescript project based on an element called `my-element`. 

My code is 
```
import { LitElement, html, customElement, property } from "lit-element";

@customElement("my-element")
export class MyElement extends LitElement {
  @property()
  foo = "world";

  render() {
    return html`
      <div>hello ${this.foo}</div>
    `;
  }
}
```

But in the file `./my-element.js` is the line
```
window.customElements.define('my-element', MyElement);
```

This leads to the repeat declaration of the customElement, creating a error in the dev console

**Comment by LarsDenBakker** [comment]
Hi there! Which instructions do you mean? We have multiple for different tools.

Also, did you add the `customElements.define` yourself or do you mean that they get generated somehow?

**Comment by simonh1000** [comment]
I was looking at https://open-wc.org/developing/es-dev-server.html#typescript-support

one of the things you get with typescript are decorators. As a result, the line `@customElement("my-element")` is - I believe - calling customElement.define behind the scenes (the code below is what is generated - it's not entirely easy to follow)

```
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
import { LitElement, html, customElement, property } from "lit-element";
let MyElement = class MyElement extends LitElement {
    constructor() {
        super(...arguments);
        this.foo = "world";
    }
    render() {
        return html `
      <div>hello ${this.foo}</div>
    `;
    }
};
__decorate([
    property()
], MyElement.prototype, "foo", void 0);
MyElement = __decorate([
    customElement("my-element")
], MyElement);
export { MyElement };
//# sourceMappingURL=MyElement.js.map
```

**Comment by LarsDenBakker** [comment]
Are you using `tsc`, or using the babel plugin. 

Also, what's wrong with this code snippet? I don't see an extra `window.customElements.define` in there.

**Comment by simonh1000** [comment]
I am using tsc and added a tsconfig.json - see https://github.com/simonh1000/openwc-typescript-example.

I agree that it is not obvious that `window.customElements.define` is present in the code snippet, but I strongly believe that it is in practise. I can comment out the define in my-element.js and it still works. And with some debugging I can see that my-element is getting defined.

**Comment by LarsDenBakker** [comment]
Looking at that repository, I think what you did is take the open-wc scaffolding and added the custom element decorator to `MyElement.ts`. That causes the double registration because it's already being registered in `my-element.ts`. Removing that line of code solves the problem, so that's working as intended, right?

**Comment by simonh1000** [comment]
no worries then. I think the only issue is that a standard use of typescript with lit-elements is going to involve using decorators, and so anyone that uses typescript is going to run into the duplicate `define`. It was easy enough to fix though
