### ISSUE TITLE
Add service worker to generators

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc#854]
We should add a service worker to the lit-element app starter in `create`

- Add a `_sw.js` with `console.warn('⚙️ Service worker is disabled during development and will be generated during build time.');`
- Add service worker registration to `index.html`: 
```html
<script>
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
      navigator.serviceWorker.register('./sw.js');
    });
  }
</script>
```

My guess is that we need to overwrite the default `index.html` from inside the `building-rollup` generator with an `index.html` that already has this service worker registration. Maybe @daKmoR has some other thoughts about how to handle this?

**Comment by Chethan2k1** [comment]
Can I work on this?

**Comment by thepassle** [comment]
For sure :)

Theres some things to iron out though:

- `building-rollup` will now generate a service worker for you by default
- If we add the `_sw.js` to the app generator, and we add the service worker registration to the `index.html`, but the user _doesnt_ opt into using `building-rollup` when using `npm init @open-wc`, the user now has a service worker that doesn't do anything. How do we go about that? Just accept it?

@Chethan2k1 If you're interested, maybe in the meanwhile you could take a stab at https://github.com/open-wc/open-wc/issues/853 ?

cc @LarsDenBakker @daKmoR

**Comment by daKmoR** [comment]
has been implemented 👍
