### ISSUE TITLE
Issue with testing components that have redux as dependency

### ISSUE THREAD

**Issue by miladkdz** [open-wc/open-wc#858]
I have an issue while writing unit tests for components that have dependency to redux. I get this error message while running the unit tests:

` ReferenceError: process is not defined`

This is the source to a simple unit test where `ticket-list-panel` has dependency to redux:

```
import { html, fixture, expect } from '@open-wc/testing';

import '../ticket-list-panel';

describe('TicketListPanel', () => {
  it('renders heading element', async () => {
    const el = await fixture(html`
      <ticket-list-panel></ticket-list-panel>
    `);

    expect(el.shadowRoot.querySelector('.heading')).to.not.be.a('null');
  });
});
```

**Comment by LarsDenBakker** [comment]
I think this is a bug in Redux itself, they're trying to access `window.process` which is not available in the browser.

**Comment by web-padawan** [comment]
The problem as I see it is how to apply the following workaround when using `karma-esm`:
https://github.com/Polymer/pwa-helpers/blob/ce6be1a18655350c33b0f8949a1a16371d2caaa6/test/connect-mixin.html#L32-L36

**Comment by thepassle** [comment]
You should be able to add global variables to Karma iirc. Something like [this](https://stackoverflow.com/questions/33695736/how-to-dictate-a-global-variable-in-specific-karma-test-block)

Additionally, [Redux does ship ES modules](https://unpkg.com/browse/redux@4.0.4/es/), which dont include the check for `window.process.env`

**Comment by miladkdz** [comment]
Thanks @thepassle. Adding the global variable fixed my issue.
