### ISSUE TITLE
defineCE should key off of current time

### ISSUE THREAD

**Issue by bennypowers** [open-wc/open-wc#86]
`defineCE` is meant to guarantee a unique custom-element tag name, but this is not always the case.

Consider:

```js
// my-one.test.js
import { My1Class } from './my-two.js';
import { defineCE } from '@open-wc/testing';
defineCE(MyElement1Class) // test-0
```
```js
// my-two.test.js
import { My2Class } from './my-two.js';
import { defineCE } from '@open-wc/testing';
defineCE(My2Class) // test-0
// Error: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
```

My guess is that this happens because webpack is transpiling to CJS, which makes copies of module state instead of live references, so that when the test runner loads a new file which imports `defineCE`, the counter is effectively "reset".

I propose that helpers.js do away with the internal name `defineCECounter` and instead, tag names should just include `Date.now()`

I'll put together a PR for your consideration.

**Comment by daKmoR** [comment]
This is actually a bug in how `karma-webpack` works.

See our issue https://github.com/open-wc/open-wc/issues/83 for it.

**Comment by daKmoR** [comment]
only "fixing" `defineCE` does not really make sense as the next problem you will run into is that `customElements.define` has the same problem... and we can't fix that... 

also, we agreed to have a `karma-webpack 5.0.0-rc.1` out by the end of this week - if not next Monday I will publish a temporary alternative and we will use that for until the official version hits.

PS: we actually had the now() version before but in a proper setup with es modules the +1 version is equally unique (so this is really only a problem in the current karma-webpack setup)

**Comment by bennypowers** [comment]
So I guess my question is why, if `now` was previously implemented, and it covered more use cases, `+=1` is preferred?

side note, in the mean time i apply this patch file in `postinstall`, so I'm not blocked.

`patches/@open-wc/testing-helpers+0.5.0.patch`
```patch
patch-package
--- a/node_modules/@open-wc/testing-helpers/helpers.js
+++ b/node_modules/@open-wc/testing-helpers/helpers.js
@@ -1,5 +1,3 @@
-let defineCECounter = 0;
-
 /**
  * Registers a new element with an automatically generated unique name.
  * Helps to make a test fully isolated.
@@ -15,9 +13,8 @@ let defineCECounter = 0;
  * @returns {string}
  */
 export function defineCE(klass) {
-  const tag = `test-${defineCECounter}`;
+  const tag = `test-${Date.now()}`;
   customElements.define(tag, klass);
-  defineCECounter += 1;
   return tag;
 }
 
```
