### ISSUE TITLE
[docs] Sub-sections of folder structure are not accessible via url

### ISSUE THREAD

**Issue by anoblet** [open-wc/open-wc#866]
https://open-wc.org/developing/es-dev-server.html#folder-structure

Sub-section:
https://open-wc.org/developing/es-dev-server.html#index-html-in-root

The behavior for this section is weird. Since the whole section is contained in a detail-summary element the user is not able to navigate to the appropriate sub-section without clicking read-more.. When the detail-summary element is expanded, navigation urls resolve to https://open-wc.org/developing/es-dev-server.html#all for every sub-section.

Removing the whole section from the detail-summary element might be a quick-fix until each sub-section is summarized?

**Comment by LarsDenBakker** [comment]
You're right the hashes don't work within the details summary, but they are a nice way to organize the docs so that it's not one huge document.

**Comment by anoblet** [comment]
If you want I can work on providing topic sentences for each sub-section and provide the read more link  with the rest of the information inside.

**Comment by LarsDenBakker** [comment]
If you can think of a nice way to have both, that would be great.

**Comment by anoblet** [comment]
I ran into a hiccup where I wasn't able to get the repo to clone correctly: 
![image](https://user-images.githubusercontent.com/7674171/68439405-74d39680-0195-11ea-90d2-dcce3ee74358.png) didn't wan't to break anything..

ran git clone and yarn install

I can do the edits, but won't be able to test them.

**Comment by bennypowers** [comment]
this looks great. I want to make a few small changes to the text then we'll merge it in
