### ISSUE TITLE
[docs] Make npm init @open-wc more prominent

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#867]
Unless I'm missing something, when you go to https://open-wc.org/ we don't really mention `npm init @open-wc` anywhere prominently.

**Comment by Westbrook** [comment]
It is the first command you get in the docs, but that is a click or two past FIRST THING... Would it make sense to change the button on the home page:
```
[ Get Started -> ]
```
To something like:
```
[ Get Started | `npm init @open-wc` ] [ Learn More -> ]
```
We could add a bit of `click to copy` interaction on the command side to make it even easier. So maybe a _hover_ state of:
```
[ Click to copy...             | OR ] [ Learn More -> ]
```

**Comment by bennypowers** [comment]
I'd say put it in the body of the page instead

something like this:

![Screen Shot 2019-10-28 at 11 07 59](https://user-images.githubusercontent.com/1466420/67665869-3a871f80-f973-11e9-8c83-382fefcf1910.png)

**Comment by thepassle** [comment]
I like that ^

**Comment by bennypowers** [comment]
to get that effect we will need to [extend the default theme](https://vuepress.vuejs.org/theme/inheritance.html#override-components)

**Comment by thepassle** [comment]
Iirc we already extend it a bit: https://github.com/open-wc/open-wc/blob/master/docs/.vuepress/styles/index.styl 😊

**Comment by bennypowers** [comment]
OHAI. k that makes things significantly easier

**Comment by bennypowers** [comment]
Looking to work on this today
