### ISSUE TITLE
[building-rollup] support .mjs out of the box

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#868]
In building-rollup, we should support `.mjs` extensions out of the box. 

I know there are ongoing discussions about whether or not `.mjs` is a good idea. I like `.js` myself, but I don't think we should block on consuming libraries that use `.mjs`.

**Comment by daKmoR** [comment]
I thought `.mjs` was dead?

it's not used in the upcoming es module implementation of node anymore - right?

and it could even introduce problems
https://twitter.com/kentcdodds/status/1085976119210196993

so I'm not sure if that is a smart move... maybe add an explanation on how to manually add it if you need it... but probably not a good default...

**Comment by abdonrd** [comment]
I'm agree about just document how to support it.

**Comment by LarsDenBakker** [comment]
I'm not sure, is it really dead? It's being used by quite some published packages. We could also use babel's default list of extensions, which I think includes `.mjs` as well.

@daKmoR to me that just explains how webpack is confusing, not really a case against `.mjs` for me :)

**Comment by bennypowers** [comment]
It's in use because supporters were very keen to tell everyone that it was a sure-thing. That's why projects adopted it.

except now it's not anymore.

That being said, it's frustrating to punish users for the choices their dependencies made. So while we shouldn't encourage adoption, we should support dependencies in `node_modules` with `mjs`

**Comment by wheresrhys** [comment]
What sources are people looking at to find information suggesting `.mjs` isn't a core part of node's esm implementation? It very much is a core part of it: https://nodejs.org/api/esm.html#esm_enabling. 

Despite there being a lot of debate, and a lot of reluctance to accept a new file extension, it is useful for resolving a few issues with interoperability of esm and cjs. This is a [great article](https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c) which explains how nodejs arrived at this conclusion.

I'd like to add to @LarsDenBakker's proposal that `es-dev-server` should prefer to use the file pointed to by the `browser` field of package.json if that file ends in `.mjs`. I'm guessing it currently prefers the file referenced by `module` based on the behaviour I'm seeing.

**Comment by LarsDenBakker** [comment]
I'm not sure about preferring the `browser` field over the `module` field, but I think `es-dev-server` should just follow the behavior of rollup, node and webpack so that the behavior is the same during development and when building.

I just ran into an issue with `.mjs` myself at work. `.mjs` files are not being compiled by babel right now :(

**Comment by wheresrhys** [comment]
Yep that seems best. Even if there were reasons not to like their particular opinions on which file is right, consistency across tools is key.

**Comment by bennypowers** [comment]
so, practically speaking, what shape does the fix for this take... updating all the regexps and glob patterns to use `/\.m?js$/` ?

**Comment by LarsDenBakker** [comment]
Yes I think so benny

**Comment by LarsDenBakker** [comment]
We now support `.mjs` in `es-dev-server` and `@open-wc/building-rollup`. For the fields in the package.json, we still just follow a hierarchy. Inspecting filename is out of scope for `es-dev-server` since we want it to be as fast as possible, and for rollup there isn't even an option there.

We will follow along with popular tools, and implement what they implement.
