### ISSUE TITLE
[testing-karma] Errors with karma 4.4.0

### ISSUE THREAD

**Issue by vlaraort** [open-wc/open-wc#879]
Hi 👋 

I am using @open-wc/testing-karma, and since the update of karma to 4.4.0, a lot of things have stopped to work, and can't start a test suite, crashing after the build.

Also, the main project tests crashes when the karma dependency is resolved to 4.4.0

**Steps to reproduce:**

- Clone master branch
- Delete yarn-lock
- yarn install && npm run test

Regards

**Comment by LarsDenBakker** [comment]
I just tried this on the master branch, and on a clean project using `npm init @open-wc`. Tests are working fine for me on both.

**Comment by thescientist13** [comment]
> Delete yarn-lock

Casually stoping by from Polymer, but this could definitely put things out of sync.  Any reason to just not manually `yarn add` the updated deps without blowing out the entire lock file?

**Comment by vlaraort** [comment]
weird, what is the output of `yarn list karma`? I have 4.4.0 and I think it's the issue

**Comment by vlaraort** [comment]
@thescientist13 this is just a way to enforce the installation of the latest versions of karma. 

When you install the package as a dependency, the `"karma": "^4.0.0",` in the package.json of the @open-wc/karma-config will resolve to the latest minor version, ignoring the yarn-lock of the main package, so it's a way to emulate the versions resolution.

**Comment by joanntaguinod** [comment]
Also experiencing this issue. Error on `[karma-server] Unhandled rejection`

**Comment by thescientist13** [comment]
@vlaraort 
Gotcha.  Wasn't sure if just using `yarn upgrade` / `yarn add` for just the **karma** dependencies individually would help / narrow the scope, instead of deleting the whole lock file, but seems the error is specific to **karma** itself, and not necessarily another dependency or maybe a transitive one.

**Comment by vlaraort** [comment]
Looks like karma has released the 4.4.1 version and now I don't have the `[karma-server] UnhandledRejection`, so for me this can be closed.

**Comment by LarsDenBakker** [comment]
Thats great to hear! Thanks for reporting it.

**Comment by pamls** [comment]
FYI

To display the error, you can add the following code in your karma configuration
```
process.on('infrastructure_error', (error) => {
  console.error('infrastructure_error', error);
});
```
