### ISSUE TITLE
[docs] Mention to NOT cache sw.js

### ISSUE THREAD

**Issue by lpellegr** [open-wc/open-wc#881]
It seems trivial but that's a common issue, especially for people discovering what a service worker is. I think there should be a note (maybe in the respective service-worker sections: rollup and webpack) to clearly mention that the generated `sw.js` file must not be cached once deployed.

For instance, with Firebase hosting, the following must be added to the `firebase.json` configuration file:

```
"headers": [
      {
        "source": "sw.js",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "no-cache"
          }
        ]
      }
],
```

**Comment by LarsDenBakker** [comment]
I thought that browsers already ignore cache headers on service worker requests

**Comment by lpellegr** [comment]
It seems to depend on the browser versions: https://stackoverflow.com/a/38854905/269447

I don't know what versions you target with open-wc. Feel free to close if it does not make sense.

**Comment by LarsDenBakker** [comment]
Officially latest 2 (and IE11) but this is a pretty serious bug if people have it, so that should extend a bit further. However Chrome 68 is quite some time ago now, so I'd say it's pretty safe not to mention this right now.

What do you think @thepassle ?

**Comment by bennypowers** [comment]
Do we have to worry about IE11 here? If not, let's rely on the browser behaviour, but add a note in docs explaining that we don't have to explicitly exclude `sw.js`
