### ISSUE TITLE
Use the workbox-config.js as default config

### ISSUE THREAD

**Issue by abdonrd** [open-wc/open-wc#883]
Docs: [Rollup > Overriding the workbox config](https://open-wc.org/building/building-rollup.html#overriding-the-workbox-config)

I want to propose that if the project already has a `workbox-config.js`, the `@open-wc/building-rollup` use it by default, without any other change. Overriding the default:

https://github.com/open-wc/open-wc/blob/85f53c94f10b4d0c86c8f93da52135654d7821d0/packages/building-rollup/modern-and-legacy-config.js#L126-L135

That way, the user just has to change the `rollup.config.js` if he wants to change the workbox mode.

**Comment by abdonrd** [comment]
One idea is #884

**Comment by bennypowers** [comment]
Closing as fixed by #884 

Please reopen if this is still relevant.
