### ISSUE TITLE
Any npm test randomly freezes

### ISSUE THREAD

**Issue by rWeave** [open-wc/open-wc#889]
Hi all,
When i use the default install from: 
```
npm init @open-wc
```
Any test randomly freezes, when i put on the debug log for karma i see that is freezes at the following line:
```
21 10 2019 11:22:02.372:DEBUG [middleware:karma]: Serving customContextFile /open-wc-test/node_modules/@open-wc/karma-esm/src/esm-context.html
21 10 2019 11:22:02.376:DEBUG [web-server]: serving: /open-wc-test/node_modules/@open-wc/karma-esm/src/esm-context.html
21 10 2019 11:22:02.392:DEBUG [web-server]: serving: /open-wc-test/node_modules/karma/static/context.js
```

It doesn't give any warning or error message. When i interrupt the command i don't know what went wrong. Had anyone else this experience and maybe have a solution to how to fix karma not working all the time.

### Environment Details

- Karma version is 4.3.0
- OSX version 10.14.6
- Open-wc version ^2.3.4
- `karma.config.js` file:
```
const { createDefaultConfig } = require('@open-wc/testing-karma');
const merge = require('webpack-merge');

module.exports = config => {
  config.set(
    merge(createDefaultConfig(config), {
      logLevel: config.LOG_DEBUG,
      files: [
        // runs all files ending with .test in the test folder,
        // can be overwritten by passing a --grep flag. examples:
        //
        // npm run test -- --grep test/foo/bar.test.js
        // npm run test -- --grep test/bar/*
        { pattern: config.grep ? config.grep : '/**/*.test.js', type: 'module' },
      ],

      esm: {
        nodeResolve: true,
      },
      // you can overwrite/extend the config further
    }),
  );
  return config;
};
```

### Steps to reproduce the behaviour
1. "test:watch": "karma start --auto-watch=true --single-run=false --no-cache"

**Comment by LarsDenBakker** [comment]
I tried this with a clean install, and I'm not getting any errors. Can you think of any specifics that might cause this? What options did you choose in the init?

**Comment by rWeave** [comment]
It was my fault, i searched al the files in my project folder with:
`**/*.test.ts`
So it wouldn't exclude node_modules thats why it was idle and wouldn't run instant or fast.

I've changed it to:
`src/**/*.test.ts`
