### ISSUE TITLE
[docs] URL for circleci config is broken

### ISSUE THREAD

**Issue by hardikpthv** [open-wc/open-wc#890]
What: Under the `Automating` section, in the `Manual Setup` the link for circleci configuration is broken.
Where: https://open-wc.org/automating/#setup

**Comment by bennypowers** [comment]
looks like that file was deleted in 17c40312c3d852465a74f94fe1d66af1ed5c1480
Since that package is deprecated, shouldn't we also remove this page?

**Comment by daKmoR** [comment]
we no longer have it in our generators but the info is still good... we probably should just show a good circleci config to copy from

at some point we might wanna switch/promote github actions - but first we need to verify that it work reliably for our usecase...

**Comment by daKmoR** [comment]
we no longer have such a section in our updated website 😅
