### ISSUE TITLE
Getting 'this._teardown is not a function' on open-wc-haunted-demos

### ISSUE THREAD

**Issue by evanplaice** [open-wc/open-wc#892]
![Screenshot of Haunted Demo Error](https://user-images.githubusercontent.com/303159/67231957-92ff6f80-f3fd-11e9-9d39-9202c69e1a7b.png)

### EnvInfo
- Browser: Chromium 77.0.3865.120 (Official Build)

### To reproduce
- open the haunted demos on StackBlitz
- wait for the demo to load
- click between Beginner/Intermediate/Advanced

**Comment by thepassle** [comment]
Hmm, looks like it could be a bug in Haunted? cc @matthewp

I can reproduce it by:
- going to: https://open-wc-haunted-demos.stackblitz.io/basic
- click `intermediate`, it loads fine
- click `basic`, it gives the error

**Comment by matthewp** [comment]
Looks like a bug in Haunted. `useEffect` is not working with async functions and assumes that any return value is a teardown function, which is not the case here. You can file an issue at https://github.com/matthewp/haunted or if not I will after I get off work.

**Comment by matthewp** [comment]
https://github.com/matthewp/haunted/issues/144

 should have it fixed shortly.

**Comment by matthewp** [comment]
Fixed in Haunted 4.6.2
