### ISSUE TITLE
[docs] events deep dive

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#895]
Events are a common source of confusion, people just make events bubbling and composed so that it works everywhere. That's a shame, I think we can really help with some deep dive docs.

**Comment by Westbrook** [comment]
I've been working on this: https://glitch.com/edit/#!/super-area?path=all-three.js:1:0 and dev.to post in this area recently...I think it's a great idea to expand the conversation in this area.

**Comment by thepassle** [comment]
@Westbrook do you think it would be possible to condense your blog post into a deep dive, and also a link to your blog for more in depth info? https://open-wc.org/faq/

**Comment by Westbrook** [comment]
Interesting. What areas do you think would be best to include? If we can agree on a rough structure on what we'd like to present locally, happy to get something together!

**Comment by Westbrook** [comment]
About halfway through expanding the initial release of this page. Look out for a PR on it sometime next week!
