### ISSUE TITLE
[es-dev-server] --compatibility all does not resolve `export {};`

### ISSUE THREAD

**Issue by goremikin** [open-wc/open-wc#913]
When the .js file contains an empty `export {};` line and `--compatibility all` is used, the line is not transformed causing an error in old browsers.

**Comment by LarsDenBakker** [comment]
This is indeed an issue, it's caused by the babel systemjs plugin. We need to file an issue there to get this fixed.

**Comment by daKmoR** [comment]
@goremikin maybe you could help out by opening an issue there https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-modules-systemjs possibly with a reproduction 🤗

**Comment by goremikin** [comment]
@daKmoR, I have raised an issue with Babel team: https://github.com/babel/babel/issues/10634. Thanks :)

**Comment by goremikin** [comment]
The issue has been fixed by Babel team and works as expected

**Comment by LarsDenBakker** [comment]
Nice, thats fast.
