### ISSUE TITLE
please add the web-animations-js polyfill

### ISSUE THREAD

**Issue by holgerengels** [open-wc/open-wc#948]
The [docs](https://github.com/web-animations/web-animations-js/blob/dev/docs/support.md#native-fallback) say ..
> When the polyfill runs on a browser that implements Element.animate() and Animation playback control, it will detect and use the underlying native features for better performance.

```
customPolyfills: [{
    name: 'web-animations-js',
    test: "window.Animation",
    path: require.resolve('web-animations-js/web-animations.min.js'),
    sourcemapPath: require.resolve('web-animations-js/web-animations.min.js.map'),
}]
```
Thus testing for window.Animation might not be sufficient.

**Comment by LarsDenBakker** [comment]
Web animations are a very fragmented API, a lot of things aren't implemented. Feature detection for this will be pretty complex. The polyfills are pretty heavy too, I'm not sure whether I would recommend anyone to use it to be honest :/

**Comment by LarsDenBakker** [comment]
Closing this one for now. It's easy to add this polyfill to the plugin yourself if you need it, but we don't think it's something we want to recommend for now.
