### ISSUE TITLE
 CSP Error: Input must be an index.html file

### ISSUE THREAD

**Issue by Genenenenaam** [open-wc/open-wc#964]
When you follow the docs for [CSP](https://www.npmjs.com/package/rollup-plugin-index-html#csp) you get an error.

`Error: [rollup-plugin-index-html]: Input must be an index.html file, or an indexHTML option must be provided.`

There is no index.html file as `If you need CSP you can separate the script in a separate file:`

What is wrong?

Steps i followed: 
Create demo project [open-wc rollup](https://open-wc.org/building/building-rollup.html#configuration)
add CSP to rollop.config.json [CSP](https://open-wc.org/building/building-rollup.html#configuration)

**Comment by thepassle** [comment]
This should be fixed in https://github.com/open-wc/open-wc/pull/965

Could you try and let me know if it works now?
