### ISSUE TITLE
[testing] Testing in Safari - problem with debug page

### ISSUE THREAD

**Issue by jarrodek** [open-wc/open-wc#972]
Not sure if this is Karma issue or something with the configuration. I started running into a problem when testing my component in Safari.

With command `npm run test:watch` I am opening `http://localhost:9876/` in Safari (Version 13.0.3 (13608.3.10.10.1)) and for a brief moment I can see the execution of the tests but after a second or so the page reloads and the error message `The webpage was reloaded because a problem occurred`.
Unfortunately Safari produces no debug information in the console. After opening the "Debug" page to run the test it also shows an error: `A problem repeatedly occurred with “‎localhost:9876/debug.html”`.

Not sure how to fix this. Have you guys had a problem like this?

**Comment by jarrodek** [comment]
To add,
The demo page loads correctly and the component works fine.

**Comment by LarsDenBakker** [comment]
I haven't had any issues with this, but I don't run my tests locally in Safari that often. It's usually just in the CI. If you have a reproduction, we can take a look at it

**Comment by jarrodek** [comment]
I noticed the issue while testing in my CI. A tests for a component started failing. The component is: https://github.com/advanced-rest-client/api-resource-example-document
I can't reproduce the problem with other components so it has to be this project specific. However, I can't figure out by myself why is this happening.

**Comment by bennypowers** [comment]
I reproduced this by cloning the above repo, adding `config.set({ browsers: ['Safari'] })` to the karma.conf.js, and running 
```
npm i -S karma-safari-launcher
npm i
npm t
```
When I did that, Safari popped up a file open dialog for `redirect.html`. If i cancel that dialog, the test hangs, if i open, the test fails with `The webpage was reloaded because a problem occurred`

With `npm run test:watch`, though, all tests pass.

**Comment by LarsDenBakker** [comment]
@bennypowers do you get the same with another project?

**Comment by jarrodek** [comment]
I just tried upgrading the dependencies and run the tests again. It works now locally. The tests are still failing on Sauce Labs but with different error: `Disconnectedreconnect failed before timeout of 10000ms (ping timeout)`. This is more likely a problem with sauce label launcher. So I am closing this ticket.
