### ISSUE TITLE
Fix typo open-wc landing page picture

### ISSUE THREAD

**Issue by ZempTime** [open-wc/open-wc#98]
I shared https://open-wc.org/ on my company chat and a bunch of people were immediately like "that should be PEACE of mind. Not Piece of mind!!"

Yes, yes, this is pedantic. However, that image really is the first thing people see when they land on the site, and your target audience are a bunch of nerds. As silly as this is, because I think this project is awesome and I want to really give it a shot, I have a need to make sure a spelling error in a meme doesn't cause people to not want to give it a shot.

If you're willing, and swapping out an image isn't too big a deal, could we update it?

In case it would be handy, generated another one that hopefully captures the same intent, but you definitely don't need to use this one:

<img width="461" alt="peace of mind" src="https://user-images.githubusercontent.com/3596468/50310982-478cd580-0469-11e9-9062-3f30b98e2443.png">

Thanks!

**Comment by thepassle** [comment]
Also, we probably should change that meme with the logo once its done, right?

**Comment by daKmoR** [comment]
Uh very nice :) and definitely not pedantic but helpful 🤗 
my spelling just sucks 🙈 

can you make a PR to replace the image?
https://github.com/open-wc/open-wc/blob/master/docs/.vuepress/public/hero.jpg

would be awesome :) also it would allow to see a preview just to be sure :)

PR: yes it's sort of a placeholder until we have a real logo... but that might take some time 🙈
