### ISSUE TITLE
[Building-rollup] use per output plugins

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#980]
We should use https://github.com/rollup/rollup/pull/3218 when its merged

**Comment by abdonrd** [comment]
Released! https://github.com/rollup/rollup/releases/tag/v1.27.0

**Comment by bennypowers** [comment]
What's the plan for this?

**Comment by LarsDenBakker** [comment]
Someone needs to dig in and analyze whether this feature can be useful for us.

My hope is that we can use the regular plugins entry for shared plugins, and then a per-output plugins for plugins that should run for the different output. That should make it a ton easier to extend the compatibility configuration for our users.

This is probably a breaking change, so we should also check whether there are any other pending breaking changes. @thepassle ?

**Comment by thepassle** [comment]
I dont have any breaking changes planned wrt workbox. It would just be a shared plugin (for both outputs), so I think it can stay where it is

**Comment by bennypowers** [comment]
We discussed this on slack. One use case for use would be something like
```js
export default {
  output: [
    { dir: 'dist/modern': plugins: [babel({ presets: ['@babel/preset-modules'] })] },
    { dir: 'dist/legacy': plugins: [babel({ presets: ['@babel/preset-env'] })] },
  ]
  // ...
}
```

**Comment by LarsDenBakker** [comment]
We will need this to be merged https://github.com/rollup/rollup-plugin-babel/pull/333

**Comment by abdonrd** [comment]
> We will need this to be merged [rollup/rollup-plugin-babel#333](https://github.com/rollup/rollup-plugin-babel/pull/333)

Merged! 😁

**Comment by LarsDenBakker** [comment]
They didn't release it yet though :/

**Comment by LarsDenBakker** [comment]
This was implemented in v1 of building-rollup.
