### ISSUE TITLE
[Building] Use babel preset modules

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#983]
https://github.com/babel/preset-modules/blob/master/README.md

Also make sure to cover the terser recommendations

**Comment by abdonrd** [comment]
Related: https://twitter.com/_developit/status/1194343651586920448

**Comment by LarsDenBakker** [comment]
It's being merged into babel preset env, tracking in https://github.com/open-wc/open-wc/issues/1407.
